'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 5  —  Monitoring and Alerting  —  20 Sub-Topics',
  groups: [
    ['5.1  Spark UI — Tab-by-Tab Reference',[
      ['01','5.1.1','Jobs Tab (One Job = One Action)'],
      ['02','5.1.2','Stages Tab — Skew Detection, Spill Identification'],
      ['03','5.1.3','SQL/DataFrame Tab — Exchange Nodes, BroadcastExchange, Predicate Pushdown'],
      ['04','5.1.4','Executors Tab — GC Time, Memory Pressure'],
      ['05','5.1.5','Storage Tab — Cache Hit Rate'],
      ['06','5.1.6','Environment Tab — Verify Spark Configuration Values'],
    ]],
    ['5.2  Query Profiler UI',[
      ['07','5.2.1','Scanned vs Skipped Files, Stage Breakdown, Bottleneck Identification'],
    ]],
    ['5.3  Ganglia UI — Cluster Metrics',[
      ['08','5.3.1','CPU, Memory, Network, Disk I/O Per Node'],
      ['09','5.3.2','Spill Detection: High Disk I/O + Memory Pressure'],
    ]],
    ['5.4  System Tables — Complete Reference',[
      ['10','5.4.1','system.billing.usage: identity_metadata.run_as vs created_by'],
      ['11','5.4.2','system.access.audit — Compliance, Failed Permission Checks (403)'],
      ['12','5.4.3','system.access.table_access_history — Table-Level Access Tracking'],
      ['13','5.4.4','system.jobs.runs — Job History, Performance Trends'],
      ['14','5.4.5','system.lakeflow.pipeline_events — Pipeline Failures, Data Quality'],
    ]],
    ['5.5  SQL Alerts',[
      ['15','5.5.1','Alert States: OK, TRIGGERED, UNKNOWN'],
      ['16','5.5.2','Notification Frequency Trap — Stops Firing != Resolved'],
    ]],
    ['5.6  Job Monitoring — REST API and Notifications',[
      ['17','5.6.1','Polling Run Status via API (life_cycle_state, result_state)'],
      ['18','5.6.2','Notification Config: on_start, on_success, on_failure, max_retries=-1'],
      ['19','5.6.3','UPSTREAM_FAILED vs FAILED Distinction'],
      ['20','5.6.4','Repair Run Re-uses Same run_id'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 5  —  Monitoring and Alerting  —  All High-Priority Traps',
};

const pages = [

// ─── 5.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'5.1.1 — Jobs Tab (One Job = One Action)',
  what:[
    'Jobs tab: top-level view of all Spark jobs executed in the current SparkSession',
    'One job = one action call — count(), show(), write(), collect(), foreach() each create one job',
    'Each job row shows: Job ID, description, submitted time, duration, stages, and tasks summary',
  ],
  how:[
    'Every action call submits a new job to the Spark scheduler — visible immediately',
    'Job description: derived from calling code location — shows file name + line number',
    'Job status: Running, Succeeded, Failed',
    'Click any job — drills into the stages that make up that job',
  ],
  facts:[
    'One action = one job — counting actions in your pipeline = counting jobs in the Jobs tab',
    'Job duration includes: DAG compilation time + scheduler overhead + actual task execution',
    'Failed jobs show the exception that caused failure — click for full stack trace',
    'Jobs tab resets when SparkSession restarts — history not persisted between cluster restarts',
  ],
  ascii:true,
  code:[
    'CODE EXECUTION -> JOBS TAB VIEW',
    '',
    'df.filter(col("age") > 25)          -> transformation, no job',
    '  .groupBy("dept")                  -> transformation, no job',
    '  .count()                          -> ACTION -> Job 0 created',
    '',
    'df.write.save("/output/")           -> ACTION -> Job 1 created',
    'df.show()                           -> ACTION -> Job 2 created',
    '',
    'JOBS TAB:',
    '  Job ID | Description        | Duration | Stages | Tasks | Status',
    '  -------|--------------------|---------:|-------:|------:|-------',
    '  Job 0  | count at line 42   |    2.3 s |      2 |   200 | Succeeded',
    '  Job 1  | save at line 45    |   15.1 s |      3 |   600 | Succeeded',
    '  Job 2  | show at line 48    |    0.8 s |      1 |    10 | Succeeded',
  ],
  mistakes:[
    '✗ Expecting one transformation = one job — only ACTIONS create jobs',
    '✗ Looking for lazy transformations in the Jobs tab — invisible until an action fires',
    '✗ Assuming job count equals stage count — one job can contain multiple stages',
  ],
  trap:[
    '✗ One ACTION = one Job — show(), count(), collect(), write() each create exactly one job',
    '✗ explain() and printSchema() do NOT create jobs — they are NOT actions',
    '✗ df.cache() does NOT create a job — lazy, job created on first action AFTER cache()',
    '✗ Job description shows calling code location — useful for correlating to notebook cells',
    '✗ Jobs tab resets on cluster restart — use system tables for historical debugging',
    '✗ Succeeded job count != correct results — a job can succeed but write wrong data',
  ],
},

// ─── 5.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'5.1.2 — Stages Tab — Skew Detection, Spill Identification',
  what:[
    'Stages tab: most diagnostic tab in Spark UI — shows task-level metrics for every stage',
    'Primary location for: detecting data skew, identifying shuffle spill, finding slow tasks',
    'Each stage row shows: Stage ID, description, tasks count, duration, input/output bytes, shuffle, spill',
  ],
  how:[
    'Expanding a stage shows the task timeline — each bar = one task, color coded by phase',
    'Task duration histogram: most tasks complete quickly but a few take much longer = DATA SKEW',
    'Shuffle spill columns: Shuffle Spill (Memory) and Shuffle Spill (Disk) — non-zero = spill',
    'GC time per task: high GC time as proportion of task time = memory pressure',
  ],
  facts:[
    'Skew detection: look for task duration outliers — median 2s, max 600s = skewed data',
    'Spill detection: Shuffle Spill (Memory) > 0 = tasks writing shuffle data to executor local disk',
    'Spill (Memory) always > Spill (Disk) — memory is pre-compression, disk is post-compression',
    'Stage summary tab: shows min/25th/median/75th/max for all task metrics',
  ],
  ascii:true,
  code:[
    'STAGES TAB — KEY COLUMNS:',
    '',
    'Stage | Tasks | Duration | Input  | Shuffle Read | Shuffle Write | Spill(Mem) | Spill(Disk)',
    '------|-------|----------|--------|-------------|---------------|------------|------------',
    '  0   |  200  |   2.3s   | 10 GB  |     0 B     |    5.2 GB    |     0 B    |     0 B',
    '  1   |  200  |  18.7s   |  0 B   |    5.2 GB   |      0 B     |   45.2 GB  |   8.1 GB <- SPILL!',
    '',
    'TASK DURATION HISTOGRAM (showing skew):',
    '',
    '  Count |',
    '   190  |##############',
    '     5  |               #',
    '     2  |                  # <- SKEWED TASKS (few taking 100x longer)',
    '        |________________________________',
    '          2s    10s   60s  120s  600s',
    '',
    'SPILL (Memory) > 0 — fix options:',
    '  1. Increase shuffle.partitions (less data per task)',
    '  2. Broadcast small side (eliminate shuffle)',
    '  3. Increase executor memory',
  ],
  mistakes:[
    '✗ Looking for skew in the Jobs tab — skew is only visible in the Stages tab task metrics',
    '✗ Confusing Spill (Memory) and Spill (Disk) — Memory always larger (pre-compression)',
    '✗ Ignoring task summary statistics — min/median/max spread reveals skew immediately',
  ],
  trap:[
    '✗ Skew detection is in STAGES tab — NOT in Jobs tab, NOT in Executors tab',
    '✗ Spill metrics in STAGES tab — Shuffle Spill (Memory) and Shuffle Spill (Disk) columns',
    '✗ Spill (Memory) ALWAYS > Spill (Disk) — memory is uncompressed bytes, disk is compressed',
    '✗ Task duration outliers = data skew — median 2s, max 600s = hot key concentrating data',
    '✗ Spill does NOT fail the job — job completes but with degraded performance',
    '✗ Stage summary shows min/25th/median/75th/max — use median vs max spread to detect skew',
    '✗ GC time column in Stages tab: high GC time = memory pressure',
  ],
},

// ─── 5.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'5.1.3 — SQL/DataFrame Tab — Exchange Nodes, BroadcastExchange, Predicate Pushdown',
  what:[
    'SQL/DataFrame tab: shows the physical execution plan as a visual DAG of operator nodes',
    'Each node is a physical operator: FileScan, Filter, Exchange, SortMergeJoin, BroadcastHashJoin',
    'Click any query — see the full physical plan with metrics per node (rows, bytes, duration)',
  ],
  how:[
    'Exchange node: represents a shuffle — Exchange hashpartitioning(col, 200) = hash shuffle 200 partitions',
    'BroadcastExchange: broadcast join — small table sent to all executors, no shuffle on large side',
    'Predicate pushdown: visible when Filter node appears BELOW FileScan — filter pushed to source',
    'Projection pruning: visible in FileScan output columns — only referenced columns listed',
  ],
  facts:[
    'Exchange in plan = shuffle — every Exchange is a wide transformation boundary',
    'BroadcastExchange in plan = broadcast join — large side NOT shuffled, small side broadcast',
    'FileScan node shows: files scanned, files skipped, output rows',
    'SortMergeJoin = both sides shuffled and sorted — expensive for large-large joins',
  ],
  ascii:true,
  code:[
    'GOOD PLAN (broadcast join + predicate pushdown):',
    '  FileScan delta [orders]           -> reads only needed files',
    '    Filter (amount > 0)             -> filter pushed INTO scan (predicate pushdown)',
    '      BroadcastHashJoin              -> broadcast join (no shuffle on large side)',
    '        FileScan delta [customers]  -> small table broadcast',
    '          HashAggregate             -> final aggregation',
    '',
    'PROBLEMATIC PLAN (sort-merge + full scan):',
    '  FileScan delta [orders]           -> scans ALL files (no file skipping)',
    '    Exchange hashpartitioning        -> SHUFFLE (expensive!)',
    '      SortMergeJoin                  -> both sides shuffled + sorted',
    '        Exchange hashpartitioning    -> SHUFFLE on second side',
    '          FileScan delta [customers]',
    '',
    'KEY INDICATORS:',
    '  BroadcastExchange  -> broadcast join working',
    '  Exchange           -> shuffle happening (check if avoidable)',
    '  SortMergeJoin      -> large-large join (can we broadcast one side?)',
    '  FileScan (0 files skipped) -> no file skipping (add ZORDER or Bloom filter)',
    '  Filter below FileScan -> predicate pushdown',
    '  Filter above FileScan -> no pushdown (UDF? complex expression?)',
  ],
  trap:[
    '✗ Exchange node = shuffle — each Exchange is a stage boundary in the execution plan',
    '✗ BroadcastExchange = broadcast join — large side NOT shuffled, the desired fast path',
    '✗ SortMergeJoin requires TWO Exchange nodes — both sides shuffled AND sorted',
    '✗ FileScan with 0 files skipped = no ZORDER, no Bloom filter, no partition pruning',
    '✗ Predicate pushdown visible when Filter appears INSIDE/BELOW FileScan',
    '✗ Python UDF breaks predicate pushdown — Filter node ABOVE FileScan',
    '✗ BroadcastHashJoin in plan = broadcast occurred; SortMergeJoin = it did NOT broadcast',
  ],
},

// ─── 5.1.4 ───────────────────────────────────────────────────────────────────
{num:'04',title:'5.1.4 — Executors Tab — GC Time, Memory Pressure',
  what:[
    'Executors tab: shows per-executor metrics — memory usage, GC time, task count, storage used',
    'Used to detect: memory pressure (GC time > 10% of task time), executor failures, uneven distribution',
    'Shows both active and dead executors — dead executors indicate node failures or evictions',
  ],
  how:[
    'Per-executor columns: Address, Status, RDD Blocks, Storage Memory, Disk Used, Cores, Active Tasks',
    'GC time: time spent on Java Garbage Collection — high GC = executor memory pressure',
    'Storage Memory: memory used for cached RDDs/DataFrames',
    'Failed Tasks: non-zero = executor had task failures — may indicate OOM',
  ],
  facts:[
    'GC time > 10% of total task time = significant memory pressure — increase executor memory',
    'High GC time + high memory utilization — executor running out of heap space',
    'Uneven task distribution: one executor has 10x more tasks than others — data skew',
    'Dead executor row: executor crashed — investigate cluster logs for OOM',
  ],
  ascii:true,
  code:[
    'EXECUTORS TAB — KEY METRICS:',
    '',
    'Executor | Status | Storage Mem    | GC Time | Active | Failed | Complete',
    '---------|--------|----------------|---------|--------|--------|----------',
    'Driver   | Active | 0.0 B / 4.0 GB |    0 s  |      0 |      0 |        0',
    'exec-1   | Active | 2.1 GB / 8 GB  |    2 s  |      4 |      0 |     1245',
    'exec-2   | Active | 2.0 GB / 8 GB  |    1 s  |      4 |      0 |     1238',
    'exec-3   | Active | 7.9 GB / 8 GB  |  180 s  |      2 |      8 |      423 <- MEMORY PRESSURE!',
    'exec-4   | Dead   | N/A            |    N/A  |      0 |     52 |      221 <- EXECUTOR FAILED!',
    '',
    'DIAGNOSIS:',
    '  exec-3: Storage Mem near 100% + high GC time + failed tasks',
    '    -> Cache too much memory + insufficient heap for tasks',
    '    -> Fix: reduce cache, increase executor memory, or reduce shuffle partitions',
    '',
    '  exec-4: Dead with many failed tasks',
    '    -> Node failure or OOM crash',
    '    -> Check cluster logs for java.lang.OutOfMemoryError',
  ],
  trap:[
    '✗ GC Time > 10% of task time = memory pressure — executor heap is too small',
    '✗ High GC + high Storage Memory usage — cache consuming memory needed for tasks',
    '✗ Dead executor = node failed — investigate cluster driver logs',
    '✗ Executors tab shows BOTH active and dead executors — dead rows remain for diagnosis',
    '✗ Failed Tasks > 0 — executor had task failures — may cascade to job failure',
    '✗ Storage Memory = memory used by cached DataFrames/RDDs — distinct from task execution memory',
  ],
},

// ─── 5.1.5 ───────────────────────────────────────────────────────────────────
{num:'05',title:'5.1.5 — Storage Tab — Cache Hit Rate',
  what:[
    'Storage tab: shows all currently cached RDDs, DataFrames, and broadcast variables',
    'Displays: fraction cached (how much of the dataset fits in memory), storage level, partitions',
    'Used to verify: cache is actually loaded, how much fits in memory vs spilling to disk',
  ],
  how:[
    'After df.cache() + an action: DataFrame appears in Storage tab with Fraction Cached metric',
    'Fraction Cached: what percentage of the data is actually in memory — < 1.0 = partial cache',
    'Storage levels shown: Memory Deserialized, Memory and Disk, Disk Only, etc.',
    'Broadcast variables also visible in Storage tab — each executor copy of broadcast data',
  ],
  facts:[
    'Fraction Cached = 1.0 means 100% of data in memory — all reads from cache',
    'Fraction Cached < 1.0 means partial cache — some partitions recomputed on access',
    'Cache hit rate is NOT shown directly — infer from Fraction Cached and task input metrics',
    'Storage tab only shows CURRENTLY cached data — evicted entries disappear from the list',
  ],
  ascii:true,
  code:[
    'STORAGE TAB — AFTER df.cache().count():',
    '',
    'RDD Name           | Storage Level       | Cached Partitions | Fraction | Size',
    '-------------------|---------------------|------------------|----------|----------',
    'orders_df [RDD 42] | Memory Deserialized |              200 |   100%   | 4.5 GB  <- Full',
    'dim_customers [43] | Memory and Disk     |              200 |    65%   | 1.2 GB  <- Partial',
    'broadcast [44]     | Memory Deserialized |               12 |   100%   | 124 MB  <- Broadcast',
    '',
    'INTERPRETATION:',
    '  orders_df (100%): all 200 partitions in memory -> every access reads from cache',
    '  dim_customers (65%): 130/200 partitions in memory, 70 on disk or evicted',
    '    -> When non-cached partition accessed: recomputed from source OR read from disk',
    '    -> Consider increasing executor memory or DISK_ONLY storage level',
    '',
    '  Fraction Cached < 100%: cache eviction occurring — executor memory too small',
    '  Fix: increase executor memory, fewer cached DataFrames, or disk-based storage level',
  ],
  trap:[
    '✗ df.cache() is LAZY — Storage tab empty until first action after cache() is called',
    '✗ Fraction Cached < 100% = partial cache = some partitions recomputed on access',
    '✗ Storage tab only shows CURRENTLY cached data — evicted partitions disappear',
    '✗ CACHE TABLE (eager) appears in Storage tab immediately; df.cache() (lazy) appears after action',
    '✗ Cache eviction happens when executor memory full — LRU eviction removes least-recently-used',
    '✗ Broadcast variables also appear in Storage tab — one entry per broadcast, size per executor',
  ],
},

// ─── 5.1.6 ───────────────────────────────────────────────────────────────────
{num:'06',title:'5.1.6 — Environment Tab — Verify Spark Configuration Values',
  what:[
    'Environment tab: shows all active Spark configuration settings for the current SparkSession',
    'Used to verify: which config values are actually in effect, overrides from multiple sources',
    'Shows: Spark properties, JVM info, classpath entries, system properties',
  ],
  how:[
    'Config hierarchy: Spark defaults -> cluster config -> notebook spark.conf.set() -> query hints',
    'Environment tab shows the RESOLVED final value — after all overrides applied',
    'Useful to confirm: spark.sql.shuffle.partitions, spark.sql.adaptive.enabled, autoBroadcastJoinThreshold',
    'Config set with spark.conf.set() in notebook overrides cluster config — visible in Environment',
  ],
  facts:[
    'Environment tab shows the EFFECTIVE configuration — not just what was set in cluster config',
    'spark.conf.set() in notebook > cluster config > Spark defaults — later overrides win',
    'Classpath section: shows all JARs loaded — useful for diagnosing library conflicts',
    'JVM info: shows Java version — important for Scala/Java library compatibility',
  ],
  code:[
    '# Verify config values programmatically',
    'spark.conf.get("spark.sql.shuffle.partitions")',
    '# "200" — or whatever is currently set',
    '',
    'spark.conf.get("spark.sql.adaptive.enabled")',
    '# "true" — AQE status',
    '',
    'spark.conf.get("spark.sql.autoBroadcastJoinThreshold")',
    '# "10485760" — 10MB in bytes',
    '',
    '# Set config and verify it took effect',
    'spark.conf.set("spark.sql.shuffle.partitions", "400")',
    'spark.conf.get("spark.sql.shuffle.partitions")',
    '# "400" — confirms override',
    '',
    '# Environment tab in Spark UI shows same values',
    '# Navigate: Spark UI -> Environment tab -> Spark Properties section',
  ],
  trap:[
    '✗ Environment tab shows EFFECTIVE config values — after all overrides applied',
    '✗ spark.conf.set() in notebook OVERRIDES cluster config — Environment tab shows overridden value',
    '✗ Use Environment tab to VERIFY config values are actually set as expected',
    '✗ Config set via spark.conf.set() is SESSION-scoped — lost when SparkSession restarts',
    '✗ Environment tab does NOT show DABs bundle variables — only Spark-level configuration',
  ],
},

// ─── 5.2.1 ───────────────────────────────────────────────────────────────────
{num:'07',title:'5.2.1 — Scanned vs Skipped Files, Stage Breakdown, Bottleneck Identification',
  what:[
    'Query Profiler: visual execution analysis tool in Databricks SQL — shows timing and metrics',
    'Available in DBSQL Query History — click any query — Query Profile tab',
    'Shows: files scanned vs skipped, time per stage, data flow (rows/bytes) between operators',
  ],
  how:[
    'Query Profile renders the physical plan as an interactive DAG — each node shows execution metrics',
    'Node width/color indicates relative time spent — wide/dark nodes are bottlenecks',
    'Click any node — see detailed metrics: rows in/out, bytes read, duration, files scanned/skipped',
    'Files Scanned vs Files Skipped: key metric for data skipping effectiveness',
  ],
  facts:[
    'Files Skipped = 0 = no data skipping = no ZORDER, no Bloom filter, no partition pruning',
    'Wide node in Query Profile = bottleneck — that operator is consuming most time',
    'SortMergeJoin with one small side = missed broadcast opportunity — add broadcast hint',
    'Query Profile available in DBSQL Query History — different from Spark UI SQL tab',
  ],
  ascii:true,
  code:[
    'QUERY PROFILE WORKFLOW:',
    '',
    'DBSQL -> Query History -> Click Query -> Query Profile tab',
    '',
    '  [FileScan: orders]                     <- check files scanned vs skipped',
    '    Files scanned: 10,000               <- ALL files read — no skipping!',
    '    Files skipped: 0                    <- FIX: run OPTIMIZE ZORDER BY filter_col',
    '    Time: 45s  ###################### <- wide node = bottleneck',
    '',
    '  [Exchange: hashpartition(200)]         <- shuffle — check if avoidable',
    '    Bytes shuffled: 120 GB',
    '    Time: 30s  ###############',
    '',
    '  [SortMergeJoin]                        <- can we broadcast one side?',
    '    Left rows: 500M, Right rows: 5K',
    '    -> Right side only 5K rows!',
    '    -> FIX: add broadcast() hint on right side',
    '',
    'OPTIMISED AFTER FIXES:',
    '  [FileScan: orders]   skipped: 9,500/10,000  (ZORDER helped)',
    '  [BroadcastHashJoin]  no Exchange needed     (broadcast hint)',
    '  [HashAggregate]      fast aggregation',
  ],
  mistakes:[
    '✗ Not checking files scanned vs files skipped — first metric to review in any slow query',
    '✗ Ignoring SortMergeJoin when one side is small — missed broadcast opportunity',
    '✗ Looking at Query Profile in Spark UI instead of DBSQL — DBSQL has richer profiler UI',
  ],
  trap:[
    '✗ Query Profiler is in DBSQL Query History — not the same as Spark UI SQL/DataFrame tab',
    '✗ Files Skipped = 0 = no data skipping = no ZORDER, no Bloom filter, no partition pruning',
    '✗ Wide node in Query Profile = BOTTLENECK — that operator consuming most time',
    '✗ SortMergeJoin with one small side = missed broadcast — add broadcast() hint',
    '✗ Query Profile available for DBSQL queries — not for all-purpose cluster notebook queries',
  ],
},

// ─── 5.3.1 ───────────────────────────────────────────────────────────────────
{num:'08',title:'5.3.1 — CPU, Memory, Network, Disk I/O Per Node',
  what:[
    'Ganglia UI: cluster-level metrics dashboard — shows real-time and historical resource utilization per node',
    'Accessible from cluster details page in Databricks UI — Metrics tab — Ganglia link',
    'Shows: CPU utilization, memory usage, network I/O, disk read/write per worker node over time',
  ],
  how:[
    'Ganglia aggregates metrics from all cluster nodes — driver and all worker nodes',
    'Time-series graphs: x-axis = time, y-axis = utilization — hover for per-node breakdown',
    'CPU: ideal is near 100% during execution — low CPU = cluster underutilized, tasks waiting',
    'Memory: consistently near 100% = memory pressure risk — may precede GC issues or OOM',
  ],
  facts:[
    'CPU healthy: 70-100% during job; warning: <30%; problem: <10% (underutilized)',
    'Memory healthy: 50-80%; warning: 80-95%; problem: 95%+ (OOM risk)',
    'Network I/O: moderate spikes during shuffle = normal; sustained high = bottleneck',
    'Disk I/O: low during compute; high + memory pressure = spill',
  ],
  ascii:true,
  code:[
    'GANGLIA DASHBOARD — TIME-SERIES METRICS:',
    '',
    'CPU (all nodes aggregate):',
    '  100% |####################',
    '   50% |          ####',
    '    0% |___________________________________',
    '         T1    T2    T3    T4    T5',
    '              ^                ^',
    '         Job starts        Job ends',
    '  Healthy: near 100% during job execution',
    '',
    'Memory (per node):',
    '  100% |          ########',
    '   80% |   ########        ####',
    '    0% |___________________________________',
    '  If memory stays at 95%+: OOM/GC risk',
    '',
    'Network I/O:',
    '  High |     ##                  ##',
    '   Med |         ##          ##',
    '   Low |___________________________________',
    '                ^ Shuffle read   ^ Shuffle write',
    '  Spikes during shuffle = normal',
    '',
    'Disk I/O:',
    '  High |                #####',
    '   Low |___________________________________',
    '  Sustained disk write during shuffle = SPILL',
  ],
  trap:[
    '✗ Ganglia is cluster-level monitoring; Spark UI is query/job-level — both needed',
    '✗ Low CPU during job = cluster UNDERUTILIZED — too few partitions or data starvation',
    '✗ High disk I/O + high memory = SPILL indicator — confirm in Spark UI Stages tab',
    '✗ Ganglia shows PER-NODE metrics — uneven memory/CPU = skew or uneven data distribution',
    '✗ Ganglia accessible from cluster details — Metrics tab — not from notebook or SQL',
  ],
},

// ─── 5.3.2 ───────────────────────────────────────────────────────────────────
{num:'09',title:'5.3.2 — Spill Detection: High Disk I/O + Memory Pressure',
  what:[
    'Spill detection pattern: combination of high disk I/O AND high memory utilization in Ganglia = spill signal',
    'Spill occurs when shuffle/aggregation data exceeds executor memory — overflow written to local disk',
    'Ganglia shows the symptom; Spark UI Stages tab confirms and quantifies the spill',
  ],
  how:[
    'Memory near capacity + tasks writing heavily to disk — executor is spilling shuffle data',
    'Pattern: memory builds up (near 100%) -> disk write spikes -> memory slightly drops -> cycle repeats',
    'Ganglia cannot show WHICH task or stage is spilling — go to Spark UI Stages tab',
    'Spill degrades performance: disk I/O is 10-100x slower than memory — significant slowdown',
  ],
  facts:[
    'Ganglia spill pattern: high memory (>90%) + high disk write I/O simultaneously',
    'Ganglia CANNOT directly show shuffle spill bytes — only in Spark UI Stages tab',
    'Spill confirmation: Spark UI -> Stages tab -> Shuffle Spill (Memory) and Shuffle Spill (Disk)',
    'Spill (Memory) > Spill (Disk) always — memory is pre-compression, disk is post-compression',
  ],
  ascii:true,
  code:[
    'GANGLIA SPILL DETECTION PATTERN:',
    '',
    'Memory utilization:',
    '  100% |################################',
    '   90% |',
    '   80% |',
    '       |___________________________________',
    '           ^ Memory near capacity',
    '',
    'Disk Write I/O:',
    '  High |    ####        ####        ####',
    '   Med |        ####        ####',
    '   Low |___________________________________',
    '           ^ Repeated disk write spikes = shuffle data being written to disk',
    '',
    'TOGETHER: High Memory + Disk Write Spikes = SPILL',
    '',
    'CONFIRMATION in Spark UI -> Stages tab:',
    '  Stage 3 -> Shuffle Spill (Memory): 45.2 GB',
    '             Shuffle Spill (Disk):   8.1 GB',
    '             -> CONFIRMED: 45GB uncompressed -> 8GB compressed to disk',
    '',
    'THREE FIXES:',
    '  1. Increase spark.sql.shuffle.partitions',
    '  2. Use broadcast join — eliminate shuffle entirely',
    '  3. Increase executor memory',
  ],
  trap:[
    '✗ Ganglia spill pattern: high memory + high disk I/O simultaneously',
    '✗ Ganglia shows SYMPTOM only — Spark UI Stages tab shows EXACT spill bytes',
    '✗ Spill (Memory) ALWAYS > Spill (Disk) — memory uncompressed, disk compressed',
    '✗ Spill does NOT fail the job — degrades performance but completes',
    '✗ Normal shuffle: brief disk write spike then stops; SPILL: sustained repeated cycles',
    '✗ Fix priority: more shuffle partitions (cheapest) -> broadcast join -> more memory',
  ],
},

// ─── 5.4.1 ───────────────────────────────────────────────────────────────────
{num:'10',title:'5.4.1 — system.billing.usage: identity_metadata.run_as vs created_by',
  what:[
    'system.billing.usage: UC system table tracking all DBU consumption',
    'Critical for cost attribution — which users, jobs, and clusters consume the most DBUs',
    'Two key identity fields: identity_metadata.run_as (execution identity) vs created_by (creator)',
  ],
  how:[
    'Every DBU-consuming activity logged: cluster uptime, job runs, SQL warehouse usage, DLT pipelines',
    'created_by: the user who created the job/cluster/resource',
    'identity_metadata.run_as: the identity under which the job actually EXECUTES — may differ',
    'For jobs with service principal ownership: run_as = SP, created_by = human who set it up',
  ],
  facts:[
    'identity_metadata.run_as = the execution identity — whose permissions used for data access',
    'created_by = the creator identity — who set up the resource, not who is running it',
    'For cost attribution: use run_as — this is the identity consuming the DBUs during execution',
    'For access control auditing: use run_as — the identity making data access requests',
  ],
  code:[
    '-- Total DBU consumption by execution identity (run_as)',
    'SELECT',
    '    identity_metadata.run_as         AS executing_identity,',
    '    sku_name,',
    '    SUM(usage_quantity)              AS total_dbus,',
    '    SUM(usage_quantity * list_price) AS estimated_cost_usd',
    'FROM system.billing.usage',
    'WHERE usage_date >= current_date() - INTERVAL 30 DAYS',
    'GROUP BY identity_metadata.run_as, sku_name',
    'ORDER BY total_dbus DESC;',
    '',
    '-- Compare created_by vs run_as',
    'SELECT',
    '    created_by                  AS creator,',
    '    identity_metadata.run_as   AS execution_identity,',
    '    COUNT(*)                    AS usage_records,',
    '    SUM(usage_quantity)         AS total_dbus',
    'FROM system.billing.usage',
    'WHERE usage_date >= current_date() - INTERVAL 7 DAYS',
    'GROUP BY created_by, identity_metadata.run_as',
    'ORDER BY total_dbus DESC;',
  ],
  mistakes:[
    '✗ Using created_by for cost attribution — run_as is the execution identity',
    '✗ Assuming created_by and run_as are always the same — differ when SPs run jobs',
    '✗ Not filtering by usage_date — querying all history is expensive',
  ],
  trap:[
    '✗ identity_metadata.run_as = who job RUNS AS (execution identity) — for cost attribution',
    '✗ created_by = who CREATED the resource — not necessarily who runs it',
    '✗ For jobs running as service principals: run_as = SP identity, created_by = human creator',
    '✗ system.billing.usage requires Unity Catalog',
    '✗ Cost attribution: always use run_as — the identity consuming compute resources',
    '✗ system.billing.usage covers: clusters, jobs, SQL warehouses, DLT pipelines, model serving',
  ],
},

// ─── 5.4.2 ───────────────────────────────────────────────────────────────────
{num:'11',title:'5.4.2 — system.access.audit — Compliance, Failed Permission Checks (403)',
  what:[
    'system.access.audit: comprehensive audit log of all UC actions — data access, permission changes, login',
    'Used for: compliance reporting, security investigations, detecting unauthorized access',
    'Every UC action generates an audit entry — SELECT queries, GRANT/REVOKE, Delta Sharing, etc.',
  ],
  how:[
    'Every UC-governed operation produces an audit record with timestamp, user, action type, resource, result',
    'response.status_code: 200 = success, 403 = permission denied (insufficient privileges)',
    'Failed permission checks (403): indicate unauthorized access or misconfigured permissions',
    'Audit log covers: table access, schema changes, permission grants/revokes, Delta Sharing, cluster ops',
  ],
  facts:[
    'status_code = 403 = permission denied — user attempted to access without sufficient privilege',
    'event_type: type of operation — e.g. getTable, updatePermissions, deltaSharingQueriedTable',
    'user_identity.email: who performed the action — principal identity',
    'Audit logs retained based on workspace retention settings — typically 365 days with UC',
  ],
  code:[
    '-- Find all failed permission checks (403 = unauthorized)',
    'SELECT',
    '    event_time,',
    '    user_identity.email                     AS user_email,',
    '    event_type,',
    '    request_params.full_name_arg            AS resource_accessed,',
    '    response.status_code,',
    '    response.error_message',
    'FROM system.access.audit',
    'WHERE response.status_code = 403',
    '  AND event_time > current_timestamp() - INTERVAL 24 HOURS',
    'ORDER BY event_time DESC;',
    '',
    '-- Find who granted permissions (compliance)',
    'SELECT',
    '    event_time,',
    '    user_identity.email                     AS granted_by,',
    '    request_params.changes                  AS permissions_granted,',
    '    request_params.securable_full_name      AS resource',
    'FROM system.access.audit',
    'WHERE event_type = \'updatePermissions\'',
    '  AND event_time > current_timestamp() - INTERVAL 30 DAYS',
    'ORDER BY event_time DESC;',
  ],
  trap:[
    '✗ status_code = 403 = permission denied — not a server error (500) or not found (404)',
    '✗ system.access.audit requires Unity Catalog',
    '✗ Audit covers ALL UC operations — not just data access, also permission changes',
    '✗ event_type distinguishes operation type — getTable, deltaSharingQueriedTable, updatePermissions',
    '✗ Audit logs are in the provider workspace for Delta Sharing — recipients cannot see',
    '✗ user_identity.email = who performed the action — always present for UC-governed operations',
  ],
},

// ─── 5.4.3 ───────────────────────────────────────────────────────────────────
{num:'12',title:'5.4.3 — system.access.table_access_history — Table-Level Access Tracking',
  what:[
    'system.access.table_access_history: tracks which tables were read or written by which queries/users',
    'More granular than system.access.audit — specifically focused on table-level data access',
    'Used for: data lineage, identifying unused tables, access frequency analysis',
  ],
  how:[
    'Every SQL query that accesses UC-governed tables generates a record in table_access_history',
    'Records: which tables read, which tables written, query text, user, timestamp',
    'Covers: SELECT reads, INSERT/UPDATE/DELETE writes, MERGE operations, COPY INTO',
    'Used by UC Data Lineage UI — same underlying data that powers the lineage graph',
  ],
  facts:[
    'table_access_history tracks actual DATA ACCESS — not just permission checks',
    'accessed_at: timestamp of access; query_text: the actual SQL executed',
    'table_changes: contains separate records for tables read vs tables written',
    'Requires Unity Catalog — not available for hive_metastore tables',
  ],
  code:[
    '-- Find all users who accessed a specific table in last 30 days',
    'SELECT',
    '    user_identity.email             AS user_email,',
    '    accessed_at,',
    '    operation_type,',
    '    query_text',
    'FROM system.access.table_access_history',
    'WHERE table_full_name = \'prod_catalog.sales.orders\'',
    '  AND accessed_at > current_timestamp() - INTERVAL 30 DAYS',
    'ORDER BY accessed_at DESC;',
    '',
    '-- Most frequently accessed tables',
    'SELECT',
    '    table_full_name,',
    '    COUNT(*)            AS access_count,',
    '    COUNT(DISTINCT user_identity.email) AS unique_users',
    'FROM system.access.table_access_history',
    'WHERE accessed_at > current_timestamp() - INTERVAL 30 DAYS',
    'GROUP BY table_full_name',
    'ORDER BY access_count DESC',
    'LIMIT 20;',
  ],
  trap:[
    '✗ table_access_history tracks DATA ACCESS — system.access.audit tracks ALL UC operations',
    '✗ Requires Unity Catalog — hive_metastore table access NOT tracked',
    '✗ Covers reads AND writes — operation_type distinguishes between them',
    '✗ Powers the Catalog Explorer lineage graph — same data used in lineage visualization',
    '✗ Different from system.access.audit — audit has 403 failures; access_history has only successful',
  ],
},

// ─── 5.4.4 ───────────────────────────────────────────────────────────────────
{num:'13',title:'5.4.4 — system.jobs.runs — Job History, Performance Trends',
  what:[
    'system.jobs.runs: system table recording all Databricks job run history',
    'Used for: SLA monitoring, performance trend analysis, failure rate tracking, cost attribution',
    'More accessible than the REST API for historical analysis — queryable with SQL',
  ],
  how:[
    'Every job run (triggered or scheduled) generates a record in system.jobs.runs',
    'Key fields: run_id, job_id, start_time, end_time, run_duration, result_state, state_message',
    'result_state: SUCCESS, FAILED, TIMEDOUT, CANCELED, UPSTREAM_FAILED',
    'state_message: failure details when result_state != SUCCESS',
  ],
  facts:[
    'system.jobs.runs requires Unity Catalog — not available in non-UC workspaces',
    'Retention: typically 60 days of job run history in the system table',
    'result_state only valid for completed runs — running jobs show RUNNING in life_cycle_state',
    'Combine with system.billing.usage (via run_id) to get cost per job run',
  ],
  code:[
    '-- Job failure rate in last 7 days',
    'SELECT',
    '    job_id,',
    '    job_name,',
    '    COUNT(*) AS total_runs,',
    '    SUM(CASE WHEN result_state = \'SUCCESS\' THEN 1 ELSE 0 END) AS successes,',
    '    SUM(CASE WHEN result_state = \'FAILED\'  THEN 1 ELSE 0 END) AS failures,',
    '    ROUND(100.0 * SUM(CASE WHEN result_state = \'FAILED\' THEN 1 ELSE 0 END) / COUNT(*), 1) AS failure_rate_pct',
    'FROM system.jobs.runs',
    'WHERE start_time > current_timestamp() - INTERVAL 7 DAYS',
    'GROUP BY job_id, job_name',
    'HAVING failures > 0',
    'ORDER BY failure_rate_pct DESC;',
    '',
    '-- Recent failed runs with error messages',
    'SELECT',
    '    run_id, job_id, job_name,',
    '    start_time, end_time,',
    '    result_state, state_message',
    'FROM system.jobs.runs',
    'WHERE result_state IN (\'FAILED\', \'TIMEDOUT\')',
    '  AND start_time > current_timestamp() - INTERVAL 24 HOURS',
    'ORDER BY start_time DESC;',
  ],
  trap:[
    '✗ system.jobs.runs requires Unity Catalog',
    '✗ result_state only valid when life_cycle_state = TERMINATED — check lifecycle first',
    '✗ state_message contains the failure reason — key field for debugging',
    '✗ Combine with system.billing.usage via run_id for per-run cost attribution',
    '✗ Table retains ~60 days of history — use external storage for longer retention',
  ],
},

// ─── 5.4.5 ───────────────────────────────────────────────────────────────────
{num:'14',title:'5.4.5 — system.lakeflow.pipeline_events — Pipeline Failures, Data Quality',
  what:[
    'system.lakeflow.pipeline_events: system table recording all DLT (Lakeflow) pipeline events',
    'Captures: pipeline updates, table-level flow progress, data quality expectation results, errors',
    'Used for: DLT pipeline monitoring, data quality trend analysis, failure investigation',
  ],
  how:[
    'Every DLT pipeline update generates events across multiple event_type categories',
    'flow_progress events: per-table status (RUNNING, COMPLETED, FAILED) and data quality metrics',
    'error events: full exception details when a pipeline or flow fails',
    'data_quality metrics: expectations results — rows passed, rows failed, rows dropped',
  ],
  facts:[
    'system.lakeflow.pipeline_events requires Unity Catalog',
    'event_type: flow_progress, error, warning, planning — filter by type for focused analysis',
    'Data quality results: details:flow_progress.data_quality.expectations — JSON array',
    'update_id: unique per pipeline run — use to correlate all events for one pipeline update',
  ],
  code:[
    '-- Recent pipeline failures',
    'SELECT',
    '    pipeline_id,',
    '    pipeline_name,',
    '    update_id,',
    '    timestamp,',
    '    event_type,',
    '    message',
    'FROM system.lakeflow.pipeline_events',
    'WHERE event_type = \'error\'',
    '  AND timestamp > current_timestamp() - INTERVAL 24 HOURS',
    'ORDER BY timestamp DESC;',
    '',
    '-- Data quality summary per pipeline run',
    'SELECT',
    '    pipeline_name,',
    '    update_id,',
    '    details:flow_progress.name                AS table_name,',
    '    details:flow_progress.data_quality.expectations AS expectations_json',
    'FROM system.lakeflow.pipeline_events',
    'WHERE event_type = \'flow_progress\'',
    '  AND details:flow_progress.data_quality IS NOT NULL',
    'ORDER BY timestamp DESC;',
  ],
  trap:[
    '✗ system.lakeflow.pipeline_events requires Unity Catalog',
    '✗ event_type = flow_progress for per-table status; event_type = error for failures',
    '✗ JSON field access uses colon syntax: details:flow_progress.status',
    '✗ update_id links all events for ONE pipeline run',
    '✗ dropped_records in data quality = rows dropped by expect_or_drop expectations',
    '✗ Pipeline event log retained ~30 days by default — export to Delta for longer retention',
  ],
},

// ─── 5.5.1 ───────────────────────────────────────────────────────────────────
{num:'15',title:'5.5.1 — Alert States: OK, TRIGGERED, UNKNOWN',
  what:[
    'SQL Alert: a scheduled query in DBSQL that monitors a metric and sends notifications',
    'Three states: OK (condition not met), TRIGGERED (condition met), UNKNOWN (query failed or never run)',
    'Alerts check a SQL query result against a threshold condition — e.g. COUNT(*) > 1000',
  ],
  how:[
    'Alert defines: a saved SQL query, a condition, and notification destinations',
    'Schedule: alert runs the query on a schedule — checks if result meets the trigger condition',
    'OK: query ran, condition NOT met — no notification sent',
    'TRIGGERED: query ran, condition IS met — notifications sent',
    'UNKNOWN: query has never run OR query failed — alert cannot evaluate condition',
  ],
  facts:[
    'Alert condition examples: Value > 1000, Value == 0, Value IS NOT NULL',
    'Notification destinations: email, Slack, PagerDuty, webhook',
    'Alert state visible in DBSQL Alerts page — color coded: green (OK), red (TRIGGERED), grey (UNKNOWN)',
    'Alert evaluates the FIRST row, FIRST column of the query result',
  ],
  code:[
    '-- Example alert query: count of failed pipeline runs today',
    '-- Alert condition: Value > 0 (trigger if any failures)',
    'SELECT COUNT(*) AS value',
    'FROM system.jobs.runs',
    'WHERE result_state = \'FAILED\'',
    '  AND DATE(start_time) = current_date();',
    '',
    '-- Example: check data freshness',
    '-- Alert condition: Value > 60 (trigger if data more than 60 minutes stale)',
    'SELECT',
    '    DATEDIFF(MINUTE, MAX(updated_at), current_timestamp()) AS value',
    'FROM catalog.schema.orders;',
  ],
  trap:[
    '✗ Three alert states: OK, TRIGGERED, UNKNOWN — UNKNOWN means query failed or never run',
    '✗ Alert evaluates FIRST row, FIRST column of query result — return single value',
    '✗ UNKNOWN state does NOT send notifications by default',
    '✗ Alert condition must match the query output column name exactly — case-sensitive',
    '✗ Alert does not auto-resolve — once TRIGGERED, stays TRIGGERED until next check shows OK',
  ],
},

// ─── 5.5.2 ───────────────────────────────────────────────────────────────────
{num:'16',title:'5.5.2 — Notification Frequency Trap — Stops Firing != Resolved',
  what:[
    'Notification frequency: controls how often notifications are sent when alert remains TRIGGERED',
    'Critical exam trap: if notifications stop after N times, it does NOT mean condition is resolved',
    'Three options: ONCE (fire once then silent), EACH TIME (every check), CUSTOM (every N checks)',
  ],
  how:[
    'Once: sends one notification when alert first TRIGGERS — never sends again even if condition persists',
    'Each Time: sends notification EVERY time scheduled check finds condition still TRIGGERED',
    'Custom frequency: sends every N checks — e.g. every 5 checks sends one notification',
    'Stopping notifications != alert resolved — alert may still be in TRIGGERED state',
  ],
  facts:[
    'UNKNOWN state: if alert query fails — alert moves to UNKNOWN — notifications may stop',
    'Notifications stop when: (a) condition resolved (OK state), OR (b) Once frequency limit reached',
    'Alert dashboard always shows current state — even if notifications stopped, alert may still be TRIGGERED',
    'on_failure webhook notifications for alerts are separate from the alert state notifications',
  ],
  ascii:true,
  code:[
    'NOTIFICATION FREQUENCY BEHAVIOR:',
    '',
    'SCENARIO: Alert condition triggers Monday, frequency = ONCE',
    '',
    'Mon 09:00 -> Query runs -> Condition MET -> State: TRIGGERED',
    '            -> Notification sent: "Alert triggered!" -> FIRES ONCE',
    'Mon 09:30 -> Query runs -> Condition still MET -> State: TRIGGERED',
    '            -> NO notification sent (frequency limit = once reached)',
    '',
    'EXAM TRAP: "Notifications stopped Monday morning — is the alert resolved?"',
    'ANSWER: NO! Alert is still TRIGGERED — notifications stopped due to ONCE frequency',
    'FIX: Check alert state in DBSQL Alerts page — still shows RED (TRIGGERED)',
    '',
    'NOTIFICATION FREQUENCY = "Each Time":',
    'Mon 09:00 -> Triggered -> SENDS notification',
    'Mon 09:30 -> Still triggered -> SENDS notification (again)',
    '',
    'UNKNOWN STATE TRAP:',
    'Mon 09:00 -> Query FAILS -> State: UNKNOWN',
    '            -> No notification (query did not execute)',
    'Mon 09:30 -> Query FAILS again -> State: UNKNOWN',
    '            -> Condition might still be triggered — we do not know!',
  ],
  trap:[
    '✗ Notifications stopped != condition resolved — could be Once frequency or UNKNOWN state',
    '✗ Alert dashboard always shows CURRENT STATE regardless of notification frequency',
    '✗ ONCE frequency: one notification ever — even if condition persists for days',
    '✗ EACH TIME: notification on every check — can be noisy',
    '✗ UNKNOWN state: alert query failed — no condition evaluation, may still be triggered',
    '✗ on_failure notification for failed alert queries is separate from alert trigger notifications',
  ],
},

// ─── 5.6.1 ───────────────────────────────────────────────────────────────────
{num:'17',title:'5.6.1 — Polling Run Status via API (life_cycle_state, result_state)',
  what:[
    'Job monitoring via REST API: programmatically check job run status by polling the Jobs API',
    'Two key state fields: life_cycle_state (current execution phase) and result_state (final outcome)',
    'result_state is only valid when life_cycle_state = TERMINATED',
  ],
  how:[
    'GET /api/2.1/jobs/runs/get?run_id=<id>: returns current run status',
    'life_cycle_state: PENDING, RUNNING, TERMINATING, TERMINATED, SKIPPED, INTERNAL_ERROR',
    'result_state: only populated when life_cycle_state = TERMINATED — SUCCESS, FAILED, etc.',
    'Polling pattern: loop until life_cycle_state = TERMINATED, then check result_state',
  ],
  facts:[
    'result_state is ONLY valid when life_cycle_state = TERMINATED — not during RUNNING',
    'UPSTREAM_FAILED: task never ran because an upstream dependency failed',
    'INTERNAL_ERROR: Databricks infrastructure error — not a user code failure',
    'Polling interval: use exponential backoff — avoid hammering the API',
  ],
  code:[
    'import time',
    'import requests',
    '',
    'def poll_run_status(run_id, poll_interval_sec=30):',
    '    headers = {"Authorization": f"Bearer {TOKEN}"}',
    '    url = f"{HOST}/api/2.1/jobs/runs/get"',
    '',
    '    while True:',
    '        response = requests.get(url, headers=headers, params={"run_id": run_id})',
    '        run_info = response.json()',
    '',
    '        lifecycle = run_info["state"]["life_cycle_state"]',
    '        print(f"Run {run_id}: life_cycle_state = {lifecycle}")',
    '',
    '        if lifecycle == "TERMINATED":',
    '            result = run_info["state"]["result_state"]',
    '            print(f"Run {run_id}: TERMINATED with result_state = {result}")',
    '            return run_info["state"]',
    '',
    '        elif lifecycle == "INTERNAL_ERROR":',
    '            return run_info["state"]',
    '',
    '        time.sleep(poll_interval_sec)',
  ],
  trap:[
    '✗ result_state ONLY valid when life_cycle_state = TERMINATED — check lifecycle FIRST',
    '✗ UPSTREAM_FAILED = task NEVER RAN — upstream dependency failed',
    '✗ INTERNAL_ERROR = Databricks infrastructure issue — not user code',
    '✗ TERMINATING -> TERMINATED is a brief transition — wait for TERMINATED before reading result',
    '✗ Always check life_cycle_state before result_state — result is null until lifecycle = TERMINATED',
  ],
},

// ─── 5.6.2 ───────────────────────────────────────────────────────────────────
{num:'18',title:'5.6.2 — Notification Config: on_start, on_success, on_failure, max_retries=-1',
  what:[
    'Job notification configuration: email or webhook notifications triggered at lifecycle events',
    'Four triggers: on_start, on_success, on_failure, on_duration_warning_threshold_exceeded',
    'Critical trap: max_retries = -1 means INFINITE retries — on_failure NEVER fires',
  ],
  how:[
    'Notifications configured per job task — different recipients for each event type',
    'on_start: fires when job run begins',
    'on_success: fires when job completes with result_state = SUCCESS',
    'on_failure: fires when result_state = FAILED (after all retries exhausted)',
    'on_duration_warning_threshold_exceeded: fires if job runs longer than threshold',
  ],
  facts:[
    'max_retries = -1: INFINITE retries — job retries forever, NEVER reaches FAILED, on_failure NEVER fires',
    'max_retries = 0: no retries — one failure triggers on_failure immediately',
    'max_retries = 3: three retries — on_failure fires only after the 4th failure',
    'Notification destinations: email, Slack webhooks, PagerDuty integration, generic webhooks',
  ],
  ascii:true,
  code:[
    'MAX RETRIES BEHAVIOR:',
    '',
    'max_retries = -1 (infinite):',
    '  Run 1 -> FAILS -> retry',
    '  Run 2 -> FAILS -> retry',
    '  Run 3 -> FAILS -> retry',
    '  ... forever ...',
    '  on_failure notification: NEVER FIRES',
    '  (job never reaches FAILED state — always retrying)',
    '',
    'max_retries = 3:',
    '  Run 1 -> FAILS -> retry (1 of 3)',
    '  Run 2 -> FAILS -> retry (2 of 3)',
    '  Run 3 -> FAILS -> retry (3 of 3)',
    '  Run 4 -> FAILS -> NO more retries -> FAILED state',
    '  on_failure notification: FIRES (after 4th failure)',
    '',
    'max_retries = 0:',
    '  Run 1 -> FAILS -> NO retries',
    '  on_failure notification: FIRES immediately',
    '',
    'JSON CONFIG:',
    '{',
    '  "email_notifications": {',
    '    "on_start": ["team@company.com"],',
    '    "on_success": ["team@company.com"],',
    '    "on_failure": ["oncall@company.com"],',
    '    "no_alert_for_skipped_runs": true',
    '  }',
    '}',
  ],
  trap:[
    '✗ max_retries = -1 means INFINITE retries — on_failure notification NEVER fires',
    '✗ on_failure fires ONLY after ALL retries exhausted and job reaches FAILED state',
    '✗ With max_retries = -1: job never reaches FAILED state — retries forever or until manually stopped',
    '✗ on_duration_warning_threshold_exceeded fires if job runs LONGER than threshold',
    '✗ no_alert_for_skipped_runs = true: suppresses notifications for UPSTREAM_FAILED tasks',
    '✗ Notification config is PER-TASK — different tasks can have different recipients',
  ],
},

// ─── 5.6.3 ───────────────────────────────────────────────────────────────────
{num:'19',title:'5.6.3 — UPSTREAM_FAILED vs FAILED Distinction',
  what:[
    'Two distinct task result states for failures: FAILED and UPSTREAM_FAILED',
    'FAILED: the task ran and failed during execution',
    'UPSTREAM_FAILED: the task NEVER RAN because an upstream dependency failed',
  ],
  how:[
    'In a multi-task job DAG: failure of an upstream task cascades to its dependents',
    'Failed task -> result_state = FAILED',
    'Tasks downstream of the failed task -> result_state = UPSTREAM_FAILED (never started)',
    'Repair run: re-runs both FAILED and UPSTREAM_FAILED tasks',
  ],
  facts:[
    'UPSTREAM_FAILED tasks have NO state_message of their own — failure is in upstream',
    'Repair run cascades: re-running upstream FAILED task automatically re-queues UPSTREAM_FAILED',
    'no_alert_for_skipped_runs = true suppresses notifications for UPSTREAM_FAILED — avoids alert storms',
    'Tasks with run_if = ALL_DONE run regardless of upstream success/failure',
  ],
  ascii:true,
  code:[
    'TASK DAG WITH FAILURE:',
    '',
    '[Task A: SUCCESS] -> [Task B: FAILED] -> [Task C: UPSTREAM_FAILED]',
    '                                       -> [Task D: UPSTREAM_FAILED]',
    '[Task E: SUCCESS] (parallel branch — unaffected)',
    '',
    'Task A: completed successfully -> SUCCESS',
    'Task B: ran but failed         -> FAILED (state_message has error)',
    'Task C: never ran (B failed)   -> UPSTREAM_FAILED (no state_message)',
    'Task D: never ran (B failed)   -> UPSTREAM_FAILED (no state_message)',
    'Task E: parallel, unaffected   -> SUCCESS',
    '',
    'REPAIR RUN:',
    '  Re-runs: B (FAILED) and C, D (UPSTREAM_FAILED)',
    '  Skips: A and E (already SUCCESS)',
    '',
    'DEBUGGING TIP:',
    '  When seeing UPSTREAM_FAILED — find the upstream FAILED task',
    '  Fix the FAILED task root cause, then repair run',
    '  UPSTREAM_FAILED is a symptom, not the cause',
  ],
  trap:[
    '✗ UPSTREAM_FAILED = task NEVER RAN — different from FAILED (task ran and failed)',
    '✗ UPSTREAM_FAILED has no state_message — failure context is in the FAILED upstream task',
    '✗ Repair run re-runs BOTH FAILED and UPSTREAM_FAILED — cascade is automatic',
    '✗ no_alert_for_skipped_runs = true suppresses UPSTREAM_FAILED alerts — useful for noisy DAGs',
    '✗ When debugging: ALWAYS find the UPSTREAM FAILED task first — it has the actual error',
    '✗ run_if = ALL_DONE makes a task run even if upstream failed — useful for cleanup tasks',
  ],
},

// ─── 5.6.4 ───────────────────────────────────────────────────────────────────
{num:'20',title:'5.6.4 — Repair Run Re-uses Same run_id',
  what:[
    'Repair run: re-executes only FAILED and UPSTREAM_FAILED tasks from a previous run',
    'Critical fact: repair uses the SAME run_id as the original — NOT a new run',
    'Successful tasks are NOT re-run — preserves results from the original run',
  ],
  how:[
    'API: POST /api/2.1/jobs/runs/repair with the run_id of the failed run',
    'Optionally specify rerun_tasks list — if omitted, repairs ALL failed tasks',
    'Parameter overrides: can pass new parameters for the repair attempt only',
    'Multiple repairs: can repair the same run multiple times if repair itself fails',
  ],
  facts:[
    'Repair run keeps original run_id — appears in DESCRIBE HISTORY as a repair entry',
    'Parameter overrides are ONE-TIME — not persisted to job definition',
    'Repair only re-runs FAILED and UPSTREAM_FAILED tasks — SUCCESS tasks NOT re-run',
    'After repair: result_state of the run is re-evaluated based on repair outcome',
  ],
  code:[
    '# Repair all failed tasks',
    'POST /api/2.1/jobs/runs/repair',
    '{',
    '    "run_id": 67890',
    '}',
    '',
    '# Repair specific tasks with parameter overrides',
    'POST /api/2.1/jobs/runs/repair',
    '{',
    '    "run_id": 67890,',
    '    "rerun_tasks": ["failed_etl_task"],',
    '    "notebook_params": {',
    '        "start_date": "2024-01-01",',
    '        "batch_size": "5000"',
    '    }',
    '}',
    '',
    '# Via Databricks CLI',
    'databricks jobs repair-run --run-id 67890',
    '',
    '# UI: Jobs -> Run History -> Failed Run -> "Repair Run" button',
  ],
  trap:[
    '✗ Repair run uses SAME run_id — not a new run_id',
    '✗ Repair only re-runs FAILED and UPSTREAM_FAILED — SUCCESS tasks NOT re-run',
    '✗ Parameter overrides in repair are ONE-TIME — NOT persisted to job definition',
    '✗ Next scheduled run uses ORIGINAL job parameters — override was only for this repair',
    '✗ Can repair the same run multiple times — if repair fails, repair again',
    '✗ Repair is idempotent for successful tasks — they are not re-run, no duplication',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain5_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
