'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 4  —  Data Sharing & Federation  —  8 Sub-Topics',
  groups: [
    ['4.1  Delta Sharing',[
      ['01','4.1.1','Share, Recipient, Provider Roles'],
      ['02','4.1.2','D2D vs D2O — Databricks-to-Databricks vs Databricks-to-Open'],
      ['03','4.1.3','Schema Sharing Auto-Includes ALL Future Tables'],
      ['04','4.1.4','Delta Sharing Audit in system.access.audit'],
    ]],
    ['4.2  Lakehouse Federation',[
      ['05','4.2.1','Connection, Foreign Catalog — Supported Sources'],
      ['06','4.2.2','UC Row Filters/Column Masks Do NOT Apply to Federation Tables'],
      ['07','4.2.3','Federation is Read-Only (SELECT Only)'],
      ['08','4.2.4','Delta Sharing vs Lakehouse Federation — Full Comparison'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 4  —  Data Sharing & Federation  —  All High-Priority Traps',
};

const pages = [

// ─── 4.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'4.1.1 — Share, Recipient, Provider Roles',
  what:[
    'Delta Sharing: open protocol for sharing live Delta table data across organizations without copying data',
    'Three core roles: Provider (owns and shares data), Share (logical container), Recipient (consumer)',
    'Data stays in the provider cloud storage — recipient queries data via REST API, no data movement',
  ],
  how:[
    'Provider: the Databricks workspace that owns the Delta tables and creates shares',
    'Share: a named, logical container — provider adds tables, views, schemas, or volumes to a share',
    'Recipient: an identity that the provider grants access to a share — receives activation link or token',
    'Recipient activates with the token, configures their client (Databricks, pandas, Power BI), queries data',
  ],
  facts:[
    'Delta Sharing is an open protocol — non-Databricks clients (pandas, Power BI, Tableau) can consume',
    'Provider controls access: can expire shares, remove recipients, rotate tokens, audit access logs',
    'Data stays in provider cloud storage — recipient reads directly via signed URLs',
    'Unity Catalog manages the provider side — recipients can be inside OR outside Databricks',
  ],
  code:[
    '-- PROVIDER: Create and configure a share',
    'CREATE SHARE sales_external_share',
    '    COMMENT \'Monthly sales data for external partners\';',
    '',
    'ALTER SHARE sales_external_share',
    'ADD TABLE catalog.schema.monthly_summary;',
    '',
    'CREATE RECIPIENT partner_analytics_team',
    '    COMMENT \'External BI team at partner company\';',
    '',
    'DESCRIBE RECIPIENT partner_analytics_team;',
    '-- Returns: activation_link field — send to recipient',
    '',
    'GRANT SELECT ON SHARE sales_external_share',
    'TO RECIPIENT partner_analytics_team;',
    '',
    'SHOW SHARES;',
    'SHOW ALL IN SHARE sales_external_share;',
    '',
    '-- RECIPIENT (D2D)',
    'CREATE PROVIDER acme_corp_provider',
    '    DELTA_SHARING_SERVER \'https://sharing.azuredatabricks.net/...\';',
    '',
    'CREATE CATALOG acme_shared_data',
    '    USING SHARE acme_corp_provider.sales_external_share;',
    '',
    'SELECT * FROM acme_shared_data.sales_schema.monthly_summary;',
  ],
  mistakes:[
    '✗ Assuming Delta Sharing copies data to the recipient — data NEVER moves',
    '✗ Granting access to a share without creating a recipient first — must create recipient first',
    '✗ Forgetting that adding a schema to a share includes ALL future tables — exposure risk',
  ],
  trap:[
    '✗ Delta Sharing does NOT copy data — recipient reads directly from provider cloud storage via signed URLs',
    '✗ Data stays in provider cloud account — not in Databricks infrastructure, not recipient account',
    '✗ Provider controls access and can EXPIRE or REVOKE at any time',
    '✗ Recipient access is READ-ONLY — recipients cannot write back under any circumstance',
    '✗ Delta Sharing requires Unity Catalog on the provider side — cannot share hive_metastore tables',
    '✗ Share is the logical container — tables, schemas, and volumes are added TO the share',
    '✗ Recipient gets an activation link/token — this is a ONE-TIME use activation credential',
  ],
},

// ─── 4.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'4.1.2 — D2D (Databricks-to-Databricks) vs D2O (Databricks-to-Open)',
  what:[
    'D2D (Databricks-to-Databricks): sharing between two Databricks workspaces — both use UC',
    'D2O (Databricks-to-Open): sharing with non-Databricks consumers — open protocol, credential file',
    'Both use the same Delta Sharing protocol — difference is in how the recipient authenticates and queries',
  ],
  how:[
    'D2D flow: recipient workspace creates a provider reference, creates catalog from share, queries via UC',
    'D2O flow: recipient downloads credential file (.share file), uses Delta Sharing connector library',
    'D2O connectors: Apache Spark, pandas, Power BI, Tableau, Apache Flink, Rust, Java',
    'D2D automatically handles token management — D2O requires recipient to manage credential file',
  ],
  facts:[
    'D2D: recipient can browse shares via Unity Catalog UI and SQL — no credential file needed',
    'D2O: recipient uses Delta Sharing open protocol client library — delta_sharing.load_as_pandas(url)',
    'Both modes: data stays in provider storage, recipient reads via short-lived signed URLs',
    'D2D: recipient sees shared data as a foreign catalog in their UC — queries look like catalog.schema.table',
  ],
  ascii:true,
  code:[
    'D2D (Databricks-to-Databricks):',
    '',
    'PROVIDER workspace (UC)          RECIPIENT workspace (UC)',
    '  Share: sales_share        ->   Provider reference -> Foreign Catalog',
    '  Table: orders                  SQL: SELECT * FROM acme.sales.orders',
    '  Recipient: partner_ws          Looks like a local UC table query',
    '  Token: managed by UC           Token: auto-managed by UC',
    '',
    'D2O (Databricks-to-Open — pandas consumer):',
    '',
    'PROVIDER workspace (UC)          RECIPIENT (any platform)',
    '  Share: sales_share        ->   Download .share credential file',
    '  Table: orders                  import delta_sharing',
    '  Recipient: partner_client      df = delta_sharing.load_as_pandas(',
    '  Token: in .share file              "profile.share#sales.schema.orders")',
    '',
    'Both modes:',
    '  Data stays at provider S3/ADLS/GCS',
    '  Provider issues short-lived signed URLs for each read',
    '  Recipient never has direct storage credentials',
  ],
  mistakes:[
    '✗ Assuming D2O only works with Spark — Delta Sharing open protocol works with pandas, Power BI, Tableau',
    '✗ Thinking D2D and D2O use different underlying protocols — both use same REST API',
    '✗ Expecting D2O recipients to have direct storage access — always go via signed URLs from provider',
  ],
  trap:[
    '✗ D2D: recipient sees share as a foreign catalog in their UC — seamless SQL access',
    '✗ D2O: recipient uses a credential file (.share file) downloaded from activation link',
    '✗ Both D2D and D2O: data NEVER copied to recipient — short-lived signed URLs used for each read',
    '✗ D2O supports non-Databricks clients: pandas, Power BI, Tableau, Apache Spark open source',
    '✗ D2D token management is AUTOMATIC — UC handles it; D2O recipient manages their own .share file',
    '✗ D2D recipient creates a catalog from the share — not a database or schema, a full catalog',
    '✗ Both modes: provider can revoke access at any time by disabling the recipient',
  ],
},

// ─── 4.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'4.1.3 — Schema Sharing Auto-Includes ALL Future Tables',
  what:[
    'When a schema (not individual tables) is added to a Delta Share, ALL current AND future tables are shared',
    'This is a critical behavior difference from adding individual tables to a share',
    'Future tables: any table created in that schema AFTER the schema was added is automatically accessible',
  ],
  how:[
    'ALTER SHARE share_name ADD TABLE schema.table: adds ONE specific table — explicit, controlled',
    'ALTER SHARE share_name ADD SCHEMA catalog.schema_name: adds ALL tables — current AND future',
    'When a new table is created in shared schema: immediately accessible to all recipients',
    'Provider may not realize they are automatically exposing new tables — major governance risk',
  ],
  facts:[
    'Schema-level sharing = automatic future table exposure — no opt-in required for new tables',
    'Table-level sharing = explicit control — only listed tables, new tables NOT included',
    'Removing schema from share: ALTER SHARE share_name REMOVE SCHEMA schema_name',
    'Best practice: prefer table-level sharing for production — schema-level for trusted internal partners only',
  ],
  ascii:true,
  code:[
    'TABLE-LEVEL SHARING (explicit, controlled):',
    '',
    'ALTER SHARE my_share ADD TABLE catalog.sales.orders;',
    'ALTER SHARE my_share ADD TABLE catalog.sales.customers;',
    '',
    '-> Only orders and customers are shared',
    '-> New table catalog.sales.products created later:',
    '   NOT automatically shared — must explicitly add it',
    '-> SAFE for external sharing',
    '',
    'SCHEMA-LEVEL SHARING (auto-includes future tables):',
    '',
    'ALTER SHARE my_share ADD SCHEMA catalog.sales;',
    '',
    '-> All current tables shared: orders, customers',
    '-> New table catalog.sales.products created later:',
    '   AUTOMATICALLY shared to all recipients!',
    '-> New table catalog.sales.pii_data created later:',
    '   ALSO AUTOMATICALLY shared — GOVERNANCE RISK!',
    '',
    'Best practice:',
    '  External partners -> TABLE-level sharing (explicit)',
    '  Trusted internal consumers -> SCHEMA-level sharing (convenient)',
    '',
    '-- Verify share contents regularly',
    'SHOW ALL IN SHARE partner_share;',
  ],
  mistakes:[
    '✗ Adding a schema to an external partner share without realizing future tables are auto-included',
    '✗ Creating sensitive tables (PII, financial) in a schema added to an external share',
    '✗ Not periodically auditing share contents — SHOW ALL IN SHARE should be run regularly',
  ],
  trap:[
    '✗ Adding a SCHEMA to a share = ALL current AND ALL FUTURE tables automatically shared',
    '✗ Adding individual TABLES to a share = explicit control — new tables NOT automatically shared',
    '✗ New table created in a shared schema is IMMEDIATELY accessible to recipients — no delay',
    '✗ SHOW ALL IN SHARE share_name shows current share contents — use to audit',
    '✗ Schema-level sharing is a GOVERNANCE RISK for external partners',
    '✗ Removing schema from share: ALTER SHARE name REMOVE SCHEMA — revokes all tables at once',
    '✗ This behavior applies to UC schemas only — cannot share hive_metastore schemas',
  ],
},

// ─── 4.1.4 ───────────────────────────────────────────────────────────────────
{num:'04',title:'4.1.4 — Delta Sharing Audit in system.access.audit',
  what:[
    'Delta Sharing access is audited in the Unity Catalog system.access.audit system table',
    'Every recipient data access (reads via Delta Sharing) generates an audit log entry',
    'Enables: compliance reporting, access monitoring, detecting unauthorized access patterns',
  ],
  how:[
    'system.access.audit: records all Delta Sharing access events — who, what, when, from where',
    'Audit fields: event_time, event_type, user_identity, request_params, response, source_ip_address',
    'Event types for Delta Sharing: deltaSharingQueriedTable, deltaSharingQueryTableChanges, deltaSharingGetTableMetadata',
    'Audit log available in provider Unity Catalog — provider can see all recipient access activity',
  ],
  facts:[
    'system.access.audit requires Unity Catalog — available in workspaces with UC enabled',
    'Audit logs retained based on workspace retention settings — typically 365 days',
    'Provider can see WHICH recipient accessed WHICH table at WHAT time — full visibility',
    'system.access.audit also covers: table access, permission changes, cluster creation',
  ],
  code:[
    '-- Query Delta Sharing audit events',
    'SELECT',
    '    event_time,',
    '    event_type,',
    '    user_identity.email                              AS recipient_email,',
    '    request_params.share                             AS share_name,',
    '    request_params.schema                            AS schema_name,',
    '    request_params.name                              AS table_name,',
    '    response.status_code,',
    '    source_ip_address',
    'FROM system.access.audit',
    'WHERE event_type LIKE \'deltaSharing%\'',
    '  AND event_time > current_timestamp() - INTERVAL 7 DAYS',
    'ORDER BY event_time DESC;',
    '',
    '-- Find all accesses to a specific shared table',
    'SELECT event_time, user_identity.email, source_ip_address',
    'FROM system.access.audit',
    'WHERE event_type = \'deltaSharingQueriedTable\'',
    '  AND request_params.name = \'monthly_summary\'',
    'ORDER BY event_time DESC;',
    '',
    '-- Summary: access count per recipient',
    'SELECT',
    '    user_identity.email AS recipient,',
    '    COUNT(*) AS access_count,',
    '    MAX(event_time) AS last_access',
    'FROM system.access.audit',
    'WHERE event_type = \'deltaSharingQueriedTable\'',
    'GROUP BY user_identity.email',
    'ORDER BY access_count DESC;',
  ],
  mistakes:[
    '✗ Looking for Delta Sharing audit in job logs or cluster logs — it is in system.access.audit',
    '✗ Expecting real-time audit alerts — system.access.audit is a queryable table, not a stream',
    '✗ Forgetting system.access.audit covers ALL UC events — filter by event_type',
  ],
  trap:[
    '✗ Delta Sharing audit is in system.access.audit — NOT in system.billing.usage or job logs',
    '✗ Requires Unity Catalog — not available in workspaces without UC enabled',
    '✗ event_type LIKE \'deltaSharing%\' filters to Delta Sharing events — multiple event types',
    '✗ Provider sees ALL recipient access — full visibility into who read what and when',
    '✗ system.access.audit covers more than Delta Sharing — also table access, permission changes',
    '✗ Audit logs are in the PROVIDER workspace UC — recipients cannot see these audit records',
    '✗ deltaSharingQueriedTable = actual data read; deltaSharingGetTableMetadata = schema peek only',
  ],
},

// ─── 4.2.1 ───────────────────────────────────────────────────────────────────
{num:'05',title:'4.2.1 — Connection, Foreign Catalog — Supported Sources',
  what:[
    'Lakehouse Federation: Unity Catalog feature for querying external database systems without moving data',
    'Creates a Connection (credentials/endpoint) and a Foreign Catalog (logical mapping) in UC',
    'Supported sources: PostgreSQL, MySQL, SQL Server, Snowflake, Redshift, BigQuery, Databricks (remote)',
  ],
  how:[
    'Connection: stores external system connection details (host, port, database, credentials) in UC',
    'Foreign Catalog: maps an external database to a UC catalog — tables appear as first-class UC objects',
    'Querying foreign catalog: SELECT * FROM foreign_catalog.schema.table — Spark pushes via JDBC',
    'Query result: fetched from external system, returned to Spark — no data persisted in Databricks',
  ],
  facts:[
    'Supported types: PostgreSQL, MySQL, SQL Server, Snowflake, Redshift, BigQuery, Databricks-to-Databricks',
    'Foreign catalog tables are read-only — SELECT queries only, no INSERT/UPDATE/DELETE',
    'Credentials stored in UC Connection object — not in plain text in notebooks or job configs',
    'Query performance: depends on external system compute — Databricks fetches results via JDBC',
  ],
  code:[
    '-- Step 1: Create a connection (stores credentials securely in UC)',
    'CREATE CONNECTION postgresql_prod',
    'TYPE POSTGRESQL',
    'OPTIONS (',
    '    host \'prod-postgres.company.com\',',
    '    port \'5432\',',
    '    database \'analytics_db\',',
    '    user \'databricks_reader\',',
    '    password secret(\'db_scope\', \'postgres_password\')',
    ');',
    '',
    '-- Step 2: Create a foreign catalog from the connection',
    'CREATE FOREIGN CATALOG postgres_analytics',
    'USING CONNECTION postgresql_prod',
    'OPTIONS (database \'analytics_db\');',
    '',
    '-- Step 3: Query external tables through UC (no data movement)',
    'SELECT order_id, amount, status',
    'FROM postgres_analytics.public.orders',
    'WHERE order_date >= \'2024-01-01\';',
    '',
    '-- Join external table with local Delta table',
    'SELECT o.order_id, o.amount, c.name AS customer_name',
    'FROM postgres_analytics.public.orders o',
    'JOIN catalog.schema.customers c ON o.customer_id = c.customer_id;',
  ],
  mistakes:[
    '✗ Expecting Federation queries to perform like local Delta queries — depends on external system',
    '✗ Storing connection credentials in notebook code — UC Connection object manages securely',
    '✗ Expecting Federation to support write operations — Federation tables are read-only',
  ],
  trap:[
    '✗ Federation is READ-ONLY — SELECT only, no INSERT, UPDATE, DELETE, or DDL on foreign tables',
    '✗ Credentials stored in UC Connection object — not in cluster config or notebook env vars',
    '✗ Query performance depends on EXTERNAL system — Spark fetches via JDBC, no distributed pushdown',
    '✗ Foreign catalog tables appear in UC alongside local catalogs — seamless governance surface',
    '✗ Federation does NOT copy data — each query hits the external system live',
    '✗ UC row filters and column masks do NOT apply to Federation tables (covered in 4.2.2)',
    '✗ Connection stores credentials securely — secret() function references a UC secret scope',
  ],
},

// ─── 4.2.2 ───────────────────────────────────────────────────────────────────
{num:'06',title:'4.2.2 — UC Row Filters/Column Masks Do NOT Apply to Federation Tables',
  what:[
    'Unity Catalog row filters and column masks are NOT enforced on Federation foreign catalog tables',
    'Critical security limitation — UC governance features that work on Delta tables do NOT work on federated',
    'If a row filter is defined on a foreign table, it is silently NOT applied — users see unfiltered data',
  ],
  how:[
    'UC row filters and column masks work by intercepting Spark SQL queries on Delta tables',
    'For foreign catalog tables: queries pushed down to the external system via JDBC',
    'External database enforces its own permissions — Databricks cannot add row-level security',
    'Result: all data returned by the external system JDBC query is visible to the Databricks user',
  ],
  facts:[
    'Row filters and column masks: work on Delta tables in UC — do NOT work on foreign catalog tables',
    'Security for federated tables must be managed at the source database level — not in UC',
    'This limitation is by design — UC cannot intercept JDBC query results from external systems',
    'Privilege model still applies: users still need SELECT on the foreign catalog table',
  ],
  ascii:true,
  code:[
    'UC ROW FILTER — works on Delta tables:',
    '',
    'ALTER TABLE local_delta_table',
    'SET ROW FILTER my_filter_fn ON (region_col);',
    '',
    'User runs: SELECT * FROM local_delta_table',
    '-> UC intercepts -> injects WHERE region_col = current_user()',
    '-> User sees filtered rows  WORKS',
    '',
    'UC ROW FILTER — does NOT work on Federation tables:',
    '',
    'ALTER TABLE postgres_analytics.public.orders',
    'SET ROW FILTER my_filter_fn ON (region_col);',
    '-- May succeed but has NO EFFECT',
    '',
    'User runs: SELECT * FROM postgres_analytics.public.orders',
    '-> Databricks sends JDBC query to PostgreSQL',
    '-> PostgreSQL returns ALL rows (no UC filter injected)',
    '-> User sees ALL rows — filter NOT applied — DOES NOT WORK',
    '',
    'SECURITY FOR FEDERATION TABLES:',
    '  UC privilege model (GRANT/REVOKE SELECT) — still enforced',
    '  UC row filters — NOT enforced',
    '  UC column masks — NOT enforced',
    '  External DB permissions — enforced by source system',
  ],
  mistakes:[
    '✗ Relying on UC row filters for sensitive federated data — filters not applied, all data visible',
    '✗ Assuming UC governance fully covers federated tables — only ACLs work, not row/column security',
    '✗ Not implementing source-level security for sensitive external tables accessible via Federation',
  ],
  trap:[
    '✗ UC row filters and column masks do NOT apply to Lakehouse Federation foreign tables',
    '✗ UC privilege model (GRANT/REVOKE SELECT) DOES apply to Federation tables',
    '✗ Federated table security must be managed at the source database level — not via UC',
    '✗ This limitation is architectural — Databricks cannot inject filter logic into external JDBC',
    '✗ If someone has SELECT on a foreign table, they see ALL rows/columns the external DB returns',
    '✗ Row filters that work on Delta tables DO NOT automatically apply to Federation versions',
    '✗ Workaround: create a Delta table copy with row filters, or use source DB views with row security',
  ],
},

// ─── 4.2.3 ───────────────────────────────────────────────────────────────────
{num:'07',title:'4.2.3 — Federation is Read-Only (SELECT Only)',
  what:[
    'Lakehouse Federation tables are read-only — only SELECT queries are supported',
    'No DML allowed: no INSERT, UPDATE, DELETE, MERGE, or TRUNCATE on foreign catalog tables',
    'No DDL operations: no CREATE TABLE, DROP TABLE, ALTER TABLE on foreign catalog tables',
  ],
  how:[
    'Federation is a read/query layer — Databricks sends SELECT queries to external system via JDBC',
    'External system executes the query using its own compute, returns results to Databricks',
    'Databricks receives the result set and makes it available to the Spark query — no write path exists',
    'Any attempt to write to a foreign catalog table raises an AnalysisException',
  ],
  facts:[
    'Federation purpose: query external data where it lives — not to replace ETL or write-back',
    'Write-back pattern: if writes needed, use JDBC directly with spark.write.format("jdbc")',
    'Foreign catalog tables appear read-only in UC Explorer — write operations greyed out',
    'Federation can be used as source for CREATE TABLE AS SELECT to ingest data into Delta',
  ],
  code:[
    '-- READ: Allowed — SELECT from foreign catalog',
    'SELECT COUNT(*) FROM postgres_analytics.public.orders;',
    'SELECT * FROM snowflake_dw.sales.transactions LIMIT 100;',
    '',
    '-- WRITE: NOT allowed — will fail with AnalysisException',
    'INSERT INTO postgres_analytics.public.orders VALUES (1, 100.0);',
    '-- AnalysisException: Writing to foreign tables is not supported',
    '',
    'UPDATE postgres_analytics.public.orders SET status = \'closed\' WHERE id = 1;',
    '-- AnalysisException: Writing to foreign tables is not supported',
    '',
    '# Use JDBC directly for writes to external systems (bypasses Federation)',
    'spark.read.table("delta_source") \\',
    '    .write \\',
    '    .format("jdbc") \\',
    '    .option("url", "jdbc:postgresql://host:5432/db") \\',
    '    .option("dbtable", "target_table") \\',
    '    .option("user", "user") \\',
    '    .option("password", dbutils.secrets.get("scope", "key")) \\',
    '    .mode("append") \\',
    '    .save()',
    '',
    '-- CTAS: Copy federated data into Delta (one-time ingestion)',
    'CREATE TABLE catalog.schema.orders_snapshot',
    'AS SELECT * FROM postgres_analytics.public.orders;',
    '-- This reads from Federation and writes to a LOCAL Delta table — allowed',
  ],
  mistakes:[
    '✗ Attempting to use Federation for bidirectional sync — Federation is one-directional read only',
    '✗ Expecting MERGE INTO to work on a foreign catalog table — MERGE not supported on foreign',
    '✗ Confusing Federation JDBC reads with direct JDBC writes — writes must use spark.write.format("jdbc")',
  ],
  trap:[
    '✗ Federation is SELECT only — no INSERT, UPDATE, DELETE, MERGE, TRUNCATE, or DDL on foreign tables',
    '✗ For writes to external system: use spark.write.format("jdbc") directly — not via Federation',
    '✗ CREATE TABLE AS SELECT FROM foreign_catalog.table IS allowed — writes to LOCAL Delta table',
    '✗ Federation can be used as a DATA SOURCE for ETL — read external, transform, write to Delta',
    '✗ Any write attempt on a foreign table raises AnalysisException immediately',
    '✗ Federation cannot be used with streaming writes either — writeStream to foreign table not supported',
  ],
},

// ─── 4.2.4 ───────────────────────────────────────────────────────────────────
{num:'08',title:'4.2.4 — Delta Sharing vs Lakehouse Federation — Full Comparison',
  what:[
    'Delta Sharing: share Delta table data with external consumers — data stays in provider storage',
    'Lakehouse Federation: query external database systems from within Databricks — data stays in external',
    'Two complementary patterns — Delta Sharing is outbound sharing; Federation is inbound querying',
  ],
  how:[
    'Delta Sharing: Databricks is the DATA PROVIDER — external consumers read Databricks data',
    'Lakehouse Federation: Databricks is the DATA CONSUMER — Databricks reads external system data',
    'Both: zero data copy — data stays in its original location for both patterns',
    'Both: read-only access — recipients/federation queries cannot write back',
  ],
  ascii:true,
  code:[
    'DELTA SHARING (Databricks is DATA PROVIDER — outbound):',
    '',
    'DATABRICKS (Provider)              EXTERNAL CONSUMER',
    '  UC Delta tables       ----->     Databricks workspace (D2D)',
    '  _delta_log + parquet             pandas client (D2O)',
    '  Stays in provider S3             Power BI / Tableau (D2O)',
    '  Provider controls access',
    '  Audit: system.access.audit',
    '',
    'LAKEHOUSE FEDERATION (Databricks is DATA CONSUMER — inbound):',
    '',
    'EXTERNAL SYSTEM                    DATABRICKS (Consumer)',
    '  PostgreSQL / Snowflake  ---->    Foreign Catalog in UC',
    '  Redshift / BigQuery              SQL: SELECT * FROM foreign.schema.table',
    '  SQL Server / MySQL               JDBC query sent to external system',
    '  Stays in external DB             Results returned to Spark',
    '  Source DB controls write access  UC ACLs control SELECT access',
    '',
    'KEY DECISION:',
    '  Need to SHARE Databricks data with others?  -> Delta Sharing',
    '  Need to QUERY external DB from Databricks?  -> Lakehouse Federation',
    '  Need to INGEST external data into Delta?    -> Federation + CTAS or ETL',
    '',
    'COMPARISON TABLE:',
    'Direction        Delta Sharing: Outbound | Federation: Inbound',
    'Data owner       Databricks (provider)   | External system',
    'Data location    Provider cloud storage  | External database',
    'Consumer types   Multi-platform          | Databricks only',
    'UC governance    Full                    | ACLs only',
    'Row filters      Applied                 | NOT applied',
    'Write support    Read-only               | Read-only',
  ],
  mistakes:[
    '✗ Confusing the direction: Delta Sharing = Databricks shares OUT; Federation = Databricks queries IN',
    '✗ Using Federation when Delta Sharing is needed (or vice versa) — different use cases',
    '✗ Expecting Federation to support UC row filters — only Delta Sharing tables get full UC governance',
  ],
  trap:[
    '✗ Delta Sharing = outbound (Databricks -> External); Federation = inbound (External -> Databricks)',
    '✗ Delta Sharing: data in provider storage; Federation: data in external system',
    '✗ Delta Sharing: supports non-Databricks consumers; Federation: Databricks only',
    '✗ Delta Sharing: full UC governance including row filters/masks; Federation: ACLs only',
    '✗ Both are read-only from the consumer/querier perspective — no write-back in either pattern',
    '✗ Delta Sharing audit: deltaSharingQueriedTable events in system.access.audit',
    '✗ Schema-level sharing in Delta Sharing auto-includes future tables — NO equivalent in Federation',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain4_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
