'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 3  —  Data Transformation, Cleansing & Quality  —  27 Sub-Topics',
  groups: [
    ['3.1  Delta Lake Internals',[
      ['01','3.1.1','Transaction Log (_delta_log) — JSON Entries, Checkpoint Every 10 Commits'],
      ['02','3.1.2','Optimistic Concurrency Control (OCC)'],
      ['03','3.1.3','DESCRIBE Commands: TABLE, EXTENDED, DETAIL, HISTORY'],
      ['04','3.1.4','Time Travel: VERSION AS OF, TIMESTAMP AS OF'],
      ['05','3.1.5','RESTORE TABLE (Changes Current Table vs SELECT Time Travel Read)'],
      ['06','3.1.6','VACUUM — 7-Day Default, Breaks Time Travel, VACUUM on Shallow Clone = ERROR'],
      ['07','3.1.7','Schema Enforcement vs Schema Evolution (mergeSchema, overwriteSchema)'],
      ['08','3.1.8','MERGE INTO — Full Syntax, Duplicate Source = Error, WHEN NOT MATCHED BY SOURCE'],
      ['09','3.1.9','ALTER TABLE RENAME — Only Updates Metastore, NOT Physical Files'],
      ['10','3.1.10','Delta Clone: Shallow vs Deep — VACUUM Behavior Difference'],
      ['11','3.1.11','Column Mapping — Rename/Drop Without File Rewrite'],
      ['12','3.1.12','Delta Table Constraints (NOT NULL, CHECK) — Do NOT Validate Existing Data'],
      ['13','3.1.13','OPTIMIZE, OPTIMIZE FULL, ZORDER BY'],
      ['14','3.1.14','Liquid Clustering: CLUSTER BY, Max 4 Keys, Incompatible with Partitioning/ZORDER'],
      ['15','3.1.15','Deletion Vectors — Bitmap-Based, No File Rewrite for DELETE/UPDATE/MERGE'],
    ]],
    ['3.2  Advanced Transformations',[
      ['16','3.2.1','PIVOT, UNPIVOT in Spark SQL'],
      ['17','3.2.2','CTEs (Common Table Expressions)'],
      ['18','3.2.3','Higher-Order Functions: TRANSFORM, FILTER, AGGREGATE, EXISTS, FORALL'],
      ['19','3.2.4','Deduplication Strategies (dropDuplicates, ROW_NUMBER, MERGE, watermark)'],
    ]],
    ['3.3  Change Data Feed (CDF)',[
      ['20','3.3.1','Enabling CDF and Reading Change Events'],
      ['21','3.3.2','_change_type Values: insert, update_preimage, update_postimage, delete'],
      ['22','3.3.3','Propagating Deletes Downstream Using CDF'],
      ['23','3.3.4','CDF for Incremental Performance (Not Just CDC)'],
    ]],
    ['3.4  SCD and Data Modelling at Silver Layer',[
      ['24','3.4.1','SCD Type 0, 1, 2 — Implementation with MERGE and APPLY CHANGES'],
      ['25','3.4.2','Medallion Architecture — Bronze/Silver/Gold Rules, PII Handling'],
      ['26','3.4.3','Multiplex Bronze Table Design (Topic Discriminator, Pitfalls)'],
      ['27','3.4.4','Quarantine Table Pattern (Route Bad Records, Never Drop Silently)'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 3  —  Data Transformation, Cleansing & Quality  —  All High-Priority Traps',
};

const pages = [

// ─── 3.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'3.1.1 — Transaction Log (_delta_log) — JSON Entries, Checkpoint Every 10 Commits',
  what:[
    'Transaction log: ordered history of every change ever made to a Delta table — the single source of truth',
    'Stored in _delta_log/ directory alongside the Parquet data files of the table',
    'Every commit = one numbered JSON file in _delta_log/ — e.g. 00000000000000000001.json',
  ],
  how:[
    'Each JSON commit file contains actions: add (new file), remove (deleted file), metaData (schema), protocol',
    'add action: records new Parquet file path, size, partition values, and column statistics',
    'remove action: marks a file as logically deleted — physical file stays until VACUUM removes it',
    'On read: Spark replays the log from the last checkpoint to reconstruct the current table state',
  ],
  facts:[
    'Checkpoint every 10 commits: every 10th commit generates a checkpoint.parquet file + _last_checkpoint marker',
    'DESCRIBE DETAIL my_table returns accurate numFiles by reading the transaction log — NOT directory listing',
    'delta.logRetentionDuration default = 30 days — controls how long commit history is accessible',
    'delta.checkpointInterval property: change checkpoint frequency (default 10)',
  ],
  ascii:true,
  code:[
    '/path/to/table/',
    '  part-00001-xxxx.parquet       <- data file (add action)',
    '  part-00002-xxxx.parquet       <- data file (add action)',
    '  _delta_log/',
    '    00000000000000000000.json   <- commit 0 (table creation)',
    '    00000000000000000001.json   <- commit 1 (first insert)',
    '    00000000000000000010.json   <- commit 10',
    '    00000000000000000010.checkpoint.parquet   <- checkpoint at commit 10',
    '    _last_checkpoint            <- pointer to latest checkpoint',
  ],
  mistakes:[
    '✗ Manually deleting _delta_log/ files — permanently corrupts the table, unrecoverable',
    '✗ Using directory listing to count files — shows both active AND removed files, always inaccurate',
    '✗ Setting logRetentionDuration shorter than VACUUM retention — time travel fails before VACUUM runs',
  ],
  trap:[
    '✗ DESCRIBE DETAIL numFiles reads the transaction log — ACCURATE; directory listing is NOT accurate',
    '✗ Removed files stay on DISK until VACUUM runs — remove action is a logical delete only',
    '✗ Checkpoint generated every 10 commits by default — _last_checkpoint points to the latest one',
    '✗ Manually deleting _delta_log/ files = table permanently broken — no recovery possible',
    '✗ logRetentionDuration default = 30 days — controls how long HISTORY is accessible, not VACUUM',
    '✗ add action records file stats (min/max column values) — used for file skipping during queries',
    '✗ JSON commit files are newline-delimited — each line is a separate action JSON object',
  ],
},

// ─── 3.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'3.1.2 — Optimistic Concurrency Control (OCC)',
  what:[
    'OCC: Delta Lake concurrency model — writers proceed optimistically assuming no conflict',
    'On commit: Delta checks for conflicts with other concurrent writers — one succeeds, conflicting ones retry',
    'Enables multiple concurrent readers and writers on the same Delta table without table-level locking',
  ],
  how:[
    'Writer reads current table version, performs transformation, attempts to commit new version',
    'If another writer committed a conflicting change since the read: ConcurrentModificationException thrown',
    'Non-conflicting concurrent writes succeed: two writers adding records to different partitions = both succeed',
    'Conflicting writes: two writers modifying the same files = one wins, other must retry from beginning',
  ],
  facts:[
    'Readers always see a consistent snapshot — reads are never blocked by concurrent writes',
    'OCC is optimistic — no locks acquired upfront, conflict detected only at commit time',
    'Conflict resolution: last writer to commit wins for conflicting changes — losing writer must retry',
    'Delta supports serializable isolation for writes and snapshot isolation for reads',
  ],
  ascii:true,
  code:[
    'OPTIMISTIC CONCURRENCY CONTROL:',
    '',
    'Writer A (starts at version 5)     Writer B (starts at version 5)',
    '    |                                   |',
    'Read version 5                     Read version 5',
    'Perform transform                  Perform transform',
    '    |                                   |',
    'Attempt commit -> version 6        Attempt commit -> version 6',
    '    |                                   |',
    'SUCCESS -> commits first           CONFLICT DETECTED',
    '(version 6 written)                ConcurrentModificationException',
    '                                   -> Writer B must retry from version 6',
  ],
  mistakes:[
    '✗ Assuming OCC means writes always succeed — conflicting concurrent writes cause exceptions',
    '✗ Thinking OCC uses database-style row locking — Delta uses file-level optimistic conflict detection',
    '✗ Expecting reads to be blocked during writes — Delta reads are NEVER blocked by concurrent writes',
  ],
  trap:[
    '✗ OCC is optimistic — no locks acquired upfront, conflict detected at COMMIT TIME only',
    '✗ Reads are NEVER blocked by concurrent writes — snapshot isolation for all reads',
    '✗ Conflicting writer throws ConcurrentModificationException — must retry the entire operation',
    '✗ Last writer to commit WINS — earlier writer that detects conflict must retry from latest version',
    '✗ Non-conflicting writes (different partitions, different files) both succeed without conflict',
    '✗ Delta does NOT use row-level locking — conflict granularity is at the FILE level',
  ],
},

// ─── 3.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'3.1.3 — DESCRIBE Commands: TABLE, EXTENDED, DETAIL, HISTORY',
  what:[
    'Four DESCRIBE variants for Delta tables — each returns different metadata about the table',
    'Essential for diagnostics, auditing, understanding table structure, and exam questions',
    'Each command serves a distinct purpose — knowing which one returns which info is exam-critical',
  ],
  how:[
    'DESCRIBE TABLE name: returns column names, data types, and partition columns — basic schema info',
    'DESCRIBE TABLE EXTENDED name: adds storage location, table type, table properties, constraints',
    'DESCRIBE DETAIL name: returns operational metadata — numFiles, sizeInBytes, location, partitionColumns, clusteringColumns',
    'DESCRIBE HISTORY name: returns full commit history — version, timestamp, operation, user, parameters',
  ],
  facts:[
    'DESCRIBE DETAIL numFiles is ACCURATE — reads Delta log, not directory listing',
    'DESCRIBE HISTORY shows operations: WRITE, MERGE, DELETE, OPTIMIZE, VACUUM START, VACUUM END',
    'DESCRIBE TABLE EXTENDED shows constraints (NOT NULL, CHECK) — DESCRIBE DETAIL does NOT',
    'DESCRIBE DETAIL shows clusteringColumns for Liquid Clustering tables',
  ],
  code:[
    '-- Basic schema',
    'DESCRIBE TABLE catalog.schema.orders;',
    '-- Returns: col_name | data_type | comment',
    '',
    '-- Extended schema + table metadata',
    'DESCRIBE TABLE EXTENDED catalog.schema.orders;',
    '-- Returns: schema + Location, Type (MANAGED/EXTERNAL),',
    '--          Provider (delta), Table Properties, Constraints',
    '',
    '-- Operational details',
    'DESCRIBE DETAIL catalog.schema.orders;',
    '-- Returns: format, id, name, location, createdAt, lastModified,',
    '--          partitionColumns, numFiles, sizeInBytes, clusteringColumns',
    '',
    '-- Full commit history',
    'DESCRIBE HISTORY catalog.schema.orders;',
    '-- Returns: version, timestamp, userId, userName,',
    '--          operation, operationParameters, notebook, clusterId',
  ],
  mistakes:[
    '✗ Using DESCRIBE TABLE to find file count — DESCRIBE TABLE does not return numFiles',
    '✗ Confusing DESCRIBE DETAIL with DESCRIBE HISTORY — DETAIL = current state, HISTORY = all commits',
    '✗ Using DESCRIBE TABLE EXTENDED when you only need numFiles — use DESCRIBE DETAIL instead',
  ],
  trap:[
    '✗ DESCRIBE DETAIL returns numFiles — DESCRIBE TABLE and DESCRIBE TABLE EXTENDED do NOT',
    '✗ DESCRIBE DETAIL numFiles reads Delta log — ACCURATE count of active files (not directory listing)',
    '✗ DESCRIBE TABLE EXTENDED shows constraints (NOT NULL, CHECK) — DESCRIBE DETAIL does NOT',
    '✗ DESCRIBE HISTORY shows the operation that created each version — useful for auditing who did what',
    '✗ DESCRIBE HISTORY shows VACUUM START and VACUUM END as separate operations in the history',
    '✗ DESCRIBE DETAIL shows clusteringColumns for Liquid Clustering tables — DESCRIBE TABLE does not',
  ],
},

// ─── 3.1.4 ───────────────────────────────────────────────────────────────────
{num:'04',title:'3.1.4 — Time Travel: VERSION AS OF, TIMESTAMP AS OF',
  what:[
    'Time travel: query any historical version of a Delta table by version number or timestamp',
    'Uses the transaction log + original Parquet files to reconstruct past table state',
    'Available as long as both the log files AND the data files have NOT been deleted by VACUUM',
  ],
  how:[
    'VERSION AS OF n: read the exact table state at commit version n (version 0 = table creation)',
    'TIMESTAMP AS OF ts: read the table state at a specific timestamp string or timestamp expression',
    'RESTORE TABLE: sets a historical version as the current version — creates a new forward commit',
    'DataFrame API: .option("versionAsOf", n) or .option("timestampAsOf", "2024-01-15 10:00:00")',
  ],
  facts:[
    'Time travel requires BOTH the log entries AND the Parquet data files — VACUUM deletes data files',
    'RESTORE TABLE creates a new commit — it does NOT rewind or delete intermediate history',
    'Version 0 = table creation; version 1 = first write — monotonically increasing integers',
    'VACUUM with default retention (7 days) deletes files older than 7 days — breaks older time travel',
  ],
  code:[
    '-- Read specific version',
    'SELECT * FROM catalog.schema.orders VERSION AS OF 5;',
    '',
    '-- Read at specific timestamp',
    'SELECT * FROM catalog.schema.orders',
    'TIMESTAMP AS OF \'2024-01-15 10:00:00\';',
    '',
    '-- Use relative timestamp',
    'SELECT * FROM catalog.schema.orders',
    'TIMESTAMP AS OF current_timestamp() - INTERVAL 2 DAYS;',
    '',
    '-- Restore table to a previous version (creates new commit)',
    'RESTORE TABLE catalog.schema.orders TO VERSION AS OF 3;',
    'RESTORE TABLE catalog.schema.orders TO TIMESTAMP AS OF \'2024-01-10\';',
    '',
    '# DataFrame API for time travel',
    'df_v5 = (spark.read.format("delta")',
    '    .option("versionAsOf", 5)',
    '    .load("/path/to/table/"))',
  ],
  mistakes:[
    '✗ Running VACUUM then expecting old-version time travel to work — data files permanently deleted',
    '✗ Using RESTORE TABLE when a time travel SELECT read is sufficient — RESTORE changes current state',
    '✗ Not checking DESCRIBE HISTORY before time travel — may request version that no longer has files',
  ],
  trap:[
    '✗ Time travel fails with FileNotFoundException after VACUUM — data files permanently gone',
    '✗ RESTORE TABLE creates a NEW commit — does NOT delete intermediate history or rewind the log',
    '✗ RESTORE TABLE CHANGES the current table — VERSION AS OF is a read-only operation',
    '✗ VACUUM with retentionHours < 168 (7 days) requires retentionDurationCheck.enabled = false',
    '✗ timestampAsOf accepts string "2024-01-15 10:00:00" — must be within retention window',
    '✗ Version 0 = table creation — always exists if log not cleaned; version N = Nth commit',
  ],
},

// ─── 3.1.5 ───────────────────────────────────────────────────────────────────
{num:'05',title:'3.1.5 — RESTORE TABLE (Changes Current Table vs SELECT Time Travel Read)',
  what:[
    'RESTORE TABLE: replaces the CURRENT table state with a historical version — writes a new commit',
    'Fundamentally different from a time travel SELECT — RESTORE changes the live table, SELECT reads history',
    'Creates a new entry in DESCRIBE HISTORY — the restoration is itself an auditable commit',
  ],
  how:[
    'RESTORE TABLE name TO VERSION AS OF n: makes version n the current table state',
    'Internally: Delta writes new add and remove actions to bring table back to historical state',
    'The intermediate commits (between n and current) are NOT deleted — history is preserved',
    'After RESTORE: queries on the table return data as it existed at version n',
  ],
  facts:[
    'RESTORE TABLE requires the historical data files to still exist — cannot restore past VACUUM window',
    'RESTORE creates a new commit — the new version number is CURRENT_VERSION + 1',
    'RESTORE does NOT delete intermediate history — all commits between restored version and now remain',
    'Use case: accidental DELETE or bad MERGE — RESTORE to last known good version',
  ],
  ascii:true,
  code:[
    'SCENARIO: accidental DELETE at version 10, want to restore to version 9',
    '',
    'DESCRIBE HISTORY shows:',
    '  version 8: WRITE (good)',
    '  version 9: WRITE (good <- last known good state)',
    '  version 10: DELETE (accidental <- want to undo this)',
    '',
    'RESTORE TABLE orders TO VERSION AS OF 9',
    '',
    'Result:',
    '  version 8: WRITE',
    '  version 9: WRITE',
    '  version 10: DELETE  <- still in history (not deleted)',
    '  version 11: RESTORE <- new commit created by RESTORE',
    '',
    'Current table now reflects version 9 state.',
    'Intermediate history preserved and auditable.',
  ],
  mistakes:[
    '✗ Using RESTORE when a time travel SELECT read is all that is needed',
    '✗ Expecting RESTORE to delete intermediate commit history — history is preserved',
    '✗ Trying to RESTORE past the VACUUM retention window — historical files must still exist',
  ],
  trap:[
    '✗ RESTORE TABLE CHANGES the current live table — VERSION AS OF in SELECT is READ-ONLY',
    '✗ RESTORE creates a NEW commit (current version + 1) — does NOT rewind or delete intermediate commits',
    '✗ RESTORE requires data files to still exist — fails if VACUUM has deleted the target version files',
    '✗ After RESTORE: DESCRIBE HISTORY shows a new RESTORE operation at the latest version',
    '✗ RESTORE TO VERSION AS OF 5 does not remove versions 6, 7, 8... — all still in DESCRIBE HISTORY',
    '✗ Cannot RESTORE to a version that predates the oldest checkpoint if log has been cleaned',
  ],
},

// ─── 3.1.6 ───────────────────────────────────────────────────────────────────
{num:'06',title:'3.1.6 — VACUUM — 7-Day Default, Breaks Time Travel, VACUUM on Shallow Clone = ERROR',
  what:[
    'VACUUM: permanently deletes Parquet data files no longer referenced by the Delta transaction log',
    'Removes files older than the retention threshold — default 7 days (168 hours)',
    'After VACUUM: time travel to vacuumed versions fails with FileNotFoundException — irreversible',
  ],
  how:[
    'VACUUM lists all files in the table directory, compares against active files in log, deletes orphaned',
    'Default retention: delta.deletedFileRetentionDuration = interval 7 days (168 hours)',
    'DRY RUN: shows files that WOULD be deleted without actually deleting them — safe preview',
    'Safety check: spark.databricks.delta.retentionDurationCheck.enabled = false required for VACUUM < 7 days',
  ],
  facts:[
    'VACUUM deletes DATA files (part-*.parquet) — does NOT delete _delta_log/ JSON commit files',
    '_delta_log/ retention is controlled separately by delta.logRetentionDuration (default 30 days)',
    'Shallow clone VACUUM = ERROR: shallow clone shares files with source — VACUUM on source breaks clone',
    'VACUUM does NOT fail if some files are already missing — skips missing files silently',
  ],
  code:[
    '-- Standard VACUUM (7-day default retention)',
    'VACUUM catalog.schema.orders;',
    '',
    '-- Custom retention',
    'VACUUM catalog.schema.orders RETAIN 72 HOURS;',
    '',
    '-- DRY RUN — preview files to be deleted (safe)',
    'VACUUM catalog.schema.orders DRY RUN;',
    '',
    '-- VACUUM below 7 days — REQUIRES disabling safety check',
    'SET spark.databricks.delta.retentionDurationCheck.enabled = false;',
    'VACUUM catalog.schema.orders RETAIN 0 HOURS;',
    'SET spark.databricks.delta.retentionDurationCheck.enabled = true;',
    '',
    '-- Change default retention',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (\'delta.deletedFileRetentionDuration\' = \'interval 30 days\');',
  ],
  mistakes:[
    '✗ Running VACUUM then expecting time travel to old versions — data files permanently gone',
    '✗ VACUUMing the source table of a shallow clone — clone files deleted, clone broken',
    '✗ Running VACUUM RETAIN 0 HOURS without disabling retentionDurationCheck — error thrown',
  ],
  trap:[
    '✗ VACUUM deletes DATA files only — _delta_log/ JSON commit files are NOT deleted by VACUUM',
    '✗ VACUUM below 7 days REQUIRES retentionDurationCheck.enabled = false — safety guard',
    '✗ VACUUM on shallow clone source = ERROR — shallow clone shares Parquet files with source table',
    '✗ After VACUUM: FileNotFoundException on time travel to vacuumed versions — permanent, no recovery',
    '✗ _delta_log/ retention controlled by logRetentionDuration (default 30 days) — separate from VACUUM',
    '✗ VACUUM DRY RUN is safe — shows files to be deleted, does NOT actually delete anything',
  ],
},

// ─── 3.1.7 ───────────────────────────────────────────────────────────────────
{num:'07',title:'3.1.7 — Schema Enforcement vs Schema Evolution (mergeSchema, overwriteSchema)',
  what:[
    'Schema enforcement: Delta rejects writes where incoming schema does not match table schema — default',
    'Schema evolution: controlled relaxation — allows new columns to be added or schema to be replaced',
    'Two evolution options: mergeSchema (add new columns) and overwriteSchema (replace entire schema)',
  ],
  how:[
    'Default enforcement: extra columns in write -> AnalysisException; missing nullable columns -> NULLs',
    'mergeSchema = true: new columns in incoming data added to table schema — existing columns unchanged',
    'overwriteSchema = true: replaces the entire table schema — destructive, only with mode("overwrite")',
    'Type changes (e.g. int -> string) NOT supported by mergeSchema — requires overwriteSchema',
  ],
  facts:[
    'mergeSchema adds NEW columns only — cannot change existing column types with mergeSchema',
    'overwriteSchema REPLACES the entire schema — existing column data may be lost if columns removed',
    'Type widening (int -> long) is allowed with mergeSchema; type narrowing (long -> int) never allowed',
    'spark.databricks.delta.schema.autoMerge.enabled = true: auto-merges on every write session-wide',
  ],
  code:[
    '# Default: strict enforcement (fails on schema mismatch)',
    'df_new.write.format("delta").mode("append").save("/path/to/table/")',
    '# AnalysisException if df_new has columns not in table schema',
    '',
    '# mergeSchema — add new columns safely',
    'df_new.write.format("delta") \\',
    '    .option("mergeSchema", "true") \\',
    '    .mode("append") \\',
    '    .save("/path/to/table/")',
    '',
    '# overwriteSchema — replace entire schema (destructive)',
    'df_new.write.format("delta") \\',
    '    .option("overwriteSchema", "true") \\',
    '    .mode("overwrite") \\',
    '    .save("/path/to/table/")',
    '',
    '# Session-wide auto merge (use with caution)',
    'spark.conf.set("spark.databricks.delta.schema.autoMerge.enabled", "true")',
  ],
  mistakes:[
    '✗ Expecting mergeSchema to handle type changes (int -> string) — it only ADDS new columns',
    '✗ Using overwriteSchema for minor additions — mergeSchema is safer and preserves existing data',
    '✗ Forgetting that extra columns in incoming data fail by default — they are NOT silently ignored',
  ],
  trap:[
    '✗ mergeSchema adds NEW columns ONLY — cannot change existing column types',
    '✗ overwriteSchema = true REPLACES the full schema — existing column data can be lost',
    '✗ Type narrowing (long -> int) is NEVER allowed even with overwriteSchema',
    '✗ Extra incoming columns cause AnalysisException by default — NOT silently dropped',
    '✗ mergeSchema requires mode("append") — cannot merge schema with mode("overwrite") alone',
    '✗ overwriteSchema ONLY works with mode("overwrite") — cannot use with append',
    '✗ Type widening (int -> long, float -> double) is allowed with mergeSchema',
  ],
},

// ─── 3.1.8 ───────────────────────────────────────────────────────────────────
{num:'08',title:'3.1.8 — MERGE INTO — Full Syntax, Duplicate Source Rows = Error, WHEN NOT MATCHED BY SOURCE',
  what:[
    'MERGE INTO: upsert operation combining INSERT, UPDATE, DELETE in a single atomic statement',
    'Matches source rows to target rows based on a join condition — applies different actions per match',
    'Delta supports full MERGE syntax including WHEN NOT MATCHED BY SOURCE (delete unmatched target rows)',
  ],
  how:[
    'WHEN MATCHED THEN UPDATE: update target row when source key matches',
    'WHEN MATCHED THEN DELETE: delete target row when source key matches (and optional condition)',
    'WHEN NOT MATCHED THEN INSERT: insert source row when key not found in target',
    'WHEN NOT MATCHED BY SOURCE THEN DELETE: delete target rows that have NO matching row in source',
  ],
  facts:[
    'Duplicate source rows = ERROR: if source has multiple rows with the same key, MERGE throws UpsertOperationNotAllowedException',
    'WHEN NOT MATCHED BY SOURCE is Delta-specific — not available in standard ANSI SQL MERGE',
    'MERGE is ATOMIC — either all changes commit or all roll back — full ACID guarantee',
    'Multiple WHEN MATCHED clauses allowed — evaluated in ORDER, first match wins',
  ],
  code:[
    '-- Full MERGE syntax',
    'MERGE INTO catalog.schema.customers AS target',
    'USING catalog.schema.customer_updates AS source',
    'ON target.customer_id = source.customer_id',
    '',
    '-- Update existing records',
    'WHEN MATCHED AND source.op_type = \'UPDATE\'',
    '    THEN UPDATE SET',
    '        target.name = source.name,',
    '        target.email = source.email,',
    '        target.updated_at = source.updated_at',
    '',
    '-- Delete records marked for deletion',
    'WHEN MATCHED AND source.op_type = \'DELETE\'',
    '    THEN DELETE',
    '',
    '-- Insert new records',
    'WHEN NOT MATCHED',
    '    THEN INSERT (customer_id, name, email, created_at)',
    '    VALUES (source.customer_id, source.name, source.email, source.created_at)',
    '',
    '-- Delete target rows not present in source (full outer sync)',
    'WHEN NOT MATCHED BY SOURCE',
    '    THEN DELETE;',
  ],
  mistakes:[
    '✗ Not deduplicating source before MERGE — duplicate source keys cause UpsertOperationNotAllowedException',
    '✗ Using MERGE INTO on non-Delta targets — MERGE only works with Delta as the target table',
    '✗ Assuming WHEN NOT MATCHED BY SOURCE is standard SQL — it is a Delta-specific extension',
  ],
  trap:[
    '✗ Duplicate source rows on the MERGE key = UpsertOperationNotAllowedException — must deduplicate first',
    '✗ WHEN NOT MATCHED BY SOURCE is DELTA-SPECIFIC — not in standard SQL, available in Delta MERGE',
    '✗ MERGE target MUST be a Delta table — cannot MERGE INTO Parquet, CSV, or Hive tables',
    '✗ Multiple WHEN MATCHED clauses evaluated in ORDER — first matching clause fires, rest skipped',
    '✗ MERGE is ATOMIC — either all changes commit or all roll back — no partial commits',
    '✗ WHEN NOT MATCHED BY SOURCE THEN DELETE removes target rows not in source — full sync pattern',
    '✗ MERGE + VACUUM for GDPR: MERGE DELETE removes logically, VACUUM removes physically from storage',
  ],
},

// ─── 3.1.9 ───────────────────────────────────────────────────────────────────
{num:'09',title:'3.1.9 — ALTER TABLE RENAME — Only Updates Metastore, NOT Physical Files',
  what:[
    'ALTER TABLE old_name RENAME TO new_name: renames the table in the metastore only',
    'Physical files on storage (S3/ADLS/GCS) are NOT moved or renamed — they stay at the original path',
    'Critical distinction: the logical table name changes but the underlying storage path does NOT change',
  ],
  how:[
    'Delta table has two components: metastore entry (logical name, schema, properties) and storage files',
    'ALTER TABLE RENAME updates ONLY the metastore entry — the storage path remains unchanged',
    'After rename: DESCRIBE DETAIL new_table shows the same location as before the rename',
    'Applies to both managed and external tables — in both cases, only the metastore name is updated',
  ],
  facts:[
    'Physical files location does NOT change after ALTER TABLE RENAME',
    'DESCRIBE DETAIL location field shows the original storage path even after rename',
    'For managed tables: DROP TABLE new_table still deletes the physical files (DROP behavior unchanged)',
    'UC-managed tables: rename updates Unity Catalog metadata — storage path in UC-managed location unchanged',
  ],
  code:[
    '-- Before rename',
    'DESCRIBE DETAIL catalog.schema.orders;',
    '-- location: s3://bucket/catalog/schema/orders/',
    '',
    '-- Rename table',
    'ALTER TABLE catalog.schema.orders',
    'RENAME TO catalog.schema.orders_v2;',
    '',
    '-- After rename: location is UNCHANGED',
    'DESCRIBE DETAIL catalog.schema.orders_v2;',
    '-- location: s3://bucket/catalog/schema/orders/  <- SAME physical path!',
    '',
    '-- Rename column (different operation — requires column mapping)',
    'ALTER TABLE catalog.schema.orders_v2',
    'RENAME COLUMN old_col_name TO new_col_name;',
    '-- Requires delta.columnMapping.mode = \'name\'',
  ],
  mistakes:[
    '✗ Assuming ALTER TABLE RENAME moves the physical files — files stay at original location',
    '✗ Expecting the location in DESCRIBE DETAIL to change after rename — shows original path',
    '✗ Confusing table rename with column rename — column rename requires column mapping enabled',
  ],
  trap:[
    '✗ ALTER TABLE RENAME updates METASTORE ONLY — physical files are NOT moved or renamed',
    '✗ DESCRIBE DETAIL location shows ORIGINAL storage path even after rename — path unchanged',
    '✗ Physical files remain at original storage location after rename',
    '✗ Column rename (ALTER TABLE ... RENAME COLUMN) requires delta.columnMapping.mode = \'name\'',
    '✗ RENAME does not affect _delta_log/ contents — transaction log entries still reference original paths',
    '✗ After rename: old table name throws AnalysisException — it no longer exists in metastore',
    '✗ Managed table DROP after rename: still deletes physical files — DROP behavior is unchanged',
  ],
},

// ─── 3.1.10 ──────────────────────────────────────────────────────────────────
{num:'10',title:'3.1.10 — Delta Clone: Shallow vs Deep — VACUUM Behavior Difference',
  what:[
    'Delta Clone: creates a copy of a Delta table — either shallow (metadata only) or deep (full copy)',
    'SHALLOW CLONE: copies only the transaction log — Parquet data files are SHARED with source',
    'DEEP CLONE: copies both transaction log AND all Parquet data files — fully independent copy',
  ],
  how:[
    'Shallow clone: _delta_log/ copied to new location; data files referenced by path to source location',
    'Deep clone: both _delta_log/ AND all Parquet files copied to new location — no dependency on source',
    'Shallow clone is fast and cheap — only copies metadata, no data movement',
    'Deep clone is slow and expensive — copies all data files to new storage location',
  ],
  facts:[
    'VACUUM source after shallow clone = broken clone: source VACUUM deletes files the clone depends on',
    'VACUUM source after deep clone = safe: deep clone has its own copy of all files, independent',
    'Shallow clone good for: short-lived dev/test environments, schema validation, quick experiments',
    'Deep clone good for: DR backups, long-lived production replicas, cross-region data copies',
  ],
  ascii:true,
  code:[
    'SHALLOW CLONE:',
    '  Original table:    /prod/orders/ [files A, B, C] + _delta_log/',
    '  Shallow clone:     /dev/orders_clone/  _delta_log/ (copy)',
    '                     data files: STILL AT /prod/orders/[A,B,C] (shared!)',
    '',
    '  VACUUM /prod/orders/  -> deletes files A, B, C',
    '  /dev/orders_clone reads A, B, C -> FileNotFoundException!  -> BROKEN',
    '',
    'DEEP CLONE:',
    '  Original table:    /prod/orders/ [files A, B, C] + _delta_log/',
    '  Deep clone:        /backup/orders/ [files A_copy, B_copy, C_copy] + _delta_log/',
    '',
    '  VACUUM /prod/orders/  -> deletes files A, B, C from prod only',
    '  /backup/orders reads independent copies -> WORKS FINE  -> INDEPENDENT',
    '',
    '-- Shallow clone (fast, shared files)',
    'CREATE TABLE dev.schema.orders_test',
    'SHALLOW CLONE prod.schema.orders;',
    '',
    '-- Deep clone (full copy, independent)',
    'CREATE TABLE backup.schema.orders_backup',
    'DEEP CLONE prod.schema.orders',
    'LOCATION \'s3://backup-bucket/orders/\';',
  ],
  mistakes:[
    '✗ VACUUMing source after creating a shallow clone — clone becomes permanently broken',
    '✗ Using shallow clone for long-lived DR copies — source VACUUM will eventually break it',
    '✗ Expecting shallow clone to have its own independent data files — it shares with source',
  ],
  trap:[
    '✗ VACUUM source after SHALLOW CLONE = FileNotFoundException on clone — clone broken permanently',
    '✗ VACUUM source after DEEP CLONE = safe — deep clone has its own independent file copies',
    '✗ Shallow clone copies ONLY the transaction log — data files remain at source location (shared)',
    '✗ Deep clone copies BOTH log AND data files — completely independent from source after creation',
    '✗ Shallow clone is cheap/fast; Deep clone is expensive/slow — choose based on independence needs',
    '✗ CREATE OR REPLACE TABLE ... DEEP CLONE is incremental — only copies changed files',
  ],
},

// ─── 3.1.11 ──────────────────────────────────────────────────────────────────
{num:'11',title:'3.1.11 — Column Mapping — Rename/Drop Without File Rewrite',
  what:[
    'Column Mapping: Delta feature that allows renaming or dropping columns WITHOUT rewriting Parquet files',
    'Without column mapping: rename/drop requires rewriting all Parquet files — expensive for large tables',
    'Two column mapping modes: id (by column ID) and name (by column name) — name is most common',
  ],
  how:[
    'Column mapping stores a mapping between physical column names in Parquet and logical column names',
    'delta.columnMapping.mode = name: enables name-based column mapping',
    'After enabling: rename a column with ALTER TABLE ... RENAME COLUMN old TO new',
    'Drop a column with ALTER TABLE ... DROP COLUMN col_name — Parquet files unchanged, column ignored',
  ],
  facts:[
    'Without column mapping: rename/drop requires REWRITE of all Parquet files — O(data size)',
    'With column mapping: rename/drop is metadata-only — O(1), instant regardless of data size',
    'Column mapping requires minReaderVersion = 2 and minWriterVersion = 5 in Delta protocol',
    'DROP COLUMN with column mapping: column metadata removed, Parquet unchanged — column ignored on read',
  ],
  code:[
    '-- Enable column mapping (one-time setup)',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (',
    '    \'delta.columnMapping.mode\' = \'name\',',
    '    \'delta.minReaderVersion\' = \'2\',',
    '    \'delta.minWriterVersion\' = \'5\'',
    ');',
    '',
    '-- Rename column (instant — no file rewrite)',
    'ALTER TABLE catalog.schema.orders',
    'RENAME COLUMN customer_name TO cust_name;',
    '',
    '-- Drop column (instant — no file rewrite)',
    'ALTER TABLE catalog.schema.orders',
    'DROP COLUMN deprecated_field;',
  ],
  mistakes:[
    '✗ Trying to rename columns without enabling column mapping — fails with AnalysisException',
    '✗ Enabling column mapping on a table existing readers depend on — older readers may break',
    '✗ Confusing column drop with data deletion — column mapping DROP removes schema entry but keeps data',
  ],
  trap:[
    '✗ Column mapping is REQUIRED to rename or drop columns without rewriting Parquet files',
    '✗ Without column mapping: rename/drop requires full REWRITE of all data files — expensive',
    '✗ RENAME COLUMN and DROP COLUMN with column mapping are metadata-only — instant, no file rewrite',
    '✗ delta.columnMapping.mode = \'name\' is the required property — not a Spark config',
    '✗ Column mapping requires Delta protocol upgrade: minReaderVersion = 2, minWriterVersion = 5',
    '✗ Dropped columns data still exists in Parquet files — just ignored during reads via the mapping',
    '✗ Column mapping cannot be disabled once enabled — it is a one-way upgrade to the table',
  ],
},

// ─── 3.1.12 ──────────────────────────────────────────────────────────────────
{num:'12',title:'3.1.12 — Delta Table Constraints (NOT NULL, CHECK) — Do NOT Validate Existing Data',
  what:[
    'Delta constraints: NOT NULL and CHECK constraints enforced on FUTURE writes to Delta tables',
    'Prevent invalid data from being written — raise SparkException or AnalysisException on violation',
    'Two types: NOT NULL (column-level nullability) and CHECK (arbitrary boolean expression)',
  ],
  how:[
    'Add constraint: ALTER TABLE name ADD CONSTRAINT constraint_name CHECK (expression)',
    'Constraint validated on every INSERT, UPDATE, and MERGE after the constraint is added',
    'Violation: entire write operation fails — no partial commit, ACID guarantee maintained',
    'Existing data: constraints do NOT retroactively validate data already in the table',
  ],
  facts:[
    'Constraints do NOT validate EXISTING data — only applied to writes AFTER the constraint is added',
    'NOT NULL enforced by schema (nullable = false); CHECK stored in TBLPROPERTIES',
    'Constraint violation on MERGE: entire MERGE fails — no partial application of rows',
    'View constraints: DESCRIBE TABLE EXTENDED shows constraints; DESCRIBE DETAIL does NOT',
  ],
  code:[
    '-- Add CHECK constraint',
    'ALTER TABLE catalog.schema.orders',
    'ADD CONSTRAINT valid_amount CHECK (amount > 0);',
    '',
    'ALTER TABLE catalog.schema.orders',
    'ADD CONSTRAINT valid_status CHECK (status IN (\'pending\', \'shipped\', \'delivered\', \'cancelled\'));',
    '',
    '-- Add NOT NULL constraint (via schema change)',
    'ALTER TABLE catalog.schema.orders',
    'ALTER COLUMN order_id SET NOT NULL;',
    '',
    '-- View constraints',
    'DESCRIBE TABLE EXTENDED catalog.schema.orders;',
    '',
    '-- Drop constraint',
    'ALTER TABLE catalog.schema.orders',
    'DROP CONSTRAINT valid_amount;',
    '',
    '-- Violation example',
    'INSERT INTO catalog.schema.orders VALUES (1, -50.0, \'pending\');',
    '-- SparkException: CHECK constraint valid_amount (amount > 0) violated',
  ],
  mistakes:[
    '✗ Expecting constraints to validate data that was in the table BEFORE the constraint was added',
    '✗ Thinking constraint violation allows partial rows to succeed — entire write operation fails',
    '✗ Using DESCRIBE DETAIL to view constraints — constraints only in DESCRIBE TABLE EXTENDED',
  ],
  trap:[
    '✗ Constraints do NOT validate EXISTING data — only future writes are checked after constraint added',
    '✗ Constraint violation = ENTIRE write fails — no partial commit, even in MERGE with many rows',
    '✗ DESCRIBE TABLE EXTENDED shows constraints; DESCRIBE DETAIL does NOT show constraints',
    '✗ Existing data may violate constraints — adding constraint does NOT clean up historical violations',
    '✗ NOT NULL and CHECK are the only two Delta constraint types — no UNIQUE or FOREIGN KEY',
    '✗ Constraint violation is caught at WRITE TIME — not at read time or query planning time',
  ],
},

// ─── 3.1.13 ──────────────────────────────────────────────────────────────────
{num:'13',title:'3.1.13 — OPTIMIZE, OPTIMIZE FULL, ZORDER BY',
  what:[
    'OPTIMIZE: compacts many small Parquet files into fewer larger files — default target 1GB per file',
    'OPTIMIZE FULL: forces rewriting ALL files regardless of size — for Liquid Clustering re-clustering',
    'ZORDER BY: multi-dimensional clustering within files for better file skipping on filter columns',
  ],
  how:[
    'OPTIMIZE: reads small files, rewrites them as fewer larger Parquet files, updates Delta log',
    'ZORDER BY (col1, col2): interleaves bits of column values to spatially co-locate related data',
    'Z-ordering improves file skipping: queries filtering on ZORDER columns skip more files',
    'Bloom filter indexes built during OPTIMIZE — effective for high-cardinality equality filters',
  ],
  facts:[
    'OPTIMIZE target file size: 1GB — files approaching or exceeding 1GB not rewritten',
    'ZORDER BY max effective columns: ~4 — effectiveness degrades rapidly beyond 4 columns',
    'ZORDER BY on partition column = zero benefit — data already co-located by partition',
    'OPTIMIZE is idempotent — running twice on unchanged data produces no changes',
  ],
  code:[
    '-- Basic file compaction',
    'OPTIMIZE catalog.schema.orders;',
    '',
    '-- With ZORDER on most-queried filter columns',
    'OPTIMIZE catalog.schema.orders',
    'ZORDER BY (customer_id, order_date);',
    '',
    '-- Partition-filtered OPTIMIZE (only compact one partition)',
    'OPTIMIZE catalog.schema.orders',
    'WHERE order_date = \'2024-01-01\';',
    '',
    '-- OPTIMIZE FULL (rewrite ALL files — for Liquid Clustering)',
    'OPTIMIZE catalog.schema.orders FULL;',
    '',
    '-- Enable auto-optimize (Databricks)',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (',
    '    \'delta.autoOptimize.optimizeWrite\' = \'true\',',
    '    \'delta.autoOptimize.autoCompact\' = \'true\'',
    ');',
  ],
  mistakes:[
    '✗ ZORDER-ing the partition column — already co-located by partition, zero additional benefit',
    '✗ Expecting Bloom filters to work before OPTIMIZE runs — they are built DURING OPTIMIZE',
    '✗ ZORDER-ing more than 4 columns — effectiveness degrades rapidly, diminishing returns',
  ],
  trap:[
    '✗ ZORDER on partition column = ZERO additional benefit — partition already groups the data',
    '✗ Bloom filters require OPTIMIZE to be built — querying before OPTIMIZE = full scan, no bloom filter',
    '✗ ZORDER max ~4 effective columns — more than 4 gives rapidly diminishing returns',
    '✗ OPTIMIZE FULL rewrites ALL files — use for Liquid Clustering re-clustering only',
    '✗ OPTIMIZE is IDEMPOTENT — running on unchanged data produces no changes, safe to re-run',
    '✗ ZORDER is INCOMPATIBLE with Liquid Clustering — cannot use both on the same table',
    '✗ OPTIMIZE is not automatic — must schedule or use Predictive Optimization (UC managed tables)',
  ],
},

// ─── 3.1.14 ──────────────────────────────────────────────────────────────────
{num:'14',title:'3.1.14 — Liquid Clustering: CLUSTER BY, Max 4 Keys, Incompatible with Partitioning/ZORDER',
  what:[
    'Liquid Clustering: modern replacement for static partitioning and ZORDER — adaptive, incremental clustering',
    'CLUSTER BY (col1, col2): defines clustering columns at table creation or via ALTER TABLE',
    'Incrementally re-clusters only CHANGED data — unlike ZORDER which rewrites all files',
  ],
  how:[
    'Liquid Clustering uses Hilbert space-filling curve to co-locate related data in files',
    'Each OPTIMIZE or OPTIMIZE FULL incrementally clusters newly added/modified data',
    'No need to know query patterns upfront — clustering columns can be changed with ALTER TABLE',
    'Clustering information stored in Delta log — Spark uses it for file skipping during queries',
  ],
  facts:[
    'Maximum 4 clustering columns — enforced limit, more columns cause an error',
    'Liquid Clustering is INCOMPATIBLE with table partitioning — cannot use both PARTITIONED BY and CLUSTER BY',
    'Liquid Clustering is INCOMPATIBLE with ZORDER BY — these are competing clustering strategies',
    'Clustering columns can be changed with ALTER TABLE ... CLUSTER BY (new_cols) — unlike partitioning',
    'OPTIMIZE FULL triggers full re-clustering of all data — use after changing clustering columns',
  ],
  code:[
    '-- Create table with Liquid Clustering',
    'CREATE TABLE catalog.schema.events',
    'CLUSTER BY (event_date, user_id)',
    'AS SELECT * FROM source_events;',
    '',
    '-- Add Liquid Clustering to existing table',
    'ALTER TABLE catalog.schema.events',
    'CLUSTER BY (event_date, user_id);',
    '',
    '-- Change clustering columns (non-destructive)',
    'ALTER TABLE catalog.schema.events',
    'CLUSTER BY (user_id, event_type);',
    '',
    '-- Full re-cluster after changing columns',
    'OPTIMIZE catalog.schema.events FULL;',
    '',
    '-- Remove Liquid Clustering',
    'ALTER TABLE catalog.schema.events',
    'CLUSTER BY NONE;',
    '',
    '-- WRONG: cannot combine with partitioning',
    '-- CREATE TABLE t PARTITIONED BY (date) CLUSTER BY (user_id)  ERROR',
  ],
  mistakes:[
    '✗ Using more than 4 clustering columns — enforced limit, causes error',
    '✗ Combining Liquid Clustering with PARTITIONED BY — mutually exclusive, causes error',
    '✗ Combining Liquid Clustering with ZORDER BY in OPTIMIZE — incompatible strategies',
    '✗ Expecting Liquid Clustering to fully cluster data without running OPTIMIZE — must run OPTIMIZE',
  ],
  trap:[
    '✗ Maximum 4 clustering columns — more than 4 causes an error, not just degraded performance',
    '✗ Liquid Clustering is INCOMPATIBLE with PARTITIONED BY — mutually exclusive at table level',
    '✗ Liquid Clustering is INCOMPATIBLE with ZORDER BY — cannot use ZORDER on clustered tables',
    '✗ Clustering columns CAN be changed with ALTER TABLE CLUSTER BY — unlike partitioning (immutable)',
    '✗ OPTIMIZE FULL needed after changing clustering columns to re-cluster existing data',
    '✗ Liquid Clustering is INCREMENTAL — only newly written data clustered on each OPTIMIZE run',
    '✗ CLUSTER BY NONE removes clustering — table reverts to non-clustered behavior',
  ],
},

// ─── 3.1.15 ──────────────────────────────────────────────────────────────────
{num:'15',title:'3.1.15 — Deletion Vectors — Bitmap-Based, No File Rewrite for DELETE/UPDATE/MERGE',
  what:[
    'Deletion vectors: bitmaps stored alongside Parquet files that mark rows as deleted — without rewriting files',
    'Enabled with delta.enableDeletionVectors = true on a table',
    'DELETE, UPDATE, and MERGE operations record deleted rows in a deletion vector bitmap instead of rewriting Parquet',
  ],
  how:[
    'Traditional DELETE: rewrites affected Parquet files with deleted rows removed — O(file size)',
    'With deletion vectors: a small bitmap file records which row positions are deleted — O(deleted rows)',
    'On read: Spark reads the Parquet file AND the deletion vector, filters out marked rows transparently',
    'OPTIMIZE eventually merges deletion vectors by rewriting Parquet files — consolidation step',
  ],
  facts:[
    'Deletion vectors dramatically speed up DELETE/UPDATE/MERGE on large files',
    'Deletion vector files stored in _delta_log/deletion_vector/ directory alongside the table files',
    'VACUUM cleans up deletion vector files — same retention rules as regular Parquet files',
    'Deletion vectors are transparent to readers — applications see clean rows without deleted entries',
  ],
  ascii:true,
  code:[
    'WITHOUT Deletion Vectors:',
    'DELETE FROM orders WHERE order_id = 42;',
    '-> Reads file part-00001.parquet (10M rows)',
    '-> Rewrites part-00002.parquet (9,999,999 rows, row 42 removed)',
    'Cost: O(file size) -> must rewrite entire 10M-row file',
    '',
    'WITH Deletion Vectors (enabled):',
    'DELETE FROM orders WHERE order_id = 42;',
    '-> Writes small bitmap: dv-xxxx.bin (marks row position 42 as deleted)',
    '-> part-00001.parquet UNCHANGED',
    'Cost: O(deleted rows) -> only bitmap written, no file rewrite',
    '',
    'On READ:',
    '-> Reads part-00001.parquet AND dv-xxxx.bin',
    '-> Filters out row at position 42 (marked in bitmap)',
    '-> Returns 9,999,999 rows correctly',
  ],
  mistakes:[
    '✗ Assuming deletion vectors permanently avoid file rewrites — OPTIMIZE eventually rewrites files',
    '✗ Expecting deletion vectors to work without enabling delta.enableDeletionVectors = true',
    '✗ Thinking deleted rows are immediately gone from storage — bitmap marks them, files still contain rows',
  ],
  trap:[
    '✗ Deletion vectors avoid FILE REWRITE for DELETE/UPDATE/MERGE — small bitmap written instead',
    '✗ Deletion vector files stored in _delta_log/deletion_vector/ — cleaned up by VACUUM',
    '✗ Rows marked in deletion vectors are still physically in Parquet files — just ignored on read',
    '✗ OPTIMIZE consolidates deletion vectors by rewriting Parquet files — permanent cleanup',
    '✗ Deletion vectors are TRANSPARENT to readers — applications see clean results without deleted rows',
    '✗ delta.enableDeletionVectors = true must be set — not enabled by default on all tables',
    '✗ GDPR delete with deletion vectors: still need VACUUM after OPTIMIZE to physically remove data',
  ],
},

// ─── 3.2.1 ───────────────────────────────────────────────────────────────────
{num:'16',title:'3.2.1 — PIVOT, UNPIVOT in Spark SQL',
  what:[
    'PIVOT: rotates rows into columns — converts unique values from one column into multiple columns',
    'UNPIVOT: rotates columns back into rows — normalizes wide table format into long format',
    'Both are analytical reshaping operations — no shuffle equivalent to wide transformation in nature',
  ],
  how:[
    'PIVOT: specify pivot column (values become columns), aggregate function, and list of pivot values',
    'UNPIVOT: specify columns to unpivot, name for the new value column, and name for the key column',
    'Spark SQL supports both in SQL syntax; DataFrame API uses .groupBy().pivot().agg()',
  ],
  facts:[
    'PIVOT aggregate must be specified — SUM, AVG, COUNT, etc. applied to the value column',
    'PIVOT column values must be specified explicitly in SQL — Spark does not auto-detect pivot values',
    'UNPIVOT is available in Spark SQL (UNPIVOT keyword) and via stack() function in DataFrame API',
  ],
  code:[
    '-- PIVOT: rotate quarters from rows to columns',
    'SELECT * FROM (',
    '    SELECT region, quarter, sales',
    '    FROM quarterly_sales',
    ')',
    'PIVOT (',
    '    SUM(sales)                      -- aggregate function',
    '    FOR quarter                     -- column whose values become new column names',
    '    IN (\'Q1\', \'Q2\', \'Q3\', \'Q4\')   -- explicit list of new column names',
    ');',
    '-- Result columns: region, Q1, Q2, Q3, Q4',
    '',
    '-- UNPIVOT: rotate quarter columns back to rows',
    'SELECT region, quarter, sales',
    'FROM quarterly_wide',
    'UNPIVOT (',
    '    sales               -- new value column name',
    '    FOR quarter         -- new key column name',
    '    IN (Q1, Q2, Q3, Q4) -- columns to unpivot',
    ');',
    '',
    '# DataFrame API for PIVOT',
    'df.groupBy("region").pivot("quarter", ["Q1","Q2","Q3","Q4"]).agg(sum("sales")).show()',
  ],
  mistakes:[
    '✗ Forgetting to specify pivot values explicitly in SQL — Spark SQL requires explicit value list',
    '✗ Not providing an aggregate function in PIVOT — aggregate is mandatory',
    '✗ Using stack() function without specifying the correct number of pairs — first arg is pair count',
  ],
  trap:[
    '✗ PIVOT requires EXPLICIT list of pivot values — Spark does NOT auto-detect unique values in SQL',
    '✗ PIVOT requires an AGGREGATE function — even if just FIRST() or MAX() for already-unique data',
    '✗ UNPIVOT is available in Spark SQL as a keyword — DataFrame API uses stack() expression',
    '✗ PIVOT creates NULL for combinations that do not exist in the source data — not filtered out',
    '✗ pivot() in DataFrame API: second arg is the list of expected values — improves performance',
    '✗ PIVOT is not a shuffle — it is a local aggregation after groupBy which IS a wide transformation',
  ],
},

// ─── 3.2.2 ───────────────────────────────────────────────────────────────────
{num:'17',title:'3.2.2 — CTEs (Common Table Expressions)',
  what:[
    'CTE (WITH clause): named temporary result set defined at the beginning of a SQL query',
    'Makes complex queries more readable by breaking them into named, reusable logical steps',
    'CTEs are evaluated inline — they are NOT materialized as physical tables or cached',
  ],
  how:[
    'WITH cte_name AS (SELECT ...): defines the CTE — referenced by name in the main query',
    'Multiple CTEs: WITH cte1 AS (...), cte2 AS (...) — later CTEs can reference earlier ones',
    'Recursive CTEs: WITH RECURSIVE cte AS (base UNION ALL recursive_step) — for hierarchical data',
    'Spark SQL supports standard CTEs — recursive CTEs available in Spark 3.0+',
  ],
  facts:[
    'CTEs are NOT materialized — they are expanded inline by the optimizer, same as a subquery',
    'CTEs referenced multiple times in the same query may be re-evaluated each time — no auto-caching',
    'CTEs improve readability — no performance advantage over equivalent subqueries in most cases',
    'Spark SQL supports multiple CTEs and nested CTE references in a single WITH clause',
  ],
  code:[
    '-- Single CTE',
    'WITH active_orders AS (',
    '    SELECT order_id, customer_id, amount',
    '    FROM catalog.schema.orders',
    '    WHERE status = \'active\'',
    '      AND order_date >= \'2024-01-01\'',
    ')',
    'SELECT customer_id, SUM(amount) AS total_active',
    'FROM active_orders',
    'GROUP BY customer_id;',
    '',
    '-- Multiple CTEs',
    'WITH',
    'orders_2024 AS (SELECT * FROM orders WHERE YEAR(order_date) = 2024),',
    'high_value AS (SELECT * FROM orders_2024 WHERE amount > 1000),',
    'customer_summary AS (',
    '    SELECT customer_id, COUNT(*) AS order_count, SUM(amount) AS total',
    '    FROM high_value',
    '    GROUP BY customer_id',
    ')',
    'SELECT c.name, cs.order_count, cs.total',
    'FROM customer_summary cs',
    'JOIN customers c ON cs.customer_id = c.customer_id;',
  ],
  mistakes:[
    '✗ Expecting CTE to be automatically cached when referenced multiple times — CTEs are NOT cached',
    '✗ Using CTEs expecting them to improve performance over subqueries — no inherent benefit',
    '✗ Defining a CTE but not referencing it in the main query — Spark evaluates only referenced CTEs',
  ],
  trap:[
    '✗ CTEs are NOT materialized — they are expanded inline, same execution as subqueries',
    '✗ CTE referenced multiple times = evaluated multiple times — no automatic caching',
    '✗ For reuse with caching: use df.cache() or CREATE TEMP VIEW — not CTE',
    '✗ Multiple CTEs in one WITH clause: later CTEs CAN reference earlier CTEs defined in same WITH',
    '✗ CTEs improve READABILITY only — no performance guarantee over subqueries',
    '✗ Recursive CTEs available in Spark SQL (WITH RECURSIVE) — for hierarchical traversal',
  ],
},

// ─── 3.2.3 ───────────────────────────────────────────────────────────────────
{num:'18',title:'3.2.3 — Higher-Order Functions: TRANSFORM, FILTER, AGGREGATE, EXISTS, FORALL',
  what:[
    'Higher-order functions: SQL/DataFrame functions that apply a lambda expression to array elements',
    'Operate on ArrayType columns without the expensive explode then group-back pattern',
    'Six key functions: TRANSFORM, FILTER, AGGREGATE, EXISTS, FORALL, ZIP_WITH',
  ],
  how:[
    'TRANSFORM(array, x -> expr): apply expression to each element — returns new array of SAME length',
    'FILTER(array, x -> condition): returns new array with ONLY elements matching condition',
    'AGGREGATE(array, init, (acc, x) -> expr): fold array to a SINGLE value using accumulator',
    'EXISTS(array, x -> condition): returns BOOLEAN true if ANY element satisfies the condition',
    'FORALL(array, x -> condition): returns boolean true only if ALL elements satisfy the condition',
    'ZIP_WITH(array1, array2, (x,y) -> expr): element-wise merge of two equal-length arrays',
  ],
  code:[
    '-- SQL syntax',
    'SELECT',
    '    TRANSFORM(prices, p -> p * 1.1)            AS prices_with_tax,',
    '    FILTER(tags, t -> t != \'expired\')         AS active_tags,',
    '    AGGREGATE(scores, 0, (acc, x) -> acc + x)  AS total_score,',
    '    EXISTS(flags, f -> f = \'urgent\')          AS has_urgent,',
    '    FORALL(checks, c -> c = true)              AS all_passed',
    'FROM event_table;',
    '',
    '# Python DataFrame API',
    'df.withColumn("prices_tax",  transform(col("prices"), lambda p: p * 1.1)) \\',
    '  .withColumn("active_tags", array_filter(col("tags"), lambda t: t != "expired")) \\',
    '  .withColumn("total",       aggregate(col("scores"), lit(0), lambda acc, x: acc + x)) \\',
    '  .withColumn("has_urgent",  exists(col("flags"), lambda f: f == "urgent")) \\',
    '  .withColumn("all_passed",  forall(col("checks"), lambda c: c == True))',
  ],
  trap:[
    '✗ FILTER returns a new ARRAY — does NOT filter DataFrame rows like .filter() does',
    '✗ EXISTS returns BOOLEAN — FORALL also returns boolean (not an array)',
    '✗ TRANSFORM returns SAME-LENGTH array — cannot reduce array size',
    '✗ AGGREGATE requires all three: input array, zero/init value, merge function',
    '✗ Python API uses lambda; SQL uses arrow -> notation',
    '✗ These work on ArrayType columns ONLY — not on MapType directly',
  ],
},

// ─── 3.2.4 ───────────────────────────────────────────────────────────────────
{num:'19',title:'3.2.4 — Deduplication Strategies (dropDuplicates, ROW_NUMBER, MERGE, watermark)',
  what:[
    'Deduplication: identifying and removing duplicate rows from a dataset',
    'Four main strategies: dropDuplicates(), ROW_NUMBER() window function, insert-only MERGE, streaming watermark dedup',
    'Strategy choice depends on: batch vs streaming, need for exactly-once, scale, and business key',
  ],
  how:[
    'dropDuplicates(["key_col"]): keeps first occurrence of each key — non-deterministic for ties',
    'ROW_NUMBER() + filter: window function ranks duplicates, filter keeps rank=1 — deterministic',
    'Insert-only MERGE: WHEN NOT MATCHED THEN INSERT — idempotent',
    'Streaming watermark dedup: withWatermark().dropDuplicates() — bounded state',
  ],
  facts:[
    'dropDuplicates() on full DataFrame: drops ALL columns duplicates; dropDuplicates(["id"]): on id only',
    'ROW_NUMBER() dedup: deterministic — use orderBy to control WHICH duplicate is kept',
    'Insert-only MERGE: never updates, ensures each key inserted once',
    'Streaming dedup WITHOUT watermark = unbounded state growth = OOM',
  ],
  code:[
    '# Strategy 1: dropDuplicates (keeps first occurrence per key)',
    'df.dropDuplicates(["order_id"])',
    '',
    '# Strategy 2: ROW_NUMBER (deterministic — keeps latest by event_time)',
    'w = Window.partitionBy("order_id").orderBy(col("event_time").desc())',
    'df.withColumn("rn", row_number().over(w)) \\',
    '  .filter(col("rn") == 1) \\',
    '  .drop("rn")',
    '',
    '# Strategy 3: Insert-only MERGE (idempotent — never inserts duplicate keys)',
    'spark.sql("""',
    '    MERGE INTO catalog.schema.orders t',
    '    USING (SELECT DISTINCT * FROM new_orders) s',
    '    ON t.order_id = s.order_id',
    '    WHEN NOT MATCHED THEN INSERT *',
    '""")',
    '',
    '# Strategy 4: Streaming dedup with watermark (bounded state)',
    '(stream_df',
    '    .withWatermark("event_time", "1 hour")',
    '    .dropDuplicates(["event_id"])',
    '    .writeStream',
    '    .outputMode("append")',
    '    .option("checkpointLocation", "/chk/dedup/")',
    '    .table("events_deduped"))',
  ],
  mistakes:[
    '✗ Using dropDuplicates() on streaming without watermark — unbounded state growth, OOM risk',
    '✗ Using insert-only MERGE without deduplicating the source first — duplicate keys cause MERGE error',
    '✗ Using dropDuplicates() in batch when ordering matters — non-deterministic, may keep wrong duplicate',
  ],
  trap:[
    '✗ dropDuplicates() in batch is NON-DETERMINISTIC for which duplicate is kept',
    '✗ Streaming dropDuplicates without watermark = UNBOUNDED STATE = OOM',
    '✗ Insert-only MERGE with duplicate source keys = UpsertOperationNotAllowedException',
    '✗ ROW_NUMBER() is deterministic — orderBy controls which duplicate survives',
    '✗ Streaming dedup with watermark: duplicates after watermark window may pass through',
    '✗ withWatermark MUST be before dropDuplicates in streaming chain — order matters',
  ],
},

// ─── 3.3.1 ───────────────────────────────────────────────────────────────────
{num:'20',title:'3.3.1 — Enabling CDF and Reading Change Events',
  what:[
    'CDF (Change Data Feed): Delta feature that tracks row-level changes — inserts, updates, deletes',
    'Enabled per table via TBLPROPERTIES — generates _change_data/ directory alongside data files',
    'Allows downstream systems to consume only changed rows instead of re-scanning the full table',
  ],
  how:[
    'Enable: ALTER TABLE t SET TBLPROPERTIES (delta.enableChangeDataFeed = true)',
    'CDF writes change records to _change_data/ directory on every DML operation',
    'Read batch: spark.read.option("readChangeFeed","true").option("startingVersion",0).table("t")',
    'Read stream: spark.readStream.option("readChangeFeed","true").option("startingVersion",0).table("t")',
    'table_changes("table_name", startVersion, endVersion): SQL function for batch CDF reads',
  ],
  facts:[
    'CDF must be enabled BEFORE changes occur — no retroactive history, CDF starts from enable commit',
    'CDF adds storage overhead (~20%) — _change_data/ stores change records alongside data',
    'startingVersion in readStream IGNORED if checkpoint exists — checkpoint takes precedence',
    'table_changes() SQL function: SELECT * FROM table_changes("my_table", 5, 10)',
  ],
  code:[
    '-- Enable CDF on existing table',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (delta.enableChangeDataFeed = true);',
    '',
    '-- Batch read: all changes from version 0 to version 10',
    'SELECT * FROM table_changes(\'catalog.schema.orders\', 0, 10);',
    '',
    '# Batch read with DataFrame API',
    'df_changes = (spark.read',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", 0)',
    '    .option("endingVersion", 10)',
    '    .table("catalog.schema.orders"))',
    '',
    '# Streaming CDF read',
    'cdf_stream = (spark.readStream',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", 0)',
    '    .table("catalog.schema.orders"))',
  ],
  mistakes:[
    '✗ Enabling CDF after data exists and expecting to read pre-enable history — CDF starts from enable',
    '✗ Not filtering by _change_type — both update_preimage and update_postimage rows returned',
    '✗ Using readChangeFeed on a table without CDF enabled — stream fails',
  ],
  trap:[
    '✗ CDF must be enabled BEFORE changes — retroactive history is NOT available',
    '✗ readChangeFeed on table without CDF enabled = stream FAILS immediately',
    '✗ startingVersion IGNORED when checkpoint exists — checkpoint always wins',
    '✗ CDF adds ~20% storage overhead — _change_data/ directory stores change records',
    '✗ table_changes() is SQL-only — DataFrame API uses .option("readChangeFeed","true")',
    '✗ CDF history bounded by logRetentionDuration — CDF records older than retention are gone',
  ],
},

// ─── 3.3.2 ───────────────────────────────────────────────────────────────────
{num:'21',title:'3.3.2 — _change_type Values: insert, update_preimage, update_postimage, delete',
  what:[
    '_change_type: column added to every row in a CDF read — identifies the type of change',
    'Four possible values: insert, update_preimage, update_postimage, delete',
    'Understanding these values is critical for correctly processing CDF data downstream',
  ],
  how:[
    'insert: a new row was inserted — contains the new row values',
    'update_preimage: the row BEFORE the update — old values before the change',
    'update_postimage: the row AFTER the update — new values after the change',
    'delete: a row was deleted — contains the deleted row values before deletion',
  ],
  facts:[
    'UPDATE always emits TWO rows: update_preimage AND update_postimage — always filter appropriately',
    '_change_type is automatically added to every row in a CDF read — cannot be disabled',
    'insert from INSERT INTO: one row per inserted record with _change_type = "insert"',
    'MERGE operations also generate CDF records — inserts as insert, updates as preimage/postimage',
  ],
  ascii:true,
  code:[
    'OPERATION       |  CDF ROWS GENERATED',
    '----------------|------------------------------------------',
    'INSERT 1 row    |  1 row: _change_type = "insert"',
    'UPDATE 1 row    |  2 rows: _change_type = "update_preimage" (before)',
    '                |          _change_type = "update_postimage" (after)',
    'DELETE 1 row    |  1 row: _change_type = "delete"',
    '',
    'MERGE 10 inserts + 5 updates + 2 deletes:',
    '                |  10 rows: "insert"',
    '                |  10 rows: 5 x "update_preimage" + 5 x "update_postimage"',
    '                |   2 rows: "delete"',
    '                |  Total: 22 CDF rows for 17 source operations',
    '',
    'FILTERING PATTERNS:',
    '-- Only new/current values (inserts + post-updates)',
    'WHERE _change_type IN (\'insert\', \'update_postimage\')',
    '',
    '-- Only deletes',
    'WHERE _change_type = \'delete\'',
  ],
  mistakes:[
    '✗ Treating update_preimage as a new insert — it represents the OLD value before the update',
    '✗ Not filtering _change_type — processing both preimage and postimage doubles data',
    '✗ Counting CDF rows as operation count — UPDATE generates 2 rows per updated record',
  ],
  trap:[
    '✗ UPDATE emits TWO rows — update_preimage (before) AND update_postimage (after)',
    '✗ Processing all CDF rows without filtering = double-counting updates as both old and new values',
    '✗ update_preimage + update_postimage are for the SAME record — joined by business key',
    '✗ MERGE operations also generate CDF records — same _change_type semantics apply',
    '✗ CDF row count != DML operation count — UPDATE generates 2 CDF rows per 1 updated record',
    '✗ delete CDF row contains the DELETED row values — useful for propagating deletes downstream',
  ],
},

// ─── 3.3.3 ───────────────────────────────────────────────────────────────────
{num:'22',title:'3.3.3 — Propagating Deletes Downstream Using CDF',
  what:[
    'Using CDF to propagate DELETE operations from a source table to a downstream Silver/Gold table',
    'Without CDF: downstream must re-scan full source to detect deleted rows — expensive and complex',
    'With CDF: DELETE events appear as _change_type = "delete" rows — process incrementally',
  ],
  how:[
    'Source table has CDF enabled — DELETE operations generate _change_type = "delete" CDF rows',
    'Downstream reads CDF stream, filters for _change_type = "delete", applies DELETE to downstream',
    'Use foreachBatch to apply MERGE or DELETE to downstream Delta table based on CDF change type',
    'GDPR erasure pattern: DELETE from source + CDF to propagate + VACUUM to physically remove',
  ],
  facts:[
    'Without propagating deletes: downstream accumulates rows that no longer exist in source',
    'CDF is the standard pattern for propagating deletes in a medallion architecture',
    'foreachBatch + MERGE: handle all change types in one streaming operation',
    'Physical deletion for GDPR: CDF DELETE + MERGE DELETE downstream + VACUUM on both tables',
  ],
  code:[
    '# Source: CDF-enabled table with deletes',
    'cdf_stream = (spark.readStream',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", 0)',
    '    .table("catalog.schema.customers"))',
    '',
    'def propagate_changes(batch_df, batch_id):',
    '    upserts = batch_df.filter(',
    '        col("_change_type").isin(["insert", "update_postimage"])',
    '    ).drop("_change_type", "_commit_version", "_commit_timestamp")',
    '',
    '    deletes = batch_df.filter(col("_change_type") == "delete") \\',
    '        .select("customer_id")',
    '',
    '    if upserts.count() > 0:',
    '        upserts.createOrReplaceTempView("upsert_batch")',
    '        spark.sql("""MERGE INTO catalog.schema.customers_silver t',
    '            USING upsert_batch s ON t.customer_id = s.customer_id',
    '            WHEN MATCHED THEN UPDATE SET *',
    '            WHEN NOT MATCHED THEN INSERT *""")',
    '',
    '    if deletes.count() > 0:',
    '        deletes.createOrReplaceTempView("delete_batch")',
    '        spark.sql("""MERGE INTO catalog.schema.customers_silver t',
    '            USING delete_batch s ON t.customer_id = s.customer_id',
    '            WHEN MATCHED THEN DELETE""")',
    '',
    '(cdf_stream.writeStream',
    '    .foreachBatch(propagate_changes)',
    '    .option("checkpointLocation", "/chk/cdf_propagate/")',
    '    .trigger(availableNow=True)',
    '    .start().awaitTermination())',
  ],
  mistakes:[
    '✗ Reading only insert and update_postimage — missing delete events means downstream never reflects deletions',
    '✗ Not using foreachBatch for delete propagation — standard writeStream cannot handle deletes',
    '✗ Forgetting to VACUUM downstream table after CDF delete propagation for GDPR',
  ],
  trap:[
    '✗ CDF is the STANDARD PATTERN for propagating deletes downstream',
    '✗ Without CDF: detecting deletes requires full outer join between source and downstream',
    '✗ foreachBatch required for delete propagation — standard writeStream cannot apply MERGE DELETE',
    '✗ GDPR erasure: CDF DELETE + downstream MERGE DELETE + VACUUM on BOTH tables',
    '✗ _change_type = "delete" rows contain the DELETED row values — use business key',
    '✗ update_preimage should NOT be propagated downstream — only propagate update_postimage',
  ],
},

// ─── 3.3.4 ───────────────────────────────────────────────────────────────────
{num:'23',title:'3.3.4 — CDF for Incremental Performance (Not Just CDC)',
  what:[
    'CDF is commonly associated with CDC but has a broader use case: incremental processing performance',
    'Instead of re-scanning entire source tables, CDF allows reading ONLY rows that changed',
    'Enables efficient incremental pipelines for aggregations and Silver/Gold table updates',
  ],
  how:[
    'Traditional incremental: filter by updated_at > last_run_timestamp — still scans all partitions',
    'CDF incremental: startingVersion = last_processed_version — reads ONLY new commit records',
    'CDF + MERGE: apply only changed rows to downstream — much smaller operation than full refresh',
    'CDF for aggregations: process only new/updated source rows, subtract old, add new',
  ],
  facts:[
    'CDF version-based incremental is more reliable than timestamp-based — no race conditions',
    'CDF reduces scan cost: only reads _change_data/ directory for changed rows',
    'CDF works well with materialized views pattern — DLT MVs use CDF internally',
    'startingVersion for batch CDF: specify version after last successful run',
  ],
  code:[
    '# Traditional incremental (full partition scan)',
    'last_run = "2024-01-15 10:00:00"',
    'df_incremental = spark.table("orders").filter(col("updated_at") > last_run)',
    '',
    '# CDF incremental (only changed rows since last version)',
    'last_version = 42  # stored in control table',
    '',
    'df_changes = (spark.read',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", last_version + 1)',
    '    .table("catalog.schema.orders"))',
    '',
    '# Process only new/changed rows',
    'new_and_updated = df_changes.filter(',
    '    col("_change_type").isin(["insert", "update_postimage"])',
    ')',
    '',
    '# Apply to downstream Silver table efficiently',
    'new_and_updated.createOrReplaceTempView("incremental_changes")',
    'spark.sql("""MERGE INTO catalog.schema.orders_silver t',
    '    USING incremental_changes s ON t.order_id = s.order_id',
    '    WHEN MATCHED THEN UPDATE SET *',
    '    WHEN NOT MATCHED THEN INSERT *""")',
  ],
  mistakes:[
    '✗ Using timestamp-based incremental instead of CDF version-based — race conditions at boundary',
    '✗ Not storing the last processed CDF version — on restart may re-process changes',
    '✗ Using CDF for tables with very high update rates — CDF storage overhead becomes significant',
  ],
  trap:[
    '✗ CDF is NOT only for CDC use cases — it enables efficient incremental processing',
    '✗ CDF version-based incremental is MORE RELIABLE than timestamp-based',
    '✗ CDF reduces scan cost by reading only _change_data/ — not re-scanning Parquet',
    '✗ Must store last processed version — CDF startingVersion with no checkpoint re-processes',
    '✗ DLT Materialized Views use CDF internally for incremental refresh',
  ],
},

// ─── 3.4.1 ───────────────────────────────────────────────────────────────────
{num:'24',title:'3.4.1 — SCD Type 0, 1, 2 — Implementation with MERGE and APPLY CHANGES',
  what:[
    'SCD (Slowly Changing Dimension): pattern for handling updates to dimension data over time',
    'Three types: Type 0 (immutable), Type 1 (overwrite), Type 2 (full history)',
    'Implementation in Databricks: MERGE INTO (batch) or APPLY CHANGES API (DLT streaming)',
  ],
  how:[
    'SCD Type 0: dimension never changes — insert only, reject updates (e.g. date dimension)',
    'SCD Type 1: overwrite current values — no history kept, current state only (MERGE UPDATE)',
    'SCD Type 2: keep full history — add __start_at, __end_at, __is_current; close old row, insert new',
    'APPLY CHANGES: stored_as_scd_type=2 — DLT manages Type 2 columns automatically',
  ],
  facts:[
    'SCD Type 2 output columns (APPLY CHANGES): __start_at, __end_at (null for current), __is_current',
    'SCD Type 2 current records: WHERE __is_current = true — always filter for current state',
    'MERGE for SCD Type 2: requires closing old row + inserting new row',
    'APPLY CHANGES handles SCD Type 2 automatically including out-of-order events via sequence_by',
  ],
  code:[
    '-- SCD Type 1: MERGE overwrite (no history)',
    'MERGE INTO catalog.schema.dim_customers t',
    'USING source_updates s',
    'ON t.customer_id = s.customer_id',
    'WHEN MATCHED THEN UPDATE SET',
    '    t.name = s.name, t.email = s.email, t.updated_at = s.updated_at',
    'WHEN NOT MATCHED THEN INSERT *;',
    '',
    '# SCD Type 2: APPLY CHANGES (DLT)',
    'import dlt',
    '',
    'dlt.apply_changes(',
    '    target="dim_customers_history",',
    '    source="customer_cdc_stream",',
    '    keys=["customer_id"],',
    '    sequence_by=col("updated_at"),',
    '    apply_as_deletes=col("op") == "DELETE",',
    '    stored_as_scd_type=2',
    ')',
    '# Output: customer_id, name, email, __start_at, __end_at, __is_current',
    '',
    '-- Query current records only',
    'SELECT * FROM catalog.schema.dim_customers_history WHERE __is_current = true;',
  ],
  mistakes:[
    '✗ Querying SCD Type 2 table without filtering __is_current = true — returns ALL historical rows',
    '✗ Using SCD Type 1 when historical analysis is needed — overwrites destroy history',
    '✗ Forgetting sequence_by in APPLY CHANGES — out-of-order events applied incorrectly',
  ],
  trap:[
    '✗ SCD Type 2 system columns: __start_at, __end_at, __is_current — exact names tested on exam',
    '✗ ALWAYS filter WHERE __is_current = true for current state',
    '✗ sequence_by is REQUIRED in APPLY CHANGES — handles late-arriving out-of-order events',
    '✗ APPLY CHANGES target MUST be a Streaming Table — not a Materialized View',
    '✗ SCD Type 1: simplest, no history; SCD Type 2: full history; SCD Type 0: immutable',
    '✗ APPLY CHANGES handles SCD Type 2 automatically — no manual __end_at management',
  ],
},

// ─── 3.4.2 ───────────────────────────────────────────────────────────────────
{num:'25',title:'3.4.2 — Medallion Architecture — Bronze/Silver/Gold Rules, PII Handling',
  what:[
    'Medallion Architecture: multi-hop data pipeline pattern with Bronze, Silver, Gold layers',
    'Each layer has specific data quality, access, and transformation responsibilities',
    'Industry-standard Lakehouse pattern — enforces progressive data quality and governance',
  ],
  how:[
    'Bronze: raw ingestion — exactly as received from source, no transformations, append-only',
    'Silver: cleansed, deduplicated, conformed — business logic applied, PII masked, joins possible',
    'Gold: aggregated, business-ready — metrics, KPIs, dashboard data, serve layer for BI/ML',
  ],
  facts:[
    'Bronze: never filter or drop records — all raw data preserved for reprocessing capability',
    'Silver: PII masked (hashing, tokenization) or removed — first access point for analysts',
    'Gold: no PII — aggregated data, safe for broad consumption',
    'Each layer stored as Delta tables — enables time travel and schema evolution at every layer',
  ],
  ascii:true,
  code:[
    'SOURCE SYSTEMS',
    '    |',
    '[BRONZE LAYER]  raw ingestion, no transforms, append-only',
    '    Kafka -> orders_bronze (all raw events, exactly as received)',
    '    Auto Loader -> customers_bronze (raw files from landing zone)',
    '    Access: Data Engineers only | PII: Present (raw)',
    '    |',
    '[SILVER LAYER]  cleaned, deduplicated, validated',
    '    orders_bronze -> orders_silver (dedup, null checks, schema conform)',
    '    customers_bronze -> customers_silver (PII masked, SCD Type 2)',
    '    Access: Data Engineers + Analysts | PII: Masked/Removed',
    '    |',
    '[GOLD LAYER]   aggregated, business metrics',
    '    orders_silver + customers_silver -> daily_revenue_gold',
    '    Access: BI tools, business users, ML models | PII: None',
  ],
  mistakes:[
    '✗ Filtering or transforming data in Bronze — Bronze should be raw, always reprocessable',
    '✗ Allowing business users direct access to Silver or Bronze — Gold is the consumption layer',
    '✗ Storing PII in Gold layer — PII should be masked/removed by Silver, Gold has no PII',
  ],
  trap:[
    '✗ Bronze should NEVER drop or filter records — preserve raw data for reprocessing',
    '✗ Silver is the FIRST layer where PII should be masked or removed — not Bronze',
    '✗ Gold is for AGGREGATED data only — should have zero PII, safe for broad business access',
    '✗ Analysts and BI tools should access GOLD layer — not Silver or Bronze directly',
    '✗ Bronze is append-only in most patterns — no deletes or updates at the Bronze layer',
    '✗ Each layer is a separate set of Delta tables — not just views on top of Bronze',
  ],
},

// ─── 3.4.3 ───────────────────────────────────────────────────────────────────
{num:'26',title:'3.4.3 — Multiplex Bronze Table Design (Topic Discriminator, Pitfalls)',
  what:[
    'Multiplex Bronze: storing multiple event types/topics in a single Bronze Delta table',
    'Uses a discriminator column (e.g. topic, event_type) to distinguish records by type',
    'Common pattern for Kafka multi-topic ingestion — single stream writes all topics to one Bronze',
  ],
  how:[
    'All events land in one table: orders_bronze with columns: topic, key, value, timestamp, offset',
    'topic column is the discriminator — used to filter and route records to per-topic Silver tables',
    'Silver processing: orders_bronze.filter(col("topic") == "orders") — parse and write per-topic',
    'JSON value payload: value column is binary/string — parse per-topic schema downstream',
  ],
  facts:[
    'Advantage: simpler ingestion — one stream, one checkpoint, one Auto Loader configuration',
    'Pitfall: different topics have different schemas — JSON value payload varies per topic',
    'Pitfall: schema inference must be per-topic — cannot infer one schema for mixed payloads',
    'Pitfall: _rescued_data may be high if wrong schema applied across all topics',
  ],
  code:[
    '# Multiplex Bronze: single stream, all Kafka topics',
    'multiplex_bronze = (spark.readStream',
    '    .format("kafka")',
    '    .option("kafka.bootstrap.servers", "broker:9092")',
    '    .option("subscribePattern", ".*")',
    '    .load()',
    '    .selectExpr(',
    '        "topic",',
    '        "CAST(key AS STRING) AS key",',
    '        "CAST(value AS STRING) AS value",',
    '        "timestamp", "partition", "offset"',
    '    ))',
    '',
    '(multiplex_bronze.writeStream',
    '    .format("delta")',
    '    .outputMode("append")',
    '    .option("checkpointLocation", "/chk/multiplex_bronze/")',
    '    .table("catalog.schema.events_bronze"))',
    '',
    '# Silver processing: filter by topic, apply per-topic schema',
    'orders_silver = (spark.readStream',
    '    .table("catalog.schema.events_bronze")',
    '    .filter(col("topic") == "orders")',
    '    .withColumn("parsed", from_json(col("value"), orders_schema))',
    '    .select("parsed.*", "timestamp", "offset"))',
  ],
  mistakes:[
    '✗ Applying a single schema to value column for all topics — different topics have different schemas',
    '✗ Not filtering by topic before applying schema — schema mismatch fills _rescued_data',
    '✗ Using one Silver checkpoint for all topics from multiplex — each Silver stream needs its own',
  ],
  trap:[
    '✗ Multiplex Bronze has ONE discriminator column — used to route to per-topic Silver tables',
    '✗ Different topics have DIFFERENT JSON schemas — apply per-topic schema AFTER filtering',
    '✗ Each Silver stream needs its OWN checkpoint — cannot share between topic-specific streams',
    '✗ value column in Kafka multiplex Bronze is a STRING (after cast) — NOT structured data',
    '✗ High _rescued_data in multiplex Silver = wrong schema applied to a topic — check filtering',
    '✗ Advantage: single ingestion stream; Pitfall: schema diversity per topic requires parsing',
  ],
},

// ─── 3.4.4 ───────────────────────────────────────────────────────────────────
{num:'27',title:'3.4.4 — Quarantine Table Pattern (Route Bad Records, Never Drop Silently)',
  what:[
    'Quarantine pattern: routing invalid records to a separate quarantine table instead of silently dropping',
    'Core principle: never silently discard data — always preserve rejected records for investigation',
    'Enables data recovery, root cause analysis, and upstream quality feedback loops',
  ],
  how:[
    'Step 1: Bronze — ingest ALL records without any quality filtering (raw layer)',
    'Step 2: Silver — apply quality checks, tag records with is_valid flag',
    'Step 3: Route — valid records to main Silver table, invalid records to quarantine table',
    'Quarantine table: same schema as Silver + error_reason column explaining why record was rejected',
  ],
  facts:[
    'expect_or_drop in DLT silently loses data — quarantine pattern is the production-safe alternative',
    'Quarantine table allows REPROCESSING after upstream fix — records not permanently lost',
    'Error reason column: critical for diagnosing upstream data quality issues quickly',
    'Monitor quarantine table: sudden increase in quarantine rate = upstream system issue',
  ],
  code:[
    'import dlt',
    '',
    '@dlt.table(name="orders_validated")',
    'def orders_validated():',
    '    return (dlt.read_stream("orders_bronze")',
    '        .withColumn("is_valid",',
    '            (col("order_id").isNotNull()) &',
    '            (col("amount") > 0) &',
    '            (col("customer_id").isNotNull()))',
    '        .withColumn("validation_timestamp", current_timestamp()))',
    '',
    '@dlt.table(name="orders_silver")',
    'def orders_silver():',
    '    return dlt.read("orders_validated").filter(col("is_valid") == True)',
    '',
    '@dlt.table(name="orders_quarantine")',
    'def orders_quarantine():',
    '    return (dlt.read("orders_validated")',
    '        .filter(col("is_valid") == False)',
    '        .withColumn("error_reason",',
    '            when(col("order_id").isNull(), "null_order_id")',
    '            .when(col("amount") <= 0, "invalid_amount")',
    '            .when(col("customer_id").isNull(), "null_customer_id")',
    '            .otherwise("unknown_validation_failure"))',
    '        .withColumn("quarantine_timestamp", current_timestamp()))',
  ],
  mistakes:[
    '✗ Using DLT expect_or_drop instead of quarantine pattern — silently loses records',
    '✗ Dropping records in Bronze layer — Bronze should always be a complete raw copy',
    '✗ Not adding error_reason column to quarantine — makes diagnosing upstream issues much harder',
    '✗ Not monitoring quarantine table row count — upstream issues accumulate silently',
  ],
  trap:[
    '✗ expect_or_drop SILENTLY DROPS records — quarantine pattern PRESERVES them for investigation',
    '✗ Bronze layer should NEVER drop or filter records — quality applied at Silver',
    '✗ Quarantine table should have SAME schema as Silver PLUS error metadata columns',
    '✗ Quarantine records can be REPROCESSED after upstream fix — data is not permanently lost',
    '✗ Monitor quarantine rate — sudden increase = upstream data quality issue',
    '✗ Quarantine vs expect: expect logs violation count; quarantine physically routes bad records',
    '✗ Never use expect_or_drop in production pipelines where data recovery is required',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain3_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
