'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 2  —  Data Ingestion & Acquisition  —  15 Sub-Topics',
  groups: [
    ['2.1  Storage Abstraction',[
      ['01','2.1.1','DBFS (Databricks File System) — path prefix, root, data plane'],
      ['02','2.1.2','Mounts — Legacy Workspace-Wide Storage (Deprecated in UC)'],
      ['03','2.1.3','Unity Catalog Volumes — Managed vs External, /Volumes/ Path'],
    ]],
    ['2.2  Auto Loader — Complete Reference',[
      ['04','2.2.1','Auto Loader vs COPY INTO — Decision Framework'],
      ['05','2.2.2','Directory Listing vs File Notification Mode'],
      ['06','2.2.3','Schema Inference (First Run Infers, Subsequent Runs Use Stored Schema)'],
      ['07','2.2.4','inferColumnTypes and schemaHints'],
      ['08','2.2.5','Schema Evolution Modes: addNewColumns, rescue, failOnNewColumns, none'],
      ['09','2.2.6','_rescued_data Column — Capture Schema Mismatches'],
      ['10','2.2.7','readChangeFeed Error When CDF Not Enabled on Source'],
    ]],
    ['2.3  File Format Ingestion',[
      ['11','2.3.1','All Formats: Delta, Parquet, ORC, Avro, JSON, CSV, XML, Text, Binary'],
    ]],
    ['2.4  Streaming Ingestion from Message Buses',[
      ['12','2.4.1','Kafka / Event Hubs: startingOffsets earliest vs latest Trap'],
      ['13','2.4.2','Kafka Message Decoding (key/value as binary — cast to string)'],
    ]],
    ['2.5  CTAS — Executes Once Only',[
      ['14','2.5.1','CTAS is a Static Snapshot — Does Not Re-Execute on Query'],
      ['15','2.5.2','VIEW vs CTAS vs Materialized View — Refresh Behavior Comparison'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 2  —  Data Ingestion & Acquisition  —  All High-Priority Traps',
};

const pages = [

// ─── 2.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'2.1.1 — DBFS (Databricks File System) — path prefix, root, data plane',
  what:[
    'DBFS: a distributed file system abstraction layer mounted into every Databricks workspace',
    'Provides a unified path namespace — allows access to cloud object storage (S3, ADLS, GCS) via file paths',
    'DBFS is NOT a real file system — it is an abstraction that maps paths to cloud storage locations',
  ],
  how:[
    'DBFS root: dbfs:/ prefix — the default DBFS root location backed by cloud storage in Databricks-managed bucket',
    '/dbfs/ FUSE mount: local path on the driver node — %sh ls /dbfs/mnt/ accesses DBFS via Linux file ops',
    'Data plane: DBFS root lives in the customer cloud account (S3/ADLS) — not in Databricks control plane',
    'Spark reads from DBFS paths: spark.read.parquet("dbfs:/mnt/data/") or spark.read.parquet("/mnt/data/")',
  ],
  facts:[
    'dbfs:/ prefix = same path as /dbfs/ on the driver — both point to the same DBFS location',
    'DBFS root (dbfs:/) is a workspace-level storage — shared by all users in that workspace',
    'DBFS root is backed by cloud storage in customer account — Databricks does not own the data',
    'Unity Catalog deprecates DBFS root access — UC Volumes is the recommended replacement',
  ],
  code:[
    '# Access DBFS via Spark — both paths are equivalent',
    'spark.read.parquet("dbfs:/mnt/data/orders/")',
    'spark.read.parquet("/mnt/data/orders/")   # dbfs:/ prefix is optional in Spark',
    '',
    '# Access DBFS via dbutils.fs',
    'dbutils.fs.ls("dbfs:/mnt/landing/")',
    'dbutils.fs.ls("/mnt/landing/")  # equivalent',
    '',
    '# Access DBFS via shell (FUSE mount on driver)',
    '%sh ls /dbfs/mnt/landing/   # /dbfs/ prefix REQUIRED for shell access',
    '',
    '# DBFS root (Databricks-managed bucket)',
    'dbutils.fs.ls("dbfs:/")',
    '# Shows: FileStore/, user/, tmp/, etc.',
    '',
    '# Write to DBFS',
    'df.write.parquet("dbfs:/user/me/output/")',
  ],
  mistakes:[
    '✗ Mixing up dbfs:/ and /dbfs/ — dbfs:/ is for Spark/dbutils; /dbfs/ is for %sh shell commands',
    '✗ Storing production data in DBFS root — DBFS root is a shared workspace bucket, not governed storage',
    '✗ Assuming DBFS provides fine-grained access control — DBFS has workspace-level access only',
  ],
  trap:[
    '✗ dbfs:/path and /mnt/path work in Spark — /dbfs/path is ONLY for %sh shell on the driver',
    '✗ DBFS root is in the customer cloud account — not in Databricks infrastructure',
    '✗ DBFS is workspace-scoped — no cross-workspace access, no Unity Catalog governance',
    '✗ DBFS root does NOT support Unity Catalog row filters, column masks, or lineage',
    '✗ Unity Catalog deprecates DBFS root — new projects should use UC Volumes or external locations',
    '✗ dbutils.fs operations run on DRIVER — not distributed to executors',
    '✗ DBFS root path dbfs:/ != a mount — it is the default Databricks-managed bucket directly',
  ],
},

// ─── 2.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'2.1.2 — Mounts — Legacy Workspace-Wide Storage (Deprecated in UC)',
  what:[
    'Mount: a DBFS path (/mnt/name) that maps to an external cloud storage location (S3, ADLS, GCS)',
    'Creates a shortcut so all workspace users can access cloud storage via /mnt/mountname/ paths',
    'Deprecated in Unity Catalog — mounts bypass UC governance, do not support row filters or lineage',
  ],
  how:[
    'dbutils.fs.mount(source, mountPoint, extraConfigs): creates the mount — runs on driver, workspace-wide',
    'Once mounted, ALL users in the workspace can access the storage via /mnt/mountname/ — no per-user auth',
    'Mount credentials stored in cluster config or secret scope — same credentials for all users',
    'Mount persists across cluster restarts — stored in workspace metadata, not cluster-specific',
  ],
  facts:[
    'Mounts are workspace-wide — once mounted, every user on any cluster can access the data',
    'Mounts bypass Unity Catalog — no row filters, no column masks, no data lineage tracked',
    'Recommended migration: replace mounts with UC External Locations + UC Volumes',
    'dbutils.fs.unmount("/mnt/name"): removes the mount — does NOT delete the underlying cloud data',
  ],
  code:[
    '# Create a mount (legacy pattern — not recommended with UC)',
    'dbutils.fs.mount(',
    '    source="s3a://my-bucket/data/",',
    '    mount_point="/mnt/my_data",',
    '    extra_configs={',
    '        "fs.s3a.access.key": dbutils.secrets.get("scope","access_key"),',
    '        "fs.s3a.secret.key": dbutils.secrets.get("scope","secret_key")',
    '    }',
    ')',
    '',
    '# Use the mount',
    'spark.read.parquet("/mnt/my_data/orders/")',
    'dbutils.fs.ls("/mnt/my_data/")',
    '',
    '# List all mounts',
    'dbutils.fs.mounts()',
    '',
    '# Remove mount (does NOT delete underlying data)',
    'dbutils.fs.unmount("/mnt/my_data")',
    '',
    '# UC replacement — External Location (governed, per-user auth)',
    'spark.read.parquet("abfss://container@account.dfs.core.windows.net/data/")',
  ],
  mistakes:[
    '✗ Creating new mounts in UC-enabled workspaces — bypasses UC governance, use External Locations',
    '✗ Storing mount credentials in cluster config directly — use secret scopes for credential management',
    '✗ Expecting per-user access control on mounts — mounts grant the same credentials to ALL users',
  ],
  trap:[
    '✗ Mounts are workspace-wide — ALL users get the same access level, no per-user auth',
    '✗ Mounts are DEPRECATED in Unity Catalog workspaces — External Locations is the replacement',
    '✗ dbutils.fs.unmount() does NOT delete the underlying cloud data — only removes the mapping',
    '✗ Mounts bypass UC row filters and column masks — no governance on mounted paths',
    '✗ Mount credentials are the same for all users — cannot restrict specific users from mount data',
    '✗ dbutils.fs.mounts() returns all current mounts including system mounts — not just user-created',
    '✗ New Databricks projects should use UC External Locations + Volumes, not mounts',
  ],
},

// ─── 2.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'2.1.3 — Unity Catalog Volumes — Managed vs External, /Volumes/ Path',
  what:[
    'UC Volume: a Unity Catalog object that provides governed access to non-tabular file storage',
    'Two types: Managed (Databricks manages storage location) and External (customer specifies location)',
    'Access path: /Volumes/catalog/schema/volume/file.csv — consistent across all cluster types',
  ],
  how:[
    'Managed Volume: storage location automatically assigned by UC — in the schema default location',
    'External Volume: user specifies an External Location — Databricks governs access but not storage',
    'UC enforces permissions on Volumes — READ VOLUME, WRITE VOLUME privileges required',
    'Accessible from: Spark, dbutils.fs, %sh via /Volumes/ path, UC UI file browser',
  ],
  facts:[
    'Volume path format: /Volumes/<catalog>/<schema>/<volume>/<path> — always this exact structure',
    'Managed Volume: dropping the volume DELETES the underlying files — same as managed table',
    'External Volume: dropping the volume does NOT delete the underlying files — same as external table',
    'UC row filters and column masks do NOT apply to Volumes — only to Delta tables',
  ],
  code:[
    '-- Create a managed volume (Databricks picks storage location)',
    'CREATE VOLUME prod_catalog.sales_schema.raw_files',
    '',
    '-- Create an external volume (customer specifies location)',
    'CREATE EXTERNAL VOLUME prod_catalog.sales_schema.raw_files',
    'LOCATION \'s3://my-bucket/raw-files/\'',
    '',
    '# Access via Spark',
    'spark.read.csv("/Volumes/prod_catalog/sales_schema/raw_files/orders.csv")',
    'df.write.parquet("/Volumes/prod_catalog/sales_schema/raw_files/output/")',
    '',
    '# Access via dbutils.fs',
    'dbutils.fs.ls("/Volumes/prod_catalog/sales_schema/raw_files/")',
    '',
    '# Access via %sh (driver only)',
    '%sh ls /Volumes/prod_catalog/sales_schema/raw_files/',
    '',
    '# Install .whl from UC Volume',
    '%pip install /Volumes/prod_catalog/libs/volume/my_pkg-1.0.0-py3-none-any.whl',
    '',
    '-- Grant access',
    'GRANT READ VOLUME ON VOLUME prod_catalog.sales_schema.raw_files TO analyst_group',
    'GRANT WRITE VOLUME ON VOLUME prod_catalog.sales_schema.raw_files TO data_engineers',
  ],
  mistakes:[
    '✗ Using DBFS root or mounts for new file storage in UC workspaces — use Volumes instead',
    '✗ Confusing /Volumes/ path with /mnt/ path — different systems, different governance models',
    '✗ Dropping a managed Volume without realizing it deletes all underlying files permanently',
  ],
  trap:[
    '✗ Volume path is ALWAYS /Volumes/catalog/schema/volume/ — four-level path, not two or three',
    '✗ Managed Volume DROP = files DELETED; External Volume DROP = files PRESERVED — same as table rules',
    '✗ UC privileges for Volumes: READ VOLUME (read files) and WRITE VOLUME (write/delete files)',
    '✗ Volumes do NOT support Delta table features — no time travel, no MERGE, no ACID on raw files',
    '✗ UC row filters and column masks do NOT apply to Volumes — they apply to Delta tables only',
    '✗ Volumes accessible from ALL cluster access modes — Single User, Shared, Serverless',
    '✗ /Volumes/ path works in %sh — unlike DBFS mounts which use /dbfs/ or /mnt/ for shell',
  ],
},

// ─── 2.2.1 ───────────────────────────────────────────────────────────────────
{num:'04',title:'2.2.1 — Auto Loader vs COPY INTO — Decision Framework',
  what:[
    'Auto Loader: structured streaming source that incrementally ingests new files from cloud storage',
    'COPY INTO: idempotent SQL command that batch-loads files from a directory into a Delta table',
    'Both handle incremental file ingestion — choice depends on scale, complexity, and use case',
  ],
  how:[
    'Auto Loader: uses streaming engine + checkpoint to track processed files — scales to millions of files',
    'COPY INTO: tracks loaded files in Delta table transaction log — re-running skips already-loaded files',
    'Auto Loader: readStream.format("cloudFiles") — continuous or triggered streaming micro-batch',
    'COPY INTO: SQL command COPY INTO my_table FROM \'path\' FILEFORMAT = JSON — runs as a batch job',
  ],
  facts:[
    'Auto Loader scales to millions of files via File Notification mode — COPY INTO does not scale as well',
    'COPY INTO is idempotent by default — same files loaded twice = loaded once (no duplicates)',
    'Auto Loader requires a checkpointLocation; COPY INTO tracks state in the Delta transaction log',
    'Auto Loader supports schema inference and evolution; COPY INTO requires schema to be known upfront',
  ],
  ascii:true,
  code:[
    'DECISION FRAMEWORK:',
    '',
    'File count < 10,000?  -> COPY INTO  (simple, SQL-based, SQL Warehouse works)',
    'File count > 10,000?  -> Auto Loader  (file notification mode, scales to millions)',
    '',
    'Need continuous streaming?  -> Auto Loader  (readStream, micro-batch or continuous)',
    'Need scheduled batch load?  -> COPY INTO or Auto Loader with availableNow trigger',
    '',
    'Need schema inference?  -> Auto Loader  (cloudFiles.schemaLocation required)',
    'Schema always known?    -> COPY INTO  (specify schema upfront)',
    '',
    'Need exactly-once?  -> COPY INTO  (idempotent by default)',
    'Need CDC / CDF?     -> Auto Loader with readChangeFeed',
    '',
    'Auto Loader:                          COPY INTO:',
    'readStream.format("cloudFiles")       COPY INTO target_table',
    '.option("cloudFiles.format","json")   FROM \'/path/to/files/\'',
    '.load("/path/")                       FILEFORMAT = JSON',
    '                                      COPY_OPTIONS (\'mergeSchema\' = \'true\')',
  ],
  mistakes:[
    '✗ Using COPY INTO for millions of files — directory listing degrades with large file counts',
    '✗ Using Auto Loader when a simple one-time scheduled load is needed — COPY INTO is simpler',
    '✗ Assuming COPY INTO is stateless — it tracks loaded files in the Delta transaction log',
  ],
  trap:[
    '✗ COPY INTO is IDEMPOTENT — loading same files twice does NOT create duplicates',
    '✗ Auto Loader requires a checkpointLocation; COPY INTO state is tracked in the Delta log',
    '✗ COPY INTO does NOT support schema inference by default — schema must be provided',
    '✗ Auto Loader scales to millions of files via File Notification — COPY INTO uses directory listing',
    '✗ COPY INTO runs on SQL Warehouse — Auto Loader requires a compute cluster',
    '✗ Auto Loader availableNow=True trigger: processes all pending files then stops — batch-style streaming',
    '✗ COPY INTO reloads files if Delta table is dropped and recreated — transaction log is reset',
  ],
},

// ─── 2.2.2 ───────────────────────────────────────────────────────────────────
{num:'05',title:'2.2.2 — Directory Listing vs File Notification Mode',
  what:[
    'Two Auto Loader file discovery modes: Directory Listing (default) and File Notification',
    'Directory Listing: scans entire source directory on each micro-batch to find new files',
    'File Notification: cloud event queue (SQS/Azure Event Grid/GCS Pub/Sub) pushes new file events',
  ],
  how:[
    'Directory Listing: Auto Loader lists all files, compares to checkpoint, identifies new ones — O(n)',
    'File Notification: cloud service sends event when new file arrives — Auto Loader reads from queue',
    'File Notification setup: Databricks automatically creates cloud resources (SQS, Event Grid topic, etc.)',
    'cloudFiles.useNotifications = true: enables file notification mode — requires cloud IAM permissions',
  ],
  facts:[
    'Directory Listing max practical scale: ~10,000 files per minute before performance degrades',
    'File Notification mode: nearly O(1) per batch regardless of total file count in directory',
    'File Notification requires cloud-specific IAM permissions to create queues and event subscriptions',
    'File Notification supported on: S3 (SQS), ADLS Gen2 (Event Grid), GCS (Pub/Sub)',
  ],
  ascii:true,
  code:[
    'DIRECTORY LISTING (default):',
    'Each micro-batch:',
    '  Auto Loader -> LIST all files in /path/ -> Compare to checkpoint -> Find new files',
    '  O(n) with total file count — slow when millions of files exist',
    '',
    'FILE NOTIFICATION (scalable):',
    'Cloud storage -> File created event -> SQS / Event Grid / Pub/Sub queue',
    '  Auto Loader -> Poll event queue -> Only new file events -> No directory scan needed',
    '  O(1) per batch regardless of total file count',
    '',
    'Enable file notification:',
    '.option("cloudFiles.useNotifications", "true")',
    '',
    'Databricks auto-creates:',
    '  AWS:   SQS queue + S3 event notification',
    '  Azure: Event Grid subscription',
    '  GCP:   Pub/Sub topic + GCS notification',
  ],
  mistakes:[
    '✗ Using Directory Listing for millions of files — listing latency degrades linearly',
    '✗ Forgetting cloud IAM permissions for File Notification mode — setup fails with auth error',
    '✗ Assuming File Notification guarantees strict ordering — order depends on cloud event delivery',
  ],
  trap:[
    '✗ Directory Listing scales O(n) with file count — slow for millions of files',
    '✗ File Notification scales O(1) — does not scan directory regardless of file count',
    '✗ File Notification requires cloud infrastructure setup (SQS/Event Grid) AND IAM permissions',
    '✗ cloudFiles.useNotifications = true — Databricks auto-creates cloud resources',
    '✗ File Notification does NOT guarantee strict file ordering — events can arrive slightly out of order',
    '✗ Without File Notification, large directories cause Auto Loader micro-batch latency to increase',
    '✗ File Notification mode costs extra — cloud queue and event infrastructure has associated cost',
  ],
},

// ─── 2.2.3 ───────────────────────────────────────────────────────────────────
{num:'06',title:'2.2.3 — Schema Inference (First Run Infers, Subsequent Runs Use Stored Schema)',
  what:[
    'Schema inference: Auto Loader automatically detects column names and types from source files',
    'cloudFiles.schemaLocation: path where inferred schema is stored as JSON for consistency across batches',
    'First run: samples files to infer schema and stores it; subsequent runs: loads stored schema directly',
  ],
  how:[
    'First micro-batch: Auto Loader samples a subset of incoming files to infer column names and types',
    'Inferred schema stored as JSON files in cloudFiles.schemaLocation directory (_schemas/ subfolder)',
    'Subsequent micro-batches: stored schema loaded directly — no re-sampling, consistent types',
    'Schema stored per source path — changing source path or schemaLocation = fresh inference',
  ],
  facts:[
    'cloudFiles.schemaLocation is REQUIRED when using schema inference — without it, schema re-inferred every batch',
    'First run inference samples only a subset of files — types may be wrong if sample is not representative',
    'Schema location stores: column names, data types, and metadata used for consistency enforcement',
    'Separate schemaLocation per Auto Loader stream — do not share between different source streams',
  ],
  code:[
    '# Schema inference with schemaLocation (REQUIRED for consistency)',
    'stream = (spark.readStream',
    '    .format("cloudFiles")',
    '    .option("cloudFiles.format", "json")',
    '    .option("cloudFiles.schemaLocation", "/Volumes/catalog/schema/vol/schema_store/orders/")',
    '    .load("/Volumes/catalog/schema/vol/landing/orders/"))',
    '',
    '# First run:',
    '#   -> samples files, infers schema -> stores in schemaLocation/_schemas/',
    '#   -> processes first batch with inferred schema',
    '',
    '# Subsequent runs:',
    '#   -> loads schema from schemaLocation/_schemas/',
    '#   -> no re-sampling -> consistent types guaranteed',
    '',
    '(stream.writeStream',
    '    .format("delta")',
    '    .option("checkpointLocation", "/Volumes/catalog/schema/vol/chk/orders/")',
    '    .table("catalog.schema.orders_bronze"))',
  ],
  mistakes:[
    '✗ Not providing schemaLocation — schema re-inferred every batch, causing type inconsistency over time',
    '✗ Sharing one schemaLocation between two Auto Loader streams — schema conflicts corrupt both streams',
    '✗ Assuming schema inference is perfect — unusual data in small sample may infer wrong types',
  ],
  trap:[
    '✗ cloudFiles.schemaLocation is REQUIRED for consistent schema inference — without it, re-infers every batch',
    '✗ First run SAMPLES a subset — types may be wrong for edge cases not in the sample',
    '✗ Subsequent runs use STORED schema — no re-sampling, consistent but potentially stale if source changes',
    '✗ schemaLocation stores schema metadata only — NOT a checkpoint for file tracking (that is separate)',
    '✗ One schemaLocation per stream — sharing between streams causes schema conflicts',
    '✗ Schema inference path: schemaLocation/_schemas/ — do not manually modify files in this directory',
    '✗ If source schema changes: Auto Loader detects mismatch and applies schema evolution rules',
  ],
},

// ─── 2.2.4 ───────────────────────────────────────────────────────────────────
{num:'07',title:'2.2.4 — inferColumnTypes and schemaHints',
  what:[
    'cloudFiles.inferColumnTypes: controls whether Auto Loader infers native types or defaults to strings',
    'cloudFiles.schemaHints: manually override inferred types for specific columns — partial schema guidance',
    'Both options refine schema inference behavior during the first-run sampling phase',
  ],
  how:[
    'inferColumnTypes = false (default): all columns inferred as StringType — safe but loses type info',
    'inferColumnTypes = true: infers native types — IntegerType, DoubleType, TimestampType, etc.',
    'schemaHints: space-separated column definitions — "amount double, event_date date"',
    'Other columns not in schemaHints are still inferred normally using inferColumnTypes setting',
  ],
  facts:[
    'inferColumnTypes = false is the default — all inferred columns are StringType unless overridden',
    'schemaHints only applies during the FIRST run when schema is being inferred',
    'CSV and JSON always default to StringType without inferColumnTypes = true',
    'Parquet/Avro/ORC: types already embedded in the file format — inferColumnTypes less relevant',
  ],
  code:[
    '# Default: all columns inferred as StringType',
    'stream = (spark.readStream',
    '    .format("cloudFiles")',
    '    .option("cloudFiles.format", "csv")',
    '    .option("cloudFiles.schemaLocation", "/chk/schema/")',
    '    .load("/landing/csv/"))',
    '# All columns will be StringType — safe but requires manual casting downstream',
    '',
    '# inferColumnTypes = true: detect int, double, timestamp etc.',
    'stream = (spark.readStream',
    '    .format("cloudFiles")',
    '    .option("cloudFiles.format", "json")',
    '    .option("cloudFiles.schemaLocation", "/chk/schema/")',
    '    .option("cloudFiles.inferColumnTypes", "true")',
    '    .load("/landing/json/"))',
    '',
    '# schemaHints: force specific types for critical columns',
    'stream = (spark.readStream',
    '    .format("cloudFiles")',
    '    .option("cloudFiles.format", "csv")',
    '    .option("cloudFiles.schemaLocation", "/chk/schema/")',
    '    .option("cloudFiles.inferColumnTypes", "true")',
    '    .option("cloudFiles.schemaHints", "amount double, event_date date, user_id long")',
    '    .load("/landing/csv/"))',
  ],
  mistakes:[
    '✗ Relying on default inferColumnTypes = false for numeric data — all columns become strings',
    '✗ Using schemaHints expecting it to override stored schema on subsequent runs — only first inference',
    '✗ Providing wrong type in schemaHints for a column — causes cast errors during ingestion',
  ],
  trap:[
    '✗ inferColumnTypes = false is the DEFAULT — columns default to StringType without this option',
    '✗ schemaHints only applies during FIRST RUN inference — ignored if schemaLocation already has stored schema',
    '✗ CSV columns are ALWAYS inferred as strings by default — even with inferColumnTypes=true, ambiguous values may stay as strings',
    '✗ schemaHints overrides inference for LISTED columns only — other columns still inferred normally',
    '✗ Parquet/Avro/ORC have embedded schemas — inferColumnTypes mainly relevant for text formats',
    '✗ If stored schema already exists in schemaLocation, schemaHints has NO effect — delete to force re-inference',
    '✗ schemaHints format: DDL-style string "col_name type, col2 type2" — not JSON or StructType object',
  ],
},

// ─── 2.2.5 ───────────────────────────────────────────────────────────────────
{num:'08',title:'2.2.5 — Schema Evolution Modes: addNewColumns, rescue, failOnNewColumns, none',
  what:[
    'Schema Evolution: how Auto Loader handles incoming data that has columns not in the stored schema',
    'Four modes: addNewColumns, rescue, failOnNewColumns, none',
    'Configured with cloudFiles.schemaEvolutionMode option on the readStream',
  ],
  how:[
    'addNewColumns (default when schemaLocation set): new columns added to target Delta schema automatically',
    'rescue: mismatched or extra columns captured in _rescued_data JSON column — no schema change',
    'failOnNewColumns: stream FAILS if incoming data has columns not in stored schema — strict enforcement',
    'none: new columns silently ignored — not added to schema, not rescued, just dropped',
  ],
  facts:[
    'addNewColumns is the default mode when schemaLocation is provided',
    'rescue mode always adds the _rescued_data column to the target schema — even if no rescue occurs',
    'failOnNewColumns triggers a stream restart with UnknownFieldException — stops pipeline for human review',
    'none mode silently drops unknown columns — data loss without warning',
  ],
  ascii:true,
  code:[
    'Incoming file has NEW column "discount" not in stored schema:',
    '',
    'MODE: addNewColumns',
    '  -> Stored schema updated: discount column ADDED',
    '  -> Target Delta table schema evolved: mergeSchema applied',
    '  -> discount values present in output rows',
    '',
    'MODE: rescue',
    '  -> Stored schema UNCHANGED',
    '  -> discount value captured in _rescued_data: {"discount": "10.5"}',
    '  -> Original row written, extra data in _rescued_data column',
    '',
    'MODE: failOnNewColumns',
    '  -> Stream FAILS with UnknownFieldException',
    '  -> Human intervention required to update schema',
    '  -> Pipeline stops until schema is manually updated',
    '',
    'MODE: none',
    '  -> Stored schema UNCHANGED',
    '  -> discount column SILENTLY DROPPED',
    '  -> Data loss — discount values are gone forever',
  ],
  mistakes:[
    '✗ Using failOnNewColumns in production with frequently changing sources — pipeline stops on every change',
    '✗ Using none mode without realizing it silently drops new columns — hidden data loss',
    '✗ Not setting mergeSchema = true on writeStream when using addNewColumns',
  ],
  trap:[
    '✗ addNewColumns is the DEFAULT when schemaLocation is provided — not rescue or none',
    '✗ rescue mode ALWAYS adds _rescued_data column to schema — even when no rescue occurs',
    '✗ failOnNewColumns causes stream FAILURE — not a warning, the stream actually stops',
    '✗ none mode SILENTLY DROPS new columns — data loss with no warning or error',
    '✗ addNewColumns requires mergeSchema = true on the writeStream target to actually persist changes',
    '✗ Schema evolution mode applies to NEW columns only — type changes on existing columns not handled',
    '✗ rescue and addNewColumns can be combined using _rescued_data column alongside schema evolution',
  ],
},

// ─── 2.2.6 ───────────────────────────────────────────────────────────────────
{num:'09',title:'2.2.6 — _rescued_data Column — Capture Schema Mismatches',
  what:[
    '_rescued_data: a special Auto Loader column that captures data that does not match the stored schema',
    'Contains any columns that were not in the expected schema — stored as a JSON string',
    'Prevents silent data loss when source data has unexpected fields or type mismatches',
  ],
  how:[
    'When schema evolution mode is rescue: extra/mismatched columns captured in _rescued_data column',
    '_rescued_data is a StringType column containing a JSON object with rescued field name-value pairs',
    'For type mismatches: column exists in schema but value cannot be cast — value goes to _rescued_data',
    'Also includes _metadata.file_path for traceability — which file the rescued data came from',
  ],
  facts:[
    '_rescued_data is NULL for rows with no schema mismatch — only populated when rescue occurs',
    '_rescued_data contains only the mismatched/extra fields — not the entire row',
    'Custom column name: .option("cloudFiles.rescuedDataColumn", "_my_rescue") — rename the rescue column',
    'Parse rescued data downstream: from_json(col("_rescued_data"), schema) to access rescued fields',
  ],
  code:[
    '# Enable rescue mode to capture schema mismatches',
    'stream = (spark.readStream',
    '    .format("cloudFiles")',
    '    .option("cloudFiles.format", "json")',
    '    .option("cloudFiles.schemaLocation", "/chk/schema/")',
    '    .option("cloudFiles.schemaEvolutionMode", "rescue")',
    '    .load("/landing/json/"))',
    '',
    '# Write to bronze with rescue column preserved',
    '(stream.writeStream',
    '    .format("delta")',
    '    .option("checkpointLocation", "/chk/stream/")',
    '    .option("mergeSchema", "true")',
    '    .table("catalog.schema.orders_bronze"))',
    '',
    '# Inspect rescued data downstream',
    'rescued_df = spark.read.table("catalog.schema.orders_bronze") \\',
    '    .filter(col("_rescued_data").isNotNull()) \\',
    '    .select("id", "event_time", "_rescued_data")',
    '',
    '# Parse rescued JSON to extract extra fields',
    'rescue_schema = StructType([StructField("discount", DoubleType())])',
    'rescued_df.withColumn("parsed_rescue", from_json(col("_rescued_data"), rescue_schema))',
  ],
  mistakes:[
    '✗ Ignoring _rescued_data column in production — high null count means schema mismatch issues upstream',
    '✗ Expecting _rescued_data to contain the full row — it contains ONLY mismatched/extra fields',
    '✗ Not monitoring _rescued_data for non-null values — silent data quality issues accumulate',
  ],
  trap:[
    '✗ _rescued_data is NULL for conforming rows — only populated when a schema mismatch occurs',
    '✗ _rescued_data is a StringType JSON string — must parse with from_json() to access fields',
    '✗ _rescued_data contains ONLY mismatched/extra fields — not the full row content',
    '✗ Rescue mode ALWAYS adds _rescued_data to the schema — even if no rescue ever occurs',
    '✗ cloudFiles.rescuedDataColumn option renames the column — "_rescued_data" is just the default name',
    '✗ High non-null rate in _rescued_data = upstream schema is changing faster than the stored schema',
    '✗ _rescued_data also captures type mismatches — field exists in schema but value fails type cast',
  ],
},

// ─── 2.2.7 ───────────────────────────────────────────────────────────────────
{num:'10',title:'2.2.7 — readChangeFeed Error When CDF Not Enabled on Source',
  what:[
    'readChangeFeed error: streaming read with readChangeFeed=true fails if CDF not enabled on the source table',
    'CDF (Change Data Feed) must be enabled on the source Delta table BEFORE using readChangeFeed in a stream',
    'Error message: "DELTA_TABLE_CHANGE_DATA_FEED_DISABLED" or similar CDF not enabled exception',
  ],
  how:[
    'readChangeFeed=true: streams row-level changes (insert/update/delete) from a Delta table',
    'CDF requires delta.enableChangeDataFeed = true on the source Delta table TBLPROPERTIES',
    'If CDF not enabled: the readChangeFeed stream fails immediately at the first micro-batch',
    'CDF must be enabled BEFORE changes occur — retroactive CDF history is NOT available',
  ],
  facts:[
    'CDF generates _change_type column: insert, update_preimage, update_postimage, delete',
    'update operations emit TWO rows: update_preimage (before) AND update_postimage (after)',
    'CDF history starts from the commit AFTER CDF was enabled — no retroactive change history',
    'CDF adds storage overhead — _change_data/ directory alongside regular Delta Parquet files',
  ],
  code:[
    '# Step 1: Enable CDF on the source table FIRST',
    'spark.sql("""',
    '    ALTER TABLE catalog.schema.orders',
    '    SET TBLPROPERTIES (delta.enableChangeDataFeed = true)',
    '""")',
    '',
    '# Step 2: Now readChangeFeed will work',
    'cdf_stream = (spark.readStream',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", 0)   # or startingTimestamp',
    '    .table("catalog.schema.orders"))',
    '',
    '# Step 3: Filter by change type downstream',
    'inserts       = cdf_stream.filter(col("_change_type") == "insert")',
    'deletes       = cdf_stream.filter(col("_change_type") == "delete")',
    'updates_after = cdf_stream.filter(col("_change_type") == "update_postimage")',
    '',
    '# COMMON ERROR — CDF not enabled:',
    '# readChangeFeed without TBLPROPERTIES set ->',
    '# AnalysisException: DELTA_TABLE_CHANGE_DATA_FEED_DISABLED',
  ],
  mistakes:[
    '✗ Enabling CDF after data has already been written — retroactive change history not available',
    '✗ Not filtering _change_type — processing both update_preimage and update_postimage as new inserts',
    '✗ Using readChangeFeed on a Delta table created with CTAS — CTAS-created tables do not auto-enable CDF',
  ],
  trap:[
    '✗ readChangeFeed=true on a table WITHOUT CDF enabled = stream fails immediately with an error',
    '✗ CDF must be enabled BEFORE changes — no retroactive history available after enabling',
    '✗ UPDATE emits TWO rows: update_preimage AND update_postimage — always filter by _change_type',
    '✗ startingVersion is IGNORED if a checkpoint already exists — checkpoint takes precedence',
    '✗ skipChangeCommits=true is the OPPOSITE — skips change commits instead of reading them',
    '✗ CDF adds ~20% storage overhead — _change_data/ directory holds the change records',
    '✗ readChangeFeed requires delta.enableChangeDataFeed = true in TBLPROPERTIES — not a Spark config',
  ],
},

// ─── 2.3.1 ───────────────────────────────────────────────────────────────────
{num:'11',title:'2.3.1 — All Formats: Delta, Parquet, ORC, Avro, JSON, CSV, XML, Text, Binary',
  what:[
    'Databricks supports reading and writing many file formats — each with different characteristics',
    'Format specified in spark.read.format("format_name") or shorthand spark.read.parquet()',
    'Choosing the right format impacts: read/write performance, schema evolution, compression, interoperability',
  ],
  how:[
    'Delta: Parquet + _delta_log/ — ACID, time travel, schema enforcement, best for lakehouse',
    'Parquet: columnar, compressed, typed, splittable — best for analytics, no ACID',
    'ORC: columnar like Parquet, Hive ecosystem — less common in Databricks, used in legacy Hive',
    'Avro: row-based, schema embedded in file, excellent for Kafka message serialization',
    'JSON: semi-structured, human-readable, row-based — slow for large scale, schema not enforced',
    'CSV: plain text, delimiter-separated, no types — requires schema or inference',
    'XML: hierarchical text, requires spark-xml library — not natively supported in Spark',
    'Text: reads each line as a single string — raw line-by-line processing',
    'Binary: reads entire file as a single binary row — for images, PDFs, audio files',
  ],
  facts:[
    'Delta = Parquet + transaction log — provides ACID and schema enforcement on top of Parquet',
    'Parquet/Delta/ORC are COLUMNAR — predicate pushdown and projection pruning apply',
    'JSON/CSV/Avro/Text/Binary are ROW-based — no columnar optimizations',
    'Multi-line JSON requires .option("multiLine","true") — default expects one JSON object per line',
  ],
  code:[
    '# Delta — full ACID, time travel',
    'spark.read.format("delta").load("/mnt/delta/orders/")',
    'spark.read.table("catalog.schema.orders")  # preferred',
    '',
    '# Parquet — fast columnar reads',
    'spark.read.parquet("/mnt/parquet/events/")',
    'spark.read.format("parquet").load("/mnt/parquet/events/")',
    '',
    '# Avro — common for Kafka payloads',
    'spark.read.format("avro").load("/mnt/avro/messages/")',
    '',
    '# JSON — multi-line JSON requires multiLine option',
    'spark.read.json("/mnt/json/logs/")',
    'spark.read.option("multiLine", "true").json("/mnt/json/nested/")',
    '',
    '# CSV — with explicit schema and options',
    'schema = StructType([StructField("id", IntegerType()), StructField("name", StringType())])',
    'spark.read.option("header", "true").option("sep", ",").schema(schema).csv("/mnt/csv/")',
    '',
    '# Text — each line as a string',
    'spark.read.text("/mnt/logs/app.log")  # returns DataFrame with single "value" column',
    '',
    '# Binary — each file as a single row',
    'spark.read.format("binaryFile").load("/mnt/images/")',
    '# Columns: path, modificationTime, length, content (BinaryType)',
  ],
  mistakes:[
    '✗ Reading multi-line JSON without multiLine=true — defaults to one JSON object per line (JSONL)',
    '✗ Using JSON for large-scale analytics — row-based format, no columnar pruning, slow for wide tables',
    '✗ Forgetting CSV has no embedded schema — must provide schema or use inference (with type risks)',
  ],
  trap:[
    '✗ Delta = columnar Parquet + transaction log — NOT just Parquet, has ACID and schema enforcement',
    '✗ Avro is ROW-based — schema embedded in file header, excellent for Kafka streaming messages',
    '✗ JSON is ROW-based — no predicate pushdown or projection pruning, much slower than Parquet',
    '✗ Text format reads each LINE as one row with single "value" column — not whole file as one row',
    '✗ Binary (binaryFile) reads each FILE as one row — content column is BinaryType',
    '✗ CSV header=true reads first row as column names — without it, columns are _c0, _c1, _c2...',
    '✗ XML is NOT natively supported — requires com.databricks.spark.xml or spark-xml library',
    '✗ ORC is mostly legacy Hive ecosystem — Parquet is preferred in Databricks for new workloads',
  ],
},

// ─── 2.4.1 ───────────────────────────────────────────────────────────────────
{num:'12',title:'2.4.1 — Kafka / Event Hubs: startingOffsets earliest vs latest Trap',
  what:[
    'startingOffsets: Kafka consumer option controlling WHERE in the topic to start reading',
    'Two main values: "earliest" (read from beginning) vs "latest" (only new messages)',
    'Critical behavior: startingOffsets is IGNORED when a checkpoint already exists',
  ],
  how:[
    'startingOffsets = "earliest": on first run, reads ALL messages from the beginning of the Kafka topic',
    'startingOffsets = "latest": on first run, only reads messages arriving AFTER the stream starts',
    'Once a checkpoint exists: startingOffsets is completely ignored — checkpoint offset always wins',
    'startingOffsets can also be JSON with per-partition offsets: {"topic":{"0":100,"1":200}}',
  ],
  facts:[
    'Default startingOffsets = "latest" — new streams read only new messages unless earliest specified',
    'startingOffsets affects FIRST RUN only — all subsequent runs use the checkpoint offset',
    'Kafka offset retention: messages deleted after retention period — earliest may not include very old messages',
    'Event Hubs uses the same Kafka-compatible API — same startingOffsets behavior applies',
  ],
  code:[
    '# Read from Kafka — startingOffsets only affects first run!',
    'kafka_stream = (spark.readStream',
    '    .format("kafka")',
    '    .option("kafka.bootstrap.servers", "broker1:9092,broker2:9092")',
    '    .option("subscribe", "orders_topic")',
    '    .option("startingOffsets", "earliest")  # read all history on first run',
    '    .load())',
    '',
    '# Read only new messages (default behavior)',
    'kafka_stream_new = (spark.readStream',
    '    .format("kafka")',
    '    .option("kafka.bootstrap.servers", "broker1:9092,broker2:9092")',
    '    .option("subscribe", "orders_topic")',
    '    .option("startingOffsets", "latest")  # only new messages after stream starts',
    '    .load())',
    '',
    '# Specific per-partition offset',
    'kafka_stream_offset = (spark.readStream',
    '    .format("kafka")',
    '    .option("kafka.bootstrap.servers", "broker1:9092")',
    '    .option("subscribe", "orders_topic")',
    '    .option("startingOffsets", \'{"orders_topic":{"0":1000,"1":500}}\')',
    '    .load())',
    '',
    '# IMPORTANT: if checkpoint exists, startingOffsets is IGNORED',
    '# To restart from beginning: DELETE the checkpoint directory',
  ],
  mistakes:[
    '✗ Setting startingOffsets="earliest" expecting to re-read all history on restart — checkpoint wins',
    '✗ Forgetting default is "latest" — new stream misses all historical Kafka messages silently',
    '✗ Confusing startingOffsets with endingOffsets — endingOffsets is for batch reads only',
  ],
  trap:[
    '✗ startingOffsets is IGNORED when a checkpoint already exists — checkpoint offset ALWAYS wins',
    '✗ Default startingOffsets = "latest" — without explicit setting, historical messages are MISSED',
    '✗ startingOffsets = "earliest" only applies on FIRST RUN — subsequent runs use checkpoint',
    '✗ To re-read from beginning: must DELETE the checkpoint directory and restart the stream',
    '✗ startingOffsets is a streaming option — for batch Kafka reads, use startingOffsets + endingOffsets',
    '✗ Kafka message retention: earliest does not guarantee all historical messages — only within retention',
    '✗ Event Hubs uses Kafka-compatible API — same startingOffsets behavior, "earliest" = beginning of retention',
  ],
},

// ─── 2.4.2 ───────────────────────────────────────────────────────────────────
{num:'13',title:'2.4.2 — Kafka Message Decoding (key/value as binary — cast to string)',
  what:[
    'Kafka message format: Kafka messages are always read as binary (BinaryType) by Spark',
    'Both key and value columns arrive as BinaryType — must explicitly cast to string or parse as Avro/JSON',
    'Failing to cast results in a binary column that cannot be used in downstream transformations',
  ],
  how:[
    'Kafka DataFrame schema: key (BinaryType), value (BinaryType), topic, partition, offset, timestamp',
    'Decode string message: .cast("string") on key or value column',
    'Decode JSON payload: cast to string first, then apply from_json(col("value"), schema)',
    'Decode Avro payload: use from_avro(col("value"), schema_str) from pyspark.sql.avro.functions',
  ],
  facts:[
    'value column is always BinaryType — this is the most common exam trap for Kafka questions',
    'Kafka key is also BinaryType — often contains a string partition key (e.g. customer ID)',
    'Full Kafka message metadata: key, value, topic, partition, offset, timestamp, timestampType',
    'kafkaDataFrame.selectExpr("CAST(value AS STRING)") — the standard first transformation',
  ],
  code:[
    '# Raw Kafka stream — key and value are BINARY',
    'raw_stream = (spark.readStream',
    '    .format("kafka")',
    '    .option("kafka.bootstrap.servers", "broker:9092")',
    '    .option("subscribe", "orders")',
    '    .load())',
    '',
    '# Step 1: Cast binary value to string',
    'string_stream = raw_stream.selectExpr(',
    '    "CAST(key AS STRING) AS key",',
    '    "CAST(value AS STRING) AS value",',
    '    "topic", "partition", "offset", "timestamp"',
    ')',
    '',
    '# Step 2: Parse JSON from string value',
    'order_schema = StructType([',
    '    StructField("order_id", LongType()),',
    '    StructField("amount", DoubleType()),',
    '    StructField("customer_id", StringType())',
    '])',
    '',
    'parsed_stream = string_stream.withColumn(',
    '    "order", from_json(col("value"), order_schema)',
    ').select("order.*", "timestamp", "offset")',
    '',
    '# Write to Delta',
    '(parsed_stream.writeStream',
    '    .format("delta")',
    '    .option("checkpointLocation", "/chk/kafka_orders/")',
    '    .outputMode("append")',
    '    .table("catalog.schema.orders_bronze"))',
  ],
  mistakes:[
    '✗ Using value column directly without casting — binary data causes errors in string/JSON operations',
    '✗ Applying from_json() directly on binary value column — must cast to STRING first',
    '✗ Forgetting key is also binary — if using Kafka key for joins or dedup, must cast it too',
  ],
  trap:[
    '✗ Kafka value column is BinaryType — always cast to string before any string or JSON operations',
    '✗ Kafka key column is also BinaryType — not automatically a string even if you wrote a string key',
    '✗ CAST(value AS STRING) must happen BEFORE from_json() — cannot parse JSON from binary directly',
    '✗ Full Kafka message metadata columns: key, value, topic, partition, offset, timestamp',
    '✗ offset is a LongType — the Kafka partition offset for the message, useful for deduplication',
    '✗ Avro-encoded Kafka messages: use from_avro(col("value"), schema_json) — NOT from_json()',
    '✗ Kafka message timestamp is the broker timestamp — not a business event timestamp in the payload',
  ],
},

// ─── 2.5.1 ───────────────────────────────────────────────────────────────────
{num:'14',title:'2.5.1 — CTAS is a Static Snapshot — Does Not Re-Execute on Query',
  what:[
    'CTAS (CREATE TABLE AS SELECT): creates a Delta table by executing a SELECT query once at creation',
    'The resulting table is a static snapshot — it does NOT re-run the query when the table is queried',
    'CTAS is NOT a view — querying a CTAS table reads the stored data, not re-executes the original query',
  ],
  how:[
    'CREATE TABLE new_table AS SELECT * FROM source_table: runs the SELECT once, stores result in Delta',
    'After creation: SELECT * FROM new_table reads the stored Delta files — source not consulted',
    'The new_table reflects the state of source_table at the time CTAS was run — not the current state',
    'To refresh: must re-run the CTAS (DROP + CREATE TABLE AS SELECT) or use a different approach',
  ],
  facts:[
    'CTAS executes the SELECT exactly ONCE — at table creation time only',
    'CTAS result is stored as a managed Delta table — has all Delta features (time travel, ACID, etc.)',
    'CTAS does NOT create a live connection to the source — it is a point-in-time snapshot',
    'CTAS does not auto-refresh like a Materialized View — must be manually re-executed to update',
  ],
  code:[
    '# CTAS — runs SELECT once, stores result as Delta table',
    'spark.sql("""',
    '    CREATE TABLE catalog.schema.orders_snapshot',
    '    AS SELECT * FROM catalog.schema.orders_raw',
    '    WHERE order_date >= \'2024-01-01\'',
    '""")',
    '# orders_snapshot now contains a static copy of orders from 2024 onwards',
    '# Adding new data to orders_raw does NOT update orders_snapshot',
    '',
    '# Querying CTAS table — reads stored Delta files, NOT the original query',
    'spark.sql("SELECT COUNT(*) FROM catalog.schema.orders_snapshot")',
    '# Returns count from the snapshot — NOT current orders_raw count',
    '',
    '# To refresh: must re-run explicitly (or use Materialized View instead)',
    'spark.sql("DROP TABLE IF EXISTS catalog.schema.orders_snapshot")',
    'spark.sql("""',
    '    CREATE TABLE catalog.schema.orders_snapshot',
    '    AS SELECT * FROM catalog.schema.orders_raw',
    '    WHERE order_date >= \'2024-01-01\'',
    '""")',
    '',
    '# CTAS with partitioning',
    'spark.sql("""',
    '    CREATE TABLE catalog.schema.sales_by_region',
    '    PARTITIONED BY (region)',
    '    AS SELECT region, product, SUM(amount) AS total_sales',
    '    FROM catalog.schema.sales_raw',
    '    GROUP BY region, product',
    '""")',
  ],
  mistakes:[
    '✗ Expecting CTAS table to reflect new data added to source after CTAS was run — static snapshot',
    '✗ Using CTAS when a Materialized View or regular View would be more appropriate for live data',
    '✗ Querying the CTAS table expecting the original SELECT to re-execute — it reads stored Delta files',
  ],
  trap:[
    '✗ CTAS executes the SELECT exactly ONCE — at creation time, NEVER re-executes on query',
    '✗ Querying a CTAS table reads STORED DATA — source table is NOT consulted at query time',
    '✗ New data added to source AFTER CTAS creation does NOT appear in the CTAS table',
    '✗ CTAS creates a managed Delta table — all Delta features available (time travel, ACID, optimize)',
    '✗ CTAS is not auto-refreshing — for auto-refresh use Materialized View (DLT) or scheduled re-run',
    '✗ CREATE OR REPLACE TABLE ... AS SELECT overwrites the existing table — re-runs the SELECT once',
    '✗ CTAS SELECT runs at the isolation level of the source — concurrent writes may or may not be visible',
  ],
},

// ─── 2.5.2 ───────────────────────────────────────────────────────────────────
{num:'15',title:'2.5.2 — VIEW vs CTAS vs Materialized View — Refresh Behavior Comparison',
  what:[
    'Three ways to create derived data objects — each with different execution, refresh, persistence behavior',
    'VIEW: virtual — query re-executes every time the view is queried',
    'CTAS: physical static snapshot — SELECT runs once at creation, never re-runs',
    'Materialized View (DLT): physical auto-refreshing — DLT pipeline re-runs to update when sources change',
  ],
  how:[
    'VIEW: stores only the query definition — SELECT * FROM view_name re-runs the full underlying SELECT',
    'CTAS: stores the physical data in Delta files — querying reads the stored data, source not consulted',
    'Materialized View: stored as Delta table — DLT pipeline refreshes it when pipeline runs',
    'Streaming Table (DLT): incremental append/merge — only processes new data since last pipeline run',
  ],
  facts:[
    'VIEW: no storage, full query cost each time, always reflects latest source',
    'CTAS: storage cost, no query cost on read, does NOT auto-refresh',
    'Materialized View: storage cost, reduced query cost, refreshes when DLT pipeline runs',
    'Streaming Table: storage cost, minimal processing per run, processes only new records',
  ],
  ascii:true,
  code:[
    'VIEW (virtual — always re-executes):',
    '  CREATE VIEW v AS SELECT * FROM source WHERE amt > 0',
    '  SELECT * FROM v  ->  re-runs SELECT * FROM source WHERE amt > 0',
    '  Always reflects latest source data',
    '  No storage cost, full query cost each time',
    '',
    'CTAS (static snapshot — executes once):',
    '  CREATE TABLE snap AS SELECT * FROM source WHERE amt > 0',
    '  SELECT * FROM snap  ->  reads stored Delta files',
    '  Does NOT reflect new source data automatically',
    '  Storage cost, no query cost (reads pre-computed data)',
    '',
    'MATERIALIZED VIEW (auto-refreshing via DLT):',
    '  @dlt.table  /  CREATE MATERIALIZED VIEW mv AS SELECT ...',
    '  DLT pipeline runs  ->  MV refreshed from source',
    '  Reflects source state at last pipeline run time',
    '  Storage cost, reduced query cost (pre-computed)',
    '',
    'STREAMING TABLE (incremental via DLT):',
    '  @dlt.table from readStream  /  CREATE STREAMING TABLE st',
    '  DLT pipeline runs  ->  only new records processed and appended',
    '  Best for append-only high-volume ingestion',
    '  Storage cost, minimal processing cost per run',
  ],
  mistakes:[
    '✗ Using CTAS when a Materialized View is needed — CTAS will not auto-refresh when source changes',
    '✗ Using VIEW for heavy aggregation queries — view re-runs the full aggregation on every query',
    '✗ Confusing Materialized View with CTAS — MV auto-refreshes via DLT pipeline, CTAS never does',
  ],
  trap:[
    '✗ VIEW re-executes the query on EVERY SELECT — always reflects latest source data',
    '✗ CTAS executes ONCE — never auto-refreshes, reads stored Delta snapshot',
    '✗ Materialized View auto-refreshes when DLT PIPELINE RUNS — not on every query, not real-time',
    '✗ Streaming Table processes ONLY NEW records each pipeline run — not full table refresh',
    '✗ Temp View is SESSION-scoped and re-executes like a regular VIEW — lost on session end',
    '✗ Materialized View and Streaming Table BOTH require DLT — cannot be created outside DLT pipeline',
    '✗ CTAS creates a managed Delta table with full ACID — not just a file dump, has all Delta features',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain2_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
