'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 6  —  Cost and Performance Optimization  —  20 Sub-Topics',
  groups: [
    ['6.1  Delta Optimization Techniques',[
      ['01','6.1.1','OPTIMIZE vs OPTIMIZE FULL (Incremental vs All Files)'],
      ['02','6.1.2','ZORDER BY — Within-File Co-Location'],
      ['03','6.1.3','Liquid Clustering — Full Decision Framework'],
      ['04','6.1.4','Liquid Clustering vs Partitioning vs ZORDER — When to Use Each'],
      ['05','6.1.5','Deletion Vectors — Enabling, Bitmap Mechanics, VACUUM Behavior'],
    ]],
    ['6.2  Data Skipping, File Pruning, and Bloom Filters',[
      ['06','6.2.1','Min/Max Statistics — How File Pruning Works (First 32 Columns)'],
      ['07','6.2.2','Bloom Filter Indexes — High-Cardinality Equality Filters, fpp Parameter'],
    ]],
    ['6.3  Query Performance Tuning',[
      ['08','6.3.1','AQE Configuration (All Key Settings)'],
      ['09','6.3.2','Key Spark Config: shuffle.partitions, maxPartitionBytes, autoBroadcastJoinThreshold'],
      ['10','6.3.3','Data Skew Salting Technique (Full Code Walkthrough)'],
      ['11','6.3.4','Spill Detection (Spark UI + Ganglia) and Fixes'],
      ['12','6.3.5','Query Profile Bottleneck Identification'],
    ]],
    ['6.4  CDF for Performance and Predictive Optimization',[
      ['13','6.4.1','CDF for Incremental Processing (Not Just CDC Use Case)'],
      ['14','6.4.2','UC Managed Tables + Predictive Optimization = Zero-Maintenance'],
    ]],
    ['6.5  Compute Optimization',[
      ['15','6.5.1','Cluster Sizing for Shuffle-Heavy Workloads (8 VMs x 50GB)'],
      ['16','6.5.2','SQL Warehouse: Scale Up (Single Query) vs Scale Out (Concurrency)'],
      ['17','6.5.3','Serverless SQL Warehouse Trade-offs'],
      ['18','6.5.4','Caching: df.cache(), CACHE TABLE, Invalidation Behavior'],
      ['19','6.5.5','Photon Engine — Vectorized Execution'],
      ['20','6.5.6','Auto-Termination and Spot/Preemptible Instances'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 6  —  Cost and Performance Optimization  —  All High-Priority Traps',
};

const pages = [

// ─── 6.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'6.1.1 — OPTIMIZE vs OPTIMIZE FULL (Incremental vs All Files)',
  what:[
    'OPTIMIZE: compacts small Parquet files into larger files — incremental, only processes new files',
    'OPTIMIZE FULL: rewrites ALL files regardless of whether they were previously optimized',
    'Both update the Delta transaction log and improve query performance via fewer, larger files',
  ],
  how:[
    'OPTIMIZE: Delta tracks which files have been optimized — skips already-optimized large files',
    'OPTIMIZE FULL: ignores optimization history — rewrites every Parquet file regardless of size',
    'Target file size: 1GB per file — files approaching/exceeding 1GB are skipped by regular OPTIMIZE',
    'OPTIMIZE runs as a Spark job — reads small files, writes fewer larger files, updates _delta_log',
  ],
  facts:[
    'OPTIMIZE is idempotent — running on unchanged data produces no changes, safe to re-run',
    'OPTIMIZE FULL needed after: changing Liquid Clustering columns, major schema changes',
    'Regular OPTIMIZE target: 1GB per output file — configurable via delta.targetFileSize',
    'Auto-optimize: delta.autoOptimize.optimizeWrite = true — Databricks optimizes file sizes on write',
  ],
  code:[
    '-- Standard incremental optimize (skips already-optimized files)',
    'OPTIMIZE catalog.schema.orders;',
    '',
    '-- Partition-filtered optimize (efficient for partitioned tables)',
    'OPTIMIZE catalog.schema.orders',
    'WHERE order_date >= \'2024-01-01\';',
    '',
    '-- OPTIMIZE FULL: rewrite ALL files (use after changing clustering columns)',
    'OPTIMIZE catalog.schema.orders FULL;',
    '',
    '-- With ZORDER (optimize + cluster by columns simultaneously)',
    'OPTIMIZE catalog.schema.orders',
    'ZORDER BY (customer_id, order_date);',
    '',
    '-- Enable auto-optimize on write',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (',
    '    \'delta.autoOptimize.optimizeWrite\' = \'true\',',
    '    \'delta.autoOptimize.autoCompact\' = \'true\'',
    ');',
  ],
  mistakes:[
    '✗ Using OPTIMIZE FULL for routine maintenance — unnecessary file rewrites, expensive',
    '✗ Not running OPTIMIZE after large data loads — small file accumulation degrades reads',
    '✗ Running OPTIMIZE without partition filter on large partitioned tables — wastes compute',
  ],
  trap:[
    '✗ OPTIMIZE is INCREMENTAL — skips files already at target size, only compacts new small files',
    '✗ OPTIMIZE FULL rewrites ALL files — use ONLY after changing Liquid Clustering or major restructuring',
    '✗ OPTIMIZE is IDEMPOTENT — running on unchanged table does nothing, safe to re-run',
    '✗ Target file size default = 1GB — files >= 1GB not rewritten by regular OPTIMIZE',
    '✗ OPTIMIZE FULL needed after ALTER TABLE ... CLUSTER BY (new_cols) — re-clusters all data',
    '✗ Partition-filtered OPTIMIZE: optimizes only that partition, much faster',
    '✗ Auto-optimize on write reduces need for manual OPTIMIZE — but does not replace scheduled OPTIMIZE',
  ],
},

// ─── 6.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'6.1.2 — ZORDER BY — Within-File Co-Location',
  what:[
    'ZORDER BY: clusters data WITHIN Parquet files to co-locate related values — improves file skipping',
    'Uses a Z-order (Morton) space-filling curve to interleave bits of multiple column values',
    'Benefit: queries filtering on ZORDER columns skip more files — fewer files read, faster queries',
  ],
  how:[
    'ZORDER rewrites files so rows with similar values on ZORDER columns are stored near each other',
    'Delta file statistics (min/max per file) become tighter after ZORDER — better file pruning',
    'ZORDER is applied during OPTIMIZE — cannot be applied separately from file compaction',
    'ZORDER column statistics written to _delta_log add actions — used by Spark for file skipping',
  ],
  facts:[
    'ZORDER max effective columns: ~4 — effectiveness degrades rapidly beyond 4 columns',
    'ZORDER on partition column = zero benefit — partition already co-locates that data',
    'ZORDER is incompatible with Liquid Clustering — cannot use both on same table',
    'ZORDER must be re-run after new data arrives — new files not automatically Z-ordered',
  ],
  code:[
    '-- ZORDER on most commonly filtered columns',
    'OPTIMIZE catalog.schema.events',
    'ZORDER BY (user_id, event_date);',
    '',
    '-- ZORDER with partition filter',
    'OPTIMIZE catalog.schema.events',
    'WHERE event_date >= \'2024-01-01\'',
    'ZORDER BY (user_id, session_id);',
    '',
    '-- Check if ZORDER helped — query with filter',
    'EXPLAIN SELECT * FROM catalog.schema.events',
    'WHERE user_id = 12345 AND event_date = \'2024-01-15\';',
    '-- Look for: PartitionFilters and DataFilters in scan node',
    '-- PartitionFilters: partition pruning (from PARTITIONED BY)',
    '-- DataFilters: file skipping (from ZORDER stats)',
  ],
  mistakes:[
    '✗ ZORDER-ing the partition column — zero additional benefit',
    '✗ Using more than 4 ZORDER columns — effectiveness degrades, file stats less useful',
    '✗ Expecting ZORDER to persist for new data — new files NOT Z-ordered until OPTIMIZE',
  ],
  trap:[
    '✗ ZORDER on partition column = ZERO additional benefit — partition already co-locates',
    '✗ ZORDER max ~4 effective columns — more columns = diminishing file skipping effectiveness',
    '✗ ZORDER is INCOMPATIBLE with Liquid Clustering — competing approaches',
    '✗ New data written after OPTIMIZE is NOT Z-ordered — must re-run OPTIMIZE ZORDER regularly',
    '✗ ZORDER improves DATA SKIPPING via file min/max stats — not a sort order visible to queries',
    '✗ Bloom filters and ZORDER are complementary — ZORDER for range, Bloom for equality',
  ],
},

// ─── 6.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'6.1.3 — Liquid Clustering — Full Decision Framework',
  what:[
    'Liquid Clustering: modern, adaptive replacement for static partitioning and ZORDER',
    'CLUSTER BY (col1, col2): defines clustering columns — incremental, dynamic, changeable',
    'Addresses key limitations of static partitioning: skew, fixed keys, full OPTIMIZE needed',
  ],
  how:[
    'Data co-located within Parquet files using Hilbert space-filling curve',
    'Each OPTIMIZE incrementally clusters only newly written/modified data — not full table rewrite',
    'Clustering columns can be changed at any time with ALTER TABLE ... CLUSTER BY (new_cols)',
    'After changing clustering columns: OPTIMIZE FULL re-clusters all existing data',
  ],
  facts:[
    'Max 4 clustering columns — hard limit, enforced at CREATE TABLE and ALTER TABLE',
    'INCOMPATIBLE with PARTITIONED BY — cannot use both, error at creation',
    'INCOMPATIBLE with ZORDER BY in OPTIMIZE — competing clustering strategies',
    'Clustering columns CAN be changed — unlike partition columns which are immutable',
    'OPTIMIZE FULL needed after changing clustering columns',
  ],
  ascii:true,
  code:[
    'DECISION FRAMEWORK:',
    '',
    'Use Liquid Clustering when:',
    '  Multiple high-cardinality filter columns (user_id, session_id, product_id)',
    '  Filter columns not known upfront or change over time',
    '  Want to avoid partition skew (hot partitions)',
    '  Table is auto-optimized with Predictive Optimization (UC managed)',
    '  Mixed query patterns — different queries filter on different columns',
    '',
    'Use Static Partitioning when:',
    '  Single low-cardinality partition column (e.g. date, region, country)',
    '  Always filter by partition column in every query',
    '  Need partition pruning for streaming micro-batches',
    '  Table > 1TB AND queries always filter on same column',
    '',
    'Use ZORDER when:',
    '  Static partitioning already in place but need sub-partition clustering',
    '  Cannot use Liquid Clustering (existing table with partitioning)',
    '',
    '-- Create with Liquid Clustering',
    'CREATE TABLE catalog.schema.events',
    'CLUSTER BY (user_id, event_date)',
    'AS SELECT * FROM source_events;',
    '',
    '-- Change clustering columns',
    'ALTER TABLE catalog.schema.events',
    'CLUSTER BY (user_id, event_type);',
    '',
    '-- Full re-cluster after column change',
    'OPTIMIZE catalog.schema.events FULL;',
  ],
  trap:[
    '✗ Liquid Clustering max 4 columns — hard limit, not a recommendation',
    '✗ INCOMPATIBLE with PARTITIONED BY — mutually exclusive at table creation',
    '✗ INCOMPATIBLE with ZORDER BY in OPTIMIZE — cannot combine',
    '✗ Clustering columns CAN be changed — partition columns CANNOT',
    '✗ OPTIMIZE FULL required after changing clustering columns',
    '✗ CLUSTER BY NONE removes clustering — table reverts to unclustered Parquet',
    '✗ Liquid Clustering is INCREMENTAL — only new/changed data clustered on each OPTIMIZE',
  ],
},

// ─── 6.1.4 ───────────────────────────────────────────────────────────────────
{num:'04',title:'6.1.4 — Liquid Clustering vs Partitioning vs ZORDER — When to Use Each',
  what:[
    'Three data layout strategies for optimizing Delta table query performance',
    'Choosing wrong strategy can degrade performance significantly',
    'Strategies can be combined: Partitioning + ZORDER (compatible); Liquid Clustering alone',
  ],
  facts:[
    'Partitioning + ZORDER is COMPATIBLE — ZORDER within partitions is valid combination',
    'Liquid Clustering + Partitioning is INCOMPATIBLE — mutually exclusive',
    'Liquid Clustering + ZORDER is INCOMPATIBLE — competing strategies',
    'Static partition keys are IMMUTABLE — cannot change after table creation',
    'Liquid Clustering keys ARE changeable — key advantage over static partitioning',
    'Partition skew: hot partition = too many rows = slow queries; Liquid Clustering has no skew risk',
  ],
  ascii:true,
  code:[
    'COMPARISON:',
    '',
    '                    | Static Partitioning | ZORDER BY     | Liquid Clustering',
    'Granularity         | Directory-level     | Within-file   | Within-file',
    'Cardinality         | Low (<10K)          | High          | High',
    'Keys changeable?    | No (immutable)      | Yes (re-OPT)  | Yes (ALTER)',
    'Skew risk           | High (hot dirs)     | No            | No',
    'Incremental?        | per write           | No (full OPT) | Yes',
    'Partition compat    | + ZORDER OK         | OK with part. | NO partition',
    'Max columns         | 1-4 practical       | ~4 effective  | 4 (hard limit)',
    'Best for            | Date/region filters | Sub-partition | Multi-column adaptive',
    '',
    'QUERY: SELECT * FROM orders WHERE customer_id = 123 AND order_date = \'2024-01-15\'',
    '',
    'WITH STATIC PARTITIONING (PARTITIONED BY order_date):',
    '  Prunes to date=2024-01-15 directory (fast)',
    '  Scans ALL files in that partition for customer_id (potentially slow)',
    '',
    'WITH ZORDER BY (customer_id, order_date):',
    '  No partition pruning (not partitioned)',
    '  File skipping via min/max stats — works for high-cardinality multi-col',
    '',
    'WITH LIQUID CLUSTERING (customer_id, order_date):',
    '  File skipping via Hilbert curve clustering',
    '  Works incrementally — only new data needs re-clustering',
    '',
    'PARTITION BY (order_date) + ZORDER BY (customer_id):',
    '  Partition pruning on order_date (directory level)',
    '  File skipping on customer_id within the partition',
  ],
  trap:[
    '✗ Partitioning + ZORDER is COMPATIBLE — ZORDER within partitions is valid',
    '✗ Liquid Clustering + Partitioning is INCOMPATIBLE — mutually exclusive',
    '✗ Liquid Clustering + ZORDER is INCOMPATIBLE — competing strategies',
    '✗ Static partition keys are IMMUTABLE; Liquid Clustering keys ARE changeable',
    '✗ Partition skew: hot partition = slow queries; Liquid Clustering has no skew risk',
    '✗ ZORDER must be re-run after each new data load; Liquid Clustering is incremental',
  ],
},

// ─── 6.1.5 ───────────────────────────────────────────────────────────────────
{num:'05',title:'6.1.5 — Deletion Vectors — Enabling, Bitmap Mechanics, VACUUM Behavior',
  what:[
    'Deletion vectors: bitmaps that mark deleted rows in Parquet files — avoid full file rewrites',
    'Dramatically reduce DELETE/UPDATE/MERGE latency for large tables',
    'Enabled per table via delta.enableDeletionVectors = true',
  ],
  how:[
    'Traditional DELETE: reads affected Parquet file, rewrites without deleted rows — O(file size)',
    'With deletion vectors: writes a small .bin bitmap marking deleted row positions — O(deleted rows)',
    'On read: Spark reads Parquet + deletion vector bitmap, filters out marked rows transparently',
    'OPTIMIZE consolidates deletion vectors by rewriting Parquet files — cleans up bitmaps',
  ],
  facts:[
    'Deletion vector files stored in _delta_log/deletion_vector/ — cleaned up by VACUUM',
    'VACUUM: deletion vector files follow same retention rules as regular Parquet files',
    'OPTIMIZE after deletion vectors: rewrites files incorporating deletion vectors — reduces overhead',
    'For GDPR: deletion vectors still require OPTIMIZE + VACUUM to physically remove data',
  ],
  ascii:true,
  code:[
    'WITHOUT Deletion Vectors:',
    'DELETE FROM large_table WHERE id = 42;',
    '  Read part-00001.parquet (100M rows, 10GB)',
    '  Write part-00002.parquet (99,999,999 rows, ~10GB)',
    '  Cost: O(file size) — rewrites entire 10GB file!',
    '',
    'WITH Deletion Vectors (enabled):',
    'DELETE FROM large_table WHERE id = 42;',
    '  Write dv-xxx.bin: tiny bitmap marking row position 42',
    '  part-00001.parquet: UNCHANGED',
    '  Cost: O(deleted rows) — only small bitmap written',
    '',
    'READ with deletion vector:',
    '  Read part-00001.parquet AND dv-xxx.bin',
    '  Filter out row at bitmap position 42',
    '  Returns 99,999,999 rows correctly',
    '',
    'VACUUM/GDPR cleanup:',
    '  Run OPTIMIZE (rewrites file without row 42)',
    '  Run VACUUM (deletes original part-00001.parquet)',
    '  Row 42 now physically removed from storage',
    '',
    '-- Enable deletion vectors',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (\'delta.enableDeletionVectors\' = \'true\');',
  ],
  trap:[
    '✗ Deletion vectors avoid FILE REWRITE at delete time — small bitmap written instead',
    '✗ Deleted rows still PHYSICALLY EXIST in Parquet — just marked in bitmap, ignored on read',
    '✗ GDPR: need OPTIMIZE + VACUUM after deletion to physically remove data from storage',
    '✗ VACUUM cleans deletion vector .bin files — same 7-day default retention applies',
    '✗ delta.enableDeletionVectors = true must be set explicitly — not enabled by default',
    '✗ Deletion vectors are transparent to readers — applications see correct results',
  ],
},

// ─── 6.2.1 ───────────────────────────────────────────────────────────────────
{num:'06',title:'6.2.1 — Min/Max Statistics — How File Pruning Works (First 32 Columns)',
  what:[
    'File-level statistics: Delta stores min/max values per column per Parquet file in transaction log',
    'Used for data skipping (file pruning): if query filter cannot match any row in file, skip it',
    'Dramatically reduces I/O for selective queries — reads only files that COULD contain matches',
  ],
  how:[
    'On write: Delta computes min/max (and null count) for each column in each Parquet file',
    'Statistics stored in _delta_log add action JSON — stats field with minValues, maxValues, nullCount',
    'On query with filter: Spark compares filter value against each file min/max — skips no-match files',
    'Example: WHERE event_date = \'2024-01-15\' — files with min > or max < that date are skipped',
  ],
  facts:[
    'Statistics collected for first 32 columns by default — columns beyond 32 have no stats',
    'delta.dataSkippingNumIndexedCols: change number of columns with stats (default 32)',
    'Statistics stored as STRINGS for string columns — lexicographic comparison',
    'ZORDER and Liquid Clustering improve min/max stats by co-locating values — tighter ranges',
  ],
  ascii:true,
  code:[
    'TABLE: orders, 100 files, order_date 2020-01-01 to 2024-12-31',
    '',
    'QUERY: SELECT * FROM orders WHERE order_date = \'2024-06-15\'',
    '',
    'File pruning with min/max stats:',
    '  File 1: min=2020-01-01, max=2021-12-31 -> SKIP (max < 2024-06-15)',
    '  File 2: min=2022-01-01, max=2022-12-31 -> SKIP',
    '  File 3: min=2023-01-01, max=2023-12-31 -> SKIP',
    '  File 4: min=2024-01-01, max=2024-06-30 -> READ (could contain match)',
    '  File 5: min=2024-07-01, max=2024-12-31 -> SKIP (min > 2024-06-15)',
    '',
    'Result: Only 1 file read out of 100 — 99% data skipping!',
    '',
    'WITHOUT ZORDER (random data layout):',
    '  All files: min=2020-01-01, max=2024-12-31 (wide range each)',
    '  Result: 0% data skipping — must read all files',
    '',
    'INCREASE indexed columns:',
    'ALTER TABLE orders SET TBLPROPERTIES (',
    '    \'delta.dataSkippingNumIndexedCols\' = \'64\'',
    ');',
  ],
  trap:[
    '✗ Stats collected for first 32 columns by default — columns beyond 32 have NO stats',
    '✗ delta.dataSkippingNumIndexedCols increases the indexed column count — default 32',
    '✗ File skipping works on RANGE queries (>, <, BETWEEN) — very effective for date/numeric',
    '✗ File skipping on string columns uses lexicographic comparison — WHERE name > \'M\' works',
    '✗ Without ZORDER/Liquid Clustering: wide min/max ranges per file = poor data skipping',
    '✗ ZORDER improves skipping by narrowing per-file min/max ranges',
  ],
},

// ─── 6.2.2 ───────────────────────────────────────────────────────────────────
{num:'07',title:'6.2.2 — Bloom Filter Indexes — High-Cardinality Equality Filters, fpp Parameter',
  what:[
    'Bloom filter: probabilistic data structure that answers "is value possibly in this file?"',
    'Dramatically reduces files read for equality predicates on high-cardinality columns',
    'Built during OPTIMIZE — NOT available before OPTIMIZE runs on the table',
  ],
  how:[
    'Bloom filter stores a compact bit array per file — set bits based on hashed values',
    'Query filter: WHERE user_id = 12345 — Spark checks bloom filter for each file before reading',
    'Bloom filter says "definitely NOT in this file" — file SKIPPED; "possibly" — file READ',
    'False positives possible: bloom filter may say "possibly" when value not actually in file',
    'False negatives impossible: if value IS in the file, bloom filter always says "possibly"',
  ],
  facts:[
    'fpp (false positive probability): default 0.1 (10%) — lower fpp = larger bloom filter, fewer false positives',
    'Bloom filters built during OPTIMIZE — querying before OPTIMIZE = no bloom filter benefit',
    'Best for: high-cardinality equality filters — WHERE user_id = 12345, WHERE email = X',
    'NOT effective for: range queries (>, <, BETWEEN) — use min/max stats for those',
  ],
  code:[
    '-- Enable bloom filter on high-cardinality columns',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (',
    '    \'delta.bloomFilter.user_id.enabled\' = \'true\',',
    '    \'delta.bloomFilter.user_id.fpp\' = \'0.01\',         -- 1% false positive rate',
    '    \'delta.bloomFilter.user_id.numItems\' = \'10000000\'  -- expected distinct values',
    ');',
    '',
    '-- Bloom filter only built when OPTIMIZE runs',
    'OPTIMIZE catalog.schema.orders;  -- bloom filters built here',
    '',
    '-- Now equality queries benefit',
    'SELECT * FROM catalog.schema.orders WHERE user_id = 12345;',
    '-- Spark checks bloom filter per file: skips files where 12345 is "definitely not"',
  ],
  trap:[
    '✗ Bloom filters require OPTIMIZE to build — querying before OPTIMIZE = full scan',
    '✗ Bloom filters work for EQUALITY only — = and IN; NOT for range filters',
    '✗ fpp default = 0.1 (10% false positive rate) — lower fpp means larger index',
    '✗ False positives POSSIBLE — bloom filter may read a file that does not contain the value',
    '✗ False negatives IMPOSSIBLE — if value is in file, bloom filter always says "possibly"',
    '✗ Min/max stats handle range queries; Bloom filters handle high-cardinality equality',
    '✗ Bloom filter files stored in _delta_log/ — cleaned up by VACUUM',
  ],
},

// ─── 6.3.1 ───────────────────────────────────────────────────────────────────
{num:'08',title:'6.3.1 — AQE Configuration (All Key Settings)',
  what:[
    'AQE (Adaptive Query Execution): runtime re-optimization using actual shuffle statistics',
    'Three features: partition coalescing, skew join splitting, dynamic broadcast switching',
    'All key AQE settings — knowing which config controls which behavior is exam-critical',
  ],
  facts:[
    'spark.sql.adaptive.enabled: default true — master switch for AQE',
    'spark.sql.adaptive.advisoryPartitionSizeInBytes: default 64MB — target after coalescing',
    'spark.sql.adaptive.coalescePartitions.enabled: default true',
    'spark.sql.adaptive.skewJoin.enabled: default true',
    'spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes: default 256MB',
    'spark.sql.adaptive.skewJoin.skewedPartitionFactor: default 5 (must be >5x median)',
    'spark.sql.autoBroadcastJoinThreshold: default 10MB (plan time, separate from AQE runtime ~30MB)',
  ],
  code:[
    '# Verify AQE is enabled',
    'spark.conf.get("spark.sql.adaptive.enabled")  # "true" in Spark 3.0+',
    '',
    '# Tune coalesce target (larger = fewer tasks after shuffle)',
    'spark.conf.set("spark.sql.adaptive.advisoryPartitionSizeInBytes", "128mb")',
    '',
    '# Tune skew detection (lower threshold = more aggressive splitting)',
    'spark.conf.set(',
    '    "spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes", "128mb")',
    '',
    '# Disable AQE for testing (not recommended in production)',
    'spark.conf.set("spark.sql.adaptive.enabled", "false")',
    '',
    '# AQE does NOT change autoBroadcastJoinThreshold',
    'spark.conf.get("spark.sql.autoBroadcastJoinThreshold")   # 10MB — plan time',
    '# AQE runtime broadcast = separate internal threshold ~30MB',
  ],
  trap:[
    '✗ AQE is ON by default since Spark 3.0',
    '✗ AQE fires AFTER each shuffle stage — NOT at planning time',
    '✗ AQE broadcast threshold (~30MB runtime) != autoBroadcastJoinThreshold (10MB plan time)',
    '✗ AQE skew: BOTH >256MB AND >5x median required — both conditions',
    '✗ Disabling AQE in production loses all runtime optimizations',
    '✗ advisoryPartitionSizeInBytes is the TARGET after coalescing — actual may vary',
  ],
},

// ─── 6.3.2 ───────────────────────────────────────────────────────────────────
{num:'09',title:'6.3.2 — Key Spark Config: shuffle.partitions, maxPartitionBytes, autoBroadcastJoinThreshold',
  what:[
    'Four critical Spark configuration settings impacting query performance and resource usage',
    'Understanding their purpose, defaults, and interactions is essential for performance tuning',
  ],
  facts:[
    'spark.sql.shuffle.partitions: default 200 — output partition count after every shuffle',
    'spark.sql.files.maxPartitionBytes: default 128MB — max bytes per partition reading files',
    'spark.sql.adaptive.advisoryPartitionSizeInBytes: default 64MB — target for AQE coalesced',
    'spark.sql.autoBroadcastJoinThreshold: default 10MB — max table size for auto-broadcast',
  ],
  code:[
    '# Tune for large dataset (TB scale) — more shuffle partitions',
    'spark.conf.set("spark.sql.shuffle.partitions", "2000")',
    '',
    '# Tune for small dataset — fewer shuffle partitions',
    'spark.conf.set("spark.sql.shuffle.partitions", "50")',
    '',
    '# Read partitions: larger input partitions (fewer tasks on read)',
    'spark.conf.set("spark.sql.files.maxPartitionBytes", str(256 * 1024 * 1024))',
    '',
    '# AQE coalesce target: larger = fewer tasks after shuffle',
    'spark.conf.set("spark.sql.adaptive.advisoryPartitionSizeInBytes", "128mb")',
    '',
    '# Increase broadcast threshold (broadcast more tables)',
    'spark.conf.set("spark.sql.autoBroadcastJoinThreshold", str(50 * 1024 * 1024))',
    '',
    '# Disable auto-broadcast (force sort-merge always)',
    'spark.conf.set("spark.sql.autoBroadcastJoinThreshold", "-1")',
  ],
  trap:[
    '✗ shuffle.partitions default = 200 — too many for small data, too few for TB-scale',
    '✗ shuffle.partitions applies to SQL/DataFrame shuffles ONLY — not RDD operations',
    '✗ maxPartitionBytes controls READ partition size; shuffle.partitions controls SHUFFLE output',
    '✗ autoBroadcastJoinThreshold measured at PLAN TIME (10MB); AQE can broadcast larger at runtime',
    '✗ Setting autoBroadcastJoinThreshold = -1 disables ALL automatic broadcasts',
    '✗ advisoryPartitionSizeInBytes is AQE target for coalesced partitions',
    '✗ These configs interact: shuffle.partitions sets initial count, AQE may coalesce',
  ],
},

// ─── 6.3.3 ───────────────────────────────────────────────────────────────────
{num:'10',title:'6.3.3 — Data Skew Salting Technique (Full Code Walkthrough)',
  what:[
    'Salting: technique to distribute skewed join keys by appending a random suffix',
    'Solves problem of hot keys (NULL, common IDs) concentrating in one partition',
    'Requires modifying BOTH sides: large side gets random salt, small side gets N copies',
  ],
  how:[
    'Large side: append random integer (0 to N-1) to join key — key_0, key_1, ... key_N',
    'Small side: explode N copies of each row — one per salt value',
    'Join on salted key — data distributed evenly across N partitions',
    'After join: drop the salt column — final output has original join key',
  ],
  facts:[
    'Salt factor N: typically 10-50 — higher N = better distribution, NX larger small side',
    'AQE handles mild skew automatically — salting needed for extreme skew beyond AQE',
    'AQE skew threshold: partition >256MB AND >5x median — if below, AQE ignores',
    'NULL keys always form their own skewed partition — filter NULLs before join',
  ],
  code:[
    'SALT_FACTOR = 10',
    '',
    '# Step 1: Salt the LARGE (skewed) side — random suffix 0 to N-1',
    'large_salted = large_df.withColumn(',
    '    "salted_key",',
    '    concat(',
    '        col("join_key").cast("string"),',
    '        lit("_"),',
    '        floor(rand() * SALT_FACTOR).cast("string")',
    '    )',
    ')',
    '',
    '# Step 2: Explode N copies of SMALL side — one per salt value',
    'small_exploded = (small_df',
    '    .withColumn("salt_array", array([lit(i) for i in range(SALT_FACTOR)]))',
    '    .withColumn("salt", explode(col("salt_array")))',
    '    .withColumn(',
    '        "salted_key",',
    '        concat(col("join_key").cast("string"), lit("_"), col("salt").cast("string"))',
    '    )',
    '    .drop("salt_array", "salt")',
    ')',
    '',
    '# Step 3: Join on salted key',
    'result = large_salted.join(small_exploded, "salted_key", "inner")',
    '',
    '# Step 4: Drop salt column — restore clean output',
    'result_clean = result.drop("salted_key")',
  ],
  mistakes:[
    '✗ Salting large side without exploding small side — join misses rows',
    '✗ Using salting when AQE would handle it automatically',
    '✗ Not dropping the salted key column after join — schema mismatch downstream',
  ],
  trap:[
    '✗ Salting changes join key — small side MUST have N copies or rows MISSED',
    '✗ Salt factor N: small side grows NX in size — balance distribution vs memory',
    '✗ AQE handles mild skew automatically — only use salting for EXTREME skew',
    '✗ AQE skew: >256MB AND >5x median — salting needed when below thresholds',
    '✗ After salting: ALWAYS drop the salt column',
    '✗ NULL join keys form their own skewed partition — filter BEFORE join',
  ],
},

// ─── 6.3.4 ───────────────────────────────────────────────────────────────────
{num:'11',title:'6.3.4 — Spill Detection (Spark UI + Ganglia) and Fixes',
  what:[
    'Spill: when shuffle/aggregation data exceeds executor memory — overflow written to local disk',
    'Spill degrades performance but prevents OOM — job completes but slower',
    'Detect via Spark UI Stages tab or Ganglia cluster metrics',
  ],
  how:[
    'Shuffle spill: during sort/hash aggregation when partition data exceeds executor memory',
    'Spill (Memory): uncompressed bytes before serialization — always larger than Spill (Disk)',
    'Spill (Disk): compressed bytes written to local executor disk',
    'Three fixes: more shuffle partitions, more executor memory, broadcast join',
  ],
  facts:[
    'Spill (Memory) always > Spill (Disk) — memory pre-compression, disk post-compression',
    'Spark UI -> Stages tab -> columns: Shuffle Spill (Memory) and Shuffle Spill (Disk)',
    'Ganglia: high disk I/O + high memory utilization — spill indicator',
    'Spill does NOT fail the job — completes with degraded performance',
  ],
  ascii:true,
  code:[
    'DETECT SPILL:',
    '',
    'Spark UI -> Jobs -> Stages tab:',
    '  Stage 3: filter/select    Spill(Mem): 0.0 B    Spill(Disk): 0.0 B',
    '  Stage 4: groupBy/agg      Spill(Mem): 45.2 GB  Spill(Disk): 8.1 GB <- PROBLEM',
    '',
    'Ganglia -> Cluster Metrics:',
    '  Memory: near 100% utilization',
    '  Disk I/O: high write spikes',
    '',
    'THREE FIXES (in order of preference):',
    '',
    'Fix 1: More shuffle partitions (less data per task)',
    '  spark.conf.set("spark.sql.shuffle.partitions", "800")',
    '  Each task processes smaller partition — less memory needed',
    '',
    'Fix 2: Broadcast join (eliminate shuffle entirely)',
    '  large.join(broadcast(small), "key")',
    '  No shuffle = no spill risk',
    '',
    'Fix 3: More executor memory (scale up cluster)',
    '  spark.executor.memory: "16g"',
    '  spark.executor.memoryOverhead: "2g"',
  ],
  trap:[
    '✗ Spill (Memory) ALWAYS > Spill (Disk) — memory is uncompressed, disk is compressed',
    '✗ Spill does NOT cause job FAILURE — degrades performance but completes',
    '✗ Spark UI -> Stages tab shows spill metrics — NOT Jobs tab or Executors tab',
    '✗ Fix order: more partitions (cheapest) -> broadcast join -> more memory',
    '✗ Ganglia: high disk I/O + high memory = spill indicator — verify in Stages',
    '✗ Increasing executor memory without memoryOverhead can cause container OOM',
  ],
},

// ─── 6.3.5 ───────────────────────────────────────────────────────────────────
{num:'12',title:'6.3.5 — Query Profile Bottleneck Identification',
  what:[
    'Query Profile: visual execution plan in Databricks SQL UI — shows time per operator',
    'Used to identify bottlenecks: slow scans, expensive joins, missing file skipping',
    'Available in DBSQL Query History and Spark UI SQL/DataFrame tab',
  ],
  how:[
    'Query Profile shows DAG of physical operators with timing and row counts per node',
    'Wide nodes (slow operators) appear visually larger — immediately visible bottlenecks',
    'Key metrics per node: duration (ms), rows output, bytes read, files scanned/skipped',
  ],
  ascii:true,
  code:[
    'KEY INDICATORS TO LOOK FOR:',
    '',
    'Observation                   | Cause                  | Fix',
    'Large scan, few files skipped | No ZORDER/Bloom        | Run OPTIMIZE ZORDER',
    'BroadcastExchange large table | Wrong side broadcast   | Disable auto-broadcast',
    'SortMergeJoin (no broadcast)  | Table too large        | Add Bloom filter',
    'High shuffle bytes            | Skew or many partitions| Tune shuffle.partitions',
    'Exchange on every join        | No co-partitioning     | Repartition before join',
    'Slow aggregate                | Skewed groupBy keys    | Salt keys',
    '',
    'QUERY PROFILE WORKFLOW:',
    '',
    '1. Run query in DBSQL or notebook',
    '2. Click "Query Profile" or view Spark UI SQL tab',
    '3. Identify wide/slow nodes:',
    '',
    '   [FileScan] -> 500GB read, 0 files skipped  <- PROBLEM: no skipping',
    '        |',
    '   [Filter]  -> 499GB filtered out             <- Filter after scan = wasteful',
    '        |',
    '   [Exchange] (shuffle 200 partitions)         <- Large shuffle',
    '        |',
    '   [SortMergeJoin] -> slow                     <- Could broadcast?',
    '',
    'FIXES:',
    '   FileScan: run OPTIMIZE ZORDER on filter columns',
    '   SortMergeJoin: if one side < 30MB -> broadcast hint',
    '   Exchange: AQE coalesces after shuffle — tune advisoryPartitionSizeInBytes',
  ],
  trap:[
    '✗ Query Profile shows TIME per node — widest/slowest is the bottleneck',
    '✗ FileScan with 0 files skipped = no ZORDER, no Liquid Clustering, no Bloom filter',
    '✗ SortMergeJoin vs BroadcastHashJoin — Broadcast almost always faster for small tables',
    '✗ Large Exchange (shuffle) node = high shuffle.partitions or skew',
    '✗ BroadcastExchange on the LARGE table = wrong side broadcast — OOM risk',
    '✗ Query Profile available in DBSQL Query History — not just Spark UI',
  ],
},

// ─── 6.4.1 ───────────────────────────────────────────────────────────────────
{num:'13',title:'6.4.1 — CDF for Incremental Processing (Not Just CDC Use Case)',
  what:[
    'CDF widely associated with CDC but valuable for incremental pipeline performance',
    'Read ONLY changed rows since last pipeline run via CDF version tracking',
    'More reliable than timestamp-based incremental — no race conditions at boundaries',
  ],
  how:[
    'Store last processed Delta version in control table or use streaming checkpoint',
    'Next run: readChangeFeed with startingVersion = last_version + 1 — only new commits',
    'Apply only changed rows to downstream Delta table via MERGE — much smaller op',
    'CDF version-based tracking eliminates "late arriving data" problem',
  ],
  facts:[
    'CDF version-based incremental MORE RELIABLE than timestamp-based',
    'CDF reduces scan cost: reads _change_data/ only — NOT full Parquet files',
    'DLT Materialized Views use CDF internally for incremental refresh',
    'Must store last processed version — on restart without tracking, re-processes',
  ],
  code:[
    '# Traditional incremental (race condition risk)',
    'last_run_ts = "2024-01-15 10:00:00"',
    'df_incremental = spark.table("orders") \\',
    '    .filter(col("updated_at") > last_run_ts)',
    '# Problem: rows updated exactly at boundary may be missed/duplicated',
    '',
    '# CDF incremental (version-based — no race condition)',
    'last_version = spark.sql("""',
    '    SELECT last_version FROM catalog.schema.pipeline_control',
    '    WHERE pipeline_name = \'orders_silver\'',
    '""").collect()[0][0]',
    '',
    'df_changes = (spark.read',
    '    .format("delta")',
    '    .option("readChangeFeed", "true")',
    '    .option("startingVersion", last_version + 1)',
    '    .table("catalog.schema.orders"))',
    '',
    '# Apply only changed rows',
    'upserts = df_changes.filter(',
    '    col("_change_type").isin(["insert", "update_postimage"])',
    ').drop("_change_type", "_commit_version", "_commit_timestamp")',
    '',
    'upserts.createOrReplaceTempView("cdf_upserts")',
    'spark.sql("""MERGE INTO catalog.schema.orders_silver t',
    '    USING cdf_upserts s ON t.order_id = s.order_id',
    '    WHEN MATCHED THEN UPDATE SET *',
    '    WHEN NOT MATCHED THEN INSERT *""")',
  ],
  trap:[
    '✗ CDF is NOT only for CDC — also for incremental processing performance',
    '✗ CDF version-based incremental MORE RELIABLE than timestamp-based',
    '✗ CDF reads _change_data/ only — NOT re-scanning full Parquet files',
    '✗ Must store last processed version explicitly — no auto checkpoint like streaming',
    '✗ DLT Materialized Views use CDF internally — same mechanism',
  ],
},

// ─── 6.4.2 ───────────────────────────────────────────────────────────────────
{num:'14',title:'6.4.2 — UC Managed Tables + Predictive Optimization = Zero-Maintenance',
  what:[
    'Predictive Optimization: Databricks feature that automatically runs OPTIMIZE and VACUUM',
    'Zero-maintenance: no need to schedule OPTIMIZE jobs or VACUUM jobs',
    'Analyzes table write patterns and query patterns to decide when and how to optimize',
  ],
  how:[
    'Predictive Optimization monitors write activity on UC managed tables',
    'Automatically triggers OPTIMIZE (with Liquid Clustering if configured)',
    'Automatically triggers VACUUM to clean up old files — default retention honored',
    'Available ONLY for Unity Catalog managed tables — NOT external tables, NOT hive_metastore',
  ],
  facts:[
    'Predictive Optimization is available for Unity Catalog MANAGED tables only',
    'Not applicable to hive_metastore tables — UC-only feature',
    'Reduces operational burden — no scheduled OPTIMIZE notebooks/jobs needed',
    'Pairs well with Liquid Clustering — automatic incremental clustering',
  ],
  code:[
    '-- Enable on a catalog (all managed tables in catalog)',
    'ALTER CATALOG my_catalog',
    'ENABLE PREDICTIVE OPTIMIZATION;',
    '',
    '-- Enable on a schema',
    'ALTER SCHEMA catalog.schema',
    'ENABLE PREDICTIVE OPTIMIZATION;',
    '',
    '-- Verify status',
    'DESCRIBE CATALOG EXTENDED my_catalog;',
    '-- Shows: Predictive Optimization: ENABLED',
    '',
    '-- Tables that benefit most:',
    '-- UC MANAGED tables with frequent small writes (streaming bronze)',
    '-- UC MANAGED tables with regular DELETE/UPDATE (SCD type 1)',
    '-- UC MANAGED tables with Liquid Clustering configured',
    '',
    '-- NOT applicable to:',
    '-- External tables (any catalog)',
    '-- hive_metastore tables',
  ],
  trap:[
    '✗ Predictive Optimization applies to UC MANAGED tables ONLY — not external',
    '✗ NOT applicable to hive_metastore tables — Unity Catalog required',
    '✗ Automatically runs OPTIMIZE and VACUUM — no manual scheduling needed',
    '✗ Predictive Optimization does NOT replace explicit OPTIMIZE for one-time restructuring',
    '✗ Enabled at catalog or schema level — not per-table in most configurations',
    '✗ Pairs with Liquid Clustering for best results — auto-clustering + auto-optimization',
  ],
},

// ─── 6.5.1 ───────────────────────────────────────────────────────────────────
{num:'15',title:'6.5.1 — Cluster Sizing for Shuffle-Heavy Workloads (8 VMs x 50GB)',
  what:[
    'Cluster sizing for shuffle-heavy workloads: balancing total cores, memory, shuffle partition count',
    'The 8 VMs x 50GB cluster sizing question is a confirmed exam scenario',
    'Rule of thumb: shuffle.partitions should be 2-4x total executor cores for optimal task distribution',
  ],
  how:[
    'Total cluster memory = num_workers x memory_per_worker',
    'Optimal shuffle.partitions: each partition should be ~100-200MB in memory',
    'Formula: shuffle.partitions = total_data_size_GB x 1024 / target_partition_size_MB',
    'Over-partitioned: too many tiny tasks; Under-partitioned: OOM/spill',
  ],
  facts:[
    '8 workers x 8 cores = 64 total cores — shuffle.partitions = 128-256 (2-4x cores)',
    '8 workers x 50GB = 400GB total executor memory — each executor: 50GB total - overhead',
    'Usable memory per executor: ~80% of total (20% overhead) = 40GB',
    'Shuffle.partitions guidance: each partition ~100-200MB',
  ],
  ascii:true,
  code:[
    'EXAM SCENARIO: 8 VMs, each with 8 cores and 50GB RAM',
    '               Processing 400GB of data for groupBy + aggregation',
    '',
    'Cluster resources:',
    '  Total cores:    8 VMs x 8 cores = 64 executor cores',
    '  Total memory:   8 VMs x 50GB   = 400GB total executor memory',
    '  Usable memory:  400GB x 80%    = 320GB usable (20% overhead)',
    '  Per-executor:   50GB x 80%     = 40GB usable per executor',
    '',
    'shuffle.partitions calculation:',
    '  Option A (core-based):  2x cores = 128 partitions',
    '                          4x cores = 256 partitions',
    '  Option B (data-based):  400GB / 200MB = 2000 partitions',
    '                          400GB / 100MB = 4000 partitions',
    '',
    'Recommendation for 400GB shuffle-heavy workload:',
    '  spark.sql.shuffle.partitions = 400  (roughly 1GB total / 200MB target)',
    '  or AQE with advisoryPartitionSizeInBytes = 128MB for auto-tuning',
    '',
    'Memory per task (with 256 partitions):',
    '  400GB / 256 tasks = 1.5GB per task',
    '  40GB per executor / 8 cores = 5GB per core — sufficient!',
  ],
  trap:[
    '✗ 8 workers x 8 cores = 64 total cores — shuffle.partitions: 2-4x = 128-256 minimum',
    '✗ 8 workers x 50GB = 400GB total — usable ~320GB after overhead',
    '✗ shuffle.partitions default 200 reasonable for ~20GB — must increase for 400GB+',
    '✗ AQE will coalesce if shuffle.partitions set too high — set high and let AQE reduce',
    '✗ Total cluster memory includes DRIVER memory — driver is separate, add ~1 VM',
    '✗ spark.executor.memoryOverhead default ~10% — total = executor.memory + overhead',
  ],
},

// ─── 6.5.2 ───────────────────────────────────────────────────────────────────
{num:'16',title:'6.5.2 — SQL Warehouse: Scale Up (Single Query) vs Scale Out (Concurrency)',
  what:[
    'SQL Warehouse sizing: two dimensions — cluster size (scale up) and max clusters (scale out)',
    'Scale up (cluster size: 2X-Small to 4X-Large): increases memory and cores for single query',
    'Scale out (max clusters: 1 to 30): adds more clusters for higher user concurrency',
  ],
  how:[
    'Single cluster: one SQL Warehouse cluster handles queries serially or with limited parallelism',
    'Multi-cluster: SQL Warehouse spins up additional clusters when load exceeds single cluster',
    'Cluster size affects: max memory per query, query execution speed for complex queries',
    'Max clusters affects: how many concurrent users/queries can run without queuing',
  ],
  facts:[
    'Scale UP: larger cluster size — more memory per query — better for complex queries',
    'Scale OUT: more clusters — higher concurrency — better for many simultaneous users',
    'Auto-scaling: SQL Warehouse scales out automatically up to max_num_clusters',
    'Serverless SQL Warehouse: scales both up and out automatically — no manual sizing',
  ],
  ascii:true,
  code:[
    'SCALE UP (cluster size):',
    '',
    '2X-Small (XS): 1 cluster node — good for simple queries, dev',
    'Medium:        4 nodes — good for moderate workloads',
    '2X-Large (2XL): 16 nodes — good for complex aggregations, large scans',
    '',
    'Single complex query: SELECT * FROM 10TB table with 10 joins',
    '  Needs: larger cluster (more memory per query)',
    '  Solution: SCALE UP to 2X-Large',
    '',
    'SCALE OUT (max clusters):',
    '',
    '100 BI users hitting the warehouse simultaneously',
    '  One cluster overwhelmed, queries queue',
    '  Solution: SCALE OUT to max 10 clusters',
    '  SQL Warehouse auto-spins additional clusters on demand',
    '',
    'DECISION:',
    '  Slow single query (large data, complex)  -> SCALE UP (bigger cluster)',
    '  Many users queuing (high concurrency)    -> SCALE OUT (more clusters)',
    '  Both                                      -> Both: scale up AND scale out',
  ],
  trap:[
    '✗ Scale UP = larger cluster size — more memory and cores per QUERY',
    '✗ Scale OUT = more max clusters — more CONCURRENT users/queries',
    '✗ Auto-scaling only increases cluster COUNT (scale out) — does NOT increase cluster SIZE',
    '✗ Serverless SQL Warehouse handles both scaling dimensions automatically',
    '✗ Cluster size affects QUERY PERFORMANCE; max clusters affects CONCURRENCY',
    '✗ SQL Warehouse auto-suspend: clusters spin down after idle — always configure to save cost',
  ],
},

// ─── 6.5.3 ───────────────────────────────────────────────────────────────────
{num:'17',title:'6.5.3 — Serverless SQL Warehouse Trade-offs',
  what:[
    'Serverless SQL Warehouse: Databricks-managed compute for SQL — starts in seconds, scales auto',
    'No infrastructure to manage — Databricks provisions, manages, and scales automatically',
    'Trade-offs vs Classic/Pro: instant start vs some latency for very large queries',
  ],
  facts:[
    'Startup time: Serverless = seconds; Classic/Pro = 2-5 minutes',
    'Infrastructure: Serverless = Databricks-managed; Classic = customer-managed VMs',
    'Idle cost: Serverless = zero when idle; Classic = DBU until auto-suspend',
    'Network: Serverless = Databricks VPC; Classic = customer VPC',
    'Photon: Serverless = always enabled; Classic = optional',
    'Cost model: Serverless = DBU per query; Classic = DBU/hour x cluster size',
  ],
  code:[
    '-- Query serverless warehouse — same SQL as any warehouse',
    'SELECT region, SUM(revenue) AS total',
    'FROM catalog.schema.orders',
    'GROUP BY region',
    'ORDER BY total DESC;',
    '',
    '-- Check if running on serverless',
    'SELECT is_serverless();  -- returns true or false',
    '',
    '-- Serverless advantages:',
    '-- Zero idle cost (pauses instantly when not in use)',
    '-- Instant start (no cold start wait)',
    '-- Automatic scaling (no max_clusters config)',
    '-- Always uses Photon engine',
    '',
    '-- Serverless limitations:',
    '-- Compute in Databricks VPC (not customer VPC)',
    '-- Not available in all regions',
    '-- Cannot customize cluster specs',
  ],
  trap:[
    '✗ Serverless SQL Warehouse starts in SECONDS — Classic/Pro start in 2-5 minutes',
    '✗ Serverless is in Databricks VPC — not customer VPC (different security model)',
    '✗ Serverless has ZERO idle cost — pauses instantly when no queries running',
    '✗ Serverless ALWAYS uses Photon — not optional like Classic/Pro',
    '✗ Serverless scales automatically — no max_num_clusters config needed',
    '✗ Not all DBR features available on Serverless — check feature parity docs',
  ],
},

// ─── 6.5.4 ───────────────────────────────────────────────────────────────────
{num:'18',title:'6.5.4 — Caching: df.cache(), CACHE TABLE, Invalidation Behavior',
  what:[
    'Caching: storing DataFrame or table results in memory to avoid re-computation',
    'Two mechanisms: df.cache() (DataFrame API — lazy) and CACHE TABLE (SQL — eager)',
    'Critical difference: invalidation behavior — CACHE TABLE auto-invalidates, df.cache() does NOT',
  ],
  how:[
    'df.cache(): marks DataFrame for caching — data not actually cached until FIRST action',
    'CACHE TABLE table_name: immediately scans and caches the table — EAGER',
    'CACHE LAZY TABLE: caches on first query — lazy variant',
    'Auto-invalidation: CACHE TABLE detects source Delta changes and automatically invalidates',
  ],
  facts:[
    'df.cache() execution: LAZY — needs action to materialize',
    'CACHE TABLE execution: EAGER — scans immediately',
    'Auto-invalidate on Delta change: df.cache() = NO; CACHE TABLE = YES',
    'Uncache: df.unpersist() / UNCACHE TABLE name',
    'Clear all: spark.catalog.clearCache() / CLEAR CACHE',
  ],
  code:[
    '# df.cache() — LAZY (needs action to materialize)',
    'df = spark.read.table("catalog.schema.large_dim")',
    'df.cache()          # marks for cache — NOTHING read yet',
    'df.count()          # triggers cache materialization (reads source)',
    'df.show()           # reads from cache — fast',
    '',
    '# Does NOT auto-invalidate if source Delta table changes!',
    'spark.sql("INSERT INTO catalog.schema.large_dim VALUES (999, \'new\')")',
    'df.count()  # still reads OLD cached data — not updated!',
    'df.unpersist()  # must manually unpersist to get fresh data',
    '',
    '# CACHE TABLE — EAGER (scans immediately)',
    'spark.sql("CACHE TABLE catalog.schema.large_dim")  # scans NOW',
    '',
    '# Auto-invalidates when source changes',
    'spark.sql("INSERT INTO catalog.schema.large_dim VALUES (999, \'new\')")',
    'spark.sql("SELECT COUNT(*) FROM catalog.schema.large_dim")  # fresh data!',
    '',
    '# CACHE LAZY TABLE — lazy variant',
    'spark.sql("CACHE LAZY TABLE catalog.schema.large_dim")  # no scan yet',
    '',
    '# StorageLevels for fine-grained control',
    'from pyspark.storagelevel import StorageLevel',
    'df.persist(StorageLevel.MEMORY_AND_DISK)  # spills to disk if needed',
    'df.persist(StorageLevel.DISK_ONLY)        # always on disk, slower but safer',
  ],
  trap:[
    '✗ CACHE TABLE auto-invalidates when source Delta table changes — df.cache() does NOT',
    '✗ df.cache() is LAZY — must call action before data is actually cached',
    '✗ CACHE TABLE is EAGER — scans and caches immediately upon execution',
    '✗ CACHE LAZY TABLE is LAZY — caches on first query, not immediately',
    '✗ df.cache() stale: after source Delta changes, df.cache() still returns OLD data',
    '✗ UNCACHE TABLE and df.unpersist() free cache memory — always clean up large caches',
    '✗ df.cache() = df.persist(StorageLevel.MEMORY_AND_DISK) — same default storage level',
  ],
},

// ─── 6.5.5 ───────────────────────────────────────────────────────────────────
{num:'19',title:'6.5.5 — Photon Engine — Vectorized Execution',
  what:[
    'Photon: Databricks vectorized query engine written in C++',
    'Optimized for SQL and DataFrame workloads — significant speedup for analytical queries',
    'Drop-in replacement for traditional Spark SQL execution — no code changes needed',
  ],
  facts:[
    'Photon is enabled at the cluster level — checkbox during cluster creation',
    'Always enabled in Serverless SQL Warehouse — not optional',
    'Optional in Classic/Pro SQL Warehouse and all-purpose clusters',
    'Photon supports: Spark SQL, DataFrame API, Delta operations',
    'Photon works with Liquid Clustering, ZORDER, Bloom filters — fully compatible',
  ],
  trap:[
    '✗ Photon ALWAYS enabled in Serverless SQL Warehouse — not optional',
    '✗ Photon is OPTIONAL in Classic/Pro warehouses and all-purpose clusters',
    '✗ Photon enabled at cluster level — checkbox in cluster creation UI',
    '✗ Photon is a vectorized C++ engine — significant speedup for analytical queries',
    '✗ Compatible with all Delta features — Liquid Clustering, ZORDER, Bloom filters',
    '✗ DBU rate is higher with Photon — but typically faster overall, lower total cost',
  ],
},

// ─── 6.5.6 ───────────────────────────────────────────────────────────────────
{num:'20',title:'6.5.6 — Auto-Termination and Spot/Preemptible Instances',
  what:[
    'Auto-termination: automatically shuts down idle clusters after configured timeout',
    'Spot/preemptible instances: cloud VMs purchased at deep discount, may be revoked',
    'Two key cost optimization strategies for Databricks workloads',
  ],
  facts:[
    'Auto-termination default: 120 minutes idle timeout for all-purpose clusters',
    'Job clusters auto-terminate immediately after job run — no idle period',
    'Spot instances: 60-90% cheaper than on-demand — but may be reclaimed at any time',
    'Spot instance handling: Databricks tries to recover from revocation automatically',
    'Driver should be on-demand (not spot) — spot driver = catastrophic job failure if reclaimed',
    'Workers can be a mix of on-demand and spot — fall back to on-demand if spot exhausted',
  ],
  code:[
    '# Auto-termination on cluster creation',
    '{',
    '    "cluster_name": "analytics-cluster",',
    '    "autotermination_minutes": 60,  # auto-terminate after 60 min idle',
    '    "num_workers": 8',
    '}',
    '',
    '# Spot instances configuration',
    '{',
    '    "azure_attributes": {  # or aws_attributes',
    '        "first_on_demand": 1,  # driver always on-demand',
    '        "availability": "SPOT_WITH_FALLBACK_AZURE",  # or SPOT_WITH_FALLBACK',
    '        "spot_bid_max_price": -1  # accept current spot price',
    '    },',
    '    "autotermination_minutes": 60',
    '}',
  ],
  trap:[
    '✗ Auto-termination default 120 minutes for all-purpose; immediate for job clusters',
    '✗ Spot instances 60-90% cheaper — BUT may be reclaimed at any time',
    '✗ Driver should NEVER be spot — spot driver reclamation = catastrophic job failure',
    '✗ first_on_demand = 1 ensures driver is on-demand, workers can be spot',
    '✗ SPOT_WITH_FALLBACK: falls back to on-demand if spot capacity exhausted',
    '✗ Critical SLA jobs: avoid spot for ALL nodes — risk of preemption mid-run',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain6_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
