'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 9  —  Debugging and Deploying  —  15 Sub-Topics',
  groups: [
    ['9.1  Debugging with Spark UI, Logs, System Tables',[
      ['01','9.1.1','Systematic Debugging Order (Run -> Task -> UI -> Stage -> Exception)'],
      ['02','9.1.2','Cluster Logs: Driver stdout, stderr, log4j'],
      ['03','9.1.3','system.jobs.runs for Programmatic Debugging'],
    ]],
    ['9.2  Job Repair and Parameter Overrides',[
      ['04','9.2.1','Repair Run via UI and REST API'],
      ['05','9.2.2','Parameter Overrides in Repair Runs'],
    ]],
    ['9.3  DABs Debugging and Deployment',[
      ['06','9.3.1','Full Command Set: validate, deploy, run, destroy with -t Flag'],
      ['07','9.3.2','databricks compute create — Correct Syntax'],
      ['08','9.3.3','pipelines.reset.allowed = false — Prevent Bronze Reset'],
      ['09','9.3.4','VACUUM on Shallow Clone = ERROR'],
      ['10','9.3.5','Time Travel After DELETE Before VACUUM'],
    ]],
    ['9.4  Debugging Lakeflow Pipelines',[
      ['11','9.4.1','Pipeline Event Log Queries (flow_progress, error, warning)'],
      ['12','9.4.2','Pipeline Update States: INITIALIZING, RUNNING, COMPLETED, FAILED'],
    ]],
    ['9.5  Idempotent Pipeline Design',[
      ['13','9.5.1','MERGE vs INSERT, Overwrite Mode, Durable Checkpoint'],
      ['14','9.5.2','batch_id for Idempotency in foreachBatch'],
      ['15','9.5.3','Streaming Checkpoint Storage Requirements'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 9  —  Debugging and Deploying  —  All High-Priority Traps',
};

const pages = [

// ─── 9.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'9.1.1 — Systematic Debugging Order (Run -> Task -> UI -> Stage -> Exception)',
  what:[
    'Systematic debugging: structured, step-by-step approach to diagnosing Spark job failures',
    'Starting from highest level and drilling down prevents wasted time looking in wrong place',
    'Five-step order: Run History -> Failed Task -> Spark UI -> Stage Details -> Exception',
  ],
  how:[
    'Step 1 — Run History: which run failed, what time, result_state',
    'Step 2 — Failed Task: identify which task failed — task ID, executor, exception type',
    'Step 3 — Spark UI: navigate to job -> stage -> failed task',
    'Step 4 — Stage Details: check task duration histogram (skew?), spill bytes, GC time',
    'Step 5 — Exception: read the full exception message and stack trace',
  ],
  facts:[
    'Always start at the HIGHEST level — run history tells WHICH job/task failed',
    'Spark UI resets on cluster restart — check system tables for historical debugging',
    'Exception message often the fastest path to root cause',
    'result_state only valid when life_cycle_state = TERMINATED — verify lifecycle first',
  ],
  ascii:true,
  code:[
    'SYSTEMATIC DEBUGGING ORDER:',
    '',
    'STEP 1: RUN HISTORY',
    '  Databricks Jobs UI -> Run History tab',
    '  OR: SELECT * FROM system.jobs.runs WHERE result_state = \'FAILED\'',
    '  -> Identify: which run_id, which job_id, what time, what result_state',
    '  -> Check state_message for high-level error description',
    '',
    'STEP 2: FAILED TASK',
    '  Jobs UI -> Failed Run -> click into failed task',
    '  -> Which task_key failed? What error type?',
    '  -> UPSTREAM_FAILED? Fix the upstream task first',
    '',
    'STEP 3: SPARK UI',
    '  Click "Spark UI" link on the cluster/run page',
    '  -> Jobs tab -> find the failed job -> click into it',
    '  -> Stages tab -> find the failed stage (red) -> click into it',
    '',
    'STEP 4: STAGE DETAILS',
    '  Failed stage -> Task list -> find failed tasks (red)',
    '  -> Check: task duration (skew?), spill bytes, GC time',
    '  -> Click failed task -> see full error message',
    '',
    'STEP 5: EXCEPTION',
    '  Read the full exception message and stack trace',
    '  Common exceptions:',
    '  - java.lang.OutOfMemoryError    = memory issue',
    '  - FileNotFoundException          = missing file or VACUUM issue',
    '  - AnalysisException              = schema/permission/name issue',
    '  - SparkException (constraint)    = constraint violation',
    '  - ConcurrentModificationException = OCC conflict',
  ],
  trap:[
    '✗ Always start with RUN HISTORY — not cluster logs, not Spark UI — highest level first',
    '✗ UPSTREAM_FAILED = task never ran — fix the UPSTREAM task',
    '✗ result_state only valid when life_cycle_state = TERMINATED',
    '✗ Exception message in Spark UI task details — most specific diagnosis',
    '✗ FileNotFoundException after VACUUM = time travel or shallow clone issue',
    '✗ Spark UI resets on cluster restart — use system.jobs.runs for historical debugging',
  ],
},

// ─── 9.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'9.1.2 — Cluster Logs: Driver stdout, stderr, log4j',
  what:[
    'Cluster logs: runtime output from driver and executors — essential for failures not in Spark UI',
    'Three log streams: stdout (standard output), stderr (errors), log4j (Spark internal logging)',
    'Accessible via: Databricks cluster UI or directly from DBFS log path',
  ],
  how:[
    'Driver stdout: output from print(), display() in notebook, driver Python output',
    'Driver stderr: Python exceptions, Java exceptions on driver, traceback',
    'log4j: Spark internal logging — INFO/WARN/ERROR from Spark internals and user code',
    'Log delivery: logs written to executor local disk -> shipped to DBFS log location',
  ],
  facts:[
    'Log location in DBFS: dbfs:/cluster-logs/<cluster_id>/driver/',
    'Executor logs: dbfs:/cluster-logs/<cluster_id>/executor/<executor_id>/',
    'Log4j log level: configurable via cluster Spark config',
    'Logs accessible in UI: Cluster Details -> Driver Logs tab -> stdout/stderr/log4j',
  ],
  ascii:true,
  code:[
    'CLUSTER LOG ACCESS PATHS:',
    '',
    'VIA DATABRICKS UI:',
    '  Clusters -> click cluster -> Driver Logs tab',
    '  +-- stdout  -> print() output, driver Python output',
    '  +-- stderr  -> exceptions, stack traces, Python errors',
    '  +-- log4j   -> Spark internal logging (INFO/WARN/ERROR)',
    '',
    'VIA DBFS:',
    '  dbfs:/cluster-logs/<cluster_id>/driver/',
    '  +-- stdout     -> driver standard output',
    '  +-- stderr     -> driver standard error / exceptions',
    '  +-- log4j-active.log -> Spark internal logging',
    '',
    '  Access via %sh (on active cluster):',
    '  %sh cat /databricks/driver/logs/stderr',
    '',
    '  Access via dbutils.fs:',
    '  dbutils.fs.head("dbfs:/cluster-logs/.../driver/log4j-active.log")',
    '',
    'LOG4J LEVELS (most to least verbose):',
    '  TRACE -> DEBUG -> INFO -> WARN -> ERROR -> FATAL',
    '',
    'COMMON LOG PATTERNS:',
    '  ERROR ExecutorLostFailure -> executor crashed (OOM, node failure)',
    '  WARN  TaskSetManager     -> task retries, slow tasks',
    '  ERROR FileNotFoundException -> missing file, VACUUM issue',
    '  INFO  BlockManager       -> cache hit/miss, memory stats',
  ],
  trap:[
    '✗ Three distinct log streams: stdout, stderr, log4j — different content, purposes',
    '✗ stderr contains Python/Java exceptions — most useful for debugging',
    '✗ log4j contains Spark internal logging — useful for memory, shuffle, GC warnings',
    '✗ Driver logs accessible via UI AND via DBFS path dbfs:/cluster-logs/<cluster_id>/driver/',
    '✗ %sh cat /databricks/driver/logs/stderr — access from running cluster driver',
    '✗ Executor logs at different path: dbfs:/cluster-logs/<cluster_id>/executor/<executor_id>/',
  ],
},

// ─── 9.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'9.1.3 — system.jobs.runs for Programmatic Debugging',
  what:[
    'system.jobs.runs: UC system table recording all job run history — queryable with SQL',
    'Enables: failure rate analysis, performance trending, SLA monitoring, cost attribution',
    'More powerful than the UI for historical analysis — SQL allows aggregation, filtering',
  ],
  how:[
    'Every completed job run generates a record: run_id, job_id, start_time, end_time, result_state',
    'state_message: contains error description when result_state = FAILED',
    'Join with system.billing.usage via run_id for per-run cost attribution',
    'system.jobs.runs requires Unity Catalog',
  ],
  facts:[
    'state_message = failure reason — most actionable debugging field',
    'Retention: approximately 60 days of job run history',
    'result_state: SUCCESS, FAILED, TIMEDOUT, CANCELED, UPSTREAM_FAILED',
    'Combine with system.billing.usage to identify expensive failing jobs',
  ],
  code:[
    '-- Find recent failures with error messages',
    'SELECT',
    '    run_id,',
    '    job_id,',
    '    job_name,',
    '    start_time,',
    '    end_time,',
    '    DATEDIFF(SECOND, start_time, end_time) AS duration_sec,',
    '    result_state,',
    '    state_message                           AS error_message',
    'FROM system.jobs.runs',
    'WHERE result_state = \'FAILED\'',
    '  AND start_time > current_timestamp() - INTERVAL 7 DAYS',
    'ORDER BY start_time DESC;',
    '',
    '-- Job failure rate trend (week-over-week)',
    'SELECT',
    '    job_name,',
    '    DATE_TRUNC(\'week\', start_time)          AS week,',
    '    COUNT(*)                                 AS total_runs,',
    '    SUM(CASE WHEN result_state = \'FAILED\' THEN 1 ELSE 0 END) AS failures,',
    '    ROUND(100.0 * SUM(CASE WHEN result_state = \'FAILED\' THEN 1 ELSE 0 END)',
    '        / COUNT(*), 1)                       AS failure_rate_pct',
    'FROM system.jobs.runs',
    'WHERE start_time > current_timestamp() - INTERVAL 90 DAYS',
    'GROUP BY job_name, week',
    'ORDER BY job_name, week;',
    '',
    '-- Most expensive failed runs (join with billing)',
    'SELECT',
    '    r.job_name,',
    '    r.run_id,',
    '    r.state_message,',
    '    SUM(b.usage_quantity) AS wasted_dbus',
    'FROM system.jobs.runs r',
    'JOIN system.billing.usage b',
    '    ON r.run_id = CAST(b.usage_metadata.run_id AS BIGINT)',
    'WHERE r.result_state = \'FAILED\'',
    '  AND r.start_time > current_timestamp() - INTERVAL 30 DAYS',
    'GROUP BY r.job_name, r.run_id, r.state_message',
    'ORDER BY wasted_dbus DESC;',
  ],
  trap:[
    '✗ system.jobs.runs requires Unity Catalog',
    '✗ state_message contains the ERROR REASON — most useful field for debugging',
    '✗ result_state only valid when life_cycle_state = TERMINATED — filter for completed',
    '✗ Retention ~60 days — for longer history, export to a Delta table regularly',
    '✗ Join with system.billing.usage via run_id for cost-per-run analysis',
  ],
},

// ─── 9.2.1 ───────────────────────────────────────────────────────────────────
{num:'04',title:'9.2.1 — Repair Run via UI and REST API',
  what:[
    'Repair run: re-executes only FAILED and UPSTREAM_FAILED tasks from a previous run',
    'Preserves successful task results — uses the SAME run_id (not a new run)',
    'Available via: Databricks Jobs UI or REST API',
  ],
  how:[
    'Failed run: tasks with FAILED or UPSTREAM_FAILED can be repaired',
    'Repair run: Databricks identifies failed tasks -> re-queues them -> runs in dependency order',
    'Same run_id: repair appends to original run record — no new run_id generated',
    'Multiple repairs: can repair the same run multiple times if repair fails',
  ],
  facts:[
    'rerun_tasks: optional list of specific task keys — if omitted, repairs ALL failed',
    'Parameter overrides: can pass new parameters for the repair run only',
    'Repair creates a new "repair history" entry within the original run',
    'result_state of repaired run: re-evaluated after all repaired tasks complete',
  ],
  code:[
    'import requests',
    '',
    '# Repair all failed tasks in a run',
    'repair_payload = {',
    '    "run_id": 67890,',
    '    # Omit rerun_tasks to repair ALL failed/upstream_failed',
    '}',
    '',
    'response = requests.post(',
    '    f"{HOST}/api/2.1/jobs/runs/repair",',
    '    headers=headers,',
    '    json=repair_payload',
    ')',
    'repair_run_id = response.json()["repair_run_id"]',
    'print(f"Repair triggered, repair_run_id: {repair_run_id}")',
    '',
    '# Via Databricks CLI',
    'databricks jobs repair-run --run-id 67890',
    '',
    '# Repair specific tasks only',
    'databricks jobs repair-run --run-id 67890 \\',
    '    --rerun-tasks \'["failed_transform_task", "failed_load_task"]\'',
    '',
    'UI REPAIR FLOW:',
    '  Jobs -> Run History -> Failed Run -> "Repair Run" button',
    '  -> Dialog shows: failed tasks to be re-run',
    '  -> Option to override parameters for this repair',
    '  -> Click "Repair Run" -> same run_id, new attempt on failed tasks',
  ],
  trap:[
    '✗ Repair run uses SAME run_id — not a new run_id',
    '✗ Repair only re-runs FAILED and UPSTREAM_FAILED tasks — SUCCESS NOT re-run',
    '✗ UPSTREAM_FAILED tasks re-queued when their dependency is repaired — cascades automatically',
    '✗ Can repair the same run multiple times — if repair fails, repair again',
    '✗ Parameter overrides in repair are ONE-TIME — not saved to job definition',
    '✗ Repair is idempotent for successful tasks — safe to re-run',
  ],
},

// ─── 9.2.2 ───────────────────────────────────────────────────────────────────
{num:'05',title:'9.2.2 — Parameter Overrides in Repair Runs',
  what:[
    'Repair runs support parameter overrides — change task parameters for repair attempt only',
    'Use case: fix a bug by changing a parameter without modifying job definition',
    'Parameters overridden only for the repair attempt — job definition remains unchanged',
  ],
  how:[
    'notebook_params: override widget parameters for notebook tasks',
    'python_params: override positional arguments for Python script tasks',
    'pipeline_params: override parameters for DLT pipeline tasks',
    'Override applies ONLY to the failed tasks being repaired',
  ],
  code:[
    '# Repair with parameter overrides',
    'repair_payload = {',
    '    "run_id": 67890,',
    '    "rerun_tasks": ["failed_etl_task"],',
    '    "notebook_params": {',
    '        "start_date": "2024-01-01",    # Override the date for this repair',
    '        "end_date": "2024-01-31",',
    '        "batch_size": "5000"           # Reduce batch size to fix OOM',
    '    },',
    '    "python_params": ["--mode", "repair", "--date", "2024-01-01"]',
    '}',
    '',
    'response = requests.post(',
    '    f"{HOST}/api/2.1/jobs/runs/repair",',
    '    headers=headers,',
    '    json=repair_payload',
    ')',
    '',
    'REPAIR PARAMETER OVERRIDE USE CASES:',
    '',
    'Scenario 1: Wrong date range caused failure',
    '  Original: start_date = \'2024-02-01\' (wrong)',
    '  Repair override: start_date = \'2024-01-01\' (corrected)',
    '  -> Repair runs with corrected date, job definition unchanged',
    '',
    'Scenario 2: OOM due to large batch_size',
    '  Original: batch_size = \'100000\' (too large)',
    '  Repair override: batch_size = \'10000\' (smaller)',
    '  -> Repair runs with smaller batches, job definition unchanged',
    '',
    'Note: Override parameters are ONE-TIME for this repair',
    '      The job definition still has the original parameters',
    '      Next scheduled run uses original job parameters',
  ],
  trap:[
    '✗ Parameter overrides in repair are ONE-TIME — NOT persisted to job definition',
    '✗ Next scheduled run uses ORIGINAL job parameters — override was only for repair',
    '✗ Override only applies to FAILED tasks being repaired — successful use original',
    '✗ notebook_params for notebook tasks; python_params for Python — different per task type',
    '✗ Can override parameters without touching job definition — no risk to future runs',
  ],
},

// ─── 9.3.1 ───────────────────────────────────────────────────────────────────
{num:'06',title:'9.3.1 — Full Command Set: validate, deploy, run, destroy with -t Flag',
  what:[
    'DABs (Databricks Asset Bundles): infrastructure-as-code for Databricks',
    'Four core commands: validate, deploy, run, destroy — each serves distinct lifecycle phase',
    '-t flag: selects target environment — -t dev, -t staging, -t prod',
  ],
  how:[
    'databricks bundle validate: checks YAML syntax — LOCAL only, no workspace connection',
    'databricks bundle deploy -t TARGET: creates or updates resources in target workspace',
    'databricks bundle run -t TARGET RESOURCE_KEY: triggers a job/pipeline run',
    'databricks bundle destroy -t TARGET: deletes ALL deployed resources',
  ],
  facts:[
    'validate: local-only — no workspace connectivity or auth required',
    'deploy: IDEMPOTENT — running twice produces same state',
    'destroy: PERMANENT — no undo, all deployed resources deleted',
    'All commands run from project root directory (where databricks.yml is)',
  ],
  code:[
    '# Step 1: Validate (local — no workspace connection)',
    'databricks bundle validate',
    '',
    '# Step 2: Deploy to dev',
    'databricks bundle deploy -t dev',
    '',
    '# Step 3: Run a deployed job in dev',
    'databricks bundle run -t dev daily_etl_job',
    '',
    '# Step 4: Deploy to prod after testing',
    'databricks bundle deploy -t prod',
    '',
    '# Teardown dev resources (permanent!)',
    'databricks bundle destroy -t dev',
    '',
    '# Debug deployment issues',
    'databricks bundle validate --output json',
    'databricks bundle deploy -t dev --debug',
    '',
    '# databricks.yml structure (must be at project root)',
    'bundle:',
    '  name: my_etl_bundle',
    '',
    'targets:',
    '  dev:',
    '    mode: development  # adds [dev username] prefix',
    '    workspace:',
    '      host: https://adb-dev.azuredatabricks.net',
    '  prod:',
    '    workspace:',
    '      host: https://adb-prod.azuredatabricks.net',
    '',
    'resources:',
    '  jobs:',
    '    daily_etl_job:        # this is the RESOURCE_KEY',
    '      name: "Daily ETL"',
  ],
  trap:[
    '✗ validate is LOCAL ONLY — does not connect to workspace, does not verify resource IDs',
    '✗ deploy is IDEMPOTENT — running twice is safe, updates existing resources',
    '✗ destroy PERMANENTLY DELETES — no undo, all resources removed',
    '✗ -t flag selects TARGET — omitting uses default which may be wrong',
    '✗ bundle run uses RESOURCE KEY (name in YAML) — not deployed display name',
    '✗ databricks.yml MUST be at project ROOT — bundle commands fail from subdirectory',
  ],
},

// ─── 9.3.2 ───────────────────────────────────────────────────────────────────
{num:'07',title:'9.3.2 — databricks compute create — Correct Syntax',
  what:[
    'databricks compute create: correct Databricks CLI v2+ command to create a cluster',
    'NOT databricks clusters create — that is old CLI v1 syntax',
    'CLI v2 uses resource-based naming: compute (not clusters), jobs (not job)',
  ],
  how:[
    'CLI v2 command structure: databricks <resource> <action>',
    '--json flag: pass cluster configuration as JSON string or @path/to/file.json',
    'Authentication: DATABRICKS_HOST + DATABRICKS_TOKEN env vars or .databrickscfg profile',
  ],
  facts:[
    'CLI v2 resource: compute (not clusters)',
    'CLI v2 resource for jobs: jobs (same name)',
    'databricks bundle deploy is separate from databricks compute create',
    'jobs/create API is NOT idempotent — three calls = three separate jobs',
  ],
  code:[
    '# CORRECT: CLI v2 syntax',
    'databricks compute create --json \'{',
    '  "cluster_name": "my-analytics-cluster",',
    '  "spark_version": "14.3.x-scala2.12",',
    '  "node_type_id": "i3.xlarge",',
    '  "num_workers": 4,',
    '  "autotermination_minutes": 60,',
    '  "spark_conf": {',
    '    "spark.sql.shuffle.partitions": "200"',
    '  }',
    '}\'',
    '',
    '# WRONG: CLI v1 syntax (deprecated)',
    '# databricks clusters create ...   <- DO NOT USE',
    '',
    '# Other CLI v2 compute commands',
    'databricks compute list',
    'databricks compute get --cluster-id 0101-xxx',
    'databricks compute start --cluster-id 0101-xxx',
    'databricks compute delete --cluster-id 0101-xxx',
    'databricks compute edit --cluster-id 0101-xxx \\',
    '    --json \'{"num_workers": 8}\'',
    '',
    '# Jobs CLI v2',
    'databricks jobs list',
    'databricks jobs run-now --job-id 12345',
    'databricks jobs get --job-id 12345',
    '',
    '# DABs CLI (separate from compute/jobs)',
    'databricks bundle validate',
    'databricks bundle deploy -t prod',
    'databricks bundle run -t prod my_job',
  ],
  trap:[
    '✗ databricks compute create is the CORRECT CLI v2 command — NOT databricks clusters create',
    '✗ CLI v2 uses compute not clusters — resource name changed between v1 and v2',
    '✗ databricks jobs create is NOT idempotent — each call creates a NEW separate job',
    '✗ databricks bundle deploy IS idempotent — correct pattern for CI/CD',
    '✗ --json flag required for create commands — cluster config as JSON string',
    '✗ CLI v2 authentication: DATABRICKS_HOST + DATABRICKS_TOKEN environment variables',
  ],
},

// ─── 9.3.3 ───────────────────────────────────────────────────────────────────
{num:'08',title:'9.3.3 — pipelines.reset.allowed = false — Prevent Bronze Reset',
  what:[
    'pipelines.reset.allowed: DLT pipeline config controlling whether full pipeline reset is allowed',
    'Setting to "false" prevents accidental full reset — protects Bronze Streaming Tables',
    'Must be the STRING "false" — NOT the boolean false — critical exam distinction',
  ],
  how:[
    'Full pipeline reset: clears all checkpoints and re-processes ALL source data',
    'Risk: Bronze Streaming Tables accumulate historical data — reset causes duplicates',
    'With pipelines.reset.allowed = "false": "Full Refresh" button disabled in UI',
    'To perform reset after setting: must change to "true" first',
  ],
  facts:[
    'Value must be STRING "false" — boolean false is NOT recognized',
    'Default: reset IS allowed — must explicitly set "false" to protect',
    'Applies to FULL pipeline reset only — individual table refresh still works',
    'Key is exact: pipelines.reset.allowed — lowercase, period-separated',
  ],
  code:[
    '# In databricks.yml (DABs) — must be quoted string',
    'resources:',
    '  pipelines:',
    '    bronze_ingestion_pipeline:',
    '      name: "Bronze Ingestion Pipeline"',
    '      configuration:',
    '        pipelines.reset.allowed: "false"    # STRING "false"',
    '',
    '# In Databricks pipeline UI:',
    '# Settings -> Configuration tab -> Add key-value pair',
    '# Key:   pipelines.reset.allowed',
    '# Value: false    <- type as string in the text field',
    '',
    '# In Python API',
    'pipeline_config = {',
    '    "name": "Bronze Pipeline",',
    '    "configuration": {',
    '        "pipelines.reset.allowed": "false"',
    '    }',
    '}',
    '',
    'BEHAVIOR:',
    '',
    'WITHOUT setting (default):',
    '  Pipeline UI shows "Full Refresh" button',
    '  Any user with Manage permission can reset',
    '  Bronze table: all records re-ingested -> DUPLICATES',
    '',
    'WITH pipelines.reset.allowed = "false":',
    '  "Full Refresh" button DISABLED in pipeline UI',
    '  API reset attempt: returns error',
    '  Bronze table: protected from accidental full reset',
    '',
    'TO RE-ENABLE RESET (if needed):',
    '  Change property value to "true" -> reset -> set back to "false"',
  ],
  trap:[
    '✗ pipelines.reset.allowed must be STRING "false" — boolean false is NOT recognized',
    '✗ Default: reset IS allowed — must explicitly configure "false" to protect',
    '✗ This prevents FULL RESET only — table-level refresh still works normally',
    '✗ Key is case-sensitive: pipelines.reset.allowed — exact lowercase spelling',
    '✗ Setting to "false" disables Full Refresh button in pipeline UI',
  ],
},

// ─── 9.3.4 ───────────────────────────────────────────────────────────────────
{num:'09',title:'9.3.4 — VACUUM on Shallow Clone = ERROR',
  what:[
    'Critical behavior: running VACUUM on the SOURCE table of a shallow clone breaks the clone',
    'Shallow clone shares Parquet files with source — VACUUM on source deletes those files',
    'Result: shallow clone becomes unreadable — FileNotFoundException on any query',
  ],
  how:[
    'Shallow clone: _delta_log/ copied to new location; Parquet data files remain at source (shared)',
    'VACUUM on source: deletes old Parquet files — including files the shallow clone depends on',
    'After VACUUM on source: shallow clone queries fail with FileNotFoundException',
    'Deep clone: unaffected by source VACUUM — has its OWN copy of all Parquet files',
  ],
  facts:[
    'VACUUM source after SHALLOW CLONE = BROKEN CLONE — most impactful Delta clone exam trap',
    'VACUUM source after DEEP CLONE = SAFE — deep clone is fully independent',
    'Shallow clone good for: short-lived dev/test environments',
    'Deep clone good for: DR backups, long-lived production replicas',
  ],
  ascii:true,
  code:[
    'SHALLOW CLONE — VACUUM DANGER:',
    '',
    'CREATE TABLE dev.schema.orders_test',
    'SHALLOW CLONE prod.schema.orders;',
    '-- dev.schema.orders_test:  _delta_log/ (copy)',
    '--                          data files: STILL AT prod.schema.orders/ (SHARED!)',
    '',
    'prod.schema.orders has: part-001.parquet, part-002.parquet',
    'dev.schema.orders_test references: same part-001.parquet (SHARED)',
    '',
    'VACUUM prod.schema.orders RETAIN 0 HOURS;',
    '-- Deletes: part-001.parquet, part-002.parquet',
    '',
    'SELECT * FROM dev.schema.orders_test;',
    '-- ERROR: FileNotFoundException: part-001.parquet not found!',
    '-- BROKEN — shared files were deleted',
    '',
    'DEEP CLONE — VACUUM SAFE:',
    '',
    'CREATE TABLE backup.schema.orders_backup',
    'DEEP CLONE prod.schema.orders;',
    '-- Fully independent — own copies of all files',
    '',
    'VACUUM prod.schema.orders RETAIN 0 HOURS;',
    '-- Deletes: part-001.parquet (from prod only)',
    '',
    'SELECT * FROM backup.schema.orders_backup;',
    '-- SUCCESS — reads from its own independent copy',
  ],
  trap:[
    '✗ VACUUM on shallow clone source = FileNotFoundException on clone — broken permanently',
    '✗ Shallow clone shares Parquet files with source — NOT an independent copy',
    '✗ Deep clone is completely independent — source VACUUM has ZERO effect',
    '✗ Shallow clone: cheap and fast — use for short-lived dev/test only',
    '✗ Deep clone: expensive — use for DR, long-lived environments',
    '✗ VACUUM DRY RUN: shows files to be deleted — safe preview',
    '✗ After shallow clone source vacuumed: no recovery — must re-create',
  ],
},

// ─── 9.3.5 ───────────────────────────────────────────────────────────────────
{num:'10',title:'9.3.5 — Time Travel After DELETE Before VACUUM',
  what:[
    'Key timing behavior: after DELETE, deleted rows STILL accessible via time travel',
    'Rows ONLY permanently removed after VACUUM physically deletes the old Parquet files',
    'Window between DELETE and VACUUM is important for: debugging, GDPR compliance, auditing',
  ],
  how:[
    'DELETE operation: adds remove action to Delta log — marks files as logically deleted',
    'Old Parquet files with deleted rows: still physically present — accessible via time travel',
    'VACUUM (after retention period): physically deletes old Parquet files',
    'After VACUUM: FileNotFoundException when accessing pre-VACUUM versions',
  ],
  facts:[
    'DELETE alone = LOGICAL delete only — rows still in time travel',
    'VACUUM after DELETE = PHYSICAL delete — time travel to pre-VACUUM versions fails',
    'Default VACUUM retention = 7 days — deleted rows physically accessible for 7 days',
    'VACUUM RETAIN 0 HOURS: requires retentionDurationCheck.enabled = false',
  ],
  ascii:true,
  code:[
    'TIMELINE OF DELETE + VACUUM:',
    '',
    'T=0: Initial table state (version 5)',
    '     data: [row1, row2, row3, row4, row5]',
    '     Files: part-001.parquet (contains all rows)',
    '',
    'T=1: DELETE FROM table WHERE id = 3  (version 6)',
    '     data: [row1, row2, row4, row5]  (row3 removed logically)',
    '     Files: part-001.parquet STILL EXISTS',
    '     _delta_log: v6.json has remove action for part-001 + add for part-002',
    '',
    '     TIME TRAVEL STILL WORKS:',
    '     SELECT * FROM table VERSION AS OF 5;',
    '     -> Returns: row1, row2, row3, row4, row5 — row3 still accessible!',
    '',
    'T=7 DAYS: VACUUM runs (default 7-day retention)',
    '     VACUUM table RETAIN 0 HOURS;',
    '     -> Deletes: part-001.parquet physically from storage',
    '',
    '     TIME TRAVEL NOW FAILS:',
    '     SELECT * FROM table VERSION AS OF 5;',
    '     -> FileNotFoundException: part-001.parquet not found',
    '     row3 is now permanently inaccessible (GDPR compliant)',
    '',
    'FOR GDPR COMPLIANCE:',
    '  Step 1: DELETE (logical remove — immediate from live queries)',
    '  Step 2: VACUUM RETAIN 0 HOURS (physical remove — from all versions)',
    '  Only after Step 2 is data truly erased from storage',
  ],
  trap:[
    '✗ After DELETE: rows STILL ACCESSIBLE via time travel — DELETE is logical only',
    '✗ After VACUUM: FileNotFoundException on time travel to pre-delete versions',
    '✗ Default VACUUM retention = 7 days — deleted rows physically accessible for 7 days',
    '✗ VACUUM RETAIN 0 HOURS: requires retentionDurationCheck.enabled = false',
    '✗ GDPR erasure requires BOTH DELETE (logical) AND VACUUM (physical)',
    '✗ Time travel window: between DELETE and VACUUM, data accessible',
  ],
},

// ─── 9.4.1 ───────────────────────────────────────────────────────────────────
{num:'11',title:'9.4.1 — Pipeline Event Log Queries (flow_progress, error, warning)',
  what:[
    'Pipeline event log: system.lakeflow.pipeline_events — records all DLT pipeline activities',
    'Three primary event types for debugging: flow_progress, error, warning',
    'Query the event log to diagnose: pipeline failures, data quality, performance',
  ],
  how:[
    'flow_progress events: one per table per pipeline update — status, row counts, DQ metrics',
    'error events: contain full exception details when a flow or pipeline fails',
    'warning events: non-fatal issues — schema evolution warnings, late-arriving data',
    'update_id: unique per pipeline run — use to correlate all events for one run',
  ],
  facts:[
    'JSON field access uses colon syntax: details:flow_progress.status',
    'event_type values: flow_progress, error, warning, planning, user_action',
    'flow_progress.status values: STARTING, RUNNING, COMPLETED, FAILED, SKIPPED',
    'Retention: ~30 days — export to Delta for longer-term event history',
  ],
  code:[
    '-- Find all errors in last 24 hours',
    'SELECT',
    '    pipeline_name,',
    '    update_id,',
    '    timestamp,',
    '    event_type,',
    '    message,',
    '    details:error.fatal                    AS is_fatal,',
    '    details:error.exceptions[0].message   AS exception_message',
    'FROM system.lakeflow.pipeline_events',
    'WHERE event_type = \'error\'',
    '  AND timestamp > current_timestamp() - INTERVAL 24 HOURS',
    'ORDER BY timestamp DESC;',
    '',
    '-- Data quality summary: dropped records by table',
    'SELECT',
    '    pipeline_name,',
    '    details:flow_progress.name              AS table_name,',
    '    details:flow_progress.status           AS status,',
    '    details:flow_progress.data_quality.dropped_records AS rows_dropped,',
    '    timestamp',
    'FROM system.lakeflow.pipeline_events',
    'WHERE event_type = \'flow_progress\'',
    '  AND details:flow_progress.data_quality.dropped_records > 0',
    'ORDER BY rows_dropped DESC;',
    '',
    '-- Full pipeline run summary',
    'SELECT',
    '    details:flow_progress.name   AS table_name,',
    '    details:flow_progress.status AS status,',
    '    timestamp',
    'FROM system.lakeflow.pipeline_events',
    'WHERE event_type = \'flow_progress\'',
    '  AND update_id = \'your-update-id-here\'',
    'ORDER BY timestamp;',
  ],
  trap:[
    '✗ system.lakeflow.pipeline_events requires Unity Catalog',
    '✗ JSON field access: details:flow_progress.status using COLON syntax',
    '✗ event_type = flow_progress for table status; event_type = error for failures',
    '✗ update_id links ALL events for ONE pipeline run',
    '✗ dropped_records in data quality = rows dropped by expect_or_drop',
    '✗ Default retention ~30 days — export to Delta for longer-term',
  ],
},

// ─── 9.4.2 ───────────────────────────────────────────────────────────────────
{num:'12',title:'9.4.2 — Pipeline Update States: INITIALIZING, RUNNING, COMPLETED, FAILED',
  what:[
    'Pipeline update states: lifecycle states a DLT pipeline progresses through',
    'Understanding these helps diagnose where a pipeline is stuck',
    'Visible in: DLT pipeline UI, pipeline event log, REST API',
  ],
  how:[
    'INITIALIZING: pipeline starting — allocating cluster resources, setting up environment',
    'SETTING_UP_TABLES: creating or validating Delta table schemas — before data processing',
    'RUNNING: actively processing data — individual flows being executed',
    'COMPLETED: all flows completed successfully',
    'FAILED: one or more flows failed — pipeline stopped due to error',
  ],
  facts:[
    'State sequence: INITIALIZING -> SETTING_UP_TABLES -> RUNNING -> COMPLETED or FAILED',
    'Stuck in INITIALIZING: cluster startup issue, driver crash, network problem',
    'Stuck in SETTING_UP_TABLES: schema conflict, permission issue, corrupt Delta log',
    'FAILED: check error events in pipeline event log for root cause',
  ],
  ascii:true,
  code:[
    'PIPELINE UPDATE LIFECYCLE:',
    '',
    'TRIGGER (manual click, schedule, or API call)',
    '    |',
    '    v',
    'INITIALIZING',
    '  + Allocating cluster resources',
    '  + Installing libraries',
    '  + Setting up Spark environment',
    '  [stuck here = cluster startup issue, check cluster logs]',
    '    |',
    '    v',
    'SETTING_UP_TABLES',
    '  + Creating Delta tables (if new)',
    '  + Validating existing table schemas',
    '  + Setting up checkpoints',
    '  [stuck here = schema conflict, permission issue]',
    '    |',
    '    v',
    'RUNNING',
    '  + Executing individual flows in dependency order',
    '  + Processing data, applying expectations',
    '  + Writing to Delta tables',
    '  [slow = check flow_progress events, data quality metrics]',
    '    |',
    '    v',
    'COMPLETED                    or                    FAILED',
    '  All flows succeeded                One or more flows failed',
    '  Metrics logged                     Check error events',
    '  Next update scheduled              Pipeline stops',
  ],
  trap:[
    '✗ State sequence: INITIALIZING -> SETTING_UP_TABLES -> RUNNING -> COMPLETED/FAILED',
    '✗ SETTING_UP_TABLES is BEFORE data processing — schema/permission issues here',
    '✗ Pipeline stuck in INITIALIZING = cluster-level issue — check cluster logs',
    '✗ FAILED state: always check error events in system.lakeflow.pipeline_events',
    '✗ Each pipeline run has unique update_id — filter all events by update',
    '✗ COMPLETED != data quality passed — can complete with dropped records from expect_or_drop',
  ],
},

// ─── 9.5.1 ───────────────────────────────────────────────────────────────────
{num:'13',title:'9.5.1 — MERGE vs INSERT, Overwrite Mode, Durable Checkpoint',
  what:[
    'Idempotent pipeline: produces same result whether run once or multiple times — no duplicates',
    'Three key patterns: MERGE (upsert), overwrite mode, checkpoint in durable storage',
    'Critical for production pipelines — re-runs after failures should not corrupt data',
  ],
  how:[
    'MERGE pattern: WHEN MATCHED THEN UPDATE, WHEN NOT MATCHED THEN INSERT — safe for re-runs',
    'Overwrite mode: df.write.mode("overwrite") — re-run replaces data, no accumulation',
    'Checkpoint in durable storage: streaming resume from last position — no re-processing',
    'INSERT (without MERGE): NOT idempotent — re-run duplicates all rows',
  ],
  facts:[
    'INSERT INTO without dedup = NOT idempotent — re-run creates duplicate rows',
    'MERGE INTO ... WHEN MATCHED UPDATE = idempotent — same key updated to same value',
    'mode("overwrite") = idempotent — re-run replaces previous output',
    'Checkpoint in /tmp/ = NOT durable — lost on restart, stream re-processes from beginning',
  ],
  ascii:true,
  code:[
    'IDEMPOTENCY PATTERNS:',
    '',
    'PATTERN 1: MERGE (safest for upsert)',
    '  Run 1: MERGE inserts order_id=1 -> table has 1 row',
    '  Run 2: MERGE finds order_id=1 exists -> UPDATES (no duplicate)',
    '  IDEMPOTENT',
    '',
    'PATTERN 2: Overwrite mode',
    '  Run 1: df.write.mode("overwrite").save("/output/") -> table has 100 rows',
    '  Run 2: df.write.mode("overwrite").save("/output/") -> table REPLACED with 100',
    '  IDEMPOTENT (previous run replaced, not appended)',
    '',
    'PATTERN 3: INSERT OVERWRITE',
    '  INSERT OVERWRITE PARTITION (date=\'2024-01-15\') ...',
    '  Replaces only the specified partition on re-run',
    '  IDEMPOTENT (partition-level replacement)',
    '',
    'PATTERN 4: Streaming with durable checkpoint',
    '  Checkpoint: s3://bucket/checkpoints/stream1/ — durable',
    '  Run 1: processes events 1-1000, checkpoint saved',
    '  Run 2 (after failure): reads checkpoint, resumes from event 1001',
    '  IDEMPOTENT (no re-processing)',
    '',
    'NON-IDEMPOTENT PATTERNS (AVOID):',
    '  INSERT INTO without dedup:',
    '    Run 1: inserts 100 rows',
    '    Run 2: inserts SAME 100 rows -> 200 rows (DUPLICATE!)',
    '',
    '  Checkpoint in /tmp/:',
    '    Run 1: processes events 1-1000, checkpoint in /tmp/',
    '    Cluster restarts: /tmp/ cleared!',
    '    Run 2: starts from beginning, re-processes events 1-1000',
  ],
  trap:[
    '✗ INSERT INTO without dedup is NOT idempotent — duplicates on re-run',
    '✗ MERGE is idempotent — same key always produces same result',
    '✗ Checkpoint in /tmp/ is NOT durable — lost on restart, stream re-processes',
    '✗ Checkpoint must be on: DBFS, S3, ADLS, GCS, or UC Volume — durable',
    '✗ mode("overwrite") is idempotent — re-run REPLACES previous output',
    '✗ Partition overwrite (INSERT OVERWRITE PARTITION) is idempotent at partition level',
  ],
},

// ─── 9.5.2 ───────────────────────────────────────────────────────────────────
{num:'14',title:'9.5.2 — batch_id for Idempotency in foreachBatch',
  what:[
    'batch_id: unique monotonically increasing integer provided to each foreachBatch call',
    'The idempotency key — used to detect and skip already-processed batches',
    'foreachBatch itself is at-least-once — same batch may be called multiple times on retry',
  ],
  how:[
    'foreachBatch(func): func signature is (batch_df: DataFrame, batch_id: int) -> None',
    'On retry: same batch_id passed again with same batch_df — idempotency check uses batch_id',
    'Idempotent pattern: check if batch_id already processed in a control table',
    'If batch_id already in control table: skip processing — return without applying',
  ],
  facts:[
    'batch_id is monotonically increasing — same value on retry of same micro-batch',
    'foreachBatch is at-least-once — batch may execute more than once',
    'Without batch_id check: retry causes duplicate data',
    'MERGE in foreachBatch: inherently idempotent — even without batch_id check',
  ],
  code:[
    'def idempotent_batch_processor(batch_df, batch_id):',
    '    """Idempotent foreachBatch using batch_id"""',
    '    # Step 1: Check if this batch_id was already processed',
    '    already_processed = (',
    '        spark.sql(f"""',
    '            SELECT COUNT(*) AS cnt',
    '            FROM catalog.schema.batch_control',
    '            WHERE batch_id = {batch_id} AND status = \'COMPLETED\'',
    '        """).collect()[0]["cnt"] > 0',
    '    )',
    '',
    '    if already_processed:',
    '        print(f"Batch {batch_id} already processed, skipping")',
    '        return  # Idempotent skip',
    '',
    '    try:',
    '        # Step 2: Apply the batch (MERGE is also idempotent)',
    '        batch_df.createOrReplaceTempView("current_batch")',
    '        spark.sql(f"""',
    '            MERGE INTO catalog.schema.orders t',
    '            USING current_batch s ON t.order_id = s.order_id',
    '            WHEN MATCHED THEN UPDATE SET *',
    '            WHEN NOT MATCHED THEN INSERT *',
    '        """)',
    '',
    '        # Step 3: Record successful processing',
    '        spark.sql(f"""',
    '            INSERT INTO catalog.schema.batch_control',
    '            VALUES ({batch_id}, \'COMPLETED\', current_timestamp())',
    '        """)',
    '',
    '    except Exception as e:',
    '        spark.sql(f"""',
    '            INSERT INTO catalog.schema.batch_control',
    '            VALUES ({batch_id}, \'FAILED\', current_timestamp())',
    '        """)',
    '        raise e',
    '',
    '(stream_df.writeStream',
    '    .foreachBatch(idempotent_batch_processor)',
    '    .option("checkpointLocation", "s3://bucket/checkpoints/orders_stream/")',
    '    .trigger(processingTime="1 minute")',
    '    .start())',
  ],
  trap:[
    '✗ foreachBatch is AT-LEAST-ONCE — same batch may execute multiple times',
    '✗ batch_id is the IDEMPOTENCY KEY — same value on retry',
    '✗ MERGE in foreachBatch is inherently idempotent — even without batch_id check',
    '✗ batch_id is monotonically increasing — NOT a random UUID',
    '✗ Without batch_id check + INSERT: retry = duplicate rows',
    '✗ Checkpoint + batch_id together = strong idempotency guarantee',
  ],
},

// ─── 9.5.3 ───────────────────────────────────────────────────────────────────
{num:'15',title:'9.5.3 — Streaming Checkpoint Storage Requirements',
  what:[
    'Streaming checkpoint: persistent storage of streaming query state',
    'Source offsets and operator state — required for resume on restart',
    'Storage location must be DURABLE — survives cluster restart',
  ],
  how:[
    'checkpointLocation option: path where checkpoint files are written',
    'Stored: source offsets (Kafka offset, file metadata, Delta version), operator state',
    'On restart: stream reads checkpoint and resumes from last processed position',
    'No checkpoint or non-durable: stream re-processes from beginning',
  ],
  facts:[
    'Durable storage: DBFS, S3, ADLS, GCS, UC Volumes — survives cluster restart',
    'Ephemeral storage: /tmp/, executor local disk — lost on restart, NOT acceptable',
    'Each streaming query needs UNIQUE checkpoint location — sharing corrupts both',
    'startingOffsets in Kafka IGNORED if checkpoint exists — checkpoint always wins',
  ],
  ascii:true,
  code:[
    'CHECKPOINT STORAGE RULES:',
    '',
    'DURABLE (acceptable):',
    '  /mnt/chk/orders_stream/                    — DBFS mount',
    '  s3://bucket/chk/orders_stream/              — S3 directly',
    '  abfss://container@acct.dfs.core.windows.net/chk/  — ADLS Gen2',
    '  gs://bucket/chk/orders_stream/              — GCS',
    '  /Volumes/catalog/schema/volume/chk/        — UC Volume',
    '',
    'EPHEMERAL (NOT acceptable):',
    '  /tmp/chk/                                  — driver local /tmp',
    '  /local_disk/chk/                           — executor local disk',
    '',
    'UNIQUE per query (required):',
    '  query_1 -> /mnt/chk/orders_stream/',
    '  query_2 -> /mnt/chk/payments_stream/        — separate directory',
    '',
    'SHARED checkpoint between queries -> CORRUPTS both',
    '',
    '# CORRECT pattern',
    '(stream_df.writeStream',
    '    .format("delta")',
    '    .outputMode("append")',
    '    .option("checkpointLocation", "s3://bucket/checkpoints/orders_stream/")',
    '    .trigger(processingTime="1 minute")',
    '    .start("/mnt/silver/orders/"))',
    '',
    '# WRONG: ephemeral checkpoint',
    '(stream_df.writeStream',
    '    .option("checkpointLocation", "/tmp/chk/")  # LOST ON RESTART!',
    '    .start("/mnt/silver/orders/"))',
  ],
  trap:[
    '✗ Checkpoint must be on durable storage — DBFS, S3, ADLS, GCS, or UC Volume',
    '✗ /tmp/ checkpoint LOST on restart — stream re-processes from beginning',
    '✗ Each streaming query needs UNIQUE checkpoint location — no sharing',
    '✗ startingOffsets IGNORED when checkpoint exists — checkpoint always wins',
    '✗ Deleting checkpoint = stream replays ALL source data from beginning',
    '✗ Checkpoint stores: source offsets + operator state — both required for correct resume',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain9_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
