'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 7  —  Ensuring Data Security & Compliance  —  18 Sub-Topics',
  groups: [
    ['7.1  Workspace Object Permissions',[
      ['01','7.1.1','Notebook Permissions: CAN READ, CAN RUN, CAN EDIT, CAN MANAGE'],
      ['02','7.1.2','Job Ownership: One Owner, Individuals Only, No Groups'],
      ['03','7.1.3','Control Plane vs Data Plane'],
    ]],
    ['7.2  Unity Catalog Permission Model',[
      ['04','7.2.1','USE CATALOG + USE SCHEMA + SELECT All Required'],
      ['05','7.2.2','GRANT, REVOKE — DENY Not Supported in UC'],
      ['06','7.2.3','All Privilege Types (USE CATALOG, MODIFY, etc.)'],
      ['07','7.2.4','Permission Inheritance: Catalog -> Schema -> Table'],
    ]],
    ['7.3  Row Filters and Column Masks',[
      ['08','7.3.1','Row Filters: CREATE FUNCTION + ALTER TABLE SET ROW FILTER'],
      ['09','7.3.2','Column Masks: CREATE FUNCTION + ALTER TABLE ALTER COLUMN SET MASK'],
      ['10','7.3.3','Dynamic Views: current_user(), is_member() — Legacy Approach'],
    ]],
    ['7.4  Anonymization and Pseudonymization',[
      ['11','7.4.1','Hashing, Tokenization, Suppression, Generalisation — Comparison'],
      ['12','7.4.2','PII Masking in Batch and Streaming Pipelines'],
    ]],
    ['7.5  Secrets Management',[
      ['13','7.5.1','Databricks-Backed vs AKV-Backed Scopes'],
      ['14','7.5.2','READ/WRITE/MANAGE Permissions on Scopes'],
      ['15','7.5.3','REDACTED Behavior Confirmed'],
    ]],
    ['7.6  Compliance: GDPR, PII, Data Retention',[
      ['16','7.6.1','GDPR Right to Erasure: DELETE + VACUUM Sequence'],
      ['17','7.6.2','PII Masking Patterns (Batch and Streaming)'],
      ['18','7.6.3','Data Retention Configuration on Delta Tables'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 7  —  Ensuring Data Security & Compliance  —  All High-Priority Traps',
};

const pages = [

// ─── 7.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'7.1.1 — Notebook Permissions: CAN READ, CAN RUN, CAN EDIT, CAN MANAGE',
  what:[
    'Notebook permissions: four access levels controlling what users can do with a Databricks notebook',
    'Set per-notebook, per-user or per-group in the notebook sharing dialog or via Permissions API',
    'Four levels from lowest to highest: CAN READ, CAN RUN, CAN EDIT, CAN MANAGE',
  ],
  how:[
    'CAN READ: view the notebook content and results — read-only, cannot execute any cells',
    'CAN RUN: run the notebook (execute cells) — cannot edit the code',
    'CAN EDIT: run AND edit notebook code — cannot change permissions or delete notebook',
    'CAN MANAGE: full control — edit, run, share, change permissions, delete the notebook',
    'Permissions are additive and hierarchical — higher includes all lower capabilities',
  ],
  facts:[
    'Notebook creator automatically has CAN MANAGE — cannot be removed from creator',
    'Workspace admins can access all notebooks regardless of explicit permissions',
    'CAN RUN without CAN READ is unusual — useful for parameterized notebooks',
    'Permission inheritance: folder-level permissions cascade to notebooks inside the folder',
  ],
  ascii:true,
  code:[
    'NOTEBOOK PERMISSION HIERARCHY (lowest -> highest):',
    '',
    'CAN READ      View notebook content and cell outputs (read-only)',
    '    |',
    'CAN RUN       Execute notebook cells (but cannot edit code)',
    '    |',
    'CAN EDIT      Edit notebook code + run cells',
    '    |',
    'CAN MANAGE    Full control: edit, run, share, change permissions, delete',
    '',
    'KEY EXAM DISTINCTIONS:',
    '  CAN READ  -> Can SEE the code but CANNOT execute it',
    '  CAN RUN   -> Can EXECUTE but CANNOT modify the code',
    '  CAN EDIT  -> Can MODIFY and EXECUTE — but CANNOT change permissions',
    '  CAN MANAGE -> Everything including changing who has what permission',
    '',
    'COMMON EXAM SCENARIOS:',
    '  "Run scheduled notebook without seeing code"  -> CAN RUN',
    '  "Modify notebook but not share it"            -> CAN EDIT',
    '  "Full control of the notebook"                -> CAN MANAGE',
  ],
  mistakes:[
    '✗ Confusing CAN RUN with CAN EDIT — CAN RUN executes only, CAN EDIT also modifies',
    '✗ Assuming CAN EDIT allows changing permissions — only CAN MANAGE can',
    '✗ Forgetting notebook creator always has CAN MANAGE — cannot be revoked',
  ],
  trap:[
    '✗ CAN RUN != CAN EDIT — CAN RUN executes, CAN EDIT modifies code — different levels',
    '✗ CAN EDIT does NOT allow changing permissions — only CAN MANAGE can',
    '✗ CAN READ allows VIEWING code but NOT executing — opposite of what some expect',
    '✗ Notebook creator always has CAN MANAGE — non-revocable by anyone including admins',
    '✗ Workspace admin bypasses notebook permissions — can access any notebook',
    '✗ Permission hierarchy: each level INCLUDES all capabilities of lower levels',
    '✗ Folder permissions cascade to child notebooks',
  ],
},

// ─── 7.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'7.1.2 — Job Ownership: One Owner, Individuals Only, No Groups',
  what:[
    'Job ownership: every Databricks job has exactly ONE owner — execution identity and notification target',
    'Groups CANNOT be job owners — only individual user accounts or service principals',
    'Job runs UNDER the owner identity — owner losing access = job loses data access',
  ],
  how:[
    'Default owner: the user who created the job via UI or API',
    'Job execution: uses the owner identity for Unity Catalog data access and cluster permissions',
    'Transfer ownership: via UI (job settings -> Owner field) or API (PUT /api/2.1/jobs/update)',
    'Service principal as owner: recommended for production — avoids dependency on individual humans',
  ],
  facts:[
    'Groups CANNOT be job owners — only individual users or service principals',
    'Job ownership != job permissions — CAN_MANAGE_RUN allows running; ownership determines identity',
    'Owner deactivated: job fails on next run because execution identity no longer has access',
    'Production best practice: transfer ownership to a service principal before user leaves',
  ],
  ascii:true,
  code:[
    'JOB OWNERSHIP RULES:',
    '',
    'ALLOWED owners:',
    '  Individual user:       alice@company.com',
    '  Service principal:     my-etl-service-principal  <- recommended for prod',
    '  Group:                 data-engineering-team      <- NOT allowed',
    '  Multiple owners:       (NOT supported — exactly one)',
    '',
    'IMPACT OF OWNERSHIP:',
    '  Job run executes AS the owner identity',
    '  Owner UC permissions determine what data is accessible',
    '  Owner cluster permissions determine which clusters can be used',
    '',
    '  Alice owns job -> job accesses data Alice can access',
    '  SP owns job -> job accesses data SP can access (more stable)',
    '',
    'TRANSFER OWNERSHIP:',
    '  Via UI: Job settings -> Owner field -> type new owner email',
    '  Via API:',
    '    PUT /api/2.1/jobs/update',
    '    {"job_id": 123, "new_settings": {"owner": "newowner@company.com"}}',
    '',
    'EXAM SCENARIO:',
    '  "Alice owns a job. Alice leaves and her account is deactivated."',
    '  -> Job runs FAIL on next execution',
    '  -> Fix: transfer ownership to service principal BEFORE deactivating Alice',
  ],
  mistakes:[
    '✗ Assigning a group as job owner — groups cannot be owners',
    '✗ Leaving production jobs owned by individual users — single point of failure',
    '✗ Confusing CAN_MANAGE permission with ownership — different concepts',
  ],
  trap:[
    '✗ Groups CANNOT be job owners — only individual users or service principals',
    '✗ Job runs AS the owner identity — owner losing access = job data access fails',
    '✗ CAN_MANAGE_RUN permission != job ownership — different concepts',
    '✗ Service principal ownership recommended for production — not tied to humans',
    '✗ Ownership transfer requires the current owner OR a workspace admin',
    '✗ One owner only — no joint ownership, no group ownership',
  ],
},

// ─── 7.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'7.1.3 — Control Plane vs Data Plane',
  what:[
    'Control plane: Databricks-managed infrastructure — UI, APIs, job scheduling, metadata',
    'Data plane: customer-managed infrastructure — where compute runs and where data lives',
    'Security boundary: data plane in customer cloud account; control plane in Databricks cloud',
  ],
  how:[
    'Control plane (Databricks account): workspace UI, REST APIs, scheduler, MLflow, UC metastore metadata',
    'Data plane (customer cloud account): EC2/VMs running Spark executors, S3/ADLS/GCS storing data',
    'Communication: control plane sends instructions to data plane; metrics return',
    'Customer data NEVER passes through the control plane — only metadata and logs',
  ],
  facts:[
    'Customer data lives in the data plane (customer cloud account) — not in Databricks control plane',
    'Cluster VMs (executors) run in the data plane — customer cloud account',
    'DBFS root storage is in customer cloud account — data plane, not control plane',
    'Serverless SQL Warehouse: runs in Databricks-managed data plane — different from classic',
    'Unity Catalog metastore: control plane (Databricks) — data referenced stays in data plane',
  ],
  ascii:true,
  code:[
    'DATABRICKS ARCHITECTURE:',
    '',
    'CONTROL PLANE (Databricks managed):',
    '  Workspace UI (web interface)',
    '  REST APIs (jobs, clusters, permissions)',
    '  Job Scheduler (triggers, retries, notifications)',
    '  Cluster Manager (creates/destroys VMs via cloud API)',
    '  UC Metastore (table definitions, permissions — metadata only)',
    '  MLflow Tracking Server (metrics, params — metadata only)',
    '        |',
    '        | Cluster start/stop commands',
    '        | Heartbeats and metrics',
    '        v',
    'DATA PLANE (Customer managed):',
    '  Cluster VMs (EC2/Azure VMs running Spark executors)',
    '  Cloud Object Storage (S3/ADLS/GCS — where data lives)',
    '  Customer VPC/VNet (network isolation)',
    '  DBFS Root (backed by customer cloud storage bucket)',
    '',
    'DATA FLOW:',
    '  Customer data: stays in DATA PLANE (never in control plane)',
    '  Commands: control plane -> data plane',
    '  Metrics/logs: data plane -> control plane (no raw data)',
    '',
    'SERVERLESS EXCEPTION:',
    '  Serverless SQL Warehouse: runs in DATABRICKS-managed data plane',
    '  Not in customer VPC — different security model than classic',
  ],
  trap:[
    '✗ Customer data NEVER passes through control plane — only metadata, logs, commands',
    '✗ Cluster VMs run in customer data plane — not Databricks infrastructure (classic)',
    '✗ Serverless SQL Warehouse runs in Databricks-managed data plane — not customer VPC',
    '✗ UC metastore stores METADATA in control plane — actual table DATA in customer data plane',
    '✗ Control plane: Databricks manages; Data plane: customer manages (classic)',
    '✗ DBFS root is in customer cloud storage (data plane) — Databricks provides abstraction',
  ],
},

// ─── 7.2.1 ───────────────────────────────────────────────────────────────────
{num:'04',title:'7.2.1 — USE CATALOG + USE SCHEMA + SELECT All Required',
  what:[
    'Unity Catalog uses a hierarchical permission model — access requires permissions at ALL three levels',
    'To read a table: USE CATALOG on catalog AND USE SCHEMA on schema AND SELECT on table',
    'Missing any ONE of these three causes access denied',
  ],
  how:[
    'USE CATALOG: grants ability to navigate/use the catalog — required for any catalog object access',
    'USE SCHEMA: grants ability to navigate/use the schema — required for any schema object access',
    'SELECT: grants ability to read data from a specific table, view, or materialized view',
    'All three must be granted on the appropriate level — no automatic cascade',
  ],
  facts:[
    'Three-level requirement: USE CATALOG + USE SCHEMA + SELECT — all three mandatory',
    'USE CATALOG alone: user can see the catalog exists but cannot access tables inside',
    'SELECT alone (without USE privileges): AnalysisException — SCHEMA_NOT_FOUND or CATALOG_NOT_FOUND',
    'ALL PRIVILEGES on catalog: includes USE CATALOG, USE SCHEMA on contained schemas',
  ],
  code:[
    '-- Grant MINIMUM required to read a table',
    'GRANT USE CATALOG ON CATALOG prod_catalog TO analyst_group;',
    'GRANT USE SCHEMA  ON SCHEMA  prod_catalog.sales_schema TO analyst_group;',
    'GRANT SELECT      ON TABLE   prod_catalog.sales_schema.orders TO analyst_group;',
    '',
    '-- Without USE CATALOG: error even if SELECT is granted',
    'GRANT SELECT ON TABLE prod_catalog.sales.orders TO analyst;',
    '-- analyst runs: SELECT * FROM prod_catalog.sales.orders',
    '-- ERROR: CATALOG_NOT_FOUND or insufficient privileges',
    '',
    '-- Grant schema-level access (USE + SELECT on all current tables)',
    'GRANT USE CATALOG ON CATALOG prod_catalog TO analyst_group;',
    'GRANT USE SCHEMA  ON SCHEMA  prod_catalog.sales_schema TO analyst_group;',
    'GRANT SELECT      ON SCHEMA  prod_catalog.sales_schema TO analyst_group;',
    '',
    '-- Verify grants',
    'SHOW GRANTS ON TABLE prod_catalog.sales_schema.orders;',
    'SHOW GRANTS ON SCHEMA prod_catalog.sales_schema;',
    'SHOW GRANTS ON CATALOG prod_catalog;',
  ],
  trap:[
    '✗ THREE grants required to read a table: USE CATALOG + USE SCHEMA + SELECT — ALL three',
    '✗ Missing any single grant causes access denied',
    '✗ SELECT on table WITHOUT USE CATALOG -> CATALOG_NOT_FOUND error — not permission error',
    '✗ USE CATALOG alone != access to tables — just ability to "see" the catalog exists',
    '✗ Granting on SCHEMA level SELECT applies to ALL current tables — new tables NOT included',
    '✗ ALL PRIVILEGES includes everything: USE CATALOG, USE SCHEMA, SELECT, MODIFY, CREATE TABLE',
    '✗ DENY does NOT exist in Unity Catalog — use REVOKE to remove permissions',
  ],
},

// ─── 7.2.2 ───────────────────────────────────────────────────────────────────
{num:'05',title:'7.2.2 — GRANT, REVOKE — DENY Not Supported in UC',
  what:[
    'Unity Catalog uses GRANT to add permissions and REVOKE to remove them — no DENY command exists',
    'DENY is a concept from traditional databases and legacy Hive metastore — does NOT exist in UC',
    'To prevent access: use REVOKE to remove previously granted privileges',
  ],
  how:[
    'GRANT privilege ON object TO principal: adds permission',
    'REVOKE privilege ON object FROM principal: removes permission',
    'No DENY: cannot explicitly deny access — if not granted, access is denied by default',
    'Default behavior: all access denied unless explicitly granted — no need for explicit DENY',
  ],
  facts:[
    'UC uses allow-list model: no explicit DENY, access denied by default unless GRANT exists',
    'REVOKE removes a specific GRANT — if other grants exist, access may still work',
    'REVOKE ALL PRIVILEGES: removes all grants for a principal on an object',
    'Legacy Hive metastore had DENY — UC does NOT have DENY — key exam distinction',
  ],
  code:[
    '-- GRANT — add permissions',
    'GRANT SELECT ON TABLE prod_catalog.sales.orders TO analyst_role;',
    'GRANT USE CATALOG ON CATALOG prod_catalog TO data_team;',
    'GRANT ALL PRIVILEGES ON SCHEMA prod_catalog.sales TO data_engineers;',
    '',
    '-- REVOKE — remove permissions',
    'REVOKE SELECT ON TABLE prod_catalog.sales.orders FROM analyst_role;',
    'REVOKE USE CATALOG ON CATALOG prod_catalog FROM data_team;',
    '',
    '-- DENY — DOES NOT EXIST IN UC',
    '-- DENY SELECT ON TABLE prod_catalog.sales.pii_table TO analyst_role;',
    '-- SyntaxError: DENY is not supported in Unity Catalog',
    '',
    '-- CORRECT approach to restrict access:',
    'REVOKE SELECT ON TABLE prod_catalog.sales.pii_table FROM analyst_role;',
    '',
    '-- Show current grants',
    'SHOW GRANTS ON TABLE prod_catalog.sales.orders;',
    '',
    '-- Revoke all privileges',
    'REVOKE ALL PRIVILEGES ON TABLE prod_catalog.sales.orders FROM analyst_role;',
  ],
  trap:[
    '✗ DENY does NOT exist in Unity Catalog — SyntaxError if attempted',
    '✗ UC uses ALLOW-LIST model: all access denied by default unless GRANT exists',
    '✗ REVOKE removes a grant — does NOT add a deny, just removes the allow',
    '✗ Legacy Hive metastore had DENY; UC does NOT — key distinction',
    '✗ No need for explicit DENY in UC — if not granted, denied by default',
    '✗ SHOW GRANTS shows active grants only — no "deny list" exists to show',
  ],
},

// ─── 7.2.3 ───────────────────────────────────────────────────────────────────
{num:'06',title:'7.2.3 — All Privilege Types (USE CATALOG, MODIFY, CREATE TABLE, etc.)',
  what:[
    'Unity Catalog defines specific privilege types for each securable object level',
    'Knowing which privilege applies to which object type is essential',
  ],
  facts:[
    'USE CATALOG: at Catalog level — navigate the catalog (required for any access)',
    'CREATE SCHEMA: at Catalog level — create new schemas',
    'USE SCHEMA: at Schema level — navigate the schema',
    'CREATE TABLE: at Schema level — create new tables',
    'CREATE VIEW: at Schema level — create new views',
    'CREATE FUNCTION: at Schema level — create UDFs',
    'CREATE VOLUME: at Schema level — create volumes',
    'SELECT: at Table/View/MV — read data',
    'MODIFY: at Table — INSERT, UPDATE, DELETE, MERGE',
    'READ VOLUME: at Volume — read files',
    'WRITE VOLUME: at Volume — write/delete files',
    'EXECUTE: at Function — execute UC function/UDF',
    'ALL PRIVILEGES: at any level — all applicable privileges',
  ],
  code:[
    '-- Read-only analyst',
    'GRANT USE CATALOG ON CATALOG prod TO analysts;',
    'GRANT USE SCHEMA  ON SCHEMA  prod.sales TO analysts;',
    'GRANT SELECT      ON TABLE   prod.sales.orders TO analysts;',
    '',
    '-- Read-write engineer',
    'GRANT USE CATALOG ON CATALOG prod TO engineers;',
    'GRANT USE SCHEMA  ON SCHEMA  prod.sales TO engineers;',
    'GRANT SELECT, MODIFY ON TABLE prod.sales.orders TO engineers;',
    '',
    '-- Schema owner (can create and manage all objects)',
    'GRANT USE CATALOG ON CATALOG prod TO schema_owners;',
    'GRANT ALL PRIVILEGES ON SCHEMA prod.sales TO schema_owners;',
    '',
    '-- Volume access',
    'GRANT READ VOLUME  ON VOLUME prod.raw.landing TO ingest_user;',
    'GRANT WRITE VOLUME ON VOLUME prod.raw.landing TO ingest_service;',
    '',
    '-- Function execution',
    'GRANT EXECUTE ON FUNCTION prod.utils.clean_name TO analysts;',
  ],
  trap:[
    '✗ MODIFY = INSERT + UPDATE + DELETE + MERGE on a table — not just UPDATE',
    '✗ SELECT alone does NOT allow any writes — need MODIFY for any DML',
    '✗ USE CATALOG + USE SCHEMA required for EVERY access — even with SELECT/MODIFY',
    '✗ CREATE TABLE is at SCHEMA level — not catalog level',
    '✗ ALL PRIVILEGES grants everything applicable to that object type',
    '✗ READ VOLUME and WRITE VOLUME are VOLUME-specific — not the same as SELECT/MODIFY',
  ],
},

// ─── 7.2.4 ───────────────────────────────────────────────────────────────────
{num:'07',title:'7.2.4 — Permission Inheritance: Catalog -> Schema -> Table',
  what:[
    'UC has a hierarchical object model — permissions can be granted at catalog, schema, or table level',
    'Inheritance: permissions granted at higher level apply to all current objects within',
    'Cascade applies to CURRENT objects only — new objects later are NOT automatically included',
  ],
  facts:[
    'Grant SELECT on CATALOG: applies to ALL schemas AND all tables currently in catalog',
    'Grant SELECT on SCHEMA: applies to ALL tables currently in that schema',
    'Grant SELECT on TABLE: applies to only that specific table',
    'Future objects: grants on existing catalog/schema do NOT extend to NEW tables created later',
  ],
  ascii:true,
  code:[
    'PERMISSION INHERITANCE:',
    '',
    'GRANT SELECT ON CATALOG prod TO analyst_group:',
    '  prod_catalog <- SELECT granted here',
    '  +-- sales_schema',
    '  |   +-- orders_table         -> SELECT inherited',
    '  |   +-- customers_table      -> SELECT inherited',
    '  |   +-- NEW TABLE (future)   -> SELECT NOT automatically inherited',
    '  +-- finance_schema',
    '      +-- revenue_table        -> SELECT inherited',
    '',
    'GRANT SELECT ON SCHEMA prod.sales TO analyst_group:',
    '  prod_catalog',
    '  +-- sales_schema <- SELECT granted here',
    '  |   +-- orders_table    -> SELECT inherited',
    '  |   +-- customers_table -> SELECT inherited',
    '  |   +-- NEW TABLE       -> SELECT NOT automatically inherited',
    '  +-- finance_schema',
    '      +-- revenue_table   -> SELECT NOT inherited (different schema)',
    '',
    'KEY POINT: Inheritance applies to CURRENT objects at time of grant',
    '           NEW objects created after the grant are NOT automatically covered',
  ],
  trap:[
    '✗ Inheritance applies to CURRENT objects only — NEW tables added AFTER grant NOT covered',
    '✗ Grant on schema SELECT: covers all current tables — not tables created later',
    '✗ USE CATALOG and USE SCHEMA still required even if SELECT inherited',
    '✗ Grant at catalog level does NOT automatically give USE SCHEMA on all schemas',
    '✗ Permission inheritance goes DOWN (catalog -> schema -> table) — not upward',
    '✗ To cover future tables: re-run GRANT, or use dynamic access control',
  ],
},

// ─── 7.3.1 ───────────────────────────────────────────────────────────────────
{num:'08',title:'7.3.1 — Row Filters: CREATE FUNCTION + ALTER TABLE SET ROW FILTER',
  what:[
    'Row filter: a UC function applied to a table that transparently restricts which rows users see',
    'Two steps: (1) create a filter function, (2) bind it to a table with ALTER TABLE SET ROW FILTER',
    'Users see only rows where the filter function returns TRUE',
  ],
  how:[
    'Create filter function: CREATE FUNCTION returning BOOLEAN — uses CURRENT_USER() or IS_ACCOUNT_GROUP_MEMBER()',
    'Bind to table: ALTER TABLE t SET ROW FILTER catalog.schema.fn ON (col)',
    'Filter function receives the column value(s) for each row — returns TRUE to show, FALSE to hide',
    'Admins typically granted IS_ACCOUNT_GROUP_MEMBER(\'admin_group\') path to see all rows',
  ],
  facts:[
    'Row filters require Unity Catalog — NOT supported in hive_metastore',
    'Row filter function: must return BOOLEAN, must accept column values as parameters',
    'IS_ACCOUNT_GROUP_MEMBER() checks UC account-level groups; IS_MEMBER() checks workspace groups',
    'Row filters enforced at query time — cannot be bypassed by any SQL technique',
  ],
  code:[
    '-- Step 1: Create row filter function',
    'CREATE OR REPLACE FUNCTION prod_catalog.security.region_filter(region STRING)',
    'RETURNS BOOLEAN',
    'RETURN IS_ACCOUNT_GROUP_MEMBER(\'admin\')',
    '    OR CURRENT_USER() LIKE \'%@\' || region || \'.company.com\'',
    '    OR IS_ACCOUNT_GROUP_MEMBER(region || \'_team\');',
    '',
    '-- Step 2: Bind row filter to table',
    'ALTER TABLE prod_catalog.sales.orders',
    'SET ROW FILTER prod_catalog.security.region_filter ON (region_col);',
    '',
    '-- Verify row filter is applied',
    'DESCRIBE TABLE EXTENDED prod_catalog.sales.orders;',
    '',
    '-- Test: different users see different rows',
    '-- admin@company.com -> sees ALL rows',
    '-- alice@us.company.com -> sees only rows where region_col = \'us\'',
    '',
    '-- Remove row filter',
    'ALTER TABLE prod_catalog.sales.orders',
    'DROP ROW FILTER;',
  ],
  trap:[
    '✗ Row filters require Unity Catalog — hive_metastore tables CANNOT have row filters',
    '✗ IS_ACCOUNT_GROUP_MEMBER() checks UC account groups; IS_MEMBER() checks WORKSPACE groups',
    '✗ Row filter blocks even admins if function logic excludes them — test carefully',
    '✗ Row filters TRANSPARENT to users — cannot see the filter, only filtered results',
    '✗ Row filters applied at QUERY TIME — cannot be bypassed with SQL tricks',
    '✗ Row filter function MUST return BOOLEAN — wrong return type causes error',
    '✗ ALTER TABLE SET ROW FILTER — exact syntax matters',
  ],
},

// ─── 7.3.2 ───────────────────────────────────────────────────────────────────
{num:'09',title:'7.3.2 — Column Masks: CREATE FUNCTION + ALTER TABLE ALTER COLUMN SET MASK',
  what:[
    'Column mask: UC function that transforms sensitive column values before returning to unauthorized users',
    'Admins/privileged users see real values; others see masked/redacted values',
    'Implemented as: (1) create mask function, (2) bind to specific column with ALTER TABLE ALTER COLUMN SET MASK',
  ],
  how:[
    'Mask function: takes the column value as input, returns either real or masked version',
    'For authorized users: return the original column value unchanged',
    'For unauthorized users: return masked value — NULL, redacted string, hash, partial value',
    'Masking applied at QUERY TIME — transparent to all users',
  ],
  facts:[
    'Column masks require Unity Catalog — NOT supported in hive_metastore',
    'Mask function must return SAME data type as the masked column — type mismatch = error',
    'Masking applies AT QUERY TIME only — data at rest in Parquet files is UNMASKED',
    'ALTER TABLE ... ALTER COLUMN ... SET MASK — note the ALTER COLUMN syntax',
  ],
  code:[
    '-- Step 1: Create column mask function for SSN',
    'CREATE OR REPLACE FUNCTION prod_catalog.security.ssn_mask(ssn STRING)',
    'RETURNS STRING',
    'RETURN CASE',
    '    WHEN IS_ACCOUNT_GROUP_MEMBER(\'hr_team\') THEN ssn',
    '    WHEN IS_ACCOUNT_GROUP_MEMBER(\'audit_team\') THEN',
    '        CONCAT(\'***-**-\', RIGHT(ssn, 4))',
    '    ELSE \'***-**-****\'',
    'END;',
    '',
    '-- Step 2: Apply mask to column',
    'ALTER TABLE prod_catalog.hr.employees',
    'ALTER COLUMN ssn',
    'SET MASK prod_catalog.security.ssn_mask;',
    '',
    '-- Test: different users see different values',
    '-- hr_user (HR team):    123-45-6789  <- full value',
    '-- auditor (audit_team): ***-**-6789  <- last 4 digits',
    '-- analyst (no group):   ***-**-****  <- fully masked',
    '',
    '-- Remove mask',
    'ALTER TABLE prod_catalog.hr.employees',
    'ALTER COLUMN ssn',
    'DROP MASK;',
  ],
  trap:[
    '✗ Column masks require Unity Catalog — hive_metastore does NOT support',
    '✗ Mask function MUST return SAME data type as the masked column',
    '✗ Masking is QUERY-TIME only — data at rest in Parquet is unmasked',
    '✗ ALTER TABLE ... ALTER COLUMN ... SET MASK — ALTER COLUMN syntax',
    '✗ Masking does NOT protect data in: DBFS exports, direct Parquet reads',
    '✗ IS_ACCOUNT_GROUP_MEMBER() for UC groups; IS_MEMBER() for workspace groups',
  ],
},

// ─── 7.3.3 ───────────────────────────────────────────────────────────────────
{num:'10',title:'7.3.3 — Dynamic Views: current_user(), is_member() — Legacy Approach',
  what:[
    'Dynamic view: SQL view that returns different data based on current user identity',
    'Legacy approach to row/column security — predates UC row filters and column masks',
    'Implemented at the VIEW level — underlying table access still needs to be controlled separately',
  ],
  how:[
    'current_user(): returns email of currently executing user — varies per caller',
    'is_member("group_name"): returns TRUE if current user is member of workspace group',
    'View definition uses IF/CASE with these functions to conditionally show/hide rows or columns',
    'Security enforcement: REVOKE direct table access, GRANT SELECT only on the view',
  ],
  facts:[
    'Dynamic views use is_member() which checks WORKSPACE groups — NOT UC account groups',
    'Dynamic views are the LEGACY approach — UC row filters/masks are MODERN',
    'Must REVOKE direct table access — otherwise users bypass the view',
    'Dynamic views work on hive_metastore tables — unlike UC row filters/masks (UC-only)',
  ],
  code:[
    '-- Dynamic view with row and column filtering (legacy)',
    'CREATE OR REPLACE VIEW prod_catalog.sales.secure_customers AS',
    'SELECT',
    '    customer_id,',
    '    -- Column masking via CASE WHEN',
    '    CASE',
    '        WHEN is_member(\'hr_admin\') THEN ssn',
    '        ELSE \'***-**-****\'',
    '    END AS ssn,',
    '    CASE',
    '        WHEN is_member(\'marketing\') OR is_member(\'hr_admin\') THEN email',
    '        ELSE CONCAT(LEFT(email, 2), \'***@***.***\')',
    '    END AS email,',
    '    name, region, created_at',
    'FROM prod_catalog.sales.customers_raw',
    'WHERE region = current_user()',
    '   OR is_member(\'hr_admin\')',
    '   OR is_member(\'data_engineering\');',
    '',
    '-- Security: revoke direct table access, grant only view',
    'REVOKE SELECT ON TABLE prod_catalog.sales.customers_raw FROM analysts;',
    'GRANT  SELECT ON VIEW  prod_catalog.sales.secure_customers TO analysts;',
  ],
  trap:[
    '✗ Must REVOKE base table access — otherwise users bypass the view',
    '✗ is_member() checks WORKSPACE groups — NOT UC account-level groups',
    '✗ Dynamic views are LEGACY — UC row filters and column masks are PREFERRED',
    '✗ Dynamic views work on hive_metastore — UC row filters/masks do NOT work on hive_metastore',
    '✗ current_user() returns different values per caller — view dynamically filtered',
    '✗ Dynamic view does NOT prevent direct Parquet file access',
  ],
},

// ─── 7.4.1 ───────────────────────────────────────────────────────────────────
{num:'11',title:'7.4.1 — Hashing, Tokenization, Suppression, Generalisation — Comparison',
  what:[
    'Four techniques for protecting PII in data pipelines',
    'Each provides different levels of protection, reversibility, and utility',
    'Choosing the right technique depends on: use case, regulatory requirements, re-identification needs',
  ],
  facts:[
    'Hashing: Apply cryptographic hash (SHA-256, MD5) — one-way, joins possible (same hash for same input)',
    'Tokenization: Replace PII with opaque token, store mapping in vault — reversible with vault, joins possible',
    'Suppression: Remove the column entirely or replace with NULL — not reversible, no joins',
    'Generalisation: Replace specific value with range/category — not reversible, loses precision',
  ],
  code:[
    '# HASHING: SHA-256 of email — consistent pseudonym, supports joins',
    'df.withColumn("email_hash", sha2(col("email"), 256))',
    '# "alice@company.com" -> "a665a45920422f9d..." (deterministic, one-way)',
    '',
    '# HASHING with salt — prevents rainbow table attacks',
    'salt = "my_secret_salt"',
    'df.withColumn("email_hash", sha2(concat(col("email"), lit(salt)), 256))',
    '',
    '# SUPPRESSION: remove SSN entirely',
    'df.drop("ssn")',
    '# or replace with NULL',
    'df.withColumn("ssn", lit(None).cast("string"))',
    '',
    '# GENERALISATION: age -> age band',
    'df.withColumn("age_band",',
    '    when(col("age") < 20, "under_20")',
    '    .when(col("age") < 30, "20-29")',
    '    .when(col("age") < 40, "30-39")',
    '    .otherwise("40+"))',
    '',
    '# TRUNCATION: postcode -> area code only',
    'df.withColumn("postcode_area", col("postcode").substr(1, 3))',
  ],
  trap:[
    '✗ Hashing is ONE-WAY — cannot reverse a hash to get original value',
    '✗ Hashing IS consistent — same input always produces same hash — supports joins',
    '✗ Tokenization IS reversible — with vault access, original can be retrieved',
    '✗ Suppression removes data ENTIRELY — not reversible, no joins possible',
    '✗ Generalisation loses precision — age 25 -> "20-29" cannot be reversed',
    '✗ Hashing without salt: same email in two tables -> same hash -> correlation',
    '✗ For GDPR right to erasure: suppression > hashing — deleted data cannot be requested',
  ],
},

// ─── 7.4.2 ───────────────────────────────────────────────────────────────────
{num:'12',title:'7.4.2 — PII Masking in Batch and Streaming Pipelines',
  what:[
    'PII masking: applying anonymization/pseudonymization techniques within data pipeline code',
    'Batch masking: applied during ETL transformation (Bronze -> Silver)',
    'Streaming masking: applied within streaming micro-batch transforms before writing to Silver/Gold',
  ],
  how:[
    'Bronze layer: stores raw PII data — access restricted to data engineers only',
    'Silver layer: PII masked using hashing, suppression, or generalisation — accessible to analysts',
    'Gold layer: aggregated data, no PII — accessible to all authorized business users',
    'Streaming: masking applied in withColumn() transforms within foreachBatch or writeStream',
  ],
  facts:[
    'Bronze must be restricted: only data engineers access raw PII — never analysts',
    'Silver masking: applied via transformations, not via UC row filters (that is access control)',
    'GDPR compliance: masked data still covered by GDPR if reversible',
    'Streaming PII masking: apply transforms in micro-batch BEFORE writing to Delta Silver',
  ],
  code:[
    'SALT = dbutils.secrets.get("scope", "pii_salt")  # salt from secrets, never in code',
    '',
    '# BATCH PII masking (Bronze -> Silver transformation)',
    'bronze_df = spark.read.table("catalog.bronze.customers_raw")',
    '',
    'silver_df = (bronze_df',
    '    # Hash email with salt (consistent pseudonym for joins)',
    '    .withColumn("email_hash",',
    '        sha2(concat(col("email"), lit(SALT)), 256))',
    '    # Suppress SSN entirely',
    '    .drop("ssn")',
    '    .drop("credit_card_number")',
    '    # Generalise date of birth to age band',
    '    .withColumn("age_band",',
    '        when((2024 - col("birth_year")) < 25, "18-24")',
    '        .when((2024 - col("birth_year")) < 35, "25-34")',
    '        .otherwise("35+"))',
    '    # Truncate postcode to area',
    '    .withColumn("postcode_area", col("postcode").substr(1, 3))',
    '    # Remove original PII columns',
    '    .drop("email", "full_name", "postcode", "birth_year")',
    ')',
    '',
    '# STREAMING PII masking',
    'def mask_pii_batch(batch_df, batch_id):',
    '    masked = (batch_df',
    '        .withColumn("email_hash", sha2(concat(col("email"), lit(SALT)), 256))',
    '        .drop("email", "ssn", "phone_number"))',
    '    masked.write.format("delta").mode("append") \\',
    '        .saveAsTable("catalog.silver.events_masked")',
    '',
    '(spark.readStream',
    '    .table("catalog.bronze.events_raw")',
    '    .writeStream',
    '    .foreachBatch(mask_pii_batch)',
    '    .option("checkpointLocation", "/chk/events_masking/")',
    '    .start())',
  ],
  trap:[
    '✗ Bronze stores RAW PII — access must be restricted to data engineers ONLY',
    '✗ Silver is where PII should be MASKED — first layer accessible to analysts',
    '✗ Gold should have ZERO PII — aggregated only',
    '✗ Salt for hashing must come from secrets — NEVER hardcode salt in code',
    '✗ Masked data may still be subject to GDPR if reversible (tokenization)',
    '✗ Streaming masking: apply in foreachBatch transform BEFORE writing — not after',
  ],
},

// ─── 7.5.1 ───────────────────────────────────────────────────────────────────
{num:'13',title:'7.5.1 — Databricks-Backed vs AKV-Backed Scopes',
  what:[
    'Secret scope: a named collection of secrets in Databricks — accessed via dbutils.secrets.get()',
    'Two types: Databricks-backed (stored in Databricks) and Azure Key Vault-backed (read from AKV)',
    'Both types: accessed identically via dbutils.secrets.get(scope, key) — same API, different backend',
  ],
  how:[
    'Databricks-backed: secrets created and managed via Databricks CLI or REST API',
    'AKV-backed: scope references an Azure Key Vault — Databricks reads at runtime via managed identity or SP',
    'AKV-backed: rotation in AKV is immediately visible — no sync needed',
    'Both types: dbutils.secrets.get() always shows [REDACTED] — never exposes actual value',
  ],
  facts:[
    'Databricks-backed: managed entirely within Databricks — simpler, no Azure dependency',
    'AKV-backed: secrets managed in AKV — better for enterprise key management and rotation',
    'AKV-backed: requires Azure setup (Key Vault + service principal) — more complex',
    'Both types display [REDACTED] when printed — cannot be revealed via print()',
  ],
  code:[
    '# Access secret — SAME API regardless of scope type',
    'secret_value = dbutils.secrets.get(scope="prod-secrets", key="db_password")',
    '',
    '# This ALWAYS shows [REDACTED] — for BOTH scope types',
    'print(secret_value)  # -> [REDACTED]',
    '',
    '# Databricks-backed scope: created via CLI',
    '# databricks secrets create-scope --scope prod-secrets',
    '# databricks secrets put-secret --scope prod-secrets --key db_password',
    '',
    '# AKV-backed scope: created via Databricks UI or REST API',
    '# POST /api/2.0/secrets/scopes/create',
    '# {',
    '#   "scope": "akv-prod-secrets",',
    '#   "scope_backend_type": "AZURE_KEYVAULT",',
    '#   "backend_azure_keyvault": {',
    '#     "resource_id": "/subscriptions/.../Microsoft.KeyVault/vaults/my-vault",',
    '#     "dns_name": "https://my-vault.vault.azure.net/"',
    '#   }',
    '# }',
    '',
    '# List scopes',
    'dbutils.secrets.listScopes()',
    '',
    '# List keys in a scope (shows key names only, NOT values)',
    'dbutils.secrets.list("prod-secrets")',
  ],
  trap:[
    '✗ Both scope types use IDENTICAL API: dbutils.secrets.get(scope, key)',
    '✗ Both types display [REDACTED] — cannot extract actual value via print()',
    '✗ AKV-backed: secrets managed in AKV — Databricks reads at RUNTIME',
    '✗ AKV secret rotation: immediate in Databricks — no sync or re-create step',
    '✗ Databricks-backed: simpler setup; AKV-backed: enterprise key management',
  ],
},

// ─── 7.5.2 ───────────────────────────────────────────────────────────────────
{num:'14',title:'7.5.2 — READ/WRITE/MANAGE Permissions on Scopes',
  what:[
    'Secret scope permissions control what users can do with a scope and the secrets within it',
    'Three permission levels: READ (get/list), WRITE (put/delete), MANAGE (admin — set ACLs)',
    'Permissions set at the SCOPE level — not on individual keys within the scope',
  ],
  facts:[
    'READ: dbutils.secrets.get(), dbutils.secrets.list() — read and list secrets',
    'WRITE: Create, update, delete secrets within scope (also includes READ)',
    'MANAGE: Set/modify ACLs on the scope (also includes WRITE + READ)',
    'Scope permissions are independent of UC privileges — separate permission system',
    'Scope creator automatically has MANAGE permission on that scope',
  ],
  code:[
    '# Set READ permission for a user on a scope',
    'databricks secrets put-acl \\',
    '    --scope prod-secrets \\',
    '    --principal alice@company.com \\',
    '    --permission READ',
    '',
    '# Set WRITE permission for a service principal',
    'databricks secrets put-acl \\',
    '    --scope prod-secrets \\',
    '    --principal service-principal-name \\',
    '    --permission WRITE',
    '',
    '# Set MANAGE permission (full admin)',
    'databricks secrets put-acl \\',
    '    --scope prod-secrets \\',
    '    --principal security-admin@company.com \\',
    '    --permission MANAGE',
    '',
    '# List current ACLs on a scope',
    'databricks secrets list-acls --scope prod-secrets',
    '',
    '# Remove ACL',
    'databricks secrets delete-acl --scope prod-secrets --principal alice@company.com',
  ],
  trap:[
    '✗ Permissions at SCOPE level — not per individual secret key within',
    '✗ READ permission: can get AND list secret keys (not values — REDACTED)',
    '✗ WRITE includes READ capabilities — additive (not replacing)',
    '✗ MANAGE includes WRITE + READ — can also set ACLs on scope',
    '✗ Scope creator has automatic MANAGE — cannot be removed by others',
    '✗ Secret scope ACLs managed via CLI/API — NOT via UC GRANT/REVOKE',
  ],
},

// ─── 7.5.3 ───────────────────────────────────────────────────────────────────
{num:'15',title:'7.5.3 — REDACTED Behavior Confirmed',
  what:[
    'REDACTED: Databricks security feature that prevents secret values from being displayed',
    'Printing, logging, displaying, error messages — secret value always shows as [REDACTED]',
    'Applies to BOTH Databricks-backed and AKV-backed secret scopes — no exceptions',
  ],
  how:[
    'When dbutils.secrets.get() returns a value, Databricks wraps it in special SecretString type',
    'Any attempt to display/print this value — Databricks intercepts and replaces with [REDACTED]',
    'Value IS accessible at runtime for use (JDBC URL, API call) — just not displayable',
    '[REDACTED] appears in: cell output, print(), cluster logs, driver logs, notebook output',
  ],
  facts:[
    '[REDACTED] in ALL display contexts — print(), display(), f-strings, str() conversion',
    'Secret value IS accessible in memory at runtime — usable in JDBC URLs, API calls',
    'dbutils.secrets.list() shows KEY NAMES only — never values',
    'Accidentally logging a secret variable shows [REDACTED] in the log — security by design',
  ],
  code:[
    '# Retrieve secret',
    'api_key = dbutils.secrets.get(scope="prod", key="openai_api_key")',
    '',
    '# ALL of these show [REDACTED]:',
    'print(api_key)               # [REDACTED]',
    'display(api_key)             # [REDACTED]',
    'print(f"Key: {api_key}")    # Key: [REDACTED]',
    'print(str(api_key))          # [REDACTED]',
    'print(type(api_key))         # <class \'str\'>',
    'len(api_key)                 # works! returns actual length (e.g. 51)',
    '                             # length is NOT redacted — only display is',
    '',
    '# Secret IS usable at runtime:',
    'headers = {"Authorization": f"Bearer {api_key}"}',
    '# The headers dict itself: {"Authorization": "Bearer [REDACTED]"}',
    '# But the actual HTTP request will use the real value',
    '',
    '# Cluster logs also show [REDACTED]',
    'spark.conf.set("spark.my.config", api_key)',
    '# spark.conf.get("spark.my.config") -> [REDACTED] in Environment tab',
    '',
    '# list() shows key names only, never values',
    'dbutils.secrets.list("prod")',
    '# [SecretMetadata(key=\'openai_api_key\'), SecretMetadata(key=\'db_password\')]',
  ],
  trap:[
    '✗ [REDACTED] in ALL display outputs — print(), display(), f-string, cluster logs',
    '✗ Secret value IS usable at runtime — REDACTED is display-only security feature',
    '✗ dbutils.secrets.list() shows KEY NAMES only — never reveals secret values',
    '✗ len(secret_value) works and returns actual length — length NOT redacted',
    '✗ type(secret_value) returns str — value is regular string, display intercepted',
    '✗ REDACTED applies to BOTH Databricks-backed AND AKV-backed scopes',
    '✗ Spark config set with secret value: Environment tab shows [REDACTED]',
  ],
},

// ─── 7.6.1 ───────────────────────────────────────────────────────────────────
{num:'16',title:'7.6.1 — GDPR Right to Erasure: DELETE + VACUUM Sequence',
  what:[
    'GDPR right to erasure: data subject can request their personal data be permanently deleted',
    'In Delta Lake: TWO steps — logical DELETE then physical VACUUM to permanently remove data',
    'Without VACUUM: data still exists in historical Parquet files and accessible via time travel',
  ],
  how:[
    'Step 1: DELETE FROM table WHERE customer_id = X — logically removes rows, adds remove action',
    'The deleted rows still physically present in old Parquet files — accessible via time travel',
    'Step 2: VACUUM table RETAIN 0 HOURS — physically deletes old Parquet files',
    'After VACUUM: data physically gone, time travel to pre-delete version fails',
  ],
  facts:[
    'DELETE alone is NOT sufficient for GDPR — data still in historical Parquet files',
    'VACUUM RETAIN 0 HOURS: requires spark.databricks.delta.retentionDurationCheck.enabled = false',
    'After DELETE + VACUUM: time travel to version with that customer data fails',
    'Deletion vectors: speed up DELETE, but OPTIMIZE + VACUUM still required for physical removal',
  ],
  code:[
    '-- GDPR Right to Erasure — Full Sequence',
    '',
    '-- Step 1: Logical DELETE',
    'DELETE FROM prod_catalog.customers.profiles',
    'WHERE customer_id = \'CUST-12345\';',
    '',
    '-- Verify logical delete worked',
    'SELECT COUNT(*) FROM prod_catalog.customers.profiles',
    'WHERE customer_id = \'CUST-12345\';',
    '-- 0 rows (logically deleted)',
    '',
    '-- But still accessible via time travel:',
    'SELECT * FROM prod_catalog.customers.profiles',
    'VERSION AS OF 10',
    'WHERE customer_id = \'CUST-12345\';',
    '-- still returns rows!',
    '',
    '-- Step 2: Disable safety check',
    'SET spark.databricks.delta.retentionDurationCheck.enabled = false;',
    '',
    '-- Step 3: VACUUM to physically remove old files',
    'VACUUM prod_catalog.customers.profiles RETAIN 0 HOURS;',
    '',
    '-- Re-enable safety check',
    'SET spark.databricks.delta.retentionDurationCheck.enabled = true;',
    '',
    '-- Verify physical deletion:',
    'SELECT * FROM prod_catalog.customers.profiles',
    'VERSION AS OF 10',
    'WHERE customer_id = \'CUST-12345\';',
    '-- FileNotFoundException (files physically deleted)',
  ],
  trap:[
    '✗ DELETE alone is NOT sufficient for GDPR erasure — data still in Parquet',
    '✗ VACUUM RETAIN 0 HOURS requires retentionDurationCheck.enabled = false',
    '✗ After DELETE only: time travel STILL shows deleted rows — Parquet unchanged',
    '✗ After DELETE + VACUUM: time travel to pre-delete version throws FileNotFoundException',
    '✗ Must delete from ALL tables containing PII — Bronze, Silver, Gold, derived',
    '✗ Deletion vectors with DELETE: still requires OPTIMIZE + VACUUM for physical removal',
  ],
},

// ─── 7.6.2 ───────────────────────────────────────────────────────────────────
{num:'17',title:'7.6.2 — PII Masking Patterns (Batch and Streaming)',
  what:[
    'PII masking patterns: standardized approaches to remove or transform PII during pipeline execution',
    'Applied during Bronze -> Silver transformation — Silver layer should have zero raw PII',
    'Two contexts: batch ETL masking and streaming micro-batch masking',
  ],
  facts:[
    'Identify PII columns: names, emails, SSN, phone, DOB, addresses, IP addresses, device IDs',
    'Choose technique per column: hash (joins), suppress (not needed), generalise (analytics)',
    'Apply in transformation: Silver step, not at read or at Gold',
    'Audit trail: Bronze retains raw PII for authorized reprocessing; Silver has masked',
  ],
  code:[
    'SALT = dbutils.secrets.get("scope", "pii_salt")',
    '',
    'def apply_pii_masking(df):',
    '    """Standard PII masking transformation — Bronze -> Silver"""',
    '    return (df',
    '        # Consistent pseudonym for customer joins',
    '        .withColumn("customer_id_hash",',
    '            sha2(concat(col("customer_id"), lit(SALT)), 256))',
    '',
    '        # Suppress sensitive identifiers',
    '        .drop("ssn", "full_name", "credit_card", "phone_number")',
    '',
    '        # Hash email (preserves uniqueness for dedup, not reversible)',
    '        .withColumn("email_hash",',
    '            sha2(concat(col("email"), lit(SALT)), 256))',
    '        .drop("email")',
    '',
    '        # Generalise date of birth to age band',
    '        .withColumn("age_band",',
    '            when(col("age") < 18, "under_18")',
    '            .when(col("age") < 30, "18-29")',
    '            .when(col("age") < 45, "30-44")',
    '            .otherwise("45+"))',
    '        .drop("date_of_birth", "age")',
    '',
    '        # Truncate IP address to /24 subnet',
    '        .withColumn("ip_subnet",',
    '            regexp_replace(col("ip_address"), r\'\\.\\d+$\', \'.0\'))',
    '        .drop("ip_address")',
    '    )',
    '',
    '# BATCH masking',
    'bronze_df = spark.read.table("catalog.bronze.user_events")',
    'silver_df = apply_pii_masking(bronze_df)',
    'silver_df.write.format("delta").mode("overwrite") \\',
    '    .saveAsTable("catalog.silver.user_events_masked")',
  ],
  trap:[
    '✗ PII masking applied at SILVER layer — Bronze has raw, Gold has aggregated',
    '✗ Salt must come from SECRETS — never hardcode in notebooks or job configs',
    '✗ Streaming masking: apply in foreachBatch transform BEFORE writing — not after',
    '✗ Hashing is ONE-WAY but CONSISTENT — same email -> same hash with same salt',
    '✗ Suppression is the STRONGEST protection — data gone, cannot be reversed',
    '✗ After masking, Silver should contain ZERO raw PII identifiers',
  ],
},

// ─── 7.6.3 ───────────────────────────────────────────────────────────────────
{num:'18',title:'7.6.3 — Data Retention Configuration on Delta Tables',
  what:[
    'Delta retention controls: two separate retention properties for different aspects',
    'delta.logRetentionDuration: how long commit history is accessible (default 30 days)',
    'delta.deletedFileRetentionDuration: how long old data files retained for VACUUM (default 7 days)',
  ],
  facts:[
    'logRetentionDuration default: 30 days — controls how far back DESCRIBE HISTORY shows',
    'deletedFileRetentionDuration default: 7 days (168 hours) — VACUUM threshold',
    'For compliance: configure both retention properties together',
    'GDPR consideration: longer retention = longer time data physically present in storage',
  ],
  code:[
    '-- Set retention for compliance (e.g. 90 days history, 30 days files)',
    'ALTER TABLE catalog.schema.orders',
    'SET TBLPROPERTIES (',
    '    \'delta.logRetentionDuration\' = \'interval 90 days\',',
    '    \'delta.deletedFileRetentionDuration\' = \'interval 30 days\'',
    ');',
    '',
    '-- Aggressive cleanup for high-PII tables',
    'ALTER TABLE catalog.pii.sensitive_data',
    'SET TBLPROPERTIES (',
    '    \'delta.logRetentionDuration\' = \'interval 7 days\',',
    '    \'delta.deletedFileRetentionDuration\' = \'interval 1 day\'',
    ');',
    '',
    '-- For long-term archive (max history retention)',
    'ALTER TABLE catalog.archive.historical',
    'SET TBLPROPERTIES (',
    '    \'delta.logRetentionDuration\' = \'interval 365 days\',',
    '    \'delta.deletedFileRetentionDuration\' = \'interval 365 days\'',
    ');',
    '',
    '-- View current retention settings',
    'DESCRIBE TABLE EXTENDED catalog.schema.orders;',
  ],
  trap:[
    '✗ TWO separate retention properties: log retention AND file retention',
    '✗ logRetentionDuration default = 30 days (history)',
    '✗ deletedFileRetentionDuration default = 7 days (VACUUM threshold)',
    '✗ For compliance: configure BOTH retention properties together',
    '✗ Setting logRetentionDuration shorter than VACUUM retention breaks time travel',
    '✗ GDPR: longer retention = longer time PII physically present in storage',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain7_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
