'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 8  —  Data Governance  —  12 Sub-Topics',
  groups: [
    ['8.1  Unity Catalog Architecture',[
      ['01','8.1.1','Three-Level Namespace: Metastore -> Catalog -> Schema -> Object'],
      ['02','8.1.2','hive_metastore Limitations (No Row Filters, No Lineage)'],
      ['03','8.1.3','Catalog Binding to Workspaces'],
    ]],
    ['8.2  Permission Inheritance',[
      ['04','8.2.1','Granting at Catalog Level Cascades to All Schemas and Tables'],
      ['05','8.2.2','USE CATALOG + USE SCHEMA Still Required Even with SELECT'],
      ['06','8.2.3','All Privilege Types with Scope'],
    ]],
    ['8.3  Data Discoverability and Metadata',[
      ['07','8.3.1','COMMENT ON TABLE/COLUMN'],
      ['08','8.3.2','Tags on Catalogs, Schemas, Tables, Columns'],
      ['09','8.3.3','UC Volumes: Managed vs External, /Volumes/ Path'],
    ]],
    ['8.4  Data Lineage',[
      ['10','8.4.1','Automatic Column-Level Lineage (No Configuration Needed)'],
      ['11','8.4.2','View Lineage in Catalog Explorer'],
      ['12','8.4.3','hive_metastore Tables: Lineage NOT Tracked'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 8  —  Data Governance  —  All High-Priority Traps',
};

const pages = [

// ─── 8.1.1 ───────────────────────────────────────────────────────────────────
{num:'01',title:'8.1.1 — Three-Level Namespace: Metastore -> Catalog -> Schema -> Object',
  what:[
    'Unity Catalog (UC): Databricks unified governance layer for all data and AI assets across workspaces',
    'Three-level namespace: catalog.schema.object — every object identified by this three-part path',
    'Object hierarchy: Metastore -> Catalog -> Schema -> Table / View / Volume / Function / Model',
  ],
  how:[
    'Metastore: top-level UC object — one per Databricks account per region, shared across workspaces',
    'Catalog: second level — logical container for schemas, used to separate environments or domains',
    'Schema (Database): third level — container for tables, views, volumes, functions, models',
    'Objects: tables, views, materialized views, streaming tables, volumes, functions, models',
  ],
  facts:[
    'One metastore per region per Databricks account — multiple workspaces share one metastore',
    'Metastore admin != workspace admin — separate roles with different scopes of control',
    'USE CATALOG + USE SCHEMA required to access any object — both levels needed',
    'hive_metastore is a special built-in catalog pointing to the legacy workspace-level Hive metastore',
  ],
  ascii:true,
  code:[
    'UNITY CATALOG HIERARCHY:',
    '',
    'ACCOUNT',
    '+-- METASTORE (one per region, shared by all workspaces in region)',
    '    +-- CATALOG: prod_catalog',
    '    |   +-- SCHEMA: sales_schema',
    '    |   |   +-- TABLE: orders',
    '    |   |   +-- VIEW: active_orders',
    '    |   |   +-- MATERIALIZED VIEW: daily_revenue',
    '    |   |   +-- STREAMING TABLE: events_bronze',
    '    |   |   +-- VOLUME: raw_files',
    '    |   |   +-- FUNCTION: clean_name',
    '    |   +-- SCHEMA: finance_schema',
    '    +-- CATALOG: dev_catalog',
    '    +-- CATALOG: hive_metastore  <- special legacy built-in',
    '',
    'THREE-LEVEL REFERENCE:',
    '  prod_catalog.sales_schema.orders',
    '  hive_metastore.default.legacy_table',
    '',
    'OBJECT TYPES PER SCHEMA:',
    '  TABLE             — managed or external Delta table',
    '  VIEW              — virtual, always re-executes',
    '  MATERIALIZED VIEW — pre-computed, DLT-refreshed',
    '  STREAMING TABLE   — incremental, DLT-managed',
    '  VOLUME            — non-tabular file storage',
    '  FUNCTION          — UDF, SQL function',
    '  MODEL             — MLflow model in UC registry',
  ],
  trap:[
    '✗ One metastore per REGION per account — ALL workspaces in region share ONE metastore',
    '✗ Metastore admin != workspace admin — separate, independent roles',
    '✗ hive_metastore is a special BUILT-IN catalog — points to legacy workspace metastore',
    '✗ UC three-level namespace: catalog.schema.table — NOT two-level',
    '✗ Schema = Database in UC — interchangeable terms',
    '✗ Objects live in SCHEMA — not directly in catalog',
    '✗ Multiple workspaces in same region share SAME metastore — permissions apply across',
  ],
},

// ─── 8.1.2 ───────────────────────────────────────────────────────────────────
{num:'02',title:'8.1.2 — hive_metastore Limitations (No Row Filters, No Lineage)',
  what:[
    'hive_metastore: legacy workspace-level Hive metastore — accessible as a special built-in catalog',
    'Critical limitations: does NOT support many UC governance features',
    'Understanding what hive_metastore CANNOT do is exam-critical',
  ],
  how:[
    'hive_metastore accessible as hive_metastore.schema.table in UC-enabled workspaces',
    'Tables in hive_metastore created before UC — managed by workspace-level Hive metastore',
    'UC governance features require objects to be in a proper UC catalog (not hive_metastore)',
    'Migration: CREATE TABLE uc_catalog.schema.table AS SELECT * FROM hive_metastore.schema.table',
  ],
  facts:[
    'hive_metastore does NOT support: row filters, column masks, automatic lineage',
    'hive_metastore does NOT support: Delta Sharing as provider, fine-grained access control',
    'hive_metastore: limited UC permissions, no column-level permissions',
    'Lineage tracking: NOT available for hive_metastore tables',
  ],
  code:[
    '-- Access hive_metastore from UC-enabled workspace',
    'USE CATALOG hive_metastore;',
    'SELECT * FROM default.legacy_orders;',
    '',
    '-- Three-level reference',
    'SELECT * FROM hive_metastore.default.legacy_orders;',
    '',
    '-- CANNOT apply row filter to hive_metastore table',
    'ALTER TABLE hive_metastore.default.legacy_orders',
    'SET ROW FILTER my_filter ON (region);',
    '-- Error: Row filters not supported for hive_metastore tables',
    '',
    '-- CANNOT view lineage for hive_metastore tables',
    '-- system.access.table_access_history does NOT track hive_metastore access',
    '',
    '-- Migration: move to UC catalog for governance features',
    'CREATE TABLE prod_catalog.sales.orders',
    'AS SELECT * FROM hive_metastore.default.legacy_orders;',
    '-- Now prod_catalog.sales.orders has full UC governance support',
  ],
  trap:[
    '✗ hive_metastore does NOT support: row filters, column masks, lineage, Delta Sharing as provider',
    '✗ hive_metastore tables: lineage NOT tracked in system.access.table_access_history',
    '✗ Cannot DENY in UC (does not exist), and hive_metastore has even fewer controls',
    '✗ Migration required for full governance: move tables from hive_metastore to UC catalog',
    '✗ hive_metastore is a special BUILT-IN catalog — NOT a regular UC catalog',
    '✗ hive_metastore appears as catalog in UC namespace but lacks governance capabilities',
  ],
},

// ─── 8.1.3 ───────────────────────────────────────────────────────────────────
{num:'03',title:'8.1.3 — Catalog Binding to Workspaces',
  what:[
    'Catalog binding: controlling which Databricks workspaces can access a specific UC catalog',
    'By default: all workspaces attached to same metastore can access all catalogs',
    'Catalog binding restricts access to specific workspaces — workspace-level isolation',
  ],
  how:[
    'Default: catalog accessible to ALL workspaces in same metastore region',
    'Binding: restrict catalog to specific workspace(s) — only bound workspaces can access',
    'Typical use: prod_catalog bound to prod_workspace; dev_catalog bound to dev_workspace',
    'Binding managed by account admin or metastore admin — not workspace admin',
  ],
  facts:[
    'Catalog binding = workspace-level isolation — prevents dev workspaces from seeing prod',
    'Binding configured via: account admin UI or REST API (/api/2.1/unity-catalog/bindings)',
    'Unbound catalog: accessible to ALL workspaces sharing the metastore — default',
    'Binding does NOT replace UC permissions — even bound workspace users still need GRANT',
  ],
  ascii:true,
  code:[
    'CATALOG BINDING EXAMPLE:',
    '',
    'METASTORE (us-east-1 region)',
    '+-- prod_catalog  <- BOUND to prod_workspace only',
    '|   +-- sales_schema',
    '|       +-- orders (sensitive production data)',
    '+-- dev_catalog   <- BOUND to dev_workspace only',
    '|   +-- dev_schema',
    '|       +-- orders (dev copy)',
    '+-- shared_catalog <- UNBOUND (accessible to ALL workspaces)',
    '    +-- reference_schema',
    '        +-- country_codes',
    '',
    'prod_workspace:',
    '  SELECT * FROM prod_catalog.sales.orders;  -> WORKS (bound)',
    '  SELECT * FROM dev_catalog.dev_schema.orders; -> ERROR (not bound)',
    '',
    'dev_workspace:',
    '  SELECT * FROM dev_catalog.dev_schema.orders; -> WORKS (bound)',
    '  SELECT * FROM prod_catalog.sales.orders; -> ERROR (not bound)',
    '  SELECT * FROM shared_catalog.reference_schema.country_codes; -> WORKS (unbound)',
    '',
    'SETUP via Account Admin:',
    '  Account Admin UI -> Catalogs -> prod_catalog -> Workspaces tab -> Bind',
  ],
  trap:[
    '✗ Catalog binding controls WORKSPACE-LEVEL access — which workspaces can SEE',
    '✗ Binding does NOT replace UC GRANT permissions — still need explicit grants',
    '✗ Unbound catalog = accessible to ALL workspaces in the metastore — exposure risk',
    '✗ Binding managed by ACCOUNT ADMIN or METASTORE ADMIN — not workspace admin',
    '✗ Binding restricts catalog from appearing in workspace — bound users still need GRANT',
    '✗ Even with binding, users still need USE CATALOG + USE SCHEMA + SELECT to access data',
  ],
},

// ─── 8.2.1 ───────────────────────────────────────────────────────────────────
{num:'04',title:'8.2.1 — Granting at Catalog Level Cascades to All Schemas and Tables',
  what:[
    'UC permission grants at higher levels cascade down to contained objects',
    'Catalog-level grants apply to all schemas and tables within',
    'Cascade applies to CURRENT objects only — new objects created later NOT automatically included',
  ],
  how:[
    'GRANT SELECT ON CATALOG prod TO analyst_group: applies to ALL current tables in ALL schemas',
    'GRANT SELECT ON SCHEMA prod.sales TO analyst_group: applies to ALL current tables in schema',
    'GRANT SELECT ON TABLE prod.sales.orders TO analyst_group: only that specific table',
    'New table created AFTER the grant: NOT automatically covered',
  ],
  facts:[
    'Cascade is CURRENT objects only — new objects need explicit or re-granted permissions',
    'Grant at catalog level is most permissive — grants access to all current objects',
    'USE CATALOG and USE SCHEMA still required — cascade does not include USE privileges automatically',
    'ALL PRIVILEGES on catalog: grants all applicable privileges on all current objects',
  ],
  code:[
    '-- Grant at catalog level: cascades to all current schemas and tables',
    'GRANT USE CATALOG ON CATALOG prod_catalog TO analyst_group;',
    'GRANT SELECT ON CATALOG prod_catalog TO analyst_group;',
    '-- analyst_group can SELECT from ALL current tables in ALL schemas',
    '-- BUT: still needs USE SCHEMA to navigate into specific schemas',
    '',
    '-- Grant at schema level: cascades to all current tables',
    'GRANT USE CATALOG ON CATALOG prod_catalog TO analyst_group;',
    'GRANT USE SCHEMA ON SCHEMA prod_catalog.sales TO analyst_group;',
    'GRANT SELECT ON SCHEMA prod_catalog.sales TO analyst_group;',
    '',
    '-- Grant at table level: only specific table',
    'GRANT SELECT ON TABLE prod_catalog.sales.orders TO analyst_group;',
    '',
    '-- Verify cascade worked',
    'SHOW GRANTS ON TABLE prod_catalog.sales.orders;',
    '',
    '-- New table created AFTER the grant (NOT automatically included)',
    'CREATE TABLE prod_catalog.sales.new_table (...);',
    '-- analyst_group does NOT have SELECT on new_table — must re-grant',
  ],
  trap:[
    '✗ Cascade applies to CURRENT objects at grant time — new objects NOT covered',
    '✗ USE CATALOG grant does NOT automatically grant USE SCHEMA — must grant separately',
    '✗ SELECT at catalog level grants on all current tables — but USE SCHEMA still needed',
    '✗ Granting at catalog level is BROAD — risk of unintended access',
    '✗ New table after grant: re-run GRANT or grant at catalog/schema level',
  ],
},

// ─── 8.2.2 ───────────────────────────────────────────────────────────────────
{num:'05',title:'8.2.2 — USE CATALOG + USE SCHEMA Still Required Even with SELECT',
  what:[
    'Even when SELECT granted at table/schema/catalog level — USE CATALOG and USE SCHEMA still SEPARATELY required',
    'This is the most common Unity Catalog permission mistake and a guaranteed exam topic',
    'Without USE privileges: user gets CATALOG_NOT_FOUND or SCHEMA_NOT_FOUND error',
  ],
  how:[
    'UC enforces three-step access check: USE catalog? USE schema? SELECT on table?',
    'All three checks must pass — failure at any step = access denied',
    'USE CATALOG on catalog AND USE SCHEMA on schema AND SELECT on table — all three required',
  ],
  facts:[
    'Three mandatory grants for any table read: USE CATALOG + USE SCHEMA + SELECT',
    'SELECT alone on a table = access denied (CATALOG_NOT_FOUND)',
    'USE CATALOG alone = can see catalog exists but cannot access any objects',
    'USE SCHEMA alone = cannot navigate to schema without USE CATALOG first',
  ],
  ascii:true,
  code:[
    'ACCESS CONTROL CHECK FLOW:',
    '',
    'SELECT * FROM prod_catalog.sales.orders:',
    '',
    'Step 1: Does user have USE CATALOG on prod_catalog?',
    '        NO  -> Error: CATALOG_NOT_FOUND',
    '        YES -> proceed to Step 2',
    '',
    'Step 2: Does user have USE SCHEMA on prod_catalog.sales?',
    '        NO  -> Error: SCHEMA_NOT_FOUND',
    '        YES -> proceed to Step 3',
    '',
    'Step 3: Does user have SELECT on prod_catalog.sales.orders?',
    '        NO  -> Error: Permission denied',
    '        YES -> Query executes successfully',
    '',
    'COMMON FAILURE SCENARIOS:',
    '',
    'Scenario A: Only SELECT granted, no USE grants',
    '  GRANT SELECT ON TABLE prod_catalog.sales.orders TO alice;',
    '  Alice runs: SELECT * FROM prod_catalog.sales.orders',
    '  -> ERROR: CATALOG_NOT_FOUND',
    '',
    'Scenario C: All three granted correctly',
    '  GRANT USE CATALOG ON CATALOG prod_catalog TO alice;',
    '  GRANT USE SCHEMA ON SCHEMA prod_catalog.sales TO alice;',
    '  GRANT SELECT ON TABLE prod_catalog.sales.orders TO alice;',
    '  Alice runs: SELECT * FROM prod_catalog.sales.orders',
    '  -> SUCCESS',
  ],
  trap:[
    '✗ THREE grants required: USE CATALOG + USE SCHEMA + SELECT — missing ANY = denied',
    '✗ SELECT alone on table -> CATALOG_NOT_FOUND — even if table grant correct',
    '✗ USE CATALOG alone -> cannot navigate to any schema or table',
    '✗ This applies even when SELECT inherited from higher-level grant',
    '✗ ALL PRIVILEGES on catalog DOES include USE CATALOG — but NOT USE SCHEMA on all schemas',
    '✗ Error message may be CATALOG_NOT_FOUND or SCHEMA_NOT_FOUND — not "permission denied"',
  ],
},

// ─── 8.2.3 ───────────────────────────────────────────────────────────────────
{num:'06',title:'8.2.3 — All Privilege Types with Scope',
  what:[
    'Unity Catalog defines specific privileges for each securable object type',
    'Knowing which privilege applies to which object level is essential',
  ],
  facts:[
    'USE CATALOG: at Catalog — navigate the catalog',
    'CREATE SCHEMA: at Catalog — create new schemas',
    'CREATE CONNECTION: at Catalog — create connections for Federation',
    'USE SCHEMA: at Schema — navigate the schema',
    'CREATE TABLE: at Schema — create new tables',
    'CREATE VIEW: at Schema — create new views',
    'CREATE FUNCTION: at Schema — create UDFs',
    'CREATE VOLUME: at Schema — create volumes',
    'CREATE MATERIALIZED VIEW: at Schema — create materialized views',
    'SELECT: at Table/View/MV — read data',
    'MODIFY: at Table — INSERT, UPDATE, DELETE, MERGE',
    'READ VOLUME / WRITE VOLUME: at Volume — read/write files',
    'EXECUTE: at Function — execute UC function/UDF',
    'ALL PRIVILEGES: at any level — all applicable privileges',
    'APPLY TAG: at Catalog/Schema/Table — add tags to objects',
  ],
  code:[
    '-- Read-only analyst',
    'GRANT USE CATALOG ON CATALOG prod TO analysts;',
    'GRANT USE SCHEMA  ON SCHEMA  prod.sales TO analysts;',
    'GRANT SELECT      ON TABLE   prod.sales.orders TO analysts;',
    '',
    '-- Read-write data engineer',
    'GRANT USE CATALOG ON CATALOG prod TO engineers;',
    'GRANT USE SCHEMA  ON SCHEMA  prod.sales TO engineers;',
    'GRANT SELECT, MODIFY ON SCHEMA prod.sales TO engineers;',
    '',
    '-- Schema creator',
    'GRANT USE CATALOG, CREATE SCHEMA ON CATALOG prod TO schema_owners;',
    'GRANT ALL PRIVILEGES ON SCHEMA prod.sales TO schema_owners;',
    '',
    '-- Volume access',
    'GRANT READ VOLUME  ON VOLUME prod.raw.landing TO ingest_svc;',
    'GRANT WRITE VOLUME ON VOLUME prod.raw.landing TO ingest_svc;',
    '',
    '-- Function execution',
    'GRANT EXECUTE ON FUNCTION prod.utils.clean_phone TO analysts;',
    '',
    '-- Tag management',
    'GRANT APPLY TAG ON CATALOG prod TO data_stewards;',
  ],
  trap:[
    '✗ MODIFY = INSERT + UPDATE + DELETE + MERGE — not just UPDATE',
    '✗ READ VOLUME and WRITE VOLUME are VOLUME-specific — separate from table SELECT/MODIFY',
    '✗ EXECUTE is for FUNCTIONS — not for running jobs or clusters',
    '✗ CREATE TABLE is at SCHEMA level — not catalog level',
    '✗ USE CATALOG and USE SCHEMA are NAVIGATION privileges — not data access',
    '✗ ALL PRIVILEGES grants everything APPLICABLE to that object type',
  ],
},

// ─── 8.3.1 ───────────────────────────────────────────────────────────────────
{num:'07',title:'8.3.1 — COMMENT ON TABLE/COLUMN',
  what:[
    'Comments: human-readable descriptions attached to UC objects — tables, columns, schemas, catalogs',
    'Visible in Catalog Explorer UI and via DESCRIBE TABLE EXTENDED',
    'Comments are metadata only — no impact on query execution or access control',
  ],
  how:[
    'COMMENT ON TABLE: adds/updates description on a table',
    'COMMENT ON COLUMN: adds/updates description on a specific column',
    'Comments at table creation: CREATE TABLE ... COMMENT \'description\'',
    'DESCRIBE TABLE EXTENDED table_name: shows comments in the output',
  ],
  facts:[
    'Comments stored as metadata in UC metastore — not in Parquet files',
    'Column comments visible in: Catalog Explorer, DESCRIBE TABLE, BI tools that read UC metadata',
    'Comments support markdown in some UI contexts',
    'Empty string \'\' or NULL clears an existing comment',
  ],
  code:[
    '-- Add comment at table creation',
    'CREATE TABLE prod_catalog.sales.orders (',
    '    order_id    BIGINT    COMMENT \'Unique identifier for each order\',',
    '    customer_id BIGINT    COMMENT \'Foreign key to customers table\',',
    '    amount      DOUBLE    COMMENT \'Order total in USD, excluding tax\',',
    '    order_date  DATE      COMMENT \'Date order was placed (UTC)\',',
    '    status      STRING    COMMENT \'Order status: pending, shipped, delivered, cancelled\'',
    ')',
    'COMMENT \'Fact table containing all customer orders since 2020-01-01\';',
    '',
    '-- Add or update comment on existing table',
    'COMMENT ON TABLE prod_catalog.sales.orders',
    'IS \'Fact table containing all customer orders. Updated daily via ETL pipeline.\';',
    '',
    '-- Add or update comment on specific column',
    'COMMENT ON TABLE prod_catalog.sales.orders',
    '    COLUMN amount',
    'IS \'Order total in USD. Negative values indicate refunds.\';',
    '',
    '-- Verify comments',
    'DESCRIBE TABLE EXTENDED prod_catalog.sales.orders;',
    '',
    '-- Remove a comment',
    'COMMENT ON TABLE prod_catalog.sales.orders IS NULL;',
  ],
  trap:[
    '✗ Comments are METADATA only — no effect on query, performance, or access control',
    '✗ DESCRIBE TABLE EXTENDED shows comments — DESCRIBE TABLE may not show all',
    '✗ Comments visible in Catalog Explorer UI — key for data discoverability',
    '✗ COMMENT ON TABLE ... IS \'text\' — note the IS keyword in the syntax',
    '✗ Column comments via COMMENT ON TABLE ... COLUMN col IS \'text\' — uses TABLE keyword',
  ],
},

// ─── 8.3.2 ───────────────────────────────────────────────────────────────────
{num:'08',title:'8.3.2 — Tags on Catalogs, Schemas, Tables, Columns',
  what:[
    'Tags: key-value metadata labels attached to UC objects',
    'Used for: governance categorization, PII identification, compliance labeling, cost attribution',
    'Tags are queryable via system tables — enabling programmatic governance workflows',
  ],
  how:[
    'Tags defined as key-value pairs: tag_key = \'tag_value\' or just a key without value',
    'Attached to objects via ALTER statement or at creation time',
    'Tags visible in: Catalog Explorer UI, DESCRIBE TABLE EXTENDED, system tables',
    'APPLY TAG privilege required to add tags — separate from SELECT/MODIFY',
  ],
  facts:[
    'Tags are key-value pairs — key required, value optional (can be empty string)',
    'Tags queryable via system.information_schema.tags or information_schema.column_tags',
    'Common tags: pii = \'true\', domain = \'finance\', owner = \'data-engineering\'',
    'Tags at COLUMN level: identify PII columns for automated masking workflows',
  ],
  code:[
    '-- Add tags at table creation',
    'CREATE TABLE prod_catalog.hr.employees',
    'TAGS (\'pii\' = \'true\', \'domain\' = \'hr\', \'owner\' = \'hr-data-team\')',
    'AS SELECT * FROM source;',
    '',
    '-- Add tags to existing table',
    'ALTER TABLE prod_catalog.hr.employees',
    'SET TAGS (\'pii\' = \'true\', \'environment\' = \'production\', \'sensitivity\' = \'high\');',
    '',
    '-- Add tags to specific columns',
    'ALTER TABLE prod_catalog.hr.employees',
    'ALTER COLUMN ssn SET TAGS (\'pii\' = \'true\', \'pii_type\' = \'national_id\');',
    '',
    '-- Add tags to schema and catalog',
    'ALTER SCHEMA prod_catalog.hr',
    'SET TAGS (\'domain\' = \'human_resources\', \'data_classification\' = \'confidential\');',
    '',
    'ALTER CATALOG prod_catalog',
    'SET TAGS (\'environment\' = \'production\', \'cost_center\' = \'CC-001\');',
    '',
    '-- Query all PII-tagged tables',
    'SELECT catalog_name, schema_name, table_name, tag_name, tag_value',
    'FROM system.information_schema.tags',
    'WHERE tag_name = \'pii\' AND tag_value = \'true\';',
    '',
    '-- Remove tags',
    'ALTER TABLE prod_catalog.hr.employees',
    'UNSET TAGS (\'pii\', \'environment\');',
  ],
  trap:[
    '✗ Tags require APPLY TAG privilege — separate from data access privileges',
    '✗ Tags are KEY-VALUE pairs — key required, value is optional',
    '✗ Tags queryable via system.information_schema.tags',
    '✗ Tags visible in Catalog Explorer — useful for data consumers',
    '✗ Column-level tags: ALTER TABLE ... ALTER COLUMN ... SET TAGS — ALTER TABLE syntax',
    '✗ Tags do NOT enforce access control — they are metadata only',
  ],
},

// ─── 8.3.3 ───────────────────────────────────────────────────────────────────
{num:'09',title:'8.3.3 — UC Volumes: Managed vs External, /Volumes/ Path',
  what:[
    'UC Volume: Unity Catalog object providing governed access to non-tabular file storage',
    'Two types: Managed (Databricks manages location) and External (customer specifies)',
    'Consistent access path: /Volumes/catalog/schema/volume/ — works across all cluster types',
  ],
  how:[
    'Managed Volume: Databricks assigns storage location (in schema managed location)',
    'External Volume: customer specifies an External Location — storage in customer-managed cloud',
    'Access path: /Volumes/<catalog>/<schema>/<volume>/ — four-level path from filesystem root',
    'Access from: Spark, dbutils.fs, %sh, UC file browser, %pip install',
  ],
  facts:[
    'Managed Volume: storage location Databricks-assigned',
    'External Volume: customer specifies location via LOCATION clause',
    'DROP behavior: Managed = files DELETED; External = files PRESERVED',
    'External Volume requires External Location to be defined first',
    'UC governance: Full for both — READ VOLUME, WRITE VOLUME privileges',
  ],
  code:[
    '-- Create managed volume (Databricks assigns storage)',
    'CREATE VOLUME prod_catalog.sales_schema.raw_files',
    'COMMENT \'Landing zone for raw CSV files from upstream systems\';',
    '',
    '-- Create external volume (customer specifies location)',
    'CREATE EXTERNAL VOLUME prod_catalog.sales_schema.archive_files',
    'LOCATION \'s3://my-bucket/archive/sales/\'',
    'COMMENT \'Long-term archive storage for historical files\';',
    '',
    '-- Grant access',
    'GRANT READ VOLUME  ON VOLUME prod_catalog.sales_schema.raw_files TO ingest_service;',
    'GRANT WRITE VOLUME ON VOLUME prod_catalog.sales_schema.raw_files TO ingest_service;',
    '',
    '# Access via Spark',
    'spark.read.csv("/Volumes/prod_catalog/sales_schema/raw_files/orders.csv")',
    'df.write.parquet("/Volumes/prod_catalog/sales_schema/raw_files/processed/")',
    '',
    '# Access via dbutils.fs',
    'dbutils.fs.ls("/Volumes/prod_catalog/sales_schema/raw_files/")',
    '',
    '# Access via %sh (driver only)',
    '%sh ls /Volumes/prod_catalog/sales_schema/raw_files/',
    '',
    '# Install .whl from UC Volume',
    '%pip install /Volumes/prod_catalog/libs/volume/my_package-1.0.0-py3-none-any.whl',
  ],
  trap:[
    '✗ Volume path: ALWAYS /Volumes/catalog/schema/volume/ — four-level path, exact format',
    '✗ Managed Volume DROP = files DELETED — same as managed table behavior',
    '✗ External Volume DROP = files PRESERVED — same as external table behavior',
    '✗ UC governance applies to Volumes: READ VOLUME and WRITE VOLUME privileges',
    '✗ UC row filters and column masks do NOT apply to Volumes — Volumes are not Delta tables',
    '✗ /Volumes/ path works in %sh — unlike DBFS mounts which use /dbfs/ for shell',
    '✗ Volumes accessible from ALL cluster access modes — Single User, Shared, Serverless',
  ],
},

// ─── 8.4.1 ───────────────────────────────────────────────────────────────────
{num:'10',title:'8.4.1 — Automatic Column-Level Lineage (No Configuration Needed)',
  what:[
    'UC Data Lineage: automatic tracking of data flow between tables, views, and columns',
    'Column-level lineage: shows which source columns contributed to each target column',
    'No configuration required — lineage captured automatically for all SQL operations on UC tables',
  ],
  how:[
    'Every SQL statement that reads from/writes to UC tables generates lineage records',
    'Lineage captures: source tables, source columns, target tables, target columns, transformation type',
    'Column-level: SELECT a.col1, b.col2 INTO target -> target.col1 <- source_a.col1',
    'Lineage stored in UC metadata — queryable via system.access.table_lineage and column_lineage',
  ],
  facts:[
    'No configuration needed — automatic for all SQL queries on UC-governed tables',
    'Lineage retained: 30 days by default — export to Delta for longer retention',
    'Lineage captures: SQL queries, DLT pipelines, MERGE operations',
    'Lineage does NOT capture: Python df.write.save() without SQL context, direct Parquet reads',
    'Column-level lineage: shows which source columns feed which target columns',
  ],
  code:[
    '-- Lineage automatically captured for these operations:',
    'CREATE TABLE prod_catalog.silver.orders_clean',
    'AS SELECT',
    '    o.order_id,',
    '    o.amount * 1.1  AS amount_with_tax,',
    '    c.name          AS customer_name',
    'FROM prod_catalog.bronze.orders o',
    'JOIN prod_catalog.dim.customers c ON o.customer_id = c.id;',
    '',
    '-- View lineage via SQL (system tables)',
    'SELECT *',
    'FROM system.access.table_lineage',
    'WHERE target_table_full_name = \'prod_catalog.silver.orders_clean\'',
    'ORDER BY event_time DESC;',
    '',
    'SELECT *',
    'FROM system.access.column_lineage',
    'WHERE target_table_full_name = \'prod_catalog.silver.orders_clean\'',
    '  AND target_column_name = \'customer_name\';',
    '-- Shows: source = prod_catalog.dim.customers.name',
    '',
    '-- Impact analysis: find all downstream tables that use orders_clean',
    'SELECT *',
    'FROM system.access.table_lineage',
    'WHERE source_table_full_name = \'prod_catalog.silver.orders_clean\'',
    'ORDER BY event_time DESC;',
  ],
  trap:[
    '✗ Lineage is AUTOMATIC — NO configuration required for UC-governed tables',
    '✗ Lineage requires Unity Catalog — hive_metastore tables have NO lineage tracking',
    '✗ system.access.table_lineage and column_lineage — two separate system tables',
    '✗ Python df.write.save() does NOT generate lineage — SQL operations DO',
    '✗ DLT pipelines DO generate lineage — captured automatically for DLT-managed tables',
    '✗ Default retention: 30 days — export to Delta for longer-term lineage history',
    '✗ Column-level lineage: identifies WHICH source column -> WHICH target column',
  ],
},

// ─── 8.4.2 ───────────────────────────────────────────────────────────────────
{num:'11',title:'8.4.2 — View Lineage in Catalog Explorer',
  what:[
    'Catalog Explorer: the Unity Catalog UI in Databricks workspace — browse objects, view metadata',
    'Lineage tab: within any UC table detail page — shows upstream sources and downstream consumers',
    'Visual graph: shows data flow as an interactive graph — click nodes to navigate',
  ],
  how:[
    'Navigate: Databricks UI -> Catalog -> select catalog -> schema -> table -> Lineage tab',
    'Lineage graph: upstream (left) shows sources; downstream (right) shows consumers',
    'Column-level: expand a table node in lineage graph to see column-level flow',
    'Time range: lineage graph shows lineage from the last 30 days by default',
  ],
  facts:[
    'Catalog Explorer is the UI for Unity Catalog — accessible from Databricks workspace nav',
    'Lineage tab available for: tables, views, materialized views, streaming tables',
    'Lineage graph is INTERACTIVE — click any table to navigate to its detail',
    'Column lineage: click "View column lineage" within the graph to see column-level flow',
  ],
  ascii:true,
  code:[
    'CATALOG EXPLORER LINEAGE TAB:',
    '',
    'Databricks UI Left Nav -> Catalog -> Expand catalog -> schema -> Click table',
    '',
    'TABLE DETAIL PAGE TABS:',
    '  Overview | Schema | Sample Data | Details | Permissions | Lineage | History',
    '',
    'LINEAGE TAB VIEW:',
    '  Upstream (sources)              Current Table          Downstream (consumers)',
    '',
    '  +------------------+           +--------------+        +------------------+',
    '  | bronze.orders_raw| --------> | silver.orders| -----> | gold.daily_revenue|',
    '  +------------------+           +-------+------+        +------------------+',
    '  +------------------+                   |',
    '  | dim.customers    | ------------------+',
    '  +------------------+',
    '',
    '  Column lineage (expanded):',
    '  bronze.orders_raw.amount       -> silver.orders.amount_usd',
    '  bronze.orders_raw.order_id     -> silver.orders.order_id',
    '  dim.customers.name             -> silver.orders.customer_name',
    '',
    '  Impact analysis: "If I change bronze.orders_raw, what is affected downstream?"',
    '  -> silver.orders -> gold.daily_revenue AND gold.customer_metrics',
  ],
  trap:[
    '✗ Catalog Explorer is the UI for browsing UC objects — not just file browser',
    '✗ Lineage tab shows BOTH upstream sources AND downstream consumers',
    '✗ Column-level lineage visible in Catalog Explorer — expand table nodes',
    '✗ Lineage only shows UC tables — hive_metastore appears as unresolved',
    '✗ Lineage graph shows last 30 days by default',
    '✗ Clicking a node in lineage graph navigates to THAT table detail page',
  ],
},

// ─── 8.4.3 ───────────────────────────────────────────────────────────────────
{num:'12',title:'8.4.3 — hive_metastore Tables: Lineage NOT Tracked',
  what:[
    'Unity Catalog lineage tracking does NOT apply to hive_metastore tables — hard limitation',
    'Queries reading from or writing to hive_metastore tables generate NO lineage records',
    'Lineage only works for tables in proper UC catalogs — not the legacy hive_metastore catalog',
  ],
  how:[
    'UC lineage engine intercepts SQL operations on UC-governed objects',
    'hive_metastore is not UC-governed — no lineage records generated',
    'system.access.table_lineage: no records for hive_metastore tables as source or target',
    'Catalog Explorer Lineage tab: shows empty or unresolved for hive_metastore',
  ],
  facts:[
    'UC catalog table: full table and column lineage tracked',
    'UC catalog view: lineage tracked, shows source tables',
    'UC DLT table: lineage tracked, DLT pipelines generate lineage',
    'hive_metastore table: NO lineage tracking',
    'External file (Parquet): NO lineage — direct file reads not captured',
    'Python df.write.save(): NO lineage — Python writes without SQL context',
  ],
  code:[
    '-- These operations generate lineage (UC tables):',
    'CREATE TABLE prod_catalog.silver.orders    -- UC catalog -> lineage tracked',
    'AS SELECT * FROM prod_catalog.bronze.raw_orders;',
    '',
    '-- These operations do NOT generate lineage:',
    'CREATE TABLE hive_metastore.default.orders -- hive_metastore -> NO lineage',
    'AS SELECT * FROM prod_catalog.bronze.raw_orders;',
    '',
    '-- Query to check if lineage exists',
    'SELECT COUNT(*) FROM system.access.table_lineage',
    'WHERE target_table_full_name LIKE \'hive_metastore%\';',
    '-- 0 rows (no lineage for hive_metastore tables)',
    '',
    'SELECT COUNT(*) FROM system.access.table_lineage',
    'WHERE target_table_full_name LIKE \'prod_catalog%\';',
    '-- N rows (lineage captured for UC catalog tables)',
    '',
    '-- Catalog Explorer shows:',
    '-- prod_catalog.silver.orders -> Lineage tab -> shows upstream and downstream',
    '-- hive_metastore.default.orders -> Lineage tab -> EMPTY',
  ],
  trap:[
    '✗ hive_metastore tables: lineage NOT tracked — hard limitation, no workaround',
    '✗ Lineage requires UC catalog tables — hive_metastore is outside UC governance',
    '✗ Migration needed for lineage: move tables to proper UC catalog',
    '✗ Python df.write.save() does NOT generate lineage — only SQL operations do',
    '✗ DLT pipeline lineage IS captured — DLT uses SQL under the hood',
    '✗ hive_metastore tables appear as "external" or unresolved in Catalog Explorer',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain8_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
