'use strict';
const { buildAndWrite } = require('./build_d_helpers.js');

const tocConfig = {
  title: 'TABLE OF CONTENTS',
  subtitle: 'Domain 10  —  Data Modelling  —  13 Sub-Topics',
  groups: [
    ['10.1  Medallion / Multi-Hop Architecture',[
      ['01','10.1.1','Bronze/Silver/Gold Layer Decision Rules (Access, PII, Transforms)'],
      ['02','10.1.2','Multi-Hop Pipeline Pattern with Lakeflow Code'],
    ]],
    ['10.2  Dimensional Modelling (Star Schema)',[
      ['03','10.2.1','Fact Tables vs Dimension Tables'],
      ['04','10.2.2','Surrogate Keys: GENERATED ALWAYS AS IDENTITY'],
      ['05','10.2.3','Dimension Types: Degenerate, Role-Playing, Conformed, Junk'],
    ]],
    ['10.3  Slowly Changing Dimensions (SCD)',[
      ['06','10.3.1','SCD Type 1 — MERGE Overwrite (No History)'],
      ['07','10.3.2','SCD Type 2 — APPLY CHANGES (__start_at, __end_at, __is_current)'],
    ]],
    ['10.4  Table Types — Complete Comparison',[
      ['08','10.4.1','Managed, External, View, MV, Streaming Table, Temp View, Dynamic View'],
      ['09','10.4.2','CTAS Executes Once — Static Snapshot'],
    ]],
    ['10.5  Data Layout Optimization for Modelling',[
      ['10','10.5.1','Partitioning Decision Rules (Low Cardinality, > 1GB, Even Distribution)'],
      ['11','10.5.2','Liquid Clustering for Dimensional and Fact Tables'],
      ['12','10.5.3','Stream-Static Join Limitations (Right Outer Not Supported)'],
      ['13','10.5.4','Choosing Surrogate Key Type for Performance'],
    ]],
  ],
};

const summaryConfig = {
  title: 'EXAM TRAPS MASTER SUMMARY',
  subtitle: 'Domain 10  —  Data Modelling  —  All High-Priority Traps',
};

const pages = [

// ─── 10.1.1 ──────────────────────────────────────────────────────────────────
{num:'01',title:'10.1.1 — Bronze/Silver/Gold Layer Decision Rules (Access, PII, Transforms)',
  what:[
    'Medallion Architecture: multi-hop pipeline pattern organizing data into three quality layers',
    'Each layer has distinct responsibilities: ingestion (Bronze), cleansing (Silver), aggregation (Gold)',
    'Foundation of the Databricks Lakehouse pattern — used in every production data platform',
  ],
  how:[
    'Bronze: raw ingestion — exact copy of source data, append-only, no transformations',
    'Silver: cleansed and conformed — deduplication, null handling, schema enforcement, PII masking',
    'Gold: aggregated business layer — metrics, KPIs, dimensional models, dashboards, ML features',
  ],
  facts:[
    'Bronze: never filter or drop records — preserve raw data, always reprocessable',
    'Silver: PII masked or removed — first access point for analysts',
    'Gold: no PII — aggregated data, safe for broad consumption',
    'Each layer is physically stored as Delta tables — NOT just views',
  ],
  ascii:true,
  code:[
    'MEDALLION ARCHITECTURE — DATA FLOW:',
    '',
    'SOURCE SYSTEMS',
    '  Kafka, REST APIs, JDBC, Files',
    '        |',
    '        v',
    '[BRONZE LAYER] Raw ingestion, no transforms',
    '  orders_bronze      (all raw events, exactly as received)',
    '  customers_bronze   (raw files from landing zone)',
    '  Access: Data Engineers ONLY',
    '  PII: PRESENT (raw)',
    '  Transforms: NONE — append-only',
    '        |',
    '        v',
    '[SILVER LAYER] Cleaned, deduplicated, validated',
    '  orders_silver      (deduped, nulls handled, validated)',
    '  customers_silver   (PII masked, SCD Type 2 history)',
    '  Access: Data Engineers + Analysts',
    '  PII: MASKED or REMOVED',
    '  Transforms: Dedup, join, conform, schema enforce, PII mask',
    '        |',
    '        v',
    '[GOLD LAYER] Aggregated, business-ready',
    '  daily_revenue_gold       (revenue by day by region)',
    '  customer_lifetime_value  (CLV metrics per segment)',
    '  Access: BI tools, ML models, business users',
    '  PII: NONE',
    '  Transforms: Aggregations, KPIs, dimensional models',
    '',
    'DECISION RULES PER LAYER:',
    '',
    'Dimension       Bronze         Silver           Gold',
    'Data quality    Raw            Cleaned          Aggregated',
    'PII present     Yes (raw)      Masked/removed   None',
    'Who accesses    DEs only       DEs + Analysts   BI/ML/business',
    'Transformations None           Dedup/join/PII   Aggregations',
    'Can drop rows?  NEVER          Yes (quarantine) N/A',
    'Reprocessable   Always         From Bronze      From Silver',
  ],
  trap:[
    '✗ Bronze should NEVER drop or filter records — preserve ALL raw data',
    '✗ PII must be MASKED or REMOVED at the Silver layer — not Bronze, not Gold',
    '✗ Analysts access GOLD — not Silver or Bronze directly',
    '✗ Bronze is append-only — no deletes or updates at Bronze layer',
    '✗ Each medallion layer is physically stored as Delta tables — NOT just views',
    '✗ Silver is the FIRST layer where PII should be masked',
    '✗ Gold is for AGGREGATED data only — should have zero PII',
  ],
},

// ─── 10.1.2 ──────────────────────────────────────────────────────────────────
{num:'02',title:'10.1.2 — Multi-Hop Pipeline Pattern with Lakeflow Code',
  what:[
    'Multi-hop pipeline: implementing Bronze -> Silver -> Gold medallion pattern using DLT (Lakeflow)',
    'DLT manages: table creation, incremental processing, data quality, checkpoints, lineage',
    'Each hop defined as a @dlt.table or @dlt.view — DLT orchestrates dependencies automatically',
  ],
  how:[
    'Bronze: readStream from source (Auto Loader, Kafka, Delta CDF) — Streaming Table',
    'Silver: dlt.read() or dlt.read_stream() from Bronze — apply quality + transforms',
    'Gold: dlt.read() from Silver — apply aggregations — Materialized View',
    'DLT handles: dependency ordering, incremental execution, checkpoint management',
  ],
  facts:[
    '@dlt.table = Materialized View or Streaming Table — DLT determines based on source',
    'dlt.read_stream("bronze") = streaming read — produces Streaming Table',
    'dlt.read("silver") = batch read — used for Materialized Views (aggregations)',
    '@dlt.expect_or_drop at Silver -> route bad records to quarantine, not silently drop',
  ],
  code:[
    'import dlt',
    'from pyspark.sql.functions import col, sha2, concat, lit, current_timestamp, when',
    '',
    'SALT = spark.conf.get("pipeline.pii_salt", "default_salt")',
    '',
    '# BRONZE LAYER: Raw ingestion (no transforms)',
    '@dlt.table(',
    '    name="orders_bronze",',
    '    comment="Raw orders from Auto Loader landing zone"',
    ')',
    'def orders_bronze():',
    '    return (spark.readStream',
    '        .format("cloudFiles")',
    '        .option("cloudFiles.format", "json")',
    '        .option("cloudFiles.schemaLocation", "/schema/orders/")',
    '        .load("/Volumes/catalog/schema/volume/landing/orders/"))',
    '',
    '# SILVER LAYER: Cleaned and conformed',
    '@dlt.table(name="orders_validated")',
    'def orders_validated():',
    '    return (dlt.read_stream("orders_bronze")',
    '        .withColumn("is_valid",',
    '            col("order_id").isNotNull() & (col("amount") > 0)',
    '            & col("customer_id").isNotNull()))',
    '',
    '@dlt.table(name="orders_silver")',
    '@dlt.expect_or_drop("valid_order_id", "order_id IS NOT NULL")',
    'def orders_silver():',
    '    return (dlt.read("orders_validated")',
    '        .filter(col("is_valid") == True)',
    '        .withColumn("customer_id_hash", sha2(concat(col("customer_id"), lit(SALT)), 256))',
    '        .drop("customer_id", "customer_email")',
    '        .withColumn("processed_at", current_timestamp()))',
    '',
    '@dlt.table(name="orders_quarantine")',
    'def orders_quarantine():',
    '    return (dlt.read("orders_validated")',
    '        .filter(col("is_valid") == False)',
    '        .withColumn("error_reason",',
    '            when(col("order_id").isNull(), "null_order_id")',
    '            .when(col("amount") <= 0, "invalid_amount")',
    '            .otherwise("validation_failure")))',
    '',
    '# GOLD LAYER: Aggregated business metrics',
    '@dlt.table(name="daily_revenue_gold")',
    'def daily_revenue_gold():',
    '    return (dlt.read("orders_silver")',
    '        .groupBy("order_date", "region")',
    '        .agg(',
    '            sum("amount").alias("total_revenue"),',
    '            count("order_id").alias("order_count"),',
    '            avg("amount").alias("avg_order_value")',
    '        ))',
  ],
  trap:[
    '✗ dlt.read_stream() produces Streaming Table; dlt.read() used in Materialized View',
    '✗ Bronze: use readStream from external source — NOT dlt.read()',
    '✗ Gold aggregations: use dlt.read() not dlt.read_stream() — aggregations are MV',
    '✗ DLT manages checkpoints automatically — no checkpointLocation needed in user code',
    '✗ @dlt.view for intermediate transforms not stored — @dlt.table for persisted',
    '✗ PII removal happens at SILVER — Bronze stores raw, Gold has none',
  ],
},

// ─── 10.2.1 ──────────────────────────────────────────────────────────────────
{num:'03',title:'10.2.1 — Fact Tables vs Dimension Tables',
  what:[
    'Star schema: dimensional modelling pattern — one central fact table surrounded by dimension tables',
    'Fact table: records business events — transactions, orders, clicks — measures + foreign keys',
    'Dimension table: provides context — who, what, when, where — descriptive attributes',
  ],
  how:[
    'Fact table: high volume, append-mostly, narrow (few columns per row)',
    'Dimension table: lower volume, changes slowly, wide (many attributes)',
    'Join: fact joined to dimensions via foreign key — surrogate key relationship',
    'Star schema: one join from fact to each dim — simple, fast for BI queries',
  ],
  facts:[
    'Fact table: high volume (millions-billions), append-only, narrow columns + measures + FK',
    'Dimension table: lower volume (thousands-millions), slow growth, wide attributes',
    'Fact grain: one row = one business event (most fundamental design decision)',
    'Dimension PK: surrogate key — referenced by fact table FK',
  ],
  code:[
    '-- Fact table: fine-grained business events',
    'CREATE TABLE prod_catalog.gold.fact_orders (',
    '    order_sk        BIGINT  GENERATED ALWAYS AS IDENTITY,  -- fact surrogate key',
    '    order_id        BIGINT,                                  -- natural/source key',
    '    customer_sk     BIGINT,  -- FK -> dim_customers.customer_sk',
    '    product_sk      BIGINT,  -- FK -> dim_products.product_sk',
    '    date_sk         INT,     -- FK -> dim_date.date_sk',
    '    order_amount    DOUBLE,  -- measure',
    '    quantity        INT,     -- measure',
    '    discount_pct    DOUBLE   -- measure',
    ')',
    'CLUSTER BY (date_sk, customer_sk);',
    '',
    '-- Dimension table: contextual attributes',
    'CREATE TABLE prod_catalog.gold.dim_customers (',
    '    customer_sk     BIGINT  GENERATED ALWAYS AS IDENTITY,  -- surrogate key (PK)',
    '    customer_id     STRING,                                  -- natural key',
    '    customer_name   STRING,',
    '    email_hash      STRING,  -- PII masked',
    '    region          STRING,',
    '    segment         STRING,',
    '    -- SCD Type 2 columns',
    '    __start_at      TIMESTAMP,',
    '    __end_at        TIMESTAMP,',
    '    __is_current    BOOLEAN',
    ')',
    'CLUSTER BY (customer_id);',
  ],
  trap:[
    '✗ Fact table grain: one row = one business event — most fundamental design decision',
    '✗ Dimension tables update via SCD — fact rows are typically NOT updated',
    '✗ Fact table FK references dim table surrogate key (SK) — not the natural source key',
    '✗ Star schema: one hop from fact to each dim — snowflake = multiple hops',
    '✗ Additive measures: sum across any dim (revenue) vs semi-additive (balance) vs non-additive (ratios)',
  ],
},

// ─── 10.2.2 ──────────────────────────────────────────────────────────────────
{num:'04',title:'10.2.2 — Surrogate Keys: GENERATED ALWAYS AS IDENTITY',
  what:[
    'Surrogate key: system-generated key uniquely identifying a row — independent of business key',
    'GENERATED ALWAYS AS IDENTITY: Delta feature to auto-generate monotonically increasing integer',
    'Integer surrogate keys faster than string UUIDs for joins',
  ],
  how:[
    'GENERATED ALWAYS AS IDENTITY: auto-assigns integer on each INSERT — cannot be manually inserted',
    'Used as primary key in dimension tables and as foreign key references in fact tables',
    'Auto-increments: each new row gets next available integer — gap-free or with gaps',
    'Concurrent inserts: may produce non-sequential values — guaranteed unique, not sequential',
  ],
  facts:[
    'GENERATED ALWAYS AS IDENTITY: cannot be explicitly inserted — auto-assigned only',
    'Integer (BIGINT) join: faster than STRING UUID joins — simpler comparison',
    'Integer storage: 8 bytes; UUID string: 36 bytes — significant difference at scale',
    'Alternative: GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)',
  ],
  code:[
    '-- Dimension table with surrogate key',
    'CREATE TABLE prod_catalog.gold.dim_products (',
    '    product_sk      BIGINT GENERATED ALWAYS AS IDENTITY,  -- surrogate (auto)',
    '    product_id      STRING,                                 -- natural key',
    '    product_name    STRING,',
    '    category        STRING,',
    '    unit_price      DOUBLE,',
    '    __is_current    BOOLEAN DEFAULT TRUE',
    ');',
    '',
    '-- INSERT: do NOT include product_sk — auto-assigned',
    'INSERT INTO prod_catalog.gold.dim_products (product_id, product_name, category, unit_price)',
    'VALUES (\'P-001\', \'Widget A\', \'Electronics\', 29.99);',
    '',
    '-- WRONG: explicitly inserting fails',
    '-- INSERT INTO dim_products VALUES (1, \'P-001\', ...);  ERROR',
    '',
    '-- Custom identity sequence',
    'CREATE TABLE prod_catalog.gold.dim_date (',
    '    date_sk         INT GENERATED ALWAYS AS IDENTITY (START WITH 20200101 INCREMENT BY 1),',
    '    full_date       DATE,',
    '    year            INT,',
    '    month           INT,',
    '    quarter         INT,',
    '    day_of_week     STRING',
    ');',
    '',
    '-- Performance comparison',
    '-- Integer (BIGINT) surrogate key join:',
    '-- fact.join(dim, fact.customer_sk == dim.customer_sk)',
    '-- 8-byte integer comparison per row — FAST',
    '',
    '-- String UUID join (avoid):',
    '-- fact.join(dim, fact.customer_uuid == dim.customer_uuid)',
    '-- 36-byte string comparison per row — SLOWER',
  ],
  trap:[
    '✗ GENERATED ALWAYS AS IDENTITY cannot accept explicit INSERT values — auto only',
    '✗ Integer (BIGINT) surrogate key is FASTER than string UUID for joins',
    '✗ Identity columns may have GAPS with concurrent inserts — unique, not sequential',
    '✗ Natural key (source ID) != surrogate key — surrogate is system-generated',
    '✗ SCD Type 2: each historical record has DIFFERENT surrogate key for SAME entity',
    '✗ GENERATED ALWAYS AS IDENTITY is Delta-specific — not all SQL dialects',
  ],
},

// ─── 10.2.3 ──────────────────────────────────────────────────────────────────
{num:'05',title:'10.2.3 — Dimension Types: Degenerate, Role-Playing, Conformed, Junk',
  what:[
    'Four special dimension types that appear on the exam',
    'Each has distinct characteristics and use cases',
    'Understanding what each is and when to use is the focus of exam questions',
  ],
  facts:[
    'Degenerate: dimension attribute stored directly in fact table — no separate dim table',
    'Role-playing: ONE physical dim used multiple times with different aliases in same query',
    'Conformed: dimension shared and standardized across multiple fact tables',
    'Junk: multiple low-cardinality flag/indicator columns combined into one dim table',
  ],
  code:[
    '-- DEGENERATE DIMENSION: order_number stored directly in fact (no dim table)',
    'CREATE TABLE fact_order_lines (',
    '    order_line_sk   BIGINT GENERATED ALWAYS AS IDENTITY,',
    '    order_number    STRING,  -- DEGENERATE DIMENSION (no dim table)',
    '    product_sk      BIGINT,',
    '    customer_sk     BIGINT,',
    '    quantity        INT,',
    '    unit_price      DOUBLE',
    ');',
    '',
    '-- ROLE-PLAYING DIMENSION: dim_date with multiple aliases',
    'SELECT',
    '    f.revenue,',
    '    od.full_date  AS order_date,     -- role: order date',
    '    sd.full_date  AS ship_date,      -- role: ship date',
    '    pd.full_date  AS payment_date    -- role: payment date',
    'FROM fact_orders f',
    'JOIN dim_date od ON f.order_date_sk   = od.date_sk   -- alias 1',
    'JOIN dim_date sd ON f.ship_date_sk    = sd.date_sk   -- alias 2',
    'JOIN dim_date pd ON f.payment_date_sk = pd.date_sk;  -- alias 3',
    '',
    '-- CONFORMED DIMENSION: dim_customer shared across fact tables',
    'SELECT * FROM fact_sales    JOIN dim_customer ON customer_sk; -- shared',
    'SELECT * FROM fact_support  JOIN dim_customer ON customer_sk; -- same dim!',
    'SELECT * FROM fact_returns  JOIN dim_customer ON customer_sk; -- consistent',
    '',
    '-- JUNK DIMENSION: low-cardinality flags combined',
    'CREATE TABLE dim_order_flags (',
    '    order_flags_sk  BIGINT GENERATED ALWAYS AS IDENTITY,',
    '    is_promotional  BOOLEAN,',
    '    is_gift_wrap    BOOLEAN,',
    '    is_express_ship BOOLEAN,',
    '    is_international BOOLEAN',
    ');',
    '-- fact_orders.order_flags_sk -> dim_order_flags',
    '-- Better than 4 flag columns in fact table',
  ],
  trap:[
    '✗ Degenerate dimension: attribute stored IN fact table — no separate dim',
    '✗ Role-playing dimension: ONE physical table, MULTIPLE aliases in same query',
    '✗ Conformed dimension: SHARED across multiple fact tables — consistent definition',
    '✗ Junk dimension: LOW-CARDINALITY flags combined into ONE dim table',
    '✗ Role-playing requires table ALIASES in SQL — cannot reference twice without alias',
    '✗ Conformed dimensions enable cross-mart consistency',
  ],
},

// ─── 10.3.1 ──────────────────────────────────────────────────────────────────
{num:'06',title:'10.3.1 — SCD Type 1 — MERGE Overwrite (No History)',
  what:[
    'SCD Type 1: overwrite the current dimension record when attributes change — NO history',
    'Simplest SCD approach — just update the row, old values are permanently lost',
    'Use when: historical values irrelevant, corrections (not changes) applied',
  ],
  how:[
    'Source record changes: find matching dimension row and UPDATE it — no new row',
    'Implementation: MERGE INTO dim USING source ON key WHEN MATCHED THEN UPDATE SET *',
    'After update: only the current value exists — previous overwritten',
    'No additional columns needed — standard dimension table schema',
  ],
  facts:[
    'SCD Type 1: simplest implementation — single MERGE statement with UPDATE',
    'Overwrites previous values PERMANENTLY — no time travel to historical dim values',
    'Use for: data corrections (typos, errors), stable attributes',
    'WHEN NOT MATCHED THEN INSERT handles new dimension members alongside updates',
  ],
  code:[
    '-- SCD Type 1: MERGE overwrite (no history preserved)',
    'MERGE INTO prod_catalog.gold.dim_customers t',
    'USING (',
    '    SELECT DISTINCT',
    '        customer_id,',
    '        customer_name,',
    '        email_hash,',
    '        region,',
    '        segment,',
    '        updated_at',
    '    FROM prod_catalog.silver.customers_silver',
    ') s',
    'ON t.customer_id = s.customer_id',
    '',
    '-- Update existing record — overwrites all attributes (history LOST)',
    'WHEN MATCHED AND s.updated_at > t.updated_at',
    '    THEN UPDATE SET',
    '        t.customer_name = s.customer_name,',
    '        t.email_hash    = s.email_hash,',
    '        t.region        = s.region,',
    '        t.segment       = s.segment,',
    '        t.updated_at    = s.updated_at',
    '',
    '-- Insert new customers',
    'WHEN NOT MATCHED',
    '    THEN INSERT (customer_id, customer_name, email_hash, region, segment, updated_at)',
    '    VALUES (s.customer_id, s.customer_name, s.email_hash, s.region, s.segment, s.updated_at);',
    '',
    '# DLT APPLY CHANGES — SCD Type 1',
    'import dlt',
    '',
    'dlt.apply_changes(',
    '    target="dim_customers",',
    '    source="customers_cdc_stream",',
    '    keys=["customer_id"],',
    '    sequence_by=col("updated_at"),',
    '    apply_as_deletes=col("op_type") == "DELETE",',
    '    stored_as_scd_type=1   # Type 1: overwrite, no history',
    ')',
  ],
  trap:[
    '✗ SCD Type 1 OVERWRITES previous values — no history, no time travel',
    '✗ Use MERGE with WHEN MATCHED THEN UPDATE for Type 1 — simple, no new rows',
    '✗ stored_as_scd_type=1 in APPLY CHANGES — overwrite mode, same row updated',
    '✗ After Type 1 update: fact table rows now see UPDATED value retroactively',
    '✗ SCD Type 1 appropriate for: data corrections, non-analytical attribute changes',
  ],
},

// ─── 10.3.2 ──────────────────────────────────────────────────────────────────
{num:'07',title:'10.3.2 — SCD Type 2 — APPLY CHANGES (__start_at, __end_at, __is_current)',
  what:[
    'SCD Type 2: preserve full history — new row added for each change, old row closed with end date',
    'Current record: __end_at = NULL and __is_current = TRUE; historical: __end_at filled, __is_current = FALSE',
    'Implemented in DLT via APPLY CHANGES with stored_as_scd_type=2',
  ],
  how:[
    'Dimension attribute changes: INSERT new row + UPDATE old row to set __end_at and __is_current = FALSE',
    '__start_at: timestamp when this version became current',
    '__end_at: timestamp when superseded (NULL = currently active)',
    '__is_current: boolean flag for current active version',
  ],
  facts:[
    'SCD Type 2 system columns: __start_at, __end_at, __is_current — exact names tested on exam',
    'Current records: WHERE __is_current = TRUE — always filter for current state',
    'APPLY CHANGES handles: out-of-order events via sequence_by, late-arriving correctly',
    'APPLY CHANGES target must be a Streaming Table — not a Materialized View',
  ],
  code:[
    '# DLT APPLY CHANGES — SCD Type 2',
    'import dlt',
    'from pyspark.sql.functions import col',
    '',
    'dlt.apply_changes(',
    '    target="dim_customers_history",      # Streaming Table target',
    '    source="customers_cdc_stream",       # CDC source stream',
    '    keys=["customer_id"],                # natural key',
    '    sequence_by=col("updated_at"),       # handles out-of-order events',
    '    apply_as_deletes=col("op_type") == "DELETE",',
    '    stored_as_scd_type=2                 # Type 2: preserves full history',
    ')',
    '# DLT automatically adds: __start_at, __end_at, __is_current',
    '',
    '-- Querying SCD Type 2 table',
    '',
    '-- Get CURRENT customer records only',
    'SELECT customer_id, customer_name, region, segment',
    'FROM prod_catalog.gold.dim_customers_history',
    'WHERE __is_current = TRUE;',
    '',
    '-- Get ALL history for a customer',
    'SELECT customer_id, customer_name, region, __start_at, __end_at, __is_current',
    'FROM prod_catalog.gold.dim_customers_history',
    'WHERE customer_id = \'CUST-12345\'',
    'ORDER BY __start_at;',
    '',
    '-- Point-in-time query: customer region on 2023-06-15?',
    'SELECT customer_id, customer_name, region',
    'FROM prod_catalog.gold.dim_customers_history',
    'WHERE customer_id = \'CUST-12345\'',
    '  AND __start_at <= \'2023-06-15\'',
    '  AND (__end_at > \'2023-06-15\' OR __end_at IS NULL);',
    '',
    '-- Example SCD Type 2 table:',
    '-- customer_sk | customer_id | name  | region | __start_at | __end_at  | __is_current',
    '-- 1001        | CUST-123    | Alice | West   | 2022-01-01 | 2023-06-15| FALSE  (historical)',
    '-- 1002        | CUST-123    | Alice | East   | 2023-06-15 | NULL      | TRUE   (current)',
  ],
  trap:[
    '✗ SCD Type 2 system columns: __start_at, __end_at, __is_current — exact names',
    '✗ Always filter WHERE __is_current = TRUE for current state',
    '✗ __end_at = NULL for the CURRENT record — not a future date',
    '✗ APPLY CHANGES target MUST be Streaming Table — NOT Materialized View',
    '✗ sequence_by is REQUIRED — handles late-arriving out-of-order CDC events',
    '✗ SCD Type 2 produces MULTIPLE surrogate keys for SAME natural key (one per version)',
  ],
},

// ─── 10.4.1 ──────────────────────────────────────────────────────────────────
{num:'08',title:'10.4.1 — Managed, External, View, MV, Streaming Table, Temp View, Dynamic View',
  what:[
    'Seven distinct table/view types in Databricks — each with different persistence, refresh, governance',
    'Choosing correct type for each use case is a recurring exam topic',
    'Key dimensions: stores data? auto-refresh? DLT-dependent? session-scoped?',
  ],
  ascii:true,
  code:[
    'COMPLETE TABLE TYPE COMPARISON:',
    '',
    'Type              | Stores | Refresh? | Re-exec? | DLT? | DROP files?| Session?',
    'Managed Table     | Yes    | No       | No       | No   | DELETED    | No',
    'External Table    | Yes    | No       | No       | No   | PRESERVED  | No',
    'View              | No     | Always   | YES      | No   | N/A        | No',
    'Materialized View | Yes    | Pipeline | No       | Yes  | DELETED    | No',
    'Streaming Table   | Yes    | Increment| No       | Yes  | DELETED    | No',
    'Temp View         | No     | Always   | YES      | No   | N/A        | YES',
    'Dynamic View      | No     | Always   | YES      | No   | N/A        | No',
    'CTAS Result       | Yes    | NEVER    | No       | No   | DELETED    | No',
    '',
    'DECISION TREE:',
    '',
    'Need to STORE data?',
    '+-- YES:',
    '|   +-- Need auto-refresh when source changes?',
    '|   |   +-- YES:',
    '|   |   |   +-- Append-only incremental?  -> STREAMING TABLE (DLT)',
    '|   |   |   +-- Aggregated / complex SQL? -> MATERIALIZED VIEW (DLT)',
    '|   |   +-- NO:',
    '|   |       +-- Databricks-managed storage? -> MANAGED TABLE',
    '|   |       +-- External storage?           -> EXTERNAL TABLE',
    '|   |       +-- One-time snapshot?          -> CTAS',
    '+-- NO (virtual):',
    '    +-- Always re-execute on query?',
    '        +-- Need row/column security (legacy)?  -> DYNAMIC VIEW',
    '        +-- Session-scoped only?                -> TEMP VIEW',
    '        +-- Permanent, always-fresh?            -> VIEW',
    '',
    'KEY DISTINCTION:',
    '  VIEW:             re-executes every query — always fresh',
    '  CTAS:             executes ONCE — static snapshot, never auto-refreshes',
    '  MATERIALIZED VIEW: auto-refreshes when DLT pipeline runs',
  ],
  trap:[
    '✗ MANAGED TABLE DROP: files DELETED; EXTERNAL TABLE DROP: files PRESERVED',
    '✗ VIEW re-executes on EVERY query — always fresh, no storage',
    '✗ CTAS executes ONCE — never auto-refreshes, reads stored Delta',
    '✗ Materialized View auto-refreshes when DLT PIPELINE RUNS — not on every query',
    '✗ Temp View is SESSION-scoped — lost when SparkSession ends',
    '✗ Dynamic View uses is_member() — workspace groups only',
    '✗ Streaming Table processes ONLY NEW records each pipeline run',
  ],
},

// ─── 10.4.2 ──────────────────────────────────────────────────────────────────
{num:'09',title:'10.4.2 — CTAS Executes Once — Static Snapshot',
  what:[
    'CTAS (CREATE TABLE AS SELECT): creates a Delta table by executing SELECT EXACTLY ONCE',
    'Result is a static snapshot — querying does NOT re-execute the SELECT',
    'Adding new data to source after CTAS does NOT update — frozen at creation time',
  ],
  how:[
    'CREATE TABLE new_table AS SELECT * FROM source: runs SELECT once, stores result in Delta',
    'After creation: SELECT * FROM new_table reads stored Delta files — source NOT consulted',
    'Table reflects state of source AT TIME of CTAS — not current state',
    'Refresh: must DROP TABLE + CREATE TABLE AS SELECT or use MV',
  ],
  facts:[
    'CTAS executes the SELECT exactly ONCE — at creation time',
    'CTAS result stored as managed Delta table — all Delta features (time travel, ACID)',
    'CTAS does NOT create live connection to source — point-in-time snapshot',
    'CREATE OR REPLACE TABLE ... AS SELECT overwrites — re-runs SELECT once more',
  ],
  code:[
    '-- CTAS: runs SELECT once at creation, stored as Delta',
    'CREATE TABLE prod_catalog.gold.orders_snapshot_jan',
    'AS SELECT *',
    'FROM prod_catalog.silver.orders',
    'WHERE order_date BETWEEN \'2024-01-01\' AND \'2024-01-31\';',
    '',
    '-- orders_snapshot_jan is now a STATIC SNAPSHOT',
    '-- Adding more orders to silver.orders does NOT update orders_snapshot_jan',
    '',
    '-- Querying CTAS table — reads stored Delta files (source NOT re-queried)',
    'SELECT COUNT(*) FROM prod_catalog.gold.orders_snapshot_jan;',
    '-- Returns: count at the time CTAS was created',
    '',
    '-- To "refresh" CTAS — must explicitly re-run',
    'CREATE OR REPLACE TABLE prod_catalog.gold.orders_snapshot_jan',
    'AS SELECT *',
    'FROM prod_catalog.silver.orders',
    'WHERE order_date BETWEEN \'2024-01-01\' AND \'2024-01-31\';',
    '-- Re-executes SELECT once — replaces table with current data',
    '',
    '-- For auto-refreshing table: use Materialized View (DLT) instead',
    '-- @dlt.table',
    '-- def orders_jan_mv():',
    '--     return dlt.read("orders_silver").filter(...)',
  ],
  trap:[
    '✗ CTAS executes the SELECT exactly ONCE — at creation, NEVER re-executes on query',
    '✗ New data added to source AFTER CTAS does NOT appear in CTAS table',
    '✗ CTAS table reads STORED DATA — source NOT consulted at query time',
    '✗ CTAS creates MANAGED Delta table — has time travel, ACID, all Delta features',
    '✗ CREATE OR REPLACE TABLE ... AS SELECT re-runs SELECT ONCE and replaces',
    '✗ Materialized View auto-refreshes; CTAS never auto-refreshes',
    '✗ CTAS vs VIEW: CTAS stores data (no re-exec); VIEW stores nothing (always re-exec)',
  ],
},

// ─── 10.5.1 ──────────────────────────────────────────────────────────────────
{num:'10',title:'10.5.1 — Partitioning Decision Rules (Low Cardinality, > 1GB, Even Distribution)',
  what:[
    'Table partitioning: physically organizing data into subdirectories by column values',
    'Three golden rules — all three must be satisfied for effective partitioning',
    'Wrong partitioning decisions worse than no partitioning at all',
  ],
  how:[
    'PARTITIONED BY (col): creates a separate directory per unique value in cloud storage',
    'Spark uses partition pruning: query filters on partition column -> reads only matching dirs',
    'Partition columns become part of file path: /table/col=value/part-xxx.parquet',
    'Filtering without partition column: full table scan — no pruning, all directories read',
  ],
  facts:[
    'Low cardinality: < 10,000 unique values — high cardinality = small file problem',
    '> 1GB per partition: each partition should contain at least 1GB',
    'Evenly distributed: roughly equal data across partition values — skewed = hot directories',
  ],
  ascii:true,
  code:[
    'PARTITIONING DECISION FRAMEWORK:',
    '',
    'GOOD PARTITION COLUMNS:',
    '  order_date (date)  — low cardinality (365/yr), >1GB/day, even distribution',
    '  region (string)    — low cardinality (5-10 regions), >1GB/region, roughly even',
    '  year_month (int)   — low cardinality (12/yr), large enough, relatively even',
    '',
    'BAD PARTITION COLUMNS:',
    '  user_id (high cardinality)   — millions unique values -> millions of dirs',
    '    each dir has tiny files -> small file problem -> slow reads',
    '  status (skewed)              — 90% \'active\', 10% other -> hot dir',
    '    rest are tiny -> uneven access patterns',
    '  event_id (UUID per row)      — one dir per row -> extreme small files',
    '',
    'WHEN NOT TO PARTITION:',
    '  Table < 1GB total -> no partitioning needed',
    '  Filter patterns unknown -> Liquid Clustering instead',
    '  High-cardinality needed -> Liquid Clustering supports high-cardinality keys',
    '',
    'PARTITIONING EXAMPLES:',
    'WRONG:',
    '  CREATE TABLE events PARTITIONED BY (user_id);    -- high cardinality!',
    '  CREATE TABLE orders PARTITIONED BY (order_date, status);  -- too granular',
    '',
    'RIGHT:',
    '  CREATE TABLE events PARTITIONED BY (event_date);          -- low cardinality',
    '  CREATE TABLE orders PARTITIONED BY (order_year, region);  -- low cardinality',
    '  CREATE TABLE logs   PARTITIONED BY (log_date, severity);  -- low cardinality',
  ],
  trap:[
    '✗ THREE rules: low cardinality, >1GB per partition, evenly distributed — ALL three',
    '✗ High-cardinality partitioning = small file problem — millions of tiny dirs',
    '✗ Partition column must be in WHERE clause of typical queries — match query patterns',
    '✗ Partition columns are IMMUTABLE after table creation — cannot change',
    '✗ Liquid Clustering INCOMPATIBLE with partitioning — choose one',
    '✗ > 1GB per partition: too small = degrades; too large = slow partition reads',
  ],
},

// ─── 10.5.2 ──────────────────────────────────────────────────────────────────
{num:'11',title:'10.5.2 — Liquid Clustering for Dimensional and Fact Tables',
  what:[
    'Liquid Clustering: modern adaptive clustering — replaces static partitioning and ZORDER for most cases',
    'Particularly valuable for dimensional model fact tables — supports high-cardinality join keys',
    'Clustering columns can be changed as query patterns evolve — unlike static partitioning',
  ],
  how:[
    'Fact tables: cluster by most common join/filter keys — CLUSTER BY (date_sk, customer_sk)',
    'Dimension tables: cluster by natural key — CLUSTER BY (customer_id) for fast lookups',
    'Incremental: each OPTIMIZE clusters only newly written files',
    'After changing clustering columns: OPTIMIZE FULL re-clusters all existing data',
  ],
  facts:[
    'Large fact table: CLUSTER BY (date_sk, customer_sk) — common join + filter columns',
    'Dimension table: CLUSTER BY (natural_key) — fast lookups by source system key',
    'SCD Type 2 dim: CLUSTER BY (natural_key, __is_current) — current record lookups',
    'Time-series table: CLUSTER BY (event_date, device_id) — time + entity filters',
  ],
  code:[
    '-- Fact table with Liquid Clustering on common join keys',
    'CREATE TABLE prod_catalog.gold.fact_orders',
    '(',
    '    order_sk        BIGINT GENERATED ALWAYS AS IDENTITY,',
    '    date_sk         INT,',
    '    customer_sk     BIGINT,',
    '    product_sk      BIGINT,',
    '    order_amount    DOUBLE,',
    '    quantity        INT',
    ')',
    'CLUSTER BY (date_sk, customer_sk)  -- most common join/filter columns',
    'COMMENT \'Fact orders — clustered for efficient star schema joins\';',
    '',
    '-- Dimension table with Liquid Clustering',
    'CREATE TABLE prod_catalog.gold.dim_customers',
    '(',
    '    customer_sk     BIGINT GENERATED ALWAYS AS IDENTITY,',
    '    customer_id     STRING,    -- natural key from source',
    '    customer_name   STRING,',
    '    region          STRING,',
    '    __is_current    BOOLEAN',
    ')',
    'CLUSTER BY (customer_id)  -- fast lookups by source system ID',
    'COMMENT \'Customer dimension — SCD Type 2, clustered by natural key\';',
    '',
    '-- Run incremental clustering',
    'OPTIMIZE prod_catalog.gold.fact_orders;',
    '',
    '-- Full re-cluster after changing clustering columns',
    'ALTER TABLE prod_catalog.gold.fact_orders',
    'CLUSTER BY (date_sk, product_sk);   -- changed customer_sk to product_sk',
    '',
    'OPTIMIZE prod_catalog.gold.fact_orders FULL;  -- re-clusters ALL existing',
    '',
    '-- Verify clustering columns',
    'DESCRIBE DETAIL prod_catalog.gold.fact_orders;',
    '-- clusteringColumns: ["date_sk", "customer_sk"]',
  ],
  trap:[
    '✗ Liquid Clustering max 4 columns — hard limit, error if exceeded',
    '✗ Liquid Clustering INCOMPATIBLE with PARTITIONED BY — mutually exclusive',
    '✗ Liquid Clustering INCOMPATIBLE with ZORDER BY — competing strategies',
    '✗ Clustering columns CAN be changed — partition columns CANNOT',
    '✗ OPTIMIZE FULL required after changing clustering columns',
    '✗ Incremental OPTIMIZE only clusters newly written data — OPTIMIZE FULL for complete',
  ],
},

// ─── 10.5.3 ──────────────────────────────────────────────────────────────────
{num:'12',title:'10.5.3 — Stream-Static Join Limitations (Right Outer Not Supported)',
  what:[
    'Stream-static join: joining streaming DataFrame with static (batch) DataFrame',
    'Critical limitation: right outer join NOT supported when streaming on LEFT side',
    'Supported: inner join, left outer join (streaming on left)',
  ],
  how:[
    'Stream LEFT + static RIGHT: inner and left outer joins supported',
    'Stream LEFT + static RIGHT: right outer and full outer NOT supported',
    'Why: right outer requires all non-matching right rows — impossible for unbounded stream',
    'Static side re-read on every micro-batch — always reflects latest version',
  ],
  ascii:true,
  code:[
    'STREAM-STATIC JOIN SUPPORT MATRIX:',
    '',
    'Join Type   | Stream LEFT + Static RIGHT | Static LEFT + Stream RIGHT',
    'Inner       | YES                        | YES',
    'Left Outer  | YES                        | NO (stream must be on left)',
    'Right Outer | NO                         | YES',
    'Full Outer  | NO                         | NO',
    'Left Semi   | YES                        | -',
    'Left Anti   | YES                        | -',
    '',
    '# Static dimension table (re-read every micro-batch)',
    'customer_dim = spark.read.table("prod_catalog.gold.dim_customers") \\',
    '    .filter(col("__is_current") == True)',
    '',
    '# Streaming orders',
    'orders_stream = spark.readStream.table("prod_catalog.bronze.orders_bronze")',
    '',
    '# SUPPORTED: inner join (stream LEFT, static RIGHT)',
    'enriched_inner = orders_stream.join(customer_dim, "customer_id", "inner")',
    '',
    '# SUPPORTED: left outer join (stream LEFT, static RIGHT)',
    'enriched_left  = orders_stream.join(customer_dim, "customer_id", "left")',
    '# Rows with no matching customer: NULLs in customer columns',
    '',
    '# NOT SUPPORTED: right outer join when streaming on LEFT',
    '# enriched_right = orders_stream.join(customer_dim, "customer_id", "right")',
    '# AnalysisException: Right outer join with streaming left side not supported',
    '',
    '# NOT SUPPORTED: full outer join',
    '# enriched_full  = orders_stream.join(customer_dim, "customer_id", "full")',
    '',
    '# Write to Silver',
    '(enriched_left.writeStream',
    '    .format("delta")',
    '    .outputMode("append")',
    '    .option("checkpointLocation", "/chk/orders_enriched/")',
    '    .table("prod_catalog.silver.orders_enriched"))',
    '',
    'STREAM-STATIC JOIN RULES:',
    '',
    'Stream (LEFT) + Static (RIGHT):',
    '  inner        -> matching rows only',
    '  left outer   -> all stream + matching static (NULL if no match)',
    '  right outer  -> NOT supported',
    '  full outer   -> NOT supported',
    '',
    'Static side:',
    '  Re-read EVERY micro-batch (always latest version)',
    '  No watermark needed (stateless join)',
    '  Do NOT cache() static DF — caching prevents seeing updates',
  ],
  trap:[
    '✗ Right outer join NOT supported when streaming is on the LEFT side — AnalysisException',
    '✗ Stream-static join is STATELESS — no watermarks needed',
    '✗ Static table re-read EVERY micro-batch — always reflects latest Delta version',
    '✗ Caching static DF prevents seeing new rows — do NOT cache the static dim',
    '✗ Inner and left outer joins ARE supported with streaming on left — most common',
    '✗ For frequently-changing dimensions: use stream-STREAM join with watermarks',
    '✗ Stream-static left outer: streaming rows with no dim match get NULL in dim columns',
  ],
},

// ─── 10.5.4 ──────────────────────────────────────────────────────────────────
{num:'13',title:'10.5.4 — Choosing Surrogate Key Type for Performance',
  what:[
    'Surrogate key type choice impacts join performance significantly',
    'Integer (BIGINT) keys outperform string UUID keys at scale',
    'Critical decision for fact-dimension join performance in dimensional models',
  ],
  facts:[
    'BIGINT (8 bytes): fastest joins, smallest storage, integer comparison',
    'INT (4 bytes): even smaller — but limited range, may overflow at scale',
    'STRING UUID (36 bytes): slow joins, larger storage, string comparison',
    'STRING natural key: slowest — variable length, lexicographic comparison',
  ],
  ascii:true,
  code:[
    'SURROGATE KEY PERFORMANCE COMPARISON:',
    '',
    'Type          | Bytes/value | Join Speed | Storage  | Range',
    'BIGINT        | 8           | Fastest    | Smallest | 9.2 quintillion',
    'INT           | 4           | Faster     | Smaller  | 2.1 billion',
    'UUID (string) | 36          | Slow       | Large    | Unlimited',
    'Natural key   | Variable    | Slowest    | Largest  | Source-dependent',
    '',
    'EXAMPLE: Fact-dim join performance at 1B-row scale',
    '',
    'fact_orders.customer_sk JOIN dim_customers.customer_sk:',
    '  BIGINT-BIGINT:  ~10s',
    '  STRING(36)-STRING(36):  ~60s (~6x slower)',
    '',
    'STORAGE IMPACT (1B rows):',
    '  BIGINT key column:  8GB',
    '  UUID string column: 36GB (~4.5x more)',
    '',
    'RECOMMENDATIONS:',
    '',
    'Use BIGINT GENERATED ALWAYS AS IDENTITY for:',
    '  Surrogate keys in dim tables (PK)',
    '  Foreign keys in fact tables (FK references)',
    '',
    'Use STRING for:',
    '  Natural keys (source system IDs) — keep as separate column',
    '  Business keys for human readability',
    '',
    'AVOID:',
    '  UUIDs as join keys at scale — significantly slower',
    '  Natural keys as PRIMARY surrogate — adds string overhead',
    '',
    '-- Example: dimension with both natural and surrogate keys',
    'CREATE TABLE dim_customers (',
    '    customer_sk     BIGINT GENERATED ALWAYS AS IDENTITY,  -- surrogate (FAST joins)',
    '    customer_id     STRING,                                -- natural (lookups)',
    '    customer_name   STRING,',
    '    PRIMARY KEY (customer_sk)',
    ');',
    '',
    '-- Fact references the surrogate key (BIGINT) — fast joins',
    'CREATE TABLE fact_orders (',
    '    order_sk        BIGINT GENERATED ALWAYS AS IDENTITY,',
    '    customer_sk     BIGINT,  -- references dim_customers.customer_sk',
    '    amount          DOUBLE,',
    '    FOREIGN KEY (customer_sk) REFERENCES dim_customers(customer_sk)',
    ');',
  ],
  trap:[
    '✗ BIGINT surrogate key is FASTEST for joins at scale',
    '✗ STRING UUID joins are 4-6x slower than BIGINT joins',
    '✗ UUID storage is ~4.5x larger than BIGINT (36 bytes vs 8 bytes)',
    '✗ INT (4 bytes) may overflow at 2.1 billion rows — use BIGINT for safety',
    '✗ Keep natural key as separate column from surrogate key — for human lookups',
    '✗ GENERATED ALWAYS AS IDENTITY auto-assigns BIGINT — recommended pattern',
  ],
},

];

buildAndWrite({
  pages,
  tocConfig,
  summaryConfig,
  outPath: '/Users/mohammednadhims/Downloads/Domain10_Complete_Study_Notes.docx',
}).catch(err => { console.error('BUILD ERROR:', err.message); process.exit(1); });
